from django.utils.translation import gettext_lazy as _
from django.db import models


class Departement(models.TextChoices):
    AIN = "Ain", _("Ain")
    AISNE = "Aisne", _("Aisne")
    ALLIER = "Allier", _("Allier")
    ALPES_DE_HAUTE_PROVENCE = "Alpes-de-Haute-Provence", _("Alpes-de-Haute-Provence")
    HAUTES_ALPES = "Hautes-Alpes", _("Hautes-Alpes")
    ALPES_MARITIMES = "Alpes-Maritimes", _("Alpes-Maritimes")
    ARDECHE = "Ardèche", _("Ardèche")
    ARDENNES = "Ardennes", _("Ardennes")
    ARIEGE = "Ariège", _("Ariège")
    AUBE = "Aube", _("Aube")
    AUDE = "Aude", _("Aude")
    AVEYRON = "Aveyron", _("Aveyron")
    BOUCHES_DU_RHONE = "Bouches-du-Rhône", _("Bouches-du-Rhône")
    CALVADOS = "Calvados", _("Calvados")
    CANTAL = "Cantal", _("Cantal")
    CHARENTE = "Charente", _("Charente")
    CHARENTE_MARITIME = (
        "Charente-Maritime",
        _(
            "Charente-Maritime",
        ),
    )
    CHER = "Cher", _("Cher")
    CORREZE = "Corrèze", _("Corrèze")
    CORSE_DU_SUD = "Corse-du-Sud", _("Corse-du-Sud")
    HAUTE_CORSE = "Haute-Corse", _("Haute-Corse")
    COTE_D_OR = "Côte-d'Or", _("Côte-d'Or")
    COTES_D_ARMOR = "Côtes-d'Armor", _("Côtes-d'Armor")
    CREUSE = "Creuse", _("Creuse")
    DORDOGNE = "Dordogne", _("Dordogne")
    DOUBS = "Doubs", _("Doubs")
    DROME = "Drôme", _("Drôme")
    EURE = "Eure", _("Eure")
    EURE_ET_LOIR = "Eure-et-Loir", _("Eure-et-Loir")
    FINISTERE = "Finistère", _("Finistère")
    GARD = "Gard", _("Gard")
    HAUTE_GARONNE = "Haute-Garonne", _("Haute-Garonne")
    GERS = "Gers", _("Gers")
    GIRONDE = "Gironde", _("Gironde")
    HERAULT = "Hérault", _("Hérault")
    ILLE_ET_VILAINE = "Ille-et-Vilaine", _("Ille-et-Vilaine")
    INDRE = "Indre", _("Indre")
    INDRE_ET_LOIRE = "Indre-et-Loire", _("Indre-et-Loire")
    ISERE = "Isère", _("Isère")
    JURA = "Jura", _("Jura")
    LANDES = "Landes", _("Landes")
    LOIR_ET_CHER = "Loir-et-Cher", _("Loir-et-Cher")
    LOIRE = "Loire", _("Loire")
    HAUTE_LOIRE = "Haute-Loire", _("Haute-Loire")
    LOIRE_ATLANTIQUE = "Loire-Atlantique", _("Loire-Atlantique")
    LOIRET = "Loiret", _("Loiret")
    LOT = "Lot", _("Lot")
    LOT_ET_GARONNE = "Lot-et-Garonne", _("Lot-et-Garonne")
    LOZERE = "Lozère", _("Lozère")
    MAINE_ET_LOIRE = "Maine-et-Loire", _("Maine-et-Loire")
    MANCHE = "Manche", _("Manche")
    MARNE = "Marne", _("Marne")
    HAUTE_MARNE = "Haute-Marne", _("Haute-Marne")
    MAYENNE = "Mayenne", _("Mayenne")
    MEURTHE_ET_MOSELLE = "Meurthe-et-Moselle", _("Meurthe-et-Moselle")
    MEUSE = "Meuse", _("Meuse")
    MORBIHAN = "Morbihan", _("Morbihan")
    MOSELLE = "Moselle", _("Moselle")
    NIEVRE = "Nièvre", _("Nièvre")
    NORD = "Nord", _("Nord")
    OISE = "Oise", _("Oise")
    ORNE = "Orne", _("Orne")
    PAS_DE_CALAIS = "Pas-de-Calais", _("Pas-de-Calais")
    PUY_DE_DEME = "Puy-de-Dôme", _("Puy-de-Dôme")
    PYRENEES_ATLANTIQUES = "Pyrénées-Atlantiques", _("Pyrénées-Atlantiques")
    HAUTES_PYRENEES = "Hautes-Pyrénées", _("Hautes-Pyrénées")
    PYRENEES_ORIENTALES = "Pyrénées-Orientales", _("Pyrénées-Orientales")
    BAS_RHIN = "Bas-Rhin", _("Bas-Rhin")
    HAUT_RHIN = "Haut-Rhin", _("Haut-Rhin")
    RHONE = "Rhône", _("Rhône")
    HAUTE_SAONE = "Haute-Saône", _("Haute-Saône")
    SAONE_ET_LOIRE = "Saône-et-Loire", _("Saône-et-Loire")
    SARTHE = "Sarthe", _("Sarthe")
    SAVOIE = "Savoie", _("Savoie")
    HAUTE_SAVOIE = "Haute-Savoie", _("Haute-Savoie")
    PARIS = "Paris", _("Paris")
    SEINE_MARITIME = "Seine-Maritime", _("Seine-Maritime")
    SEINE_ET_MARNE = "Seine-et-Marne", _("Seine-et-Marne")
    YVELINES = "Yvelines", _("Yvelines")
    DEUX_SEVRES = "Deux-Sèvres", _("Deux-Sèvres")
    SOMME = "Somme", _("Somme")
    TARN = "Tarn", _("Tarn")
    TARN_ET_GARONNE = "Tarn-et-Garonne", _("Tarn-et-Garonne")
    VAR = "Var", _("Var")
    VAUCLUSE = "Vaucluse", _("Vaucluse")
    VENDEE = "Vendée", _("Vendée")
    VIENNE = "Vienne", _("Vienne")
    HAUTE_VIENNE = "Haute-Vienne", _("Haute-Vienne")
    VOSGES = "Vosges", _("Vosges")
    YONNE = "Yonne", _("Yonne")
    TERRITOIRE_DE_BELFORT = (
        "Territoire de Belfort",
        _(
            "Territoire de Belfort",
        ),
    )
    ESSONNE = "Essonne", _("Essonne")
    HAUTS_DE_SEINE = "Hauts-de-Seine", _("Hauts-de-Seine")
    SEINE_SAINT_DENIS = "Seine-Saint-Denis", _("Seine-Saint-Denis")
    VAL_DE_MARNE = "Val-de-Marne", _("Val-de-Marne")
    VAL_D_OISE = "Val-d'Oise", _("Val-d'Oise")
    GUADELOUPE = "Guadeloupe", _("Guadeloupe")
    MARTINIQUE = "Martinique", _("Martinique")
    GUYANE = "Guyane", _("Guyane")
    REUNION = "La Réunion", _("La Réunion")
    MAYOTTE = "Mayotte", _("Mayotte")
    HORS_FRANCE = "Hors France", _("Hors France")
