# Generated by Django 5.0.3 on 2024-06-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("structure", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("nom", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("fonction_hierarchique", models.CharField(blank=True, max_length=255, null=True)),
                ("complement_fonction", models.CharField(blank=True, max_length=255, null=True)),
                ("telephone", models.CharField(blank=True, max_length=20, null=True)),
                ("mobile", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "indexes": [models.Index(fields=["structure"], name="core_contac_structu_e0ef78_idx")],
            },
        ),
    ]
