# Generated by Django 5.0.3 on 2024-06-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="complement_fonction",
            field=models.TextField(blank=True, null=True),
        ),
    ]
