# Generated by Django 5.0.3 on 2024-06-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_contact_complement_fonction"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["email"], name="core_contac_email_800caf_idx"),
        ),
    ]
