# Generated by Django 5.0.3 on 2024-07-02 06:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_structurehierarchique_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StructureHierarchique",
        ),
    ]
