# Generated by Django 5.0.3 on 2024-07-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[("cartographie", "Cartographie"), ("autre", "Autre document")],
                max_length=100,
                verbose_name="Type de document",
            ),
        ),
    ]
