# Generated by Django 5.0.3 on 2024-07-24 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("structure_complete", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("nom", models.CharField(max_length=255)),
                ("fonction_hierarchique", models.CharField(blank=True, max_length=255)),
                ("complement_fonction", models.TextField(blank=True)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("mobile", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "verbose_name": "Agent",
                "verbose_name_plural": "Agents",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="Structure",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("niveau1", models.CharField(max_length=255)),
                ("niveau2", models.CharField(blank=True, max_length=255)),
                ("libelle", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Structure",
                "verbose_name_plural": "Structures",
                "ordering": ["niveau1", "niveau2"],
            },
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["structure", "agent"], "verbose_name": "Contact", "verbose_name_plural": "Contacts"},
        ),
        migrations.RemoveIndex(
            model_name="contact",
            name="core_contac_structu_e0ef78_idx",
        ),
        migrations.RemoveIndex(
            model_name="contact",
            name="core_contac_email_800caf_idx",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="complement_fonction",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="fonction_hierarchique",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="mobile",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="nom",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="prenom",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="telephone",
        ),
        migrations.AlterField(
            model_name="message",
            name="title",
            field=models.CharField(max_length=512, verbose_name="Titre"),
        ),
        migrations.AddField(
            model_name="agent",
            name="user",
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="contact",
            name="agent",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to="core.agent"),
        ),
        migrations.AddField(
            model_name="agent",
            name="structure",
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="core.structure"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="structure",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to="core.structure"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["email", "structure", "agent"], name="core_contac_email_815e92_idx"),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.CheckConstraint(
                condition=models.Q(("structure__isnull", False), ("agent__isnull", False), _connector="OR"),
                name="contact_has_structure_or_agent",
            ),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(fields=["user"], name="core_agent_user_id_60ca3a_idx"),
        ),
    ]
