# Generated by Django 5.0.3 on 2024-07-24 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_user(apps, schema_editor):
    Document = apps.get_model("core", "Document")
    Structure = apps.get_model("core", "Structure")
    Agent = apps.get_model("core", "Agent")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))

    try:
        user = User.objects.get(email="service_account@seves.com")
    except User.DoesNotExist:
        user = User.objects.create_user(username="service_account", email="service_account@seves.com")

    try:
        structure = Structure.objects.get(niveau1="service_account")
    except Structure.DoesNotExist:
        structure = Structure.objects.create(niveau1="service_account")

    try:
        agent = Agent.objects.get(user=user)
    except Agent.DoesNotExist:
        agent = Agent.objects.create(
            user=user, prenom="Service", nom="Account", structure_complete="Service account", structure=structure
        )

    structure, _ = Structure.objects.get_or_create(niveau1="service_account")
    Document.objects.update(created_by=agent, created_by_structure=structure)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_message_sender"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents_created",
                to="core.Agent",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="created_by_structure",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents_created",
                to="core.structure",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents_deleted",
                to="core.Agent",
            ),
        ),
        migrations.RunPython(add_user, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="document",
            name="created_by",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents_created",
                to="core.Agent",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="created_by_structure",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents_created",
                to="core.Structure",
            ),
        ),
    ]
