# Generated by Django 5.0.3 on 2024-08-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_contact_agent_alter_contact_structure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("message", "Message"),
                    ("note", "Note"),
                    ("point de situation", "Point de situation"),
                    ("demande d'intervention", "Demande d'intervention"),
                    (
                        "compte rendu sur demande d'intervention",
                        "Compte rendu sur demande d'intervention",
                    ),
                    ("fin d'intervention", "Fin d'intervention"),
                ],
                max_length=100,
            ),
        ),
    ]
