# Generated by Django 5.0.3 on 2024-09-05 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0014_alter_message_message_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="LienLibre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id_1", models.PositiveIntegerField()),
                ("object_id_2", models.PositiveIntegerField()),
                (
                    "content_type_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relation_1",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "content_type_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relation_2",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="lienlibre",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("content_type_1", models.F("content_type_2")),
                    ("object_id_1", models.F("object_id_2")),
                    _negated=True,
                ),
                name="no_self_relation",
            ),
        ),
    ]
