# Generated by Django 5.0.8 on 2024-09-11 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0015_lienlibre_lienlibre_no_self_relation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("message", "Message"),
                    ("note", "Note"),
                    ("point de situation", "Point de situation"),
                    ("demande d'intervention", "Demande d'intervention"),
                    ("compte rendu sur demande d'intervention", "Compte rendu sur demande d'intervention"),
                    ("fin de suivi", "Fin de suivi"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="FinSuiviContact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                ("contact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.contact")),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="finsuivicontact",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id", "contact"), name="unique_fin_suivi_contact"
            ),
        ),
    ]
