# Generated by Django 5.0.3 on 2024-09-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_message_message_type_finsuivicontact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    (
                        "arrete prefectoral ministériel",
                        "Arrêté préfectoral/ministériel",
                    ),
                    ("autre", "Autre document"),
                    ("cartographie", "Cartographie"),
                    ("certificat phytosanitaire", "Certificat phytosanitaire"),
                    ("compte rendu reunion", "Compte rendu de réunion"),
                    ("courrier officiel", "Courrier officiel"),
                    ("dsce", "DSCE"),
                    ("facture", "Facture"),
                    ("image", "Image"),
                    ("passeport phytosanitaire", "Passeport phytosanitaire"),
                    ("rapport analyse", "Rapport d'analyse"),
                    ("rapport inspection", "Rapport d'inspection"),
                    ("reglementation", "Réglementation"),
                    ("document de transport", "Document de transport"),
                ],
                max_length=100,
                verbose_name="Type de document",
            ),
        ),
    ]
