# Generated by Django 5.0.3 on 2024-09-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_message_message_type_finsuivicontact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("message", "Message"),
                    ("note", "Note"),
                    ("point de situation", "Point de situation"),
                    ("demande d'intervention", "Demande d'intervention"),
                    (
                        "compte rendu sur demande d'intervention",
                        "Compte rendu sur demande d'intervention",
                    ),
                    ("fin de suivi", "Fin de suivi"),
                    ("notification ac", "Notification à l'administration centrale"),
                ],
                max_length=100,
            ),
        ),
    ]
