# Generated by Django 5.0.3 on 2024-11-05 15:28

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_message_message_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to=core.storage.get_timestamped_filename),
        ),
    ]
