# Generated by Django 5.0.3 on 2024-11-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_document_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    (
                        "arrete_prefectoral_ministériel",
                        "Arrêté préfectoral/ministériel",
                    ),
                    ("autre", "Autre document"),
                    ("cartographie", "Cartographie"),
                    ("certificat_phytosanitaire", "Certificat phytosanitaire"),
                    ("compte_rendu_reunion", "Compte rendu de réunion"),
                    ("courrier_officiel", "Courrier officiel"),
                    ("dsce", "DSCE"),
                    ("facture", "Facture"),
                    ("image", "Image"),
                    ("passeport_phytosanitaire", "Passeport phytosanitaire"),
                    ("rapport_analyse", "Rapport d'analyse"),
                    ("rapport_inspection", "Rapport d'inspection"),
                    ("reglementation", "Réglementation"),
                    ("document_de_transport", "Document de transport"),
                ],
                max_length=100,
                verbose_name="Type de document",
            ),
        ),
    ]
