# Generated by Django 5.0.8 on 2024-11-15 07:52
from django.contrib.auth.models import Group
from django.db import migrations


def create_admin_group(apps, schema_editor):
    Group.objects.get_or_create(name="access_admin")


def remove_admin_group(apps, schema_editor):
    Group.objects.filter(name="access_admin").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_document_document_type"),
    ]

    operations = [
        migrations.RunPython(create_admin_group, remove_admin_group),
    ]
