# Generated by Django 5.0.8 on 2024-11-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_create_access_admin_group"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contact",
            name="contact_has_structure_or_agent",
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("structure__isnull", False), ("agent__isnull", True)),
                    models.Q(("structure__isnull", True), ("agent__isnull", False)),
                    _connector="OR",
                ),
                name="contact_has_structure_or_agent",
            ),
        ),
    ]
