# Generated by Django 5.1.5 on 2025-02-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_alter_document_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_infected",
            field=models.BooleanField(
                default=None,
                null=True,
                verbose_name="Est ce que le fichier est infecté",
            ),
        ),
    ]
