# Generated by Django 5.1.7 on 2025-03-26 16:34

from django.db import migrations

# Liste des structures à mettre à jour
# Ancien libellé: Nouveau libellé
STRUCTURES_LIBELLES_UPDATE = {
    "Contacts technique": "Contact technique",
    "BNEVP/BNEVP-RUNGIS": "BNEVP",
    "SAS/PGAS": "PGAS",
    "SAS/SDSBEA": "SDSBEA",
    "SAS/SDSBEA/BBEA": "BBEA",
    "SAS/SDSBEA/BICMA": "BICMA",
    "SAS/SDSBEA/BPRSE": "BPRSE",
    "SAS/SDSBEA/BSA": "BSA",
    "SAS/SDSPV": "SDSPV",
    "SAS/SDSPV/BIB": "BIB",
    "SAS/SDSPV/BSSA": "BSSA",
    "SAS/SDSPV/BSV": "BSV",
    "SAS/SDSPV/DSF": "DSF",
    "SAS/SDSSA": "SDSSA",
    "SAS/SDSSA/BAMRA": "BAMRA",
    "SAS/SDSSA/BEAD": "BEAD",
    "SAS/SDSSA/BEPIAS": "BEPIAS",
    "SAS/SDSSA/BETD": "BETD",
    "SAS/SDSSA/BPMED": "BPMED",
    "SPPSI/SDATAA": "SDATAA",
    "SPPSI/SDATAA/BAPI": "BAPI",
    "SPPSI/SDATAA/BPAL": "BPAL",
    "SPPSI/SDATAA/BTPAD": "BTPAD",
    "SPPSI/SDEIGIR": "SDEIGIR",
    "SPPSI/SDEIGIR/BEPT": "BEPT",
    "SPPSI/SDEIGIR/BGIR": "BGIR",
    "SPPSI/SDEIGIR/BNEM": "BNEM",
    "SPPSI/SDEIGIR/SIVEP": "SIVEP",
    "SPPSI/SDPRS": "SDPRS",
    "SPPSI/SDPRS/BAMOSIAL": "BAMOSIAL",
    "SPPSI/SDPRS/BL": "BL",
    "SPPSI/SDPRS/BPB206": "BPB206",
    "SPPSI/SDPRS/BPE206": "BPE206",
    "SPPSI/SDPRS/BQPPS": "BQPPS",
    "DRAAF-AUVERGNE-RHONE-ALPES": "DRAAF AURA",
    "DRAAF-BOURGOGNE-FRANCHE-COMTE": "DRAAF BFC",
    "DRAAF-BRETAGNE": "DRAAF BRE",
    "DRAAF-CENTRE-VAL-DE-LOIRE": "DRAAF CVL",
    "DRAAF-CORSE": "DRAAF CORSE",
    "DRAAF-GRAND-EST": "DRAAF GES",
    "DRAAF-HAUTS-DE-FRANCE": "DRAAF HDF",
    "DRAAF-ILE-DE-FRANCE": "DRAAF IDF",
    "DRAAF-NORMANDIE": "DRAAF NOR",
    "DRAAF-NOUVELLE-AQUITAINE": "DRAAF NAQ",
    "DRAAF-OCCITANIE": "DRAAF OCC",
    "DRAAF-PACA": "DRAAF PACA",
    "DRAAF-PAYS-DE-LA-LOIRE": "DRAFF PDL",
    "Seves": "SEVES",
}


def normaliser_noms_structures(apps, schema_editor):
    structure_model = apps.get_model("core", "Structure")
    for old_libelle, new_libelle in STRUCTURES_LIBELLES_UPDATE.items():
        structure_model.objects.filter(libelle=old_libelle).update(libelle=new_libelle)


def reverse_normaliser_noms_structures(apps, schema_editor):
    structure_model = apps.get_model("core", "Structure")
    for old_libelle, new_libelle in STRUCTURES_LIBELLES_UPDATE.items():
        structure_model.objects.filter(libelle=new_libelle).update(libelle=old_libelle)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_alter_document_deleted_by_alter_document_description"),
    ]

    operations = [
        migrations.RunPython(normaliser_noms_structures, reverse_normaliser_noms_structures),
    ]
