# Generated by Django 5.1.7 on 2025-03-27 13:33
from django.contrib.auth import get_user_model
from django.db import migrations
from django.contrib.auth.models import Group
from django.conf import settings

User = get_user_model()


def create_and_assign_groups(apps, schema_editor):
    sv_group, _ = Group.objects.get_or_create(name=settings.SV_GROUP)

    for user in User.objects.filter(is_active=True):
        user.groups.add(sv_group)

    Group.objects.get_or_create(name=settings.SSA_GROUP)


def remove_groups(apps, schema_editor):
    Group.objects.filter(name=settings.SV_GROUP).delete()
    Group.objects.filter(name=settings.SSA_GROUP).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_normaliser_noms_structures"),
    ]

    operations = [migrations.RunPython(create_and_assign_groups, remove_groups)]
