# Generated by Django 5.1.7 on 2025-04-08 20:35

import core.storage
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_auto_20250327_1433"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                upload_to=core.storage.get_timestamped_filename,
                validators=[
                    core.validators.validate_upload_file,
                    django.core.validators.FileExtensionValidator(
                        [
                            "png",
                            "jpg",
                            "jpeg",
                            "gif",
                            "pdf",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "odt",
                            "ods",
                            "csv",
                            "qgs",
                            "qgz",
                            "txt",
                            "eml",
                        ]
                    ),
                ],
            ),
        ),
    ]
