# Generated by Django 5.1.8 on 2025-04-24 08:23

from django.db import migrations

REFERENT_NATIONAL_GROUP_NAME = "referent_national"


def create_referent_national_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name=REFERENT_NATIONAL_GROUP_NAME)


def reverse_create_referent_national_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name=REFERENT_NATIONAL_GROUP_NAME).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_alter_document_file"),
    ]

    operations = [
        migrations.RunPython(create_referent_national_group, reverse_create_referent_national_group),
    ]
