# Generated by Django 5.1.8 on 2025-05-23 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_message_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["status", "-date_creation"]},
        ),
    ]
