# Generated by Django 5.2.2 on 2025-06-17 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_alter_document_document_type"),
        ("sv", "0101_move_departement_and_region_to_core"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Region",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "nom",
                            models.CharField(max_length=100, unique=True, verbose_name="Nom"),
                        ),
                    ],
                    options={
                        "verbose_name": "Région",
                        "verbose_name_plural": "Régions",
                        "ordering": ["nom"],
                    },
                ),
                migrations.CreateModel(
                    name="Departement",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "numero",
                            models.CharField(max_length=3, unique=True, verbose_name="Numéro"),
                        ),
                        (
                            "nom",
                            models.CharField(max_length=100, unique=True, verbose_name="Nom"),
                        ),
                        (
                            "region",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                to="core.region",
                                verbose_name="Région",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Département",
                        "verbose_name_plural": "Départements",
                        "ordering": ["numero"],
                        "constraints": [
                            models.UniqueConstraint(fields=("numero", "nom"), name="unique_departement_numero_nom")
                        ],
                    },
                ),
            ],
        ),
    ]
