# Generated by Django 5.2.2 on 2025-06-17 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_move_departement_and_region_to_core"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departement",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.region",
                verbose_name="Région",
            ),
        ),
        migrations.RunSQL("insert into core_departement (numero, nom, region_id) values ('-1', 'Hors France', null);"),
    ]
