# Generated by Django 5.2.3 on 2025-06-27 12:49

import django.db.models.deletion
from django.db import migrations, models


def add_sender_structure(apps, schema_editor):
    Message = apps.get_model("core", "Message")
    for message in Message.objects.all():
        if message.sender.agent:
            message.sender_structure = message.sender.agent.structure
            message.save(update_fields=("sender_structure",))
        elif message.sender.structure:
            message.sender_structure = message.sender.structure
            message.save(update_fields=("sender_structure",))


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_alter_document_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sender_structure",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="messages",
                to="core.structure",
            ),
        ),
        migrations.RunPython(add_sender_structure, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="message",
            name="sender_structure",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="messages",
                to="core.structure",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="messages",
                to="core.contact",
            ),
        ),
    ]
