# Generated by Django 5.2.4 on 2025-08-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_message_sender_structure_alter_message_sender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    (
                        "arrete_prefectoral_ministériel",
                        "Arrêté préfectoral/ministériel",
                    ),
                    ("autre", "Autre document"),
                    ("cartographie", "Cartographie"),
                    ("certificat_phytosanitaire", "Certificat phytosanitaire"),
                    ("compte_rendu_reunion", "Compte rendu de réunion"),
                    ("courrier_officiel", "Courrier officiel"),
                    ("dsce", "DSCE"),
                    ("facture", "Facture"),
                    ("image", "Image"),
                    ("passeport_phytosanitaire", "Passeport phytosanitaire"),
                    ("rapport_analyse", "Rapport d'analyse"),
                    ("rapport_inspection", "Rapport d'inspection"),
                    ("reglementation", "Réglementation"),
                    ("document_de_transport", "Document de transport"),
                    ("tracabilité", "Traçabilité"),
                    ("cerfa", "Signalement/notification : Cerfa"),
                    ("fiche_rasff", "Signalement/notification : Fiche RASFF"),
                    ("signalement_autre", "Signalement/notification : Autre"),
                    ("analyse_risque", "Analyse de risque"),
                    ("tracabilite_interne", "Traçabilité interne"),
                    (
                        "tracabilite_aval_recipient",
                        "Traçabilité aval : « Recipient list »",
                    ),
                    ("tracabilite_aval_autre", "Traçabilité aval : Autre"),
                    ("tracabilite_amont", "Traçabilité amont"),
                    ("dsce_ched", "DSCE/CHED"),
                    ("etiquetage", "Étiquetage"),
                    ("suites_administratives", "Suites administratives"),
                    ("communique_presse", "Communiqué de presse"),
                    ("certificat_sanitaire", "Certificat sanitaire"),
                    ("courriers", "Courriers/courriels"),
                    ("compte_rendu", "Compte-rendu"),
                    ("photo", "Photo (du produit, photo de l’établissement…)"),
                    ("affichette rappel", "Affichette de rappel"),
                ],
                max_length=100,
                verbose_name="Type de document",
            ),
        ),
    ]
