# Generated by Django 5.2.7 on 2025-10-28 08:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_alter_document_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="export",
            name="queryset_sequence",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="export",
            name="object_ids",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), null=True, size=None),
        ),
    ]
