# Generated by Django 5.2.7 on 2025-11-25 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_message_is_deleted"),
        ("reversion", "0002_add_index_on_version_for_content_type_and_db"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomRevisionMetaData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("extra_data", models.JSONField()),
                (
                    "revision",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="reversion.revision"),
                ),
            ],
        ),
    ]
