# Generated by Django 5.2.8 on 2025-12-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_customrevisionmetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="historical_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="message",
            name="historical_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
