# Generated by Django 5.2.8 on 2025-12-16 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_document_historical_data_message_historical_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents_created",
                to="core.agent",
            ),
        ),
    ]
