# Generated by Django 5.2.8 on 2025-12-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_alter_document_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="ssa_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="sv_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="tiac_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("agent__isnull", True),
                    models.Q(
                        ("email__isnull", False),
                        models.Q(("email", ""), _negated=True),
                        models.Q(("sv_email", ""), ("sv_email__isnull", True), _connector="OR"),
                        models.Q(("ssa_email", ""), ("ssa_email__isnull", True), _connector="OR"),
                        models.Q(("tiac_email", ""), ("tiac_email__isnull", True), _connector="OR"),
                    ),
                    _connector="OR",
                ),
                name="contact_agent_email_only",
            ),
        ),
    ]
