# Generated by Django 5.2.8 on 2025-12-17 12:40
from datetime import datetime

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations, models


def create_fake_agent(apps, schema_editor):
    from core.constants import SORA_MIGRATION_FAKE_AGENT

    User = get_user_model()
    Structure = apps.get_model("core", "Structure")
    Agent = apps.get_model("core", "Agent")

    id, _ = User.objects.get_or_create(
        username=SORA_MIGRATION_FAKE_AGENT,
        defaults={
            "first_name": SORA_MIGRATION_FAKE_AGENT,
            "last_name": SORA_MIGRATION_FAKE_AGENT,
            "email": "no-reply@seves.beta.gouv.fr",
            "is_staff": False,
            "is_active": False,
            "date_joined": datetime.fromtimestamp(0),
        },
    )

    structure_id, _ = Structure.objects.get_or_create(
        niveau1=SORA_MIGRATION_FAKE_AGENT, defaults={"libelle": "Fake structure for data coming from SORA"}
    )

    Agent.objects.get_or_create(
        user=id,
        structure=structure_id,
        defaults={
            "prenom": SORA_MIGRATION_FAKE_AGENT,
            "nom": SORA_MIGRATION_FAKE_AGENT,
            "fonction_hierarchique": "",
            "complement_fonction": "",
            "telephone": "",
            "mobile": "",
        },
    )


def delete_fake_agent(apps, schema_editor):
    from core.constants import SORA_MIGRATION_FAKE_AGENT

    User = get_user_model()
    Structure = apps.get_model("core", "Structure")
    Agent = apps.get_model("core", "Agent")

    Agent.objects.get(user__username=SORA_MIGRATION_FAKE_AGENT).delete()
    Structure.objects.get(niveau1=SORA_MIGRATION_FAKE_AGENT).delete()
    User.objects.get(username=SORA_MIGRATION_FAKE_AGENT).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_alter_document_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_fake_agent, reverse_code=delete_fake_agent),
        migrations.AlterField(
            model_name="document",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents_created",
                to="core.agent",
            ),
        ),
    ]
