# Generated by Django 5.2.8 on 2026-01-29 09:47

from django.db import migrations


def add_departement(apps, schema_editor):
    Departement = apps.get_model("core", "Departement")
    Region = apps.get_model("core", "Region")
    regions = [
        (977, "Saint-Barthélemy"),
        (978, "Saint-Martin"),
        (984, "Terres australes et antarctiques françaises"),
        (986, "Wallis-et-Futuna"),
        (987, "Polynésie française"),
        (988, "Nouvelle-Calédonie"),
        (989, "Île de Clipperton"),
    ]

    for code, name in regions:
        region, _ = Region.objects.get_or_create(nom=name)
        Departement.objects.get_or_create(numero=code, defaults={"nom": name, "region": region})


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_alter_document_document_type"),
    ]

    operations = [
        migrations.RunPython(add_departement, migrations.RunPython.noop),
    ]
