# Generated by Django 5.2.8 on 2026-02-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_alter_document_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="force_can_be_contacted",
            field=models.BooleanField(default=False),
        ),
    ]
