# Generated by Django 5.2.11 on 2026-02-12 08:18

from django.db import migrations


def add_departement(apps, schema_editor):
    Departement = apps.get_model("core", "Departement")
    Region = apps.get_model("core", "Region")

    region, _ = Region.objects.get_or_create(nom="Saint-Pierre-et-Miquelon")
    Departement.objects.get_or_create(numero=975, defaults={"nom": "Saint-Pierre-et-Miquelon", "region": region})


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_alter_document_file"),
    ]

    operations = [migrations.RunPython(add_departement, migrations.RunPython.noop)]
