# Generated by Django 5.2.10 on 2026-02-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_auto_20260212_0918"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("avant_sauvegarde", "Avant sauvegarde"),
                    ("brouillon", "Brouillon"),
                    ("finalise", "Finalisé"),
                ],
                default="finalise",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
