# Generated by Django 5.2.11 on 2026-02-23 12:33

import django.core.validators
from django.db import migrations, models

import core.storage
import core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_alter_message_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                max_length=180,
                upload_to=core.storage.get_timestamped_filename,
                validators=[
                    core.validators.AnyOfValidator(
                        django.core.validators.FileExtensionValidator(
                            [
                                "png",
                                "jpg",
                                "jpeg",
                                "gif",
                                "pdf",
                                "doc",
                                "docx",
                                "xls",
                                "xlsx",
                                "odt",
                                "ods",
                                "csv",
                                "qgs",
                                "qgz",
                                "txt",
                                "eml",
                            ]
                        ),
                        core.validators.MagicMimeValidator(),
                    )
                ],
            ),
        ),
    ]
