# Generated by Django 5.2.11 on 2026-03-04 08:08

from django.db import migrations, models


def set_document_sent(apps, schema_editor):
    Document = apps.get_model("core", "Document")
    ContentType = apps.get_model("contenttypes", "ContentType")
    EvenementProduit = apps.get_model("ssa", "EvenementProduit")
    EvenementInvestigationCasHumain = apps.get_model("ssa", "EvenementInvestigationCasHumain")

    content_type_1 = ContentType.objects.get_for_model(EvenementProduit)
    content_type_2 = ContentType.objects.get_for_model(EvenementInvestigationCasHumain)
    base_queryset = Document.objects.filter(
        notification_sent=False, document_type__in=["tracabilite_aval_recipient", "rapport_analyse", "analyse_risque"]
    )
    base_queryset = base_queryset.filter(content_type_id__in=[content_type_1.id, content_type_2.id])
    base_queryset.update(notification_sent=True)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_alter_document_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="notification_sent",
            field=models.BooleanField(
                default=False,
                verbose_name="Est ce qu'une notification a été envoyé suite à l'upload'",
            ),
        ),
        migrations.RunPython(set_document_sent, migrations.RunPython.noop),
    ]
