# Generated by Django 5.2.11 on 2026-03-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_alter_document_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="notification_sent",
            field=models.BooleanField(
                default=False,
                verbose_name="Est-ce qu'une notification a été envoyé suite à l'upload'",
            ),
        ),
    ]
