# Generated by Django 5.2.11 on 2026-03-13 09:35

from django.db import migrations, models
import django.db.models.deletion

REGION_STRUCTURE_MAPPING = {
    "Auvergne-Rhône-Alpes": "DRAAF AURA",
    "Bourgogne-Franche-Comté": "DRAAF BFC",
    "Bretagne": "DRAAF BRE",
    "Centre-Val de Loire": "DRAAF CVL",
    "Corse": "DRAAF CORSE",
    "Grand Est": "DRAAF GES",
    "Hauts-de-France": "DRAAF HDF",
    "Île-de-France": "DRAAF IDF",
    "Normandie": "DRAAF NOR",
    "Nouvelle-Aquitaine": "DRAAF NAQ",
    "Occitanie": "DRAAF OCC",
    "Pays de la Loire": "DRAFF PDL",
    "Provence-Alpes-Côte d'Azur": "DRAAF PACA",
    "Guadeloupe": "DAAF971",
    "Martinique": "DAAF972",
    "Guyane": "DAAF973",
    "La Réunion": "DAAF974",
    "Mayotte": "DAAF976",
}


def add_region_departement_where_needed(apps, schema_editor):
    Structure = apps.get_model("core", "Structure")
    Departement = apps.get_model("core", "Departement")
    Region = apps.get_model("core", "Region")

    for region_name, structure_name in REGION_STRUCTURE_MAPPING.items():
        Structure.objects.filter(libelle=structure_name).update(region=Region.objects.get(nom=region_name))

    for structure in Structure.objects.filter(libelle__startswith="DDETSPP"):
        try:
            structure.departement = Departement.objects.get(numero=structure.libelle.replace("DDETSPP", "").strip())
        except Departement.DoesNotExist:
            continue
        structure.save()
    for structure in Structure.objects.filter(libelle__startswith="DDPP"):
        try:
            structure.departement = Departement.objects.get(numero=structure.libelle.replace("DDPP", "").strip())
        except Departement.DoesNotExist:
            continue
        structure.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_alter_document_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="departement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.departement",
                verbose_name="Département",
            ),
        ),
        migrations.AddField(
            model_name="structure",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.region",
                verbose_name="Région",
            ),
        ),
        migrations.RunPython(add_region_departement_where_needed, migrations.RunPython.noop),
    ]
