# Generated by Django 5.2.11 on 2026-03-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_structure_departement_structure_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Suppression"),
        ),
    ]
