# Generated by Django 5.2.11 on 2026-03-23 08:25

from django.db import migrations


def change_structure_libelle(apps, schema_editor):
    Structure = apps.get_model("core", "Structure")
    Structure.objects.filter(libelle="DRAFF PDL").update(libelle="DRAAF PDL")


def revert_change_structure_libelle(apps, schema_editor):
    Structure = apps.get_model("core", "Structure")
    Structure.objects.filter(libelle="DRAAF PDL").update(libelle="DRAFF PDL")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_alter_document_is_deleted"),
    ]

    operations = [
        migrations.RunPython(change_structure_libelle, revert_change_structure_libelle),
    ]
