# Generated by Django 6.0.3 on 2026-04-08 09:50

from django.db import migrations, models


def copy_date_creation_to_date_publication(apps, schema_editor):
    Message = apps.get_model("core", "Message")
    Message.objects.filter(status="finalise").update(date_publication=models.F("date_creation"))


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0059_auto_20260323_0925"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="date_publication",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de publication"),
        ),
        migrations.AddField(
            model_name="message",
            name="last_updated",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Date de dernière mise à jour",
            ),
        ),
        migrations.RunPython(copy_date_creation_to_date_publication, migrations.RunPython.noop),
    ]
