# Generated by Django 6.0.3 on 2026-04-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0060_message_date_publication_message_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="mimetype",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
