# Generated by Django 6.0.5 on 2026-06-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0061_document_mimetype"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="date_picked",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date sélectionnée par le créateur"),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("message_type", "note"),
                    ("date_picked__isnull", True),
                    _connector="OR",
                ),
                name="date_picked_only_for_note",
            ),
        ),
    ]
