# Generated by Django 6.0.6 on 2026-07-06 09:25

from django.db import migrations
from django.db.models import F


def add_date_publication_notification_ac(apps, schema_editor):
    Message = apps.get_model("core", "Message")
    Message.objects.filter(message_type="notification ac", date_publication__isnull=True).update(
        date_publication=F("date_creation")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0062_message_date_picked_and_more"),
    ]

    operations = [migrations.RunPython(add_date_publication_notification_ac, migrations.RunPython.noop)]
