# Generated by Django 6.0.6 on 2026-07-27 11:57
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_auto_20260706_1125"),
    ]

    operations = [CreateExtension("postgis")]
