# Generated by Django 6.0.7 on 2026-09-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0065_create_sa_group"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contact",
            name="contact_agent_email_only",
        ),
        migrations.AddField(
            model_name="contact",
            name="sa_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("agent__isnull", True),
                    models.Q(
                        ("email__isnull", False),
                        models.Q(("email", ""), _negated=True),
                        models.Q(
                            ("sv_email", ""),
                            ("sv_email__isnull", True),
                            _connector="OR",
                        ),
                        models.Q(
                            ("ssa_email", ""),
                            ("ssa_email__isnull", True),
                            _connector="OR",
                        ),
                        models.Q(
                            ("tiac_email", ""),
                            ("tiac_email__isnull", True),
                            _connector="OR",
                        ),
                        models.Q(
                            ("sa_email", ""),
                            ("sa_email__isnull", True),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="contact_agent_email_only",
            ),
        ),
    ]
