# Generated by Django 6.0.7 on 2026-09-24 12:49

from django.db import migrations, models


def migrate_reglementation_to_autre(apps, schema_editor):
    Document = apps.get_model("core", "Document")
    Document.objects.filter(document_type="reglementation").update(document_type="autre")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0066_remove_contact_contact_agent_email_only_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_reglementation_to_autre, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("arrete_prefectoral_ministériel", "Arrêté préfectoral/ministériel"),
                    ("autre", "Autre document"),
                    ("cartographie", "Cartographie / plans / localisation"),
                    ("certificat_phytosanitaire", "Certificat phytosanitaire"),
                    ("compte_rendu_reunion", "Compte rendu de réunion"),
                    ("courrier_officiel", "Correspondances (courriers, e-mails)"),
                    ("dsce", "DSCE"),
                    ("facture", "Facture"),
                    ("image", "Image/photo"),
                    ("note_technique", "Note technique / Avis / Documentation interne"),
                    ("notification_ue", "Notification UE (Europhyt, iRASFF)"),
                    ("passeport_phytosanitaire", "Passeport phytosanitaire"),
                    ("rapport_analyse", "Rapport d'analyse"),
                    ("rapport_inspection", "Rapport d'inspection"),
                    ("document_de_transport", "Document de transport"),
                    ("tracabilité", "Traçabilité / mouvements / livraisons"),
                    ("cerfa", "Signalement/notification : Cerfa"),
                    ("fiche_rasff", "Signalement/notification : Fiche RASFF"),
                    ("signalement_autre", "Signalement/notification : Autre"),
                    ("signalement_multiple", "Signalement/notification : Cerfa, DO ARS, Autre"),
                    ("enquete_alimentaire", "Enquête alimentaire de l’ARS/SpF"),
                    ("menu", "Menu"),
                    ("analyse_risque", "Analyse de risque"),
                    (
                        "tracabilite_interne_tableau",
                        "Traçabilité interne : tableau de suivi (des productions et autocontrôles)",
                    ),
                    (
                        "tracabilite_interne_justificatif",
                        "Traçabilité interne : justificatif (enregistrement, autocontrôle…)",
                    ),
                    ("tracabilite_aval_recipient", "Traçabilité externe : « Recipient list »"),
                    ("tracabilite_aval_autre", "Traçabilité externe : Autre liste (tableau, relevé)"),
                    ("tracabilite_aval_justificatif", "Traçabilité externe : Justificatif (BL, facture)"),
                    ("dsce_ched", "DSCE/CHED"),
                    ("certificat_sanitaire", "Certificat sanitaire"),
                    ("etiquetage", "Étiquetage (y compris photo)"),
                    ("photo", "Photo (du danger, photo de l’établissement)"),
                    ("affichette rappel", "Affichette de rappel"),
                    ("communique_presse", "Communiqué de presse"),
                    ("courriers", "Courriers/courriels"),
                    ("suites_administratives", "Suites administratives"),
                    ("compte_rendu", "Compte-rendu"),
                    ("fiche_produit", "Fiche produit à risque particulier\xa0: œuf, huitre…"),
                ],
                max_length=100,
                verbose_name="Type de document",
            ),
        ),
    ]
