# Generated by Django 6.0.7 on 2026-09-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0067_alter_document_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="is_in_agricoll",
            field=models.BooleanField(default=True, help_text="Présent dans le dernier export Agricoll"),
        ),
    ]
