# Generated by Django 5.0.3 on 2024-04-11 20:21

from django.db import migrations


ADMINISTRATIONS = ["Administration centrale", "Service régional"]

UNITES_ADMINISTRATION_CENTRALE_NOMS = [
    "Mission des urgences sanitaires",
    "Bureau de la santé des végétaux",
]

UNITES_SERVICE_REGIONAL_NOMS = [
    "DRAAF Auvergne Rhône Alpes",
    "DRAAF Bourgogne Franche Comté",
    "DRAAF Bretagne",
    "DRAAF Centre Val de Loire",
    "DRAAF Corse",
    "DRAAF Grand Est",
    "DAAF Guadeloupe",
    "DAAF Guyane",
    "DRAAF Hauts de France",
    "DRAAF Île de France",
    "DAAF La Réunion",
    "DAAF Martinique",
    "DAAF Mayotte",
    "DRAAF Normandie",
    "DRAAF Nouvelle Aquitaine",
    "DRAAF Occitanie",
    "DRAAF Pays de la Loire",
    "DRAAF Provence Alpes Côte d'Azur",
]

ORGANISMES_NUISIBLES = {
    "OE_ABTV00": "Abaca bunchy top virus",
    "OE_ACNVDU": "Acanthonevra dunlopi",
    "OE_ACANOB": "Acanthoscelides obtectus (bruche du haricot|bruchide des haricots)",
    "OE_1ACARO": "Acarida (Acariens)",
    "OE_ACIEKA": "Acidiella kagoshimensis",
    "OE_ACIXBO": "Acidoxantha bombacis",
    "OE_1ACLRG": "Acleris",
    "OE_ACLRGL": "Acleris gloverana",
    "OE_ACLRIS": "Acleris issikii",
    "OE_ACLRMI": "Acleris minuta (tordeuse à tête jaune)",
    "OE_ACLRNI": "Acleris nishidai",
    "OE_ACLRNV": "Acleris nivisellana",
    "OE_ACLRRO": "Acleris robinsoniana",
    "OE_CROISE": "Acleris semipurpurana",
    "OE_ACLRSE": "Acleris senescens",
    "OE_ACLRVA": "Acleris variana (tordeuse à tête noire de l'épinette)",
    "OE_NUMOPI": "Acrobasis pirivorella",
    "OE_ACRSDI": "Acroceratitis distincta",
    "OE_ACRGCI": "Acrogonia citrina",
    "OE_ACRGVI": "Acrogonia virescens",
    "OE_ACUPFU": "Aculops fuchsiae (phytopte du fuchsia)",
    "OE_1ADRAG": "Adrama",
    "OE_AGRLAX": "Agrilus anxius (agrile du bouleau|perceur doré du bouleau)",
    "OE_AGRLPL": "Agrilus planipennis (agrile du frêne)",
    "OE_1AGRBG": "Agrobacterium",
    "OE_AGRBTU": "Agrobacterium tumefaciens (broussin|galle du collet|tumeur du collet)",
    "OE_ALECCT": "Aleurocanthus citriperdus",
    "OE_ALECSN": "Aleurocanthus spiniferus (aleurode épineux du citronnier)",
    "OE_ALECWO": "Aleurocanthus woglumi (aleurode noir des agrumes)",
    "OE_ALTHFL": "Aleurothrixus floccosus",
    "OE_ALTELI": "Alternaria linicola (moisissure verte du lin)",
    "OE_APLPV0": "American plum line pattern virus",
    "OE_1ANSTG": "Anastrepha",
    "OE_TOXTCU": "Anastrepha curvicauda",
    "OE_ANSTFR": "Anastrepha fraterculus (mouche des fruits sud-américaine)",
    "OE_ANSTLU": "Anastrepha ludens (mouche mexicaine des fruits)",
    "OE_ANSTOB": "Anastrepha obliqua (mouche antillaise des fruits)",
    "OE_ANSTRE": "Anastrepha recurcauda",
    "OE_ANSTSU": "Anastrepha suspensa (mouche des fruits caribéenne)",
    "OE_APLV00": "Andean potato latent virus",
    "OE_APMMV0": "Andean potato mild mosaic virus",
    "OE_APMOV0": "Andean potato mottle virus",
    "OE_CRSPAN": "Anisogramma anomala (brûlure orientale du noisetier)",
    "OE_ANOLCN": "Anoplophora chinensis (capricorne à points blancs|capricorne asiatique des agrumes)",
    "OE_ANOLGL": "Anoplophora glabripennis (capricorne asiatique|longicorne asiatique)",
    "OE_ANTHBI": "Anthonomus bisignifer",
    "OE_ANTHEU": "Anthonomus eugenii",
    "OE_ANTHGR": "Anthonomus grandis grandis (anthonome du cotonnier|charançon américain de la capsule|charançon du cotonnier)",
    "OE_TACYQU": "Anthonomus quadrigibbus (charançon de la pomme)",
    "OE_ANTHSI": "Anthonomus signatus (anthonome de la fleur du fraisier|charançon du fraisier)",
    "OE_APLOBE": "Aphelenchoides besseyi (nématode du bout blanc du riz|nématode foliaire du riz)",
    "OE_APLOBL": "Aphelenchoides blastophthorus",
    "OE_APLOFR": "Aphelenchoides fragariae (anguillule du fraisier et des fougères)",
    "OE_APLORI": "Aphelenchoides ritzemabosi (anguillule des chrysanthèmes)",
    "OE_TOXOCI": "Aphis citricidus (puceron brun des agrumes|puceron toxoptère citricide|puceron tropical de l'oranger)",
    "OE_1APHRG": "Aphrophora",
    "OE_APHRAN": "Aphrophora angulata",
    "OE_APHRPE": "Aphrophora permutata",
    "OE_DIBOMO": "Apiosporina morbosa (nodule noir du cerisier|nodule noir du pêcher|nodule noir du prunier)",
    "OE_APCF00": "Apple chat fruit agent (fruit atrophié du pommier)",
    "OE_ACLSV0": "Apple chlorotic leaf spot virus",
    "OE_ADFVD0": "Apple dimple fruit viroid",
    "OE_AFL000": "Apple flat limb agent",
    "OE_AFCVD0": "Apple fruit crinkle viroid",
    "OE_APGC00": "Apple green crinkle agent (green crinkle des pommes)",
    "OE_APLP00": "Apple leaf pucker agent",
    "OE_APMV00": "Apple mosaic virus",
    "OE_APNMV0": "Apple necrotic mosaic virus",
    "OE_APRSK0": "Apple rough skin agent",
    "OE_ARW000": "Apple rubbery wood agent",
    "OE_ASSVD0": "Apple scar skin viroid",
    "OE_APHW00": "Apple star crack agent",
    "OE_ASGV00": "Apple stem grooving virus",
    "OE_ASPV00": "Apple stem pitting virus",
    "OE_ALV000": "Apricot latent virus",
    "OE_APRICI": "Apriona cinerea",
    "OE_APRIGE": "Apriona germari",
    "OE_APRIJA": "Apriona rugicollis (capricorne du mûrier)",
    "OE_ARMV00": "Arabis mosaic virus",
    "OE_1AREG": "Arceuthobium",
    "OE_ARMIME": "Armillaria mellea (armillaire couleur de miel|armillaire obscure|blanc des racines|pourridié agaric|pourridié des racines)",
    "OE_AROMBU": "Aromia bungii",
    "OE_AVBO00": "Arracacha virus B oca strain",
    "OE_ARRHMI": "Arrhenodes minutus (charançon du chêne)",
    "OE_ASCXEP": "Aschistonyx eppoi (cécidomyie du genévrier)",
    "OE_ASIMPA": "Asimoneura pantomelas",
    "OE_1ATRPG": "Atropellis",
    "OE_AUSHPR": "Austrotephritis protrusa",
    "OE_1BACTK": "Bacteria (Bactéries)",
    "OE_PARZCO": "Bactericera cockerelli (psylle de la pomme de terre|psylle de la tomate)",
    "OE_1BCTRG": "Bactrocera",
    "OE_DACUDO": "Bactrocera dorsalis (mouche des fruits asiatique|mouche orientale des fruits)",
    "OE_DACULA": "Bactrocera latifrons",
    "OE_DACUTR": "Bactrocera tryoni (mouche des fruits de Queensland)",
    "OE_DACUTS": "Bactrocera tsuneonis (mouche du citronnier)",
    "OE_DACUZO": "Bactrocera zonata",
    "OE_BBRMV0": "Banana bract mosaic virus",
    "OE_BBTV00": "Banana bunchy top virus (sommet touffu du bananier)",
    "OE_BANMMV": "Banana mild mosaic virus",
    "OE_BSV000": "Banana streak virus",
    "OE_BCTV00": "Beet curly top virus",
    "OE_BNYVV0": "Beet necrotic yellow vein virus (rhizomanie de la betterave)",
    "OE_1BEGOG": "Begomovirus",
    "OE_BEMITA": "Bemisia tabaci (aleurode|aleurode de la patate douce|aleurode du cotonnier|aleurode du tabac)",
    "OE_BISRFO": "Bistrispinaria fortis",
    "OE_BISRMA": "Bistrispinaria magniceps",
    "OE_BRAV00": "Blackcurrant reversion virus",
    "OE_BRNV00": "Black raspberry necrosis virus",
    "OE_BLMOV0": "Blueberry leaf mottle virus",
    "OE_BLMAV0": "Blueberry mosaic associated ophiovirus",
    "OE_BRRV00": "Blueberry red ringspot virus",
    "OE_BLSCV0": "Blueberry scorch virus",
    "OE_BLSHV0": "Blueberry shock virus",
    "OE_BSSV00": "Blueberry shoestring virus",
    "OE_PHOMEL": "Boeremia linicola (mort lin)",
    "OE_PHYOPI": "Botryosphaeria kuwatsukai",
    "OE_BOTRCI": "Botrytis cinerea (Botrytis de l'oeil|cinérite|grillure des feuilles|maladie de la toile|moisissure commune|moisissure grise|pourriture grise)",
    "OE_CERAFA": "Bretziella fagacearum (flétrissement américain du chêne)",
    "OE_BRCHPI": "Bruchus pisorum (bruche du pois|bruchide des pois)",
    "OE_BRCHRU": "Bruchus rufimanus (bruche de la fève|bruche de la gourgane|bruche des fèves)",
    "OE_BUCLXA": "Bucephalogonia xanthophis",
    "OE_PHYP77": "Buckland valley grapevine yellows phytoplasma",
    "OE_BURSXY": "Bursaphelenchus xylophilus (dépérissement des pins|nématode du bois de pin|nématode du pin)",
    "OE_CLMYFL": "Callistomyia flavilabris",
    "OE_CAMGAL": "Campiglossa albiceps",
    "OE_CAMGCA": "Campiglossa californica",
    "OE_CAMGDU": "Campiglossa duplex",
    "OE_CAMGRE": "Campiglossa reticulata",
    "OE_CAMGSN": "Campiglossa snowi",
    "OE_LIBEAF": "Candidatus Liberibacter africanus (greening des agrumes|virescence des agrumes)",
    "OE_LIBEAM": "Candidatus Liberibacter americanus",
    "OE_LIBEAS": "Candidatus Liberibacter asiaticus (greening des agrumes)",
    "OE_LIBEPS": "Candidatus Liberibacter solanacearum",
    "OE_PHMBFR": "Candidatus Phlomobacter fragariae",
    "OE_PHYPAE": "Candidatus Phytoplasma americanum",
    "OE_PHYPAS": "Candidatus Phytoplasma asteris (jaunisse de l'aster)",
    "OE_PHYPAF": "Candidatus Phytoplasma aurantifolia",
    "OE_PHYPAU": "Candidatus Phytoplasma australiense",
    "OE_PHYPFG": "Candidatus Phytoplasma fragariae",
    "OE_PHYPFR": "Candidatus Phytoplasma fraxini",
    "OE_PHYP07": "Candidatus Phytoplasma hispanicum",
    "OE_PHYPMA": "Candidatus Phytoplasma mali (proliférations du pommier)",
    "OE_PHYPPH": "Candidatus Phytoplasma phoenicium",
    "OE_PHYPPN": "Candidatus Phytoplasma pruni (maladie X du pêcher)",
    "OE_PHYPPR": "Candidatus Phytoplasma prunorum (dépérissement de Molières|enroulement chlorotique de l'abricotier)",
    "OE_PHYPPY": "Candidatus Phytoplasma pyri (dépérissement du poirier|flétrissement du poirier)",
    "OE_PHYPRU": "Candidatus Phytoplasma rubi",
    "OE_PHYPSO": "Candidatus Phytoplasma solani (bois noir de la vigne|dépérissement de la lavande)",
    "OE_PHYPUL": "Candidatus Phytoplasma ulmi (nécrose du liber de l'orme)",
    "OE_PHYPZI": "Candidatus Phytoplasma ziziphi",
    "OE_CARYIN": "Carpomya incompleta",
    "OE_CARSSA": "Carposina sasakii (carpocapse du pêcher)",
    "OE_ERPHRI": "Cecidophyopsis ribis (phytopte du groseillier)",
    "OE_CEPCAL": "Cephalcia lariciphila",
    "OE_1CERTG": "Ceratitis",
    "OE_CERTCA": "Ceratitis capitata (mouche de l'oranger|mouche des fruits|mouche méditerranéenne|mouche méditerranéenne des fruits)",
    "OE_CERTQU": "Ceratitis quinaria",
    "OE_CERTRO": "Ceratitis rosa (mouche des fruits du Natal)",
    "OE_CERAPA": "Ceratocystis paradoxa (pourriture couronnée du bananier|pourriture couronnée du palmier-dattier|pourriture noire de l'ananas)",
    "OE_CERAFP": "Ceratocystis platani (chancre coloré du platane|tache chancreuse du platane)",
    "OE_CRTZCL": "Ceratothripoides claratris",
    "OE_1CERCF": "Cercopidae",
    "OE_1CERCP": "Cercozoa",
    "OE_CERPRU": "Ceroplastes rusci (céroplaste du figuier|cochenille du figuier)",
    "OE_CHTSFR": "Chaetosiphon fragaefolii (puceron du fraisier|puceron jaune du fraisier)",
    "OE_CGRMV0": "Cherry green ring mottle virus",
    "OE_CLRV00": "Cherry leaf roll virus",
    "OE_CMLV00": "Cherry mottle leaf virus",
    "OE_CRNRM0": "Cherry necrotic rusty mottle virus (mosaïque rouge nécrotique du cerisier)",
    "OE_CRLV00": "Cherry rasp leaf virus (feuilles râpeuses du cerisier)",
    "OE_CRV000": "Cherry rosette virus",
    "OE_CRMAV0": "Cherry rusty mottle associated virus",
    "OE_CTLAV0": "Cherry twisted leaf associated virus",
    "OE_CHILCU": "Chilli leaf curl virus",
    "OE_HELIVI": "Chloridea virescens (phalène verdoyante)",
    "OE_STERPU": "Chondrostereum purpureum (chondrostéréum pourpré|plomb des arbres fruitiers|plomb parasitaire|stéréum pourpré)",
    "OE_1CHONG": "Choristoneura",
    "OE_CHONCA": "Choristoneura carnana",
    "OE_ARCHCO": "Choristoneura conflictana (tordeuse du tremble)",
    "OE_CHONFU": "Choristoneura fumiferana (tordeuse des bourgeons de l'épicéa|tordeuse des bourgeons de l'épinette|ver du bourgeon de l'épinette)",
    "OE_TORTLA": "Choristoneura lambertiana",
    "OE_CHONBI": "Choristoneura occidentalis biennis (tordeuse bisannuelle de l'épinette)",
    "OE_ARCHOC": "Choristoneura occidentalis occidentalis (tordeuse occidentale de l'épinette)",
    "OE_CHONOR": "Choristoneura orae",
    "OE_CHONPA": "Choristoneura parallela",
    "OE_CHONPI": "Choristoneura pinus pinus (tordeuse du pin gris)",
    "OE_CHONRE": "Choristoneura retiniana",
    "OE_CHONRO": "Choristoneura rosaceana (cigareuse à bande oblique|tordeuse à bandes obliques)",
    "OE_CSNV00": "Chrysanthemum stem necrosis virus",
    "OE_CSVD00": "Chrysanthemum stunt viroid (rabougrissement du chrysanthème)",
    "OE_CHMYAR": "Chrysomyxa arctostaphyli",
    "OE_1CICLG": "Cicadella",
    "OE_1CICDF": "Cicadellidae",
    "OE_CICSV0": "Citrus chlorotic spot dichorhavirus",
    "OE_CSCC00": "Citrus cristacortis agent",
    "OE_CEVD00": "Citrus exocortis viroid",
    "OE_CSI000": "Citrus impietratura agent",
    "OE_CLBV00": "Citrus leaf blotch virus",
    "OE_CILVN0": "Citrus leprosis N dichorhavirus",
    "OE_CILVC0": "Citrus leprosis virus C",
    "OE_CILVC2": "Citrus leprosis virus C2",
    "OE_CILV00": "Citrus leprosis virus sensu lato (léprose des agrumes)",
    "OE_CPSV00": "Citrus psorosis ophiovirus (psorose écailleuse des agrumes)",
    "OE_CTV000": "Citrus tristeza virus (tristeza des agrumes)",
    "OE_CVV000": "Citrus variegation virus",
    "OE_CLASAC": "Clastoptera achatina",
    "OE_CLASBR": "Clastoptera brunnea",
    "OE_CORBIN": "Clavibacter insidiosus (flétrissement bactérien de la luzerne|jaunissement bactérien de la luzerne)",
    "OE_CORBMI": "Clavibacter michiganensis subsp. michiganensis (chancre bactérien de la tomate)",
    "OE_CORBSE": "Clavibacter sepedonicus (bactériose annulaire de la pomme de terre|flétrissement bactérien de la pomme de terre|pourriture annulaire de la p de terre)",
    "OE_PHYP03": "Clover phyllody phytoplasma",
    "OE_CCCVD0": "Coconut cadang-cadang viroid",
    "OE_PHYP56": "Coconut lethal yellowing phytoplasma (jaunisse létale des palmiers|jaunissement mortel du cocotier|pourriture du bourgeon terminal du cocotier)",
    "OE_COLLAC": "Colletotrichum acutatum (anthracnose du fraisier|taches noires du fraisier)",
    "OE_COLLLI": "Colletotrichum lini (anthracnose du lin-graine)",
    "OE_CLVD00": "Columnea latent viroid",
    "OE_QUADPE": "Comstockaspis perniciosa (pou de San José)",
    "OE_PHELSU": "Coniferiporia sulphurascens",
    "OE_INONWE": "Coniferiporia weirii (pourridié des racines des conifères)",
    "OE_CONHNE": "Conotrachelus nenuphar (charançon américain du prunier|charançon de la prune)",
    "OE_CPMMV0": "Cowpea mild mottle virus",
    "OE_PHYPFB": "Cranberry false blossom phytoplasma",
    "OE_CRSXMA": "Craspedoxantha marginalis",
    "OE_1CRONG": "Cronartium",
    "OE_ENDOPA": "Cryphonectria parasitica (chancre de l'écorce du châtaignier|chancre du châtaignier|maladie chancreuse du châtaignier)",
    "OE_CMV000": "Cucumber mosaic virus (mosaïque à tirets|mosaïque du concombre)",
    "OE_CUERCO": "Cuerna costalis",
    "OE_CUEROC": "Cuerna occidentalis",
    "OE_CORBFL": "Curtobacterium flaccumfaciens pv. flaccumfaciens (bactériose vasculaire du haricot|flétrissement bactérien du haricot)",
    "OE_CYPACG": "Cyphonia clavigera",
    "OE_1DACUG": "Dacus",
    "OE_DACUCI": "Dacus ciliatus (mouche éthiopienne des cucurbitacées)",
    "OE_VITEVI": "Daktulosphaira vitifoliae (phylloxéra de la vigne)",
    "OE_DASYTE": "Dasineura tetensi (cécidomyie des feuilles de cassis|cécidomyie des pousses de cassisier|cécidomyie du cassissier)",
    "OE_CERAVI": "Davidsoniella virescens",
    "OE_ONCMMI": "Dechacona missionum",
    "OE_DENCMI": "Dendroctonus micans (dendroctone|hylésine géant)",
    "OE_DENDSI": "Dendrolimus sibiricus",
    "OE_DIABLO": "Diabrotica barberi (chrysomèle des racines du maïs)",
    "OE_DIABUH": "Diabrotica undecimpunctata howardi (chrysomèle maculée du concombre)",
    "OE_DIABUN": "Diabrotica undecimpunctata undecimpunctata",
    "OE_DIABVZ": "Diabrotica virgifera zeae",
    "OE_DIAACI": "Diaphorina citri (psylle de l'oranger)",
    "OE_DIAPPC": "Diaporthe caulivora (chancre de la tige du soja)",
    "OE_DIAPPS": "Diaporthe sojae (brûlure du soja|brûlure phomopsienne du soja|phomopsis du soja)",
    "OE_DIAPST": "Diaporthe strumella",
    "OE_DIAPVA": "Diaporthe vaccinii (brûlure phomopsienne de la myrtille|chancre phomopsien de la myrtille)",
    "OE_1DICKG": "Dickeya",
    "OE_DLBPCO": "Dilobopterus costalimai",
    "OE_MARGME": "Dimargarodes meridionalis",
    "OE_DIOXCH": "Dioxyna chilensis",
    "OE_TRYEMU": "Dirioxa pornia",
    "OE_DITYDE": "Ditylenchus destructor (maladie vermiculaire de la pomme de terre|nématode de la pomme de terre)",
    "OE_DITYDI": "Ditylenchus dipsaci (anguillule commune des tiges|anguillule des céreales et des bulbes|avoine poireautée|nématode des bulbes|nématode des tiges)",
    "OE_DOTSPI": "Dothistroma pini",
    "OE_SCIRPI": "Dothistroma septosporum (bandes rouges du pin|strie rouge des aiguilles du pin)",
    "OE_DRAEMI": "Draeculacephala minerva",
    "OE_DRAERO": "Draeculacephala robinsoni",
    "OE_DRAESP": "Draeculacephala sp.",
    "OE_DROSSU": "Drosophila suzukii (drosophile à ailes tachetées|drosophile du cerisier)",
    "OE_DRYCKU": "Dryocosmus kuriphilus (chalcide du châtaignier|cynips du châtaignier)",
    "OE_ELSIAU": "Elsinoë australis (anthracnose de l'oranger|gale des agrumes)",
    "OE_ELSICI": "Elsinoë citricola",
    "OE_ELSIFA": "Elsinoë fawcettii (gale commune des agrumes|scab des agrumes|verrues des agrumes)",
    "OE_HYPOMA": "Entoleuca mammata (chancre du peuplier|chancre du tremble)",
    "OE_EOTELE": "Eotetranychus lewisi",
    "OE_EPIDBE": "Epidiaspis leperii (cochenille rouge du poirier|diaspis du poirier)",
    "OE_1EPIXG": "Epitrix",
    "OE_EPIXCU": "Epitrix cucumeris (altise de la pomme de terre)",
    "OE_EPIXPP": "Epitrix papa",
    "OE_EPIXSI": "Epitrix similaris (altise américaine de la pomme de terre)",
    "OE_EPIXSU": "Epitrix subcrinita (altise de la pomme de terre de l'ouest)",
    "OE_EPIXTU": "Epitrix tuberis (altise des tubercules)",
    "OE_ERISLA": "Eriosoma lanigerum (puceron lanigère|puceron lanigère du pommier)",
    "OE_ERWIAM": "Erwinia amylovora (brûlure bactérienne du poirier|brûlure bactérienne du pommier|feu bactérien)",
    "OE_EULISE": "Euleia separata",
    "OE_EUMGLA": "Eumargarodes laingi",
    "OE_EPHNCA": "Euphranta camelliae",
    "OE_EPOCCA": "Euphranta canadensis (mouche du groseillier|ver des grappes de groseille)",
    "OE_RHACCA": "Euphranta cassiae",
    "OE_RHACJA": "Euphranta japonica (mouche japonaise du cerisier)",
    "OE_EPHNOS": "Euphranta oshimensis",
    "OE_EURHBR": "Eurhizococcus brasiliensis",
    "OE_EURHCO": "Eurhizococcus colombianus",
    "OE_EUOSSO": "Eurosta solidaginis",
    "OE_1EUTTG": "Eutreta",
    "OE_XYLBFO": "Euwallacea fornicatus sensu lato (scolyte du théier)",
    "OE_EXOBVA": "Exobasidium vaccinii (fausse cloque de l'airelle|rouge de l'airelle)",
    "OE_ANMLOR": "Exomala orientalis",
    "OE_FRRATR": "Ferrariana trivittata",
    "OE_FGM000": "Fig mosaic agent",
    "OE_FINGDU": "Fingeriana dubia",
    "OE_FRISFR": "Friscanus friscanus",
    "OE_1FUNGK": "Fungi (Champignons)",
    "OE_1FUSAG": "Fusarium",
    "OE_GIBBCI": "Fusarium circinatum (chancre résineux du pin|chancre suintant du pin)",
    "OE_GIBBFU": "Fusarium fujikuroi (fusariose de la tige du mais, du blé, moniliforme|gigantisme du riz|pourriture des tiges du mais|tache fusarienne de l'oignon)",
    "OE_FUSAC4": "Fusarium odoratissimum",
    "OE_FUSAAL": "Fusarium oxysporum f. sp. albedinis (maladie du bayoud du palmier dattier)",
    "OE_GASZNI": "Gastrozona nigrifemur",
    "OE_GEOHMO": "Geosmithia morbida",
    "OE_GILPPO": "Gilpinia hercyniae (tenthrède européenne de l'épinette)",
    "OE_HETDPA": "Globodera pallida (nématode blanc de la pomme de terre)",
    "OE_HETDRO": "Globodera rostochiensis (anguillule à kyste de la pomme de terre|anguillule des racines de la pomme de terre|nématode doré de la pomme de terre)",
    "OE_GLOMCI": "Glomerella cingulata (anthracnose de l'amandier|anthracnose de la tomate, de l'aubergine, du piment|anthracnose des agrumes|anthracnose des pommes)",
    "OE_GLOMGO": "Glomerella gossypii (anthracnose du cotonnier)",
    "OE_GODRCA": "Godronia cassandrae (chancre de l'airelle)",
    "OE_GOEDST": "Goedenia stenoparia",
    "OE_GONPSC": "Gonipterus scutellatus species complex (charançon de l'eucalyptus)",
    "OE_GOVB00": "Gooseberry vein banding associated virus",
    "OE_GINV00": "Grapevine berry inner necrosis virus",
    "OE_GFLV00": "Grapevine fanleaf virus (court-noué de la vigne)",
    "OE_PHYP64": "Grapevine flavescence dorée phytoplasma (flavescence dorée de la vigne|rougeau)",
    "OE_GFKV00": "Grapevine fleck virus (marbrure de la vigne)",
    "OE_GLRAV1": "Grapevine leafroll-associated virus 1",
    "OE_GLRAV3": "Grapevine leafroll-associated virus 3",
    "OE_GRBAV0": "Grapevine red blotch virus",
    "OE_GVCV00": "Grapevine vein clearing virus",
    "OE_GRCPAT": "Graphocephala atropunctata",
    "OE_GRCPCF": "Graphocephala confluens",
    "OE_GRCPVE": "Graphocephala versuta",
    "OE_CYDIIN": "Grapholita inopinata",
    "OE_LASPPA": "Grapholita packardi (phalène des cerises)",
    "OE_LASPPR": "Grapholita prunivora (petite pyrale de la pomme)",
    "OE_GREMAB": "Gremmeniella abietina (chancre des résineux|chancre gremmenielléen|chancre scléroderrien|dépérissement des résineux|déssèchement des rameaux de pin)",
    "OE_GYMRSP": "Gymnocarena sp.",
    "OE_1GYMNG": "Gymnosporangium",
    "OE_MYNDCR": "Haplaxius crudus",
    "OE_HLCBBR": "Helicobasidium brebissonii (mort du safran|pourriture violette des légumineuses fourragères|rhizoctone de la luzerne|rhizoctone violet)",
    "OE_HELIAR": "Helicoverpa armigera (chenille des épis du maïs|noctuelle de la tomate|ver de la capsule)",
    "OE_HELIZE": "Helicoverpa zea (chenille des épis du maïs|noctuelle des tomates|ver de la capsule)",
    "OE_HELHDE": "Helochara delta",
    "OE_HETDFI": "Heterodera fici",
    "OE_HGSV20": "Hibiscus green spot virus 2",
    "OE_1HIRSG": "Hirschmanniella",
    "OE_HISHPH": "Hishimonus phycitis",
    "OE_HOMLIG": "Homalodisca ignorata",
    "OE_HOMLIN": "Homalodisca insolita",
    "OE_HOMLTR": "Homalodisca vitripennis (cicadelle pisseuse)",
    "OE_HSVD00": "Hop stunt viroid (xyloporose des agrumes)",
    "OE_INSV00": "Impatiens necrotic spot virus",
    "OE_1INSEC": "Insecta (Insectes)",
    "OE_INZWOB": "Insizwa oblita",
    "OE_IPSXAM": "Ips amitinus (petit bostryche du pin)",
    "OE_IPSXCE": "Ips cembrae (grand bostryche du mélèze)",
    "OE_IPSXDU": "Ips duplicatus",
    "OE_IPSXSE": "Ips sexdentatus (grand rongeur du pin|sténographe)",
    "OE_IPSXTY": "Ips typographus (bostryche typographe|grand rongeur de l'épicéa|grand scolyte de l'épicéa|scolyte typographe|typographe)",
    "OE_GNORLY": "Keiferia lycopersicella (mineuse de la tomate)",
    "OE_SCIRAC": "Lecanosticta acicola (tache brune des aiguilles du pin)",
    "OE_LYSV00": "Leek yellow stripe virus",
    "OE_LPTNDE": "Leptinotarsa decemlineata (chrysomèle de la pomme de terre|doryphore|doryphore de la pomme de terre)",
    "OE_LEPOCO": "Lepyronia coleoptrata",
    "OE_LEPOQU": "Lepyronia quadrangularis (cercope quadrangulaire)",
    "OE_LIYV00": "Lettuce infectious yellows virus",
    "OE_LEUIOR": "Leucinodes orbonalis (perceuse de l'aubergine)",
    "OE_LEUIPS": "Leucinodes pseudorbonalis",
    "OE_LIRIBO": "Liriomyza bryoniae",
    "OE_LIRIHU": "Liriomyza huidobrensis (mouche mineuse sud américaine)",
    "OE_LIRISA": "Liriomyza sativae",
    "OE_LIRITR": "Liriomyza trifolii (mineuse du gerbéra|mouche mineuse californienne)",
    "OE_HYROBO": "Listronotus bonariensis (charançon argentin des tiges)",
    "OE_LCHV10": "Little cherry virus 1 (petite cerise)",
    "OE_LCHV20": "Little cherry virus 2",
    "OE_LONGAT": "Longidorus attenuatus",
    "OE_LONGDI": "Longidorus diadecturus",
    "OE_LONGEL": "Longidorus elongatus",
    "OE_LONGMA": "Longidorus macrosoma",
    "OE_LOPLJA": "Lopholeucaspis japonica (kermès japonais)",
    "OE_LYCMDE": "Lycorma delicatula (fulgore tacheté)",
    "OE_MAGOCA": "Macugonalia cavifrons",
    "OE_MAGOLE": "Macugonalia leucomelas",
    "OE_1MARGG": "Margarodes",
    "OE_MARGCA": "Margarodes capensis",
    "OE_MARGGR": "Margarodes greeni",
    "OE_MARGPR": "Margarodes prieskaensis (perles de terre)",
    "OE_MARGTR": "Margarodes trimeni",
    "OE_MARGVI": "Margarodes vitis (cochenille des vignes|cochenille du Chili|perles de terre)",
    "OE_MARGVR": "Margarodes vredendalensis (perles de terre)",
    "OE_MARREX": "Marriottella exquisita",
    "OE_MALLRA": "Massicus raddei (capricorne du châtaignier)",
    "OE_MELMFA": "Melampsora farlowii",
    "OE_MELMMT": "Melampsora medusae f. sp. tremuloidis",
    "OE_MELGAR": "Meloidogyne arenaria",
    "OE_MELGCH": "Meloidogyne chitwoodi (nématode cécidogène du Columbia)",
    "OE_MELGMY": "Meloidogyne enterolobii",
    "OE_MELGFA": "Meloidogyne fallax",
    "OE_MELGHA": "Meloidogyne hapla (nématode à galles des racines)",
    "OE_MELGIN": "Meloidogyne incognita (anguillule à noeud de la patate)",
    "OE_MELGJA": "Meloidogyne javanica (anguillule javanaise à noeud des racines)",
    "OE_MYAV00": "Melon yellowing-associated virus",
    "OE_MCRSGR": "Microsphaera grossulariae (oïdium blanc du groseillier|oïdium européen du groseillier)",
    "OE_1MOLLP": "Mollusca (Mollusques)",
    "OE_MOLMCO": "Molomea consolida",
    "OE_MNAHCI": "Monacrostichus citricola",
    "OE_1MONCG": "Monochamus",
    "OE_MYCOLL": "Mycodiella laricis-leptolepidis",
    "OE_CARYPA": "Myiopardalis pardalina",
    "OE_MLRSV0": "Myrobalan latent ringspot virus",
    "OE_NACOBA": "Nacobbus aberrans",
    "OE_GRAGLE": "Naupactus leucoloma",
    "OE_NEAIAL": "Neaspilota alba",
    "OE_NEAIRE": "Neaspilota reticulata",
    "OE_1NEMAP": "Nematoda (Nématodes)",
    "OE_AMAZMA": "Nemorimyza maculosa",
    "OE_CERTCY": "Neoceratitis cyanescens",
    "OE_FUSAAM": "Neocosmospora ambrosia",
    "OE_FUSAEW": "Neocosmospora euwallaceae",
    "OE_PEZIMA": "Neofabraea malicorticis (anthracnose du pêcher, du poirier, du pommier|chancre annuel de l'Oregon|chancre pérennant|pourriture concentrique pommier)",
    "OE_GUIGLA": "Neofusicoccum laricinum",
    "OE_GRCPHI": "Neokolla hieroglyphica",
    "OE_NKOLSE": "Neokolla severini",
    "OE_NEOLEL": "Neoleucinodes elegantalis (petit foreur de la tomate)",
    "OE_NECTGA": "Neonectria ditissima (brûlure des pousses du hêtre|chancre des arbres fruitiers à pépins|chancre européen du poirier|chancre européen du pommier)",
    "OE_1NEOPG": "Neophilaenus",
    "OE_OEMOHI": "Oemona hirta",
    "OE_OLIGPD": "Oligonychus perditus",
    "OE_OLYAV0": "Olive leaf yellowing-associated virus",
    "OE_OVYAV0": "Olive vein yellowing associated virus",
    "OE_OYMDAV": "Olive yellow mottling and decline associated virus",
    "OE_ONCMFA": "Oncometopia facialis",
    "OE_ONCMNI": "Oncometopia nigricans",
    "OE_ONCMUN": "Oncometopia orbona",
    "OE_OYDV00": "Onion yellow dwarf virus",
    "OE_1OOMYC": "Oomycetes",
    "OE_OPOGSC": "Opogona sacchari (teigne du bananier)",
    "OE_ORAGDI": "Oragua discoidula",
    "OE_OFV000": "Orchid fleck dichorhavirus",
    "OE_PGARCO": "Pagaronia confusa",
    "OE_PGARFU": "Pagaronia furcata",
    "OE_PGARTR": "Pagaronia tredecimpunctata",
    "OE_PGARTN": "Pagaronia triunata",
    "OE_ERWIST": "Pantoea stewartii subsp. stewartii (flétrissement bactérien du maïs|maladie de Stewart)",
    "OE_PRABMY": "Parabemisia myricae",
    "OE_PCANTR": "Paracantha trinotata",
    "OE_PSTELI": "Parastenopa limata",
    "OE_PTEPFU": "Paratephritis fukaii",
    "OE_PTEPTA": "Paratephritis takeuchii",
    "OE_PTLLVA": "Paraterellia varipennis",
    "OE_PTHOGR": "Parathona gratiosa",
    "OE_PAYSAR": "Paysandisia archon (papillon du palmier|papillon palmivore)",
    "OE_PLMVD0": "Peach latent mosaic viroid (mosaïque latente du pêcher)",
    "OE_PCMV00": "Peach mosaic virus (mosaïque américaine du pêcher)",
    "OE_PRMV00": "Peach rosette mosaic virus",
    "OE_PRBN00": "Pear bark necrosis agent",
    "OE_PRBS00": "Pear bark split agent",
    "OE_PBCVD0": "Pear blister canker viroid",
    "OE_PRRB00": "Pear rough bark agent",
    "OE_1PECBG": "Pectobacterium",
    "OE_PEPMV0": "Pepino mosaic virus",
    "OE_PERORU": "Peronospora rubi",
    "OE_PHILSU": "Philaenus spumarius",
    "OE_PHIPFO": "Philophylla fossata",
    "OE_PEZIAL": "Phlyctema vagabunda (anthracnose d'entrepôt de la poire|anthracnose d'entrepôt de la pomme|anthracnose des pommes)",
    "OE_PHYSCA": "Phyllosticta cavendishii (black spot du bananier|moucheture noire du bananier|taches noires du bananier)",
    "OE_GUIGCI": "Phyllosticta citricarpa (taches noires des agrumes|taches noires des fruits des agrumes)",
    "OE_GUIGMU": "Phyllosticta maculata (black spot du bananier|moucheture noire du bananier|taches noires du bananier)",
    "OE_PHYSMU": "Phyllosticta musarum (black spot du bananier|moucheture noire du bananier|taches noires du bananier)",
    "OE_PHYSSL": "Phyllosticta solitaria (blotch du pommier)",
    "OE_PHMPOM": "Phymatotrichopsis omnivora (maladie du Texas du cotonnier|rhizoctone du Texas)",
    "OE_PHRDMU": "Phyrdenus muriceus",
    "OE_TARSPA": "Phytonemus pallidus (tarsonème commun|tarsonème du fraisier)",
    "OE_1PHYTG": "Phytophthora",
    "OE_PHYTCC": "Phytophthora cactorum (chancre du collet|encre du châtaignier|mildiou de l'abricotier, des poiriers, du collet du cerisier, du pommier, du fraisier)",
    "OE_PHYTCM": "Phytophthora cambivora (encre du châtaignier|encre du noyer)",
    "OE_PHYTCN": "Phytophthora cinnamomi (pourriture des racines|pourriture des racines des éricacées, du pêcher|pourriture du coeur de l'ananas|pourriture du collet)",
    "OE_PHYTCO": "Phytophthora citrophthora (gommose des citrus|mildiou des agrumes|pourriture brune des agrumes)",
    "OE_PHYTCR": "Phytophthora cryptogea (coeur rouge des racines du fraisier|pourriture de l'endive|pourriture du collet des plantes d'ornement)",
    "OE_PHYTFR": "Phytophthora fragariae (coeur rouge des racines du fraisier|mildiou du fraisier|stèle rouge du fraisier)",
    "OE_PHYTNN": "Phytophthora nicotianae var. nicotianae (tige noire du tabac)",
    "OE_PHYTNP": "Phytophthora nicotianae var. parasitica (gommose des agrumes|mildiou des agrumes|mildiou terrestre|mildiou zoné de la tomate|pourriture brune)",
    "OE_PHYTRA": "Phytophthora ramorum",
    "OE_1PHYPG": "Phytoplasma (Phytoplasmes)",
    "OE_ERPHAV": "Phytoptus avellanae (ériophyide du noisetier|phytopte du noisetier)",
    "OE_PMWAV1": "Pineapple mealybug wilt-associated virus 1",
    "OE_PMWAV2": "Pineapple mealybug wilt-associated virus 2",
    "OE_PMWAV3": "Pineapple mealybug wilt-associated virus 3",
    "OE_PISOCI": "Pissodes cibriani",
    "OE_PISOFA": "Pissodes fasciatus",
    "OE_PISONE": "Pissodes nemorensis (charançon du tronc des pins)",
    "OE_PISONI": "Pissodes nitidus (charançon brillant)",
    "OE_PISOPU": "Pissodes punctatus",
    "OE_PISOST": "Pissodes strobi (charançon de l'épinette de Sitka|charançon d'Engelmann|charançon du pin blanc|charançon du pin Weymouth)",
    "OE_PISOTE": "Pissodes terminalis",
    "OE_PISOYU": "Pissodes yunnanensis",
    "OE_PISOZI": "Pissodes zitacuarense",
    "OE_PITOJU": "Pityophthorus juglandis (scolyte des pousses du noyer)",
    "OE_1PLAK": "Plantae",
    "OE_PLASHA": "Plasmopara halstedii (mildiou du tournesol)",
    "OE_DEUTTR": "Plenodomus tracheiphilus (dépérissement des agrumes|mal secco des agrumes)",
    "OE_PLSOCO": "Plesiommata corniculata",
    "OE_PLSOMO": "Plesiommata mollicella",
    "OE_PPV000": "Plum pox virus (sharka|variole du prunier)",
    "OE_POCZSH": "Pochazia shantungensis",
    "OE_PODOAP": "Podosphaera aphanis (blanc du fraisier|blanc du framboisier|oïdium du fraisier|oïdium du framboisier)",
    "OE_SPHRMU": "Podosphaera mors-uvae (blanc du groseillier|oïdium américain du groseillier|oïdium brun du groseillier|oïdium gris du groseillier)",
    "OE_POLGPR": "Polygraphus proximus (polygraphe du sapin de Maries|polygraphe oblong)",
    "OE_1POMAG": "Pomacea",
    "OE_POOPCO": "Poophilus costalis",
    "OE_POPIJA": "Popillia japonica (hanneton japonais|scarabée japonais)",
    "OE_PORPTR": "Porphyrophora tritici",
    "OE_PBRSV0": "Potato black ringspot virus (calico de la pomme de terre)",
    "OE_PLRV00": "Potato leafroll virus",
    "OE_PSTVD0": "Potato spindle tuber viroid",
    "OE_PVA000": "Potato virus A",
    "OE_PVB000": "Potato virus B",
    "OE_PVH000": "Potato virus H",
    "OE_PVM000": "Potato virus M",
    "OE_PVP000": "Potato virus P",
    "OE_PVS000": "Potato virus S",
    "OE_PVT000": "Potato virus T",
    "OE_PVV000": "Potato virus V",
    "OE_PVX000": "Potato virus X",
    "OE_PVY000": "Potato virus Y",
    "OE_PYDV00": "Potato yellow dwarf nucleorhabdovirus",
    "OE_PYV000": "Potato yellowing virus",
    "OE_PYMV00": "Potato yellow mosaic virus",
    "OE_PYVV00": "Potato yellow vein virus",
    "OE_PRATPE": "Pratylenchus penetrans (anguillule des racines|nématode des prairies)",
    "OE_PRATVU": "Pratylenchus vulnus (anguillule des racines du noyer|nématode des racines)",
    "OE_1PREMG": "Premnotrypes",
    "OE_PROISP": "Procecidochares sp.",
    "OE_PRDILO": "Prodiplosis longifila",
    "OE_PDV000": "Prune dwarf virus (dégénérescence du prunier|jaunisse du griottier)",
    "OE_PNRSV0": "Prunus necrotic ringspot virus",
    "OE_PSEAPE": "Pseudaulacaspis pentagona (cochenille du mûrier|kermès du mûrier)",
    "OE_CERCAN": "Pseudocercospora angolensis (cercosporiose des agrumes)",
    "OE_MYCOFI": "Pseudocercospora fijiensis (Sigatoka noir du bananier|Sigatoka noir du plantain|stries noires des feuilles du bananier)",
    "OE_MYCOMU": "Pseudocercospora musae (cercosporiose du bananier|Sigatoka du bananier)",
    "OE_CERSPD": "Pseudocercospora pini-densiflorae (cercosporiose des aiguilles du pin)",
    "OE_PSDMAL": "Pseudomonas avellanae",
    "OE_PSDMSA": "Pseudomonas savastanoi pv. savastanoi (bactériose de l'olivier)",
    "OE_PSDMAK": "Pseudomonas syringae pv. actinidiae (chancre bactérien du kiwi)",
    "OE_PSDMMP": "Pseudomonas syringae pv. morsprunorum (chancre bactérien du cerisier|dépérissement bactérien du pêcher)",
    "OE_PSDMPE": "Pseudomonas syringae pv. persicae (dépérissement bactérien du pêcher)",
    "OE_PSDMSY": "Pseudomonas syringae pv. syringae (bactériose des agrumes, des arbres fruitiers à noyau, du poirier|blast des agrumes|dessèchement bactérien)",
    "OE_PSDMVF": "Pseudomonas viridiflava (dépérissement bactérien de l'abricotier)",
    "OE_PSDPMI": "Pseudopityophthorus minutissimus",
    "OE_PSDPPR": "Pseudopityophthorus pruinosus",
    "OE_1PSYLG": "Psylla",
    "OE_PTIOCO": "Ptilona confinis",
    "OE_PTIOPE": "Ptilona persimilis",
    "OE_PUCCHN": "Puccinia horiana (rouille blanche du chrysanthème|rouille japonaise du chrysanthème)",
    "OE_PUCCPT": "Puccinia pittieriana (rouille de la pomme de terre)",
    "OE_RALSPS": "Ralstonia pseudosolanacearum",
    "OE_RALSSL": "Ralstonia solanacearum (maladie de Moko du bananier|pourriture brune de la pomme de terre)",
    "OE_PSDMS2": "Ralstonia solanacearum race 2 (no longer in use) (maladie de Moko du bananier)",
    "OE_RALSSC": "Ralstonia syzygii subsp. celebesensis",
    "OE_RALSSI": "Ralstonia syzygii subsp. indonesiensis",
    "OE_RAMUEN": "Ramularia endophylla",
    "OE_RBDV00": "Raspberry bushy dwarf virus",
    "OE_RPLV00": "Raspberry latent virus",
    "OE_RLCV00": "Raspberry leaf curl virus",
    "OE_RLMV00": "Raspberry leaf mottle virus",
    "OE_RPRSV0": "Raspberry ringspot virus (taches annulaires du framboisier)",
    "OE_RVCV00": "Raspberry vein chlorosis virus",
    "OE_RYS000": "Raspberry yellow spot agent",
    "OE_RESSCI": "Resseliella citrifrugis",
    "OE_THOMTE": "Resseliella theobaldi (cécidomyie de l'écorce du framboisier)",
    "OE_1RHAGG": "Rhagoletis",
    "OE_RHAGFA": "Rhagoletis fausta (trypète noir des cerises)",
    "OE_RHAGIN": "Rhagoletis indifferens",
    "OE_RHAGME": "Rhagoletis mendax (mouche de l'airelle|mouche du bleuet)",
    "OE_RHAGPO": "Rhagoletis pomonella (larve de la pomme|mouche de la pomme)",
    "OE_RHAGRI": "Rhagoletis ribicola",
    "OE_RHAGSU": "Rhagoletis suavis",
    "OE_RHGPTU": "Rhigopsidius tucumanus (charançon de la pomme de terre)",
    "OE_RHIZFR": "Rhizoctonia fragariae (pourriture noire du fraisier)",
    "OE_RHIZSO": "Rhizoctonia solani (chancre de la tige|chancre du pied de la p de terre|fonte des semis|maladie des manchettes de la p de terre|pied noir|pourridié)",
    "OE_CORBFA": "Rhodococcus fascians (chou-fleur du fraisier|fasciation des plantes ornementales|frisée du fraisier|gale foliaire des plantes ornementales)",
    "OE_RHYCFE": "Rhynchophorus ferrugineus (charançon asiatique du palmier|charançon rouge du palmier)",
    "OE_RHYCPA": "Rhynchophorus palmarum (charançon du palmier)",
    "OE_RHIOHI": "Ripersiella hibisci",
    "OE_ROSLNE": "Rosellinia necatrix (blanc des racines de la vigne|blanc des racines des arbres fruitiers|pourridié de la vigne, des arbres fruitiers, laineux)",
    "OE_RRV000": "Rose rosette emaravirus",
    "OE_RYNV00": "Rubus yellow net virus",
    "OE_SAPECN": "Saperda candida (saperde du pommier)",
    "OE_SDV000": "Satsuma dwarf virus",
    "OE_SCITAU": "Scirtothrips aurantii (thrips sud-africain des agrumes)",
    "OE_SCITCI": "Scirtothrips citri (thrips californien des agrumes|thrips des agrumes|thrips du cacaoyer)",
    "OE_SCITDO": "Scirtothrips dorsalis (thrips jaune du théier)",
    "OE_SKLPPA": "Sclerophora pallida",
    "OE_SCLESC": "Sclerotinia sclerotiorum (affaissement à sclérotes|flétrissement à sclérotes|maladie à sclérotes|pourriture à sclérotes, blanche|sclérotiniose)",
    "OE_1SCOLF": "Scolytidae",
    "OE_SEPTLM": "Septoria malagutii",
    "OE_SIBOSA": "Sibovia sagata",
    "OE_SONEGR": "Sonesimia grossa",
    "OE_SFANBI": "Sphaeniscus binoculatus",
    "OE_MYCOPP": "Sphaerulina musiva",
    "OE_SFENNI": "Sphenella nigricornis",
    "OE_SPIRCI": "Spiroplasma citri (stubborn des agrumes)",
    "OE_PRODER": "Spodoptera eridania",
    "OE_LAPHFR": "Spodoptera frugiperda (légionnaire d'automne)",
    "OE_SPODLI": "Spodoptera littoralis (noctuelle méditerranéenne|ver du coton|ver du cotonnier)",
    "OE_PRODLI": "Spodoptera litura (chenille défoliante|noctuelle rayée|ver du coton|ver du tabac)",
    "OE_PRODOR": "Spodoptera ornithogalli",
    "OE_SPONSU": "Spongospora subterranea (gale poudreuse de la pomme de terre|spongosporiose de la pomme de terre)",
    "OE_SQVYVX": "Squash vein yellowing virus",
    "OE_PHOMAN": "Stagonosporopsis andigena",
    "OE_GNOMUL": "Stegophora ulmea (anthracnose de l'orme)",
    "OE_CRYPMA": "Sternochetus mangiferae (charançon de la graine du manguier|charançon de la mangue)",
    "OE_1STRAG": "Strauzia",
    "OE_SCFAV0": "Strawberry chlorotic fleck-associated virus",
    "OE_SCRV00": "Strawberry crinkle cytorhabdovirus",
    "OE_SLRSV0": "Strawberry latent ringspot virus",
    "OE_STWLCV": "Strawberry leaf curl virus",
    "OE_SMYEV0": "Strawberry mild yellow edge virus",
    "OE_SMOV00": "Strawberry mottle virus",
    "OE_PHYP75": "Strawberry multiplier disease phytoplasma",
    "OE_SNSV00": "Strawberry necrotic shock virus",
    "OE_SVBV00": "Strawberry vein banding virus",
    "OE_SYWB00": "Strawberry witches' broom phytoplasma",
    "OE_1STRG": "Striga",
    "OE_SCLOCE": "Stromatinia cepivora (pourriture blanche de l'ail, de l'échalote, de l'oignon|pourriture blanche des alliacées|pourriture noire de l'ail)",
    "OE_SPCSV0": "Sweet potato chlorotic stunt virus",
    "OE_PHYP39": "Sweet potato little leaf phytoplasma",
    "OE_SPMMV0": "Sweet potato mild mottle virus (mosaïque de la patate douce)",
    "OE_SYNCEN": "Synchytrium endobioticum (galle noire de la pomme de terre|galle verruqueuse de la pomme de terre|maladie verruqueuse de la pomme de terre)",
    "OE_TAOMMA": "Taomyia marshalli",
    "OE_TAPARU": "Tapajosa rubromarginata",
    "OE_TECASO": "Tecia solanivora (teigne guatémaltèque de la pomme de terre)",
    "OE_TFDAV0": "Temperate fruit decay-associated virus",
    "OE_1TEPHF": "Tephritidae",
    "OE_TEPRLE": "Tephritis leavittensis",
    "OE_TEPRLU": "Tephritis luteipes",
    "OE_TEPROV": "Tephritis ovatipennis",
    "OE_TEPRPU": "Tephritis pura",
    "OE_TETRUR": "Tetranychus urticae (acarien jaune tisserand|araignée rouge des serres|araignée rouge du cotonnier|tétranyche tisserand|tétranyque à deux points)",
    "OE_TETTFE": "Tettigella ferruginea",
    "OE_ARGPLE": "Thaumatotibia leucotreta (faux carpocapse)",
    "OE_THAUPI": "Thaumetopoea pityocampa (processionnaire du pin)",
    "OE_THAUPR": "Thaumetopoea processionea (processionnaire du chêne)",
    "OE_THPHSO": "Thecaphora solani (charbon de la pomme de terre)",
    "OE_THRIPL": "Thrips palmi",
    "OE_TILLCA": "Tilletia caries (carie commune du blé|carie double|carie du blé|carie ordinaire du blé)",
    "OE_TILLCO": "Tilletia controversa (carie naine du blé|carie naine du seigle)",
    "OE_NEOVIN": "Tilletia indica (carie de Karnal)",
    "OE_TILLFO": "Tilletia laevis (carie commune du blé|carie du blé|carie lisse du blé)",
    "OE_TRSV00": "Tobacco ringspot virus (virus des taches en anneaux du tabac)",
    "OE_TSVBL0": "Tobacco streak virus black raspberry latent strain",
    "OE_TBRV00": "Tomato black ring virus",
    "OE_TOBRFV": "Tomato brown rugose fruit virus (virus du fruit rugueux brun de la tomate)",
    "OE_TOCHV0": "Tomato chocolàte virus",
    "OE_TOLCND": "Tomato leaf curl New Delhi virus",
    "OE_TOANV0": "Tomato marchitez virus",
    "OE_TOMMOV": "Tomato mild mottle virus",
    "OE_THV000": "Tomato mosaic Havana virus",
    "OE_TOMOTV": "Tomato mottle Taino virus",
    "OE_TORSV0": "Tomato ringspot virus",
    "OE_TOSRV0": "Tomato severe rugose virus",
    "OE_TSWV00": "Tomato spotted wilt virus (maladie bronzée|taches de bronze de la tomate)",
    "OE_TOYVSV": "Tomato yellow vein streak virus",
    "OE_TOUMPA": "Toumeyella parvicornis (cochenille tortue du pin|kermès tortue du pin)",
    "OE_TRIZER": "Trioza erytreae (psylle des agrumes)",
    "OE_AELSSA": "Trirachys sartus",
    "OE_TRUPBI": "Trupanea bisetosa",
    "OE_TRUPFE": "Trupanea femoralis",
    "OE_TRUPWH": "Trupanea wheeleri",
    "OE_TRYNNI": "Trypanocentra nigrithorax",
    "OE_TRYEFL": "Trypeta flaveola",
    "OE_GNORAB": "Tuta absoluta (mineuse de la tomate)",
    "OE_TYLESE": "Tylenchulus semipenetrans (anguillule des racines des agrumes|anguillule du citronnier|nématode des agrumes)",
    "OE_UNASCI": "Unaspis citri (cochenille blanche du tronc)",
    "OE_URORCH": "Urophora christophi",
    "OE_VENTNA": "Venturia nashicola (tavelure du nashi|tavelure du poirier du Japon)",
    "OE_VERTAA": "Verticillium albo-atrum (flétrissement verticillien|marbrure des feuilles du tournesol|verticilliose)",
    "OE_VERTDA": "Verticillium dahliae (apoplexie de l'abricotier|dépérissement de l'abricotier|flétrissement verticillien|verticilliose)",
    "OE_VERTNO": "Verticillium nonalfalfae",
    "OE_1VIRUK": "Viruses and viroids (Virus et viroïdes)",
    "OE_XANRIN": "Xanthaciura insecta",
    "OE_XANTCY": "Xanthomonas arboricola pv. corylina (bactériose du noisetier)",
    "OE_XANTJU": "Xanthomonas arboricola pv. juglandis (bactériose du noyer|taches noires du noyer)",
    "OE_XANTPR": "Xanthomonas arboricola pv. pruni (bactériose des arbres fruitiers à noyau|tache bactérienne des arbres fruitiers à noyau|tache bactérienne du prunier)",
    "OE_XANTDF": "Xanthomonas axonopodis pv. dieffenbachiae (dépérissement de l'anthurium)",
    "OE_XANTFI": "Xanthomonas campestris pv. fici",
    "OE_XANTAU": "Xanthomonas citri pv. aurantifolii (chancre citrique)",
    "OE_XANTCI": "Xanthomonas citri pv. citri (bactériose des agrumes|chancre bactérien des agrumes|chancre citrique|chancre des agrumes)",
    "OE_XANTFF": "Xanthomonas citri pv. fuscans (bactériose du haricot|brûlure bactérienne du haricot|feu bactérien du haricot|flétrissement bactérien du haricot)",
    "OE_XANTEU": "Xanthomonas euvesicatoria pv. euvesicatoria (gale bactérienne de la tomate)",
    "OE_XANTPF": "Xanthomonas euvesicatoria pv. perforans (gale bactérienne de la tomate)",
    "OE_XANTFR": "Xanthomonas fragariae (bactériose du fraisier|flétrissement vasculaire du fraisier|taches angulaires du fraisier)",
    "OE_XANTGA": "Xanthomonas hortorum pv. gardneri (gale bactérienne de la tomate|gale bactérienne de la tomate)",
    "OE_XANTOR": "Xanthomonas oryzae pv. oryzae (bactériose des feuilles du riz|maladie bactérienne des feuilles de riz)",
    "OE_XANTTO": "Xanthomonas oryzae pv. oryzicola (brûlure bactérienne du riz|stries bactériennes du riz)",
    "OE_XANTPH": "Xanthomonas phaseoli pv. phaseoli (bactériose du haricot|brûlure bactérienne du haricot|feu bactérien du haricot|flétrissement bactérien du haricot)",
    "OE_XANTVE": "Xanthomonas vesicatoria (gale bactérienne de la tomate|tache bactérienne de la tomate)",
    "OE_XIPHAA": "Xiphinema americanum sensu stricto (anguillule xiphinème américain)",
    "OE_XIPHBC": "Xiphinema bricolense",
    "OE_XIPHCA": "Xiphinema californicum",
    "OE_XIPHDI": "Xiphinema diversicaudatum",
    "OE_XIPHIN": "Xiphinema index",
    "OE_XIPHIM": "Xiphinema intermedium",
    "OE_XIPHNA": "Xiphinema neoamericanum",
    "OE_XIPHRI": "Xiphinema rivesi",
    "OE_XIPHTA": "Xiphinema tarjanense",
    "OE_XYLEFA": "Xylella fastidiosa (maladie de Pierce)",
    "OE_XYLEFF": "Xylella fastidiosa subsp. fastidiosa",
    "OE_XYLEFO": "Xylella fastidiosa subsp. morus",
    "OE_XYLEFM": "Xylella fastidiosa subsp. multiplex",
    "OE_XYLEFP": "Xylella fastidiosa subsp. pauca",
    "OE_XYLEFS": "Xylella fastidiosa subsp. sandyi",
    "OE_XYLEFT": "Xylella fastidiosa subsp. tashke",
    "OE_XANTAM": "Xylophilus ampelinus (brûlure bactérienne de la vigne|maladie d'Oléron de la vigne|nécrose bactérienne de la vigne)",
    "OE_XYLOCH": "Xylotrechus chinensis (longicorne tigre|perceur chinois)",
    "OE_CARNFL": "Xyphon flaviceps (cicadelle à tête jaune)",
    "OE_CARNFU": "Xyphon fulgidum",
    "OE_CARNTR": "Xyphon triguttatum",
    "OE_ZACEAS": "Zacerata asparagi",
    "OE_1ZEUDG": "Zeugodacus",
    "OE_DACUCU": "Zeugodacus cucurbitae (mouche des curcurbitacées|mouche du concombre|mouche du melon)",
    "OE_ZONOEL": "Zonosemata electa (mouche du piment)",
}

STATUTS_REGLEMENTAIRES = {
    "OQP": "organisme quarantaine prioritaire",
    "OQ": "organisme quarantaine",
    "OQZP": "organisme quarantaine zone protégée",
    "ORNQ": "organisme réglementée non quarantaine",
}

CONTEXTES = [
    "enquête officielle relative aux organismes nuisibles",
    "enquête liée à un foyer existant ou éradiqué d’un organisme nuisible",
    "inspections phytosanitaires de tout type",
    "inspection de traçage en amont et en aval liée à la présence spécifique de l’organisme nuisible",
    "inspection officielle à des fins autres que phytosanitaires",
    "informations fournies par des opérateurs professionnels, des laboratoires ou d’autres personnes",
    "informations scientifiques",
    "notification rasff",
    "autre (à préciser dans le fil de suivi)",
]

REGIONS = [
    "Auvergne-Rhône-Alpes",
    "Bourgogne-Franche-Comté",
    "Bretagne",
    "Centre-Val de Loire",
    "Corse",
    "Grand Est",
    "Hauts-de-France",
    "Île-de-France",
    "Normandie",
    "Nouvelle-Aquitaine",
    "Occitanie",
    "Pays de la Loire",
    "Provence-Alpes-Côte d'Azur",
    "Guadeloupe",
    "Martinique",
    "Guyane",
    "La Réunion",
    "Mayotte",
]

DEPARTEMENTS = [
    ("01", "Ain", "Auvergne-Rhône-Alpes"),
    ("03", "Allier", "Auvergne-Rhône-Alpes"),
    ("07", "Ardèche", "Auvergne-Rhône-Alpes"),
    ("15", "Cantal", "Auvergne-Rhône-Alpes"),
    ("26", "Drôme", "Auvergne-Rhône-Alpes"),
    ("38", "Isère", "Auvergne-Rhône-Alpes"),
    ("42", "Loire", "Auvergne-Rhône-Alpes"),
    ("43", "Haute-Loire", "Auvergne-Rhône-Alpes"),
    ("63", "Puy-de-Dôme", "Auvergne-Rhône-Alpes"),
    ("69", "Rhône", "Auvergne-Rhône-Alpes"),
    ("73", "Savoie", "Auvergne-Rhône-Alpes"),
    ("74", "Haute-Savoie", "Auvergne-Rhône-Alpes"),
    ("21", "Côte-d'Or", "Bourgogne-Franche-Comté"),
    ("25", "Doubs", "Bourgogne-Franche-Comté"),
    ("39", "Jura", "Bourgogne-Franche-Comté"),
    ("58", "Nièvre", "Bourgogne-Franche-Comté"),
    ("70", "Haute-Saône", "Bourgogne-Franche-Comté"),
    ("71", "Saône-et-Loire", "Bourgogne-Franche-Comté"),
    ("89", "Yonne", "Bourgogne-Franche-Comté"),
    ("90", "Territoire de Belfort", "Bourgogne-Franche-Comté"),
    ("22", "Côtes-d'Armor", "Bretagne"),
    ("29", "Finistère", "Bretagne"),
    ("35", "Ille-et-Vilaine", "Bretagne"),
    ("56", "Morbihan", "Bretagne"),
    ("18", "Cher", "Centre-Val de Loire"),
    ("28", "Eure-et-Loir", "Centre-Val de Loire"),
    ("36", "Indre", "Centre-Val de Loire"),
    ("37", "Indre-et-Loire", "Centre-Val de Loire"),
    ("41", "Loir-et-Cher", "Centre-Val de Loire"),
    ("45", "Loiret", "Centre-Val de Loire"),
    ("2A", "Corse-du-Sud", "Corse"),
    ("2B", "Haute-Corse", "Corse"),
    ("08", "Ardennes", "Grand Est"),
    ("10", "Aube", "Grand Est"),
    ("51", "Marne", "Grand Est"),
    ("52", "Haute-Marne", "Grand Est"),
    ("54", "Meurthe-et-Moselle", "Grand Est"),
    ("55", "Meuse", "Grand Est"),
    ("57", "Moselle", "Grand Est"),
    ("67", "Bas-Rhin", "Grand Est"),
    ("68", "Haut-Rhin", "Grand Est"),
    ("88", "Vosges", "Grand Est"),
    ("02", "Aisne", "Hauts-de-France"),
    ("59", "Nord", "Hauts-de-France"),
    ("60", "Oise", "Hauts-de-France"),
    ("62", "Pas-de-Calais", "Hauts-de-France"),
    ("80", "Somme", "Hauts-de-France"),
    ("75", "Paris", "Île-de-France"),
    ("77", "Seine-et-Marne", "Île-de-France"),
    ("78", "Yvelines", "Île-de-France"),
    ("91", "Essonne", "Île-de-France"),
    ("92", "Hauts-de-Seine", "Île-de-France"),
    ("93", "Seine-Saint-Denis", "Île-de-France"),
    ("94", "Val-de-Marne", "Île-de-France"),
    ("95", "Val-d'Oise", "Île-de-France"),
    ("14", "Calvados", "Normandie"),
    ("27", "Eure", "Normandie"),
    ("50", "Manche", "Normandie"),
    ("61", "Orne", "Normandie"),
    ("76", "Seine-Maritime", "Normandie"),
    ("16", "Charente", "Nouvelle-Aquitaine"),
    ("17", "Charente-Maritime", "Nouvelle-Aquitaine"),
    ("19", "Corrèze", "Nouvelle-Aquitaine"),
    ("23", "Creuse", "Nouvelle-Aquitaine"),
    ("24", "Dordogne", "Nouvelle-Aquitaine"),
    ("33", "Gironde", "Nouvelle-Aquitaine"),
    ("40", "Landes", "Nouvelle-Aquitaine"),
    ("47", "Lot-et-Garonne", "Nouvelle-Aquitaine"),
    ("64", "Pyrénées-Atlantiques", "Nouvelle-Aquitaine"),
    ("79", "Deux-Sèvres", "Nouvelle-Aquitaine"),
    ("86", "Vienne", "Nouvelle-Aquitaine"),
    ("87", "Haute-Vienne", "Nouvelle-Aquitaine"),
    ("09", "Ariège", "Occitanie"),
    ("11", "Aude", "Occitanie"),
    ("12", "Aveyron", "Occitanie"),
    ("30", "Gard", "Occitanie"),
    ("31", "Haute-Garonne", "Occitanie"),
    ("32", "Gers", "Occitanie"),
    ("34", "Hérault", "Occitanie"),
    ("46", "Lot", "Occitanie"),
    ("48", "Lozère", "Occitanie"),
    ("65", "Hautes-Pyrénées", "Occitanie"),
    ("66", "Pyrénées-Orientales", "Occitanie"),
    ("81", "Tarn", "Occitanie"),
    ("82", "Tarn-et-Garonne", "Occitanie"),
    ("44", "Loire-Atlantique", "Pays de la Loire"),
    ("49", "Maine-et-Loire", "Pays de la Loire"),
    ("53", "Mayenne", "Pays de la Loire"),
    ("72", "Sarthe", "Pays de la Loire"),
    ("85", "Vendée", "Pays de la Loire"),
    ("04", "Alpes-de-Haute-Provence", "Provence-Alpes-Côte d'Azur"),
    ("05", "Hautes-Alpes", "Provence-Alpes-Côte d'Azur"),
    ("06", "Alpes-Maritimes", "Provence-Alpes-Côte d'Azur"),
    ("13", "Bouches-du-Rhône", "Provence-Alpes-Côte d'Azur"),
    ("83", "Var", "Provence-Alpes-Côte d'Azur"),
    ("84", "Vaucluse", "Provence-Alpes-Côte d'Azur"),
    ("971", "Guadeloupe", "Guadeloupe"),
    ("972", "Martinique", "Martinique"),
    ("973", "Guyane", "Guyane"),
    ("974", "La Réunion", "La Réunion"),
    ("976", "Mayotte", "Mayotte"),
]

STATUTS_ETABLISSEMENT = [
    "établissement",
    "propriétaire",
]

TYPES_EXPLOITANT = [
    "Verger à graine",
    "Peuplement classé",
    "Champ",
    "Verger",
    "Vignoble",
    "Pépinière",
    "Forêt",
    "Jardin privé",
    "Site public",
    "Espace protégé",
    "Friches",
    "Jardinerie",
    "Plateforme logistique",
    "Site de stockage de bois",
    "Serre",
    "Batiment privé",
    "Batiment public",
    "Autre (à préciser dans le fil de suivi)",
    "Sans objet",
]

POSITIONS_CHAINE_DISTRIBUTION = [
    "Fournisseur",
    "Opérateur intermédiaire",
    "Autre maillon de la chaine de distribution",
    "Autre (à préciser)",
]

STRUCTURES_PRELEVEUR = [
    "SRAL",
    "OVS",
    "DSF",
    "SIVEP",
    "SEMAE",
    "FAM",
    "CTIFL",
    "Exploitant",
]

SITES_INSPECTION = [
    "Verger à graine",
    "Peuplement classé",
    "Champ",
    "Verger",
    "Vignoble",
    "Pépinière",
    "Forêt",
    "Jardin privé",
    "Site public",
    "Espace protégé",
    "Friches",
    "Jardinerie",
    "Plateforme logistique",
    "Site de stockage de bois",
    "Serre",
    "Bâtiment privé",
    "Bâtiment public",
    "Autre (à préciser dans le fil de suivi)",
    "Sans objet",
]

MATRICES_PRELEVEES = [
    "Plante vivante",
    "Partie vivante de plante",
    "Caisse",
    "Palette",
    "Autre emballage en bois",
    "Ecorce",
    "Grume",
    "Sciage",
    "Autre bois",
    "Insecte",
    "Environnement",
]

LABORATOIRES_AGREES = [
    "ANSES 49",
    "ANSES 63",
    "ANSES 34",
    "ANSES 54b",
    "ANSES 35b",
    "ANSES 974",
    "LDA 02",
    "LDA 13",
    "SEDIA 21",
    "LDA 22",
    "CTI 24",
    "BRET 29",
    "IFV 30",
    "LDA 31",
    "LCA 33",
    "LDA 33b",
    "SNES 49",
    "QUAL 54",
]

LABORATOIRES_CONFIRMATION_OFFICIELLE = [
    "ANSES 34 - Unité d'Entomologie et Plantes invasives",
    "ANSES 49 - Unité de Bactériologie, Virologie et OGM",
    "ANSES 54 - Unité de Mycologie",
    "ANSES 35 -  Unité de Nématologie",
    "COM 62",
    "LOOS 62",
    "LDA 67",
    "LDA 71",
    "CENTRESUD 87",
    "LDA 972 (Martinique)",
    "FDGDON 974 (Réunion)",
    "FREDON 14",
    "FREDON 51",
    "FREDON 80",
]

STATUTS_EVENEMENT = ["Foyer", "Interception", "Incursion", "Suspicion"]


def insert_administrations(apps, schema_editor):
    Administration = apps.get_model("sv", "Administration")
    administrations = [Administration(nom=nom) for nom in ADMINISTRATIONS]
    Administration.objects.bulk_create(administrations)


def delete_administrations(apps, schema_editor):
    Administration = apps.get_model("sv", "Administration")
    Administration.objects.filter(nom__in=ADMINISTRATIONS).delete()


def insert_unites(apps, schema_editor):
    Administration = apps.get_model("sv", "Administration")
    administration_centrale = Administration.objects.get(nom="Administration centrale")
    service_regional = Administration.objects.get(nom="Service régional")

    Unite = apps.get_model("sv", "Unite")

    unites_administration_centrale = [
        Unite(nom=nom, type=administration_centrale) for nom in UNITES_ADMINISTRATION_CENTRALE_NOMS
    ]
    unites_service_regional = [Unite(nom=nom, type=service_regional) for nom in UNITES_SERVICE_REGIONAL_NOMS]

    Unite.objects.bulk_create(unites_administration_centrale + unites_service_regional)


def delete_unites(apps, schema_editor):
    Unite = apps.get_model("sv", "Unite")
    Unite.objects.filter(nom__in=UNITES_ADMINISTRATION_CENTRALE_NOMS + UNITES_SERVICE_REGIONAL_NOMS).delete()


def insert_organismes_nuisibles(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    organismes_nuisibles = [
        OrganismeNuisible(code_oepp=code_oepp, libelle_court=libelle_court)
        for code_oepp, libelle_court in ORGANISMES_NUISIBLES.items()
    ]
    OrganismeNuisible.objects.bulk_create(organismes_nuisibles)


def delete_organismes_nuisibles(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.filter(code_oepp__in=ORGANISMES_NUISIBLES).delete()


def insert_statuts_reglementaires(apps, schema_editor):
    StatutReglementaire = apps.get_model("sv", "StatutReglementaire")
    statuts_reglementaires = [
        StatutReglementaire(code=code, libelle=libelle) for code, libelle in STATUTS_REGLEMENTAIRES.items()
    ]
    StatutReglementaire.objects.bulk_create(statuts_reglementaires)


def delete_statuts_reglementaires(apps, schema_editor):
    StatutReglementaire = apps.get_model("sv", "StatutReglementaire")
    StatutReglementaire.objects.filter(code__in=STATUTS_REGLEMENTAIRES).delete()


def insert_contextes(apps, schema_editor):
    Contexte = apps.get_model("sv", "Contexte")
    contextes = [Contexte(nom=nom) for nom in CONTEXTES]
    Contexte.objects.bulk_create(contextes)


def delete_contextes(apps, schema_editor):
    Contexte = apps.get_model("sv", "Contexte")
    Contexte.objects.filter(nom__in=CONTEXTES).delete()


def insert_regions(apps, schema_editor):
    Region = apps.get_model("sv", "Region")
    regions = [Region(nom=nom) for nom in REGIONS]
    Region.objects.bulk_create(regions)


def delete_regions(apps, schema_editor):
    Region = apps.get_model("sv", "Region")
    Region.objects.filter(nom__in=REGIONS).delete()


def insert_departements(apps, schema_editor):
    Region = apps.get_model("sv", "Region")
    Departement = apps.get_model("sv", "Departement")

    departements_to_create = []
    for numero, nom, region_nom in DEPARTEMENTS:
        region = Region.objects.get(nom=region_nom)
        departement = Departement(numero=numero, nom=nom, region=region)
        departements_to_create.append(departement)

    Departement.objects.bulk_create(departements_to_create)


def delete_departements(apps, schema_editor):
    Departement = apps.get_model("sv", "Departement")
    Departement.objects.filter(numero__in=[numero for numero, _, _ in DEPARTEMENTS]).delete()


def insert_statuts_etablissement(apps, schema_editor):
    StatutEtablissement = apps.get_model("sv", "StatutEtablissement")
    statuts_etablissement = [StatutEtablissement(libelle=libelle) for libelle in STATUTS_ETABLISSEMENT]
    StatutEtablissement.objects.bulk_create(statuts_etablissement)


def delete_statuts_etablissement(apps, schema_editor):
    StatutEtablissement = apps.get_model("sv", "StatutEtablissement")
    StatutEtablissement.objects.filter(libelle__in=STATUTS_ETABLISSEMENT).delete()


def insert_types_exploitant(apps, schema_editor):
    TypeExploitant = apps.get_model("sv", "TypeExploitant")
    types_exploitant = [TypeExploitant(libelle=libelle) for libelle in TYPES_EXPLOITANT]
    TypeExploitant.objects.bulk_create(types_exploitant)


def delete_types_exploitant(apps, schema_editor):
    TypeExploitant = apps.get_model("sv", "TypeExploitant")
    TypeExploitant.objects.filter(libelle__in=TYPES_EXPLOITANT).delete()


def insert_positions_chaine_distribution(apps, schema_editor):
    PositionChaineDistribution = apps.get_model("sv", "PositionChaineDistribution")
    positions_chaine_distribution = [
        PositionChaineDistribution(libelle=libelle) for libelle in POSITIONS_CHAINE_DISTRIBUTION
    ]
    PositionChaineDistribution.objects.bulk_create(positions_chaine_distribution)


def delete_positions_chaine_distribution(apps, schema_editor):
    PositionChaineDistribution = apps.get_model("sv", "PositionChaineDistribution")
    PositionChaineDistribution.objects.filter(libelle__in=POSITIONS_CHAINE_DISTRIBUTION).delete()


def insert_structures_preleveur(apps, schema_editor):
    StructurePreleveur = apps.get_model("sv", "StructurePreleveur")
    structures_preleveur = [StructurePreleveur(nom=nom) for nom in STRUCTURES_PRELEVEUR]
    StructurePreleveur.objects.bulk_create(structures_preleveur)


def delete_structures_preleveur(apps, schema_editor):
    StructurePreleveur = apps.get_model("sv", "StructurePreleveur")
    StructurePreleveur.objects.filter(nom__in=STRUCTURES_PRELEVEUR).delete()


def insert_sites_inspection(apps, schema_editor):
    SiteInspection = apps.get_model("sv", "SiteInspection")
    sites_inspection = [SiteInspection(nom=nom) for nom in SITES_INSPECTION]
    SiteInspection.objects.bulk_create(sites_inspection)


def delete_sites_inspection(apps, schema_editor):
    SiteInspection = apps.get_model("sv", "SiteInspection")
    SiteInspection.objects.filter(nom__in=SITES_INSPECTION).delete()


def insert_matrices_prelevees(apps, schema_editor):
    MatricePrelevee = apps.get_model("sv", "MatricePrelevee")
    matrices_prelevees = [MatricePrelevee(libelle=libelle) for libelle in MATRICES_PRELEVEES]
    MatricePrelevee.objects.bulk_create(matrices_prelevees)


def delete_matrices_prelevees(apps, schema_editor):
    MatricePrelevee = apps.get_model("sv", "MatricePrelevee")
    MatricePrelevee.objects.filter(libelle__in=MATRICES_PRELEVEES).delete()


def insert_laboratoires_agrees(apps, schema_editor):
    LaboratoireAgree = apps.get_model("sv", "LaboratoireAgree")
    laboratoires_agrees = [LaboratoireAgree(nom=nom) for nom in LABORATOIRES_AGREES]
    LaboratoireAgree.objects.bulk_create(laboratoires_agrees)


def delete_laboratoires_agrees(apps, schema_editor):
    LaboratoireAgree = apps.get_model("sv", "LaboratoireAgree")
    LaboratoireAgree.objects.filter(nom__in=LABORATOIRES_AGREES).delete()


def insert_laboratoires_confirmation_officielle(apps, schema_editor):
    LaboratoireConfirmationOfficielle = apps.get_model("sv", "LaboratoireConfirmationOfficielle")
    laboratoires_confirmation_officielle = [
        LaboratoireConfirmationOfficielle(nom=nom) for nom in LABORATOIRES_CONFIRMATION_OFFICIELLE
    ]
    LaboratoireConfirmationOfficielle.objects.bulk_create(laboratoires_confirmation_officielle)


def delete_laboratoires_confirmation_officielle(apps, schema_editor):
    LaboratoireConfirmationOfficielle = apps.get_model("sv", "LaboratoireConfirmationOfficielle")
    LaboratoireConfirmationOfficielle.objects.filter(nom__in=LABORATOIRES_CONFIRMATION_OFFICIELLE).delete()


def insert_statuts_evenement(apps, schema_editor):
    StatutEvenement = apps.get_model("sv", "StatutEvenement")
    statuts_evenement = [StatutEvenement(libelle=libelle) for libelle in STATUTS_EVENEMENT]
    StatutEvenement.objects.bulk_create(statuts_evenement)


def delete_statuts_evenement(apps, schema_editor):
    StatutEvenement = apps.get_model("sv", "StatutEvenement")
    StatutEvenement.objects.filter(libelle__in=STATUTS_EVENEMENT).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(insert_administrations, delete_administrations),
        migrations.RunPython(insert_unites, delete_unites),
        migrations.RunPython(insert_organismes_nuisibles, delete_organismes_nuisibles),
        migrations.RunPython(insert_statuts_reglementaires, delete_statuts_reglementaires),
        migrations.RunPython(insert_contextes, delete_contextes),
        migrations.RunPython(insert_regions, delete_regions),
        migrations.RunPython(insert_departements, delete_departements),
        migrations.RunPython(insert_statuts_etablissement, delete_statuts_etablissement),
        migrations.RunPython(insert_types_exploitant, delete_types_exploitant),
        migrations.RunPython(insert_positions_chaine_distribution, delete_positions_chaine_distribution),
        migrations.RunPython(insert_structures_preleveur, delete_structures_preleveur),
        migrations.RunPython(insert_sites_inspection, delete_sites_inspection),
        migrations.RunPython(insert_matrices_prelevees, delete_matrices_prelevees),
        migrations.RunPython(insert_laboratoires_agrees, delete_laboratoires_agrees),
        migrations.RunPython(
            insert_laboratoires_confirmation_officielle,
            delete_laboratoires_confirmation_officielle,
        ),
        migrations.RunPython(insert_statuts_evenement, delete_statuts_evenement),
    ]
