# Generated by Django 5.0.3 on 2024-06-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0005_alter_prelevement_lieu"),
    ]

    operations = [
        migrations.AddField(
            model_name="lieu",
            name="lambert93_latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude Lambert 93"),
        ),
        migrations.AddField(
            model_name="lieu",
            name="lambert93_longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitude Lambert 93"),
        ),
    ]
