# Generated by Django 5.0.3 on 2024-05-08 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0005_alter_prelevement_lieu"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaracteristiquesPrincipalesZoneDelimitee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("libelle", models.CharField(max_length=100, verbose_name="Libellé")),
            ],
            options={
                "verbose_name": "Caractéristiques principales de la zone délimitée",
                "verbose_name_plural": "Caractéristiques principales des zones délimitées",
                "db_table": "sv_caracteristiques_principales_zone_delimitee",
            },
        ),
        migrations.CreateModel(
            name="FicheZone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "createur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sv.unite", verbose_name="Créateur"
                    ),
                ),
                (
                    "numero",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="sv.numerofiche", verbose_name="Numéro de fiche"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche zone",
                "verbose_name_plural": "Fiches zone",
                "db_table": "sv_fiche_zone",
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("surface_zone_infestee", models.FloatField(verbose_name="Surface de la zone infestée")),
                (
                    "unite_surface_zone_infestee",
                    models.CharField(
                        choices=[("ha", "Hectare"), ("km2", "Kilomètre carré")],
                        default="km2",
                        max_length=3,
                        verbose_name="Unité de la surface de la zone infestée",
                    ),
                ),
                ("rayon_zone_infestee", models.FloatField(verbose_name="Rayon de la zone infestée")),
                (
                    "unite_rayon_zone_infestee",
                    models.CharField(
                        choices=[("m", "Mètre"), ("km", "Kilomètre")],
                        default="m",
                        max_length=2,
                        verbose_name="Unité du rayon de la zone infestée",
                    ),
                ),
                ("rayon_zone_tamponee", models.FloatField(verbose_name="Rayon de la zone tampon")),
                (
                    "unite_rayon_zone_tamponee",
                    models.CharField(
                        choices=[("m", "Mètre"), ("km", "Kilomètre")],
                        default="m",
                        max_length=2,
                        verbose_name="Unité du rayon de la zone tampon",
                    ),
                ),
                ("commentaire", models.TextField(blank=True, verbose_name="Commentaire")),
                ("vegetaux_infestes", models.TextField(blank=True, verbose_name="Végétaux infestés")),
                (
                    "caracteristiques_principales_zone_delimitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sv.caracteristiquesprincipaleszonedelimitee",
                        verbose_name="Caractéristiques principales de la zone délimitée",
                    ),
                ),
                (
                    "fiche_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sv.fichezone", verbose_name="Fiche zone"
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone",
                "verbose_name_plural": "Zones",
            },
        ),
    ]
