# Generated by Django 5.0.3 on 2024-06-12 13:43

from django.db import migrations, models


def generate_etats(apps, schema_editor):
    Etat = apps.get_model("sv", "Etat")
    Etat.objects.create(libelle="nouveau")
    Etat.objects.create(libelle="en cours")
    Etat.objects.create(libelle="clôturé")


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0006_lieu_lambert93_latitude_lieu_lambert93_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="Etat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("libelle", models.CharField(max_length=30, unique=True)),
            ],
            options={
                "verbose_name": "Etat",
                "verbose_name_plural": "Etats",
                "db_table": "sv_etat",
            },
        ),
        migrations.RunPython(generate_etats),
    ]
