# Generated by Django 5.0.3 on 2024-06-05 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0006_caracteristiquesprincipaleszonedelimitee_fichezone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichezone",
            name="fiche_detection",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="sv.fichedetection",
                verbose_name="Fiche détection",
            ),
            preserve_default=False,
        ),
    ]
