# Generated by Django 5.0.3 on 2024-06-07 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0007_fichezone_fiche_detection"),
    ]

    operations = [
        migrations.RenameField(
            model_name="zone",
            old_name="rayon_zone_tamponee",
            new_name="rayon_zone_tampon",
        ),
        migrations.RenameField(
            model_name="zone",
            old_name="unite_rayon_zone_tamponee",
            new_name="unite_rayon_zone_tampon",
        ),
    ]
