# Generated by Django 5.0.3 on 2024-06-12 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0007_etat"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichedetection",
            name="etat",
            field=models.ForeignKey(
                default="sv.models.Etat.get_etat_initial",
                on_delete=django.db.models.deletion.PROTECT,
                to="sv.etat",
                verbose_name="État de la fiche",
            ),
        ),
    ]
