# Generated by Django 5.0.3 on 2024-06-11 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0006_lieu_lambert93_latitude_lieu_lambert93_longitude"),
        ("sv", "0008_rename_rayon_zone_tamponee_zone_rayon_zone_tampon_and_more"),
    ]

    operations = []
