# Generated by Django 5.0.3 on 2024-07-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_document"),
        ("sv", "0009_fichedetection_date_creation"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichedetection",
            name="contacts",
            field=models.ManyToManyField(blank=True, to="core.contact", verbose_name="Contacts"),
        ),
    ]
