# Generated by Django 5.0.3 on 2024-07-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0010_fichedetection_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="prelevement",
            name="resultat",
            field=models.CharField(
                blank=True,
                choices=[("detecte", "Détecté"), ("non_detecte", "Non détecté")],
                max_length=50,
                verbose_name="Résultat",
            ),
        ),
    ]
