# Generated by Django 5.0.3 on 2024-08-01 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0012_fichedetection_createur_structure"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unite",
            name="type",
        ),
        migrations.RemoveField(
            model_name="fichedetection",
            name="createur",
        ),
        migrations.DeleteModel(
            name="Administration",
        ),
        migrations.DeleteModel(
            name="Unite",
        ),
    ]
