# Generated by Django 5.0.3 on 2024-08-01 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0013_remove_unite_type_remove_fichedetection_createur_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fichedetection",
            old_name="createur_structure",
            new_name="createur",
        ),
    ]
