# Generated by Django 5.0.3 on 2024-08-01 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_contact_agent_alter_contact_structure"),
        ("sv", "0014_rename_createur_structure_fichedetection_createur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichedetection",
            name="createur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.structure", verbose_name="Structure créatrice"
            ),
        ),
    ]
