# Generated by Django 5.0.8 on 2024-08-28 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0015_alter_fichedetection_createur"),
    ]

    operations = [
        migrations.AddField(
            model_name="lieu",
            name="activite_etablissement",
            field=models.CharField(blank=True, max_length=100, verbose_name="Activité établissement"),
        ),
        migrations.AddField(
            model_name="lieu",
            name="adresse_etablissement",
            field=models.CharField(blank=True, max_length=100, verbose_name="Adresse établissement"),
        ),
        migrations.AddField(
            model_name="lieu",
            name="is_etablissement",
            field=models.BooleanField(default=False, verbose_name="Établissement"),
        ),
        migrations.AddField(
            model_name="lieu",
            name="nom_etablissement",
            field=models.CharField(blank=True, max_length=100, verbose_name="Nom établissement"),
        ),
        migrations.AddField(
            model_name="lieu",
            name="pays_etablissement",
            field=models.CharField(blank=True, max_length=100, verbose_name="Pays établissement"),
        ),
        migrations.AddField(
            model_name="lieu",
            name="position_chaine_distribution_etablissement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sv.positionchainedistribution",
                verbose_name="Position dans la chaîne de distribution établissement",
            ),
        ),
        migrations.AddField(
            model_name="lieu",
            name="raison_sociale_etablissement",
            field=models.CharField(blank=True, max_length=100, verbose_name="Raison sociale établissement"),
        ),
        migrations.AddField(
            model_name="lieu",
            name="siret_etablissement",
            field=models.CharField(blank=True, max_length=100, verbose_name="SIRET établissement"),
        ),
        migrations.AddField(
            model_name="lieu",
            name="type_exploitant_etablissement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sv.typeexploitant",
                verbose_name="Type d'exploitant établissement",
            ),
        ),
        migrations.DeleteModel(
            name="Etablissement",
        ),
    ]
