# Generated by Django 5.0.3 on 2024-09-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0017_lieu_code_inpp_etablissement"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichedetection",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
