# Generated by Django 5.0.3 on 2024-09-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0019_alter_especeechantillon_code_oepp"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichedetection",
            name="is_ac_notified",
            field=models.BooleanField(default=False),
        ),
    ]
