# Generated by Django 5.0.8 on 2024-09-27 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_message_message_type_finsuivicontact_and_more"),
        ("sv", "0019_alter_especeechantillon_code_oepp"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaracteristiquesPrincipalesZoneDelimitee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("libelle", models.CharField(max_length=100, verbose_name="Libellé")),
            ],
            options={
                "verbose_name": "Caractéristiques principales de la zone délimitée",
                "verbose_name_plural": "Caractéristiques principales des zones délimitées",
                "db_table": "sv_caracteristiques_principales_zone_delimitee",
            },
        ),
        migrations.CreateModel(
            name="FicheZoneDelimitee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_creation", models.DateTimeField(auto_now_add=True, verbose_name="Date de création")),
                (
                    "vegetaux_infestes",
                    models.TextField(blank=True, verbose_name="Nombre ou volume de végétaux infestés"),
                ),
                ("commentaire", models.TextField(blank=True, verbose_name="Commentaire")),
                ("rayon_zone_tampon", models.FloatField(verbose_name="Rayon tampon réglemantaire ou arbitré")),
                (
                    "unite_rayon_zone_tampon",
                    models.CharField(
                        choices=[("m", "Metre"), ("km", "Kilometre")],
                        default="km",
                        max_length=2,
                        verbose_name="Unité du rayon tampon réglemantaire ou arbitré",
                    ),
                ),
                ("surface_tampon_totale", models.FloatField(verbose_name="Surface tampon totale")),
                (
                    "unite_surface_tampon_totale",
                    models.CharField(
                        choices=[("m2", "Metre Carre"), ("km2", "Kilometre Carre")],
                        default="m2",
                        max_length=3,
                        verbose_name="Unité de la surface tampon totale",
                    ),
                ),
                (
                    "is_zone_tampon_toute_commune",
                    models.BooleanField(
                        default=False, verbose_name="La zone tampon s'étend à toute la ou les commune(s)"
                    ),
                ),
                (
                    "caracteristiques_principales_zone_delimitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sv.caracteristiquesprincipaleszonedelimitee",
                        verbose_name="Caractéristiques principales de la zone délimitée",
                    ),
                ),
                (
                    "createur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.structure", verbose_name="Créateur"
                    ),
                ),
                (
                    "numero",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="sv.numerofiche", verbose_name="Numéro de fiche"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche zone délimitée",
                "verbose_name_plural": "Fiches zones délimitées",
            },
        ),
        migrations.AddField(
            model_name="fichedetection",
            name="hors_zone_infestee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fiches_detection",
                to="sv.fichezonedelimitee",
            ),
        ),
        migrations.CreateModel(
            name="ZoneInfestee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero", models.CharField(max_length=50, verbose_name="Numéro de la zone")),
                ("surface_infestee_totale", models.FloatField(verbose_name="Surface infestée totale")),
                (
                    "unite_surface_infestee_totale",
                    models.CharField(
                        choices=[("ha", "Hectare"), ("m2", "Metre Carre"), ("km2", "Kilometre Carre")],
                        default="m2",
                        max_length=3,
                        verbose_name="Unité de la surface infestée totale",
                    ),
                ),
                (
                    "fiche_zone_delimitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sv.fichezonedelimitee",
                        verbose_name="Fiche zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone infestée",
                "verbose_name_plural": "Zones infestées",
            },
        ),
        migrations.AddField(
            model_name="fichedetection",
            name="zone_infestee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fiches_detection",
                to="sv.zoneinfestee",
            ),
        ),
        migrations.AddConstraint(
            model_name="fichedetection",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("hors_zone_infestee__isnull", True), ("zone_infestee__isnull", True)),
                    models.Q(("hors_zone_infestee__isnull", True), ("zone_infestee__isnull", False)),
                    models.Q(("hors_zone_infestee__isnull", False), ("zone_infestee__isnull", True)),
                    _connector="OR",
                ),
                name="check_hors_zone_infestee_or_zone_infestee_or_none",
            ),
        ),
    ]
