# Generated by Django 5.0.8 on 2024-10-02 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_message_message_type"),
        ("sv", "0020_fichedetection_is_ac_notified"),
    ]

    operations = [
        migrations.CreateModel(
            name="FicheZoneDelimitee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_creation", models.DateTimeField(auto_now_add=True, verbose_name="Date de création")),
                (
                    "caracteristiques_principales_zone_delimitee",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "plein_air_zone_production_champ",
                                "(1) Plein air — zone de production (1.1) champ (culture, pâturage)",
                            ),
                            (
                                "plein_air_zone_production_verger_vigne",
                                "(1) Plein air — zone de production (1.2) verger/vigne",
                            ),
                            (
                                "plein_air_zone_production_pepiniere",
                                "(1) Plein air — zone de production (1.3) pépinière",
                            ),
                            ("plein_air_zone_production_foret", "(1) Plein air — zone de production (1.4) forêt"),
                            ("plein_air_autre_jardin_prive", "(2) Plein air — autre (2.1) jardin privé"),
                            ("plein_air_autre_sites_publics", "(2) Plein air — autre (2.2) sites publics"),
                            ("plein_air_autre_zone_protegee", "(2) Plein air — autre (2.3) zone protégée"),
                            (
                                "plein_air_autre_plantes_sauvages",
                                "(2) Plein air — autre (2.4) plantes sauvages dans des zones non protégées",
                            ),
                            ("plein_air_autre_autre", "(2) Plein air — autre (2.5) autre (veuillez préciser)"),
                            ("environnement_ferme_serre", "(3) Environnement fermé (3.1) serre"),
                            (
                                "environnement_ferme_autres_jardins_hiver",
                                "(3) Environnement fermé (3.2) autres jardins d’hiver",
                            ),
                            (
                                "environnement_ferme_site_prive",
                                "(3) Environnement fermé (3.3) site privé (autre qu’une serre)",
                            ),
                            (
                                "environnement_ferme_site_public",
                                "(3) Environnement fermé (3.4) site public (autre qu’une serre)",
                            ),
                            ("environnement_ferme_autre", "(3) Environnement fermé (3.5) autre (veuillez préciser)"),
                        ],
                        max_length=50,
                        verbose_name="Caractéristiques principales de la zone délimitée",
                    ),
                ),
                (
                    "vegetaux_infestes",
                    models.TextField(blank=True, verbose_name="Nombre ou volume de végétaux infestés"),
                ),
                ("commentaire", models.TextField(blank=True, verbose_name="Commentaire")),
                ("rayon_zone_tampon", models.FloatField(verbose_name="Rayon tampon réglemantaire ou arbitré")),
                (
                    "unite_rayon_zone_tampon",
                    models.CharField(
                        choices=[("m", "Metre"), ("km", "Kilometre")],
                        default="km",
                        max_length=2,
                        verbose_name="Unité du rayon tampon réglemantaire ou arbitré",
                    ),
                ),
                ("surface_tampon_totale", models.FloatField(verbose_name="Surface tampon totale")),
                (
                    "unite_surface_tampon_totale",
                    models.CharField(
                        choices=[("m2", "Metre Carre"), ("km2", "Kilometre Carre")],
                        default="m2",
                        max_length=3,
                        verbose_name="Unité de la surface tampon totale",
                    ),
                ),
                (
                    "is_zone_tampon_toute_commune",
                    models.BooleanField(
                        default=False, verbose_name="La zone tampon s'étend à toute la ou les commune(s)"
                    ),
                ),
                (
                    "createur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.structure", verbose_name="Créateur"
                    ),
                ),
                (
                    "numero",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="sv.numerofiche", verbose_name="Numéro de fiche"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche zone délimitée",
                "verbose_name_plural": "Fiches zones délimitées",
            },
        ),
        migrations.AddField(
            model_name="fichedetection",
            name="hors_zone_infestee",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="sv.fichezonedelimitee"
            ),
        ),
        migrations.CreateModel(
            name="ZoneInfestee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero", models.CharField(max_length=50, verbose_name="Numéro de la zone")),
                ("surface_infestee_totale", models.FloatField(verbose_name="Surface infestée totale")),
                (
                    "unite_surface_infestee_totale",
                    models.CharField(
                        choices=[("ha", "Hectare"), ("m2", "Metre Carre"), ("km2", "Kilometre Carre")],
                        default="m2",
                        max_length=3,
                        verbose_name="Unité de la surface infestée totale",
                    ),
                ),
                (
                    "fiche_zone_delimitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sv.fichezonedelimitee",
                        verbose_name="Fiche zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone infestée",
                "verbose_name_plural": "Zones infestées",
            },
        ),
        migrations.AddField(
            model_name="fichedetection",
            name="zone_infestee",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="sv.zoneinfestee"
            ),
        ),
    ]
