# Generated by Django 5.0.8 on 2024-10-08 10:02

from django.db import migrations, models


def add_default_visibilite_to_existing_fichedetection(apps, schema_editor):
    FicheDetection = apps.get_model("sv", "FicheDetection")
    for fiche in FicheDetection.objects.all():
        fiche.visibilite = "brouillon"
        fiche.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0021_fichezonedelimitee_fichedetection_hors_zone_infestee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichedetection",
            name="visibilite",
            field=models.CharField(
                choices=[
                    ("brouillon", "Vous seul pourrez voir la fiche et la modifier"),
                    (
                        "local",
                        "Seul votre structure et l'administration centrale pourront consulter et modifier la fiche",
                    ),
                    ("national", "La fiche sera et modifiable par toutes les structures"),
                ],
                default="brouillon",
                max_length=100,
            ),
        ),
        migrations.RunPython(add_default_visibilite_to_existing_fichedetection, migrations.RunPython.noop),
    ]
