# Generated by Django 5.0.3 on 2024-10-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0022_fichedetection_visibilite"),
    ]

    operations = [
        migrations.AddField(
            model_name="prelevement",
            name="numero_resytal",
            field=models.CharField(blank=True, max_length=100, verbose_name="Numéro RESYTAL"),
        ),
    ]
