# Generated by Django 5.0.3 on 2024-10-11 11:37

from django.db import migrations, models


def copy_fk_to_charfield(apps, schema_editor):
    Prelevement = apps.get_model("sv", "Prelevement")

    for prelevement in Prelevement.objects.all():
        matrice = prelevement.matrice_prelevee
        if matrice:
            prelevement.matrice_prelevee_temp = prelevement.matrice_prelevee.libelle.lower()
            prelevement.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0022_fichedetection_visibilite"),
    ]

    operations = [
        migrations.AddField(
            model_name="prelevement",
            name="matrice_prelevee_temp",
            field=models.CharField(
                choices=[
                    ("plante vivante", "Plante vivante"),
                    ("partie vivante de plante", "Partie vivante de plante"),
                    ("caisse", "Caisse"),
                    ("palette", "Palette"),
                    ("autre emballage en bois", "Autre emballage en bois"),
                    ("ecorce", "Ecorce"),
                    ("grume", "Grume"),
                    ("sciage", "Sciage"),
                    ("autre bois", "Autre bois"),
                    ("insecte", "Insecte"),
                    ("environnement", "Environnement"),
                ],
                max_length=50,
                null=True,
                verbose_name="Matrice prélevée",
            ),
        ),
        migrations.RunPython(copy_fk_to_charfield, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="prelevement",
            name="matrice_prelevee",
        ),
        migrations.RenameField(
            model_name="prelevement",
            old_name="matrice_prelevee_temp",
            new_name="matrice_prelevee",
        ),
    ]
