# Generated by Django 5.0.8 on 2024-10-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_message_message_type"),
        ("sv", "0023_prelevement_numero_resytal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichezonedelimitee",
            name="rayon_zone_tampon",
            field=models.FloatField(blank=True, null=True, verbose_name="Rayon tampon réglementaire ou arbitré"),
        ),
        migrations.AlterField(
            model_name="fichezonedelimitee",
            name="surface_tampon_totale",
            field=models.FloatField(blank=True, null=True, verbose_name="Surface tampon totale"),
        ),
        migrations.AlterField(
            model_name="fichezonedelimitee",
            name="unite_rayon_zone_tampon",
            field=models.CharField(
                choices=[("m", "Metre"), ("km", "Kilometre")],
                default="km",
                max_length=2,
                verbose_name="Unité du rayon tampon réglementaire ou arbitré",
            ),
        ),
        migrations.AlterField(
            model_name="zoneinfestee",
            name="numero",
            field=models.CharField(blank=True, max_length=50, verbose_name="Numéro de la zone"),
        ),
        migrations.AlterField(
            model_name="zoneinfestee",
            name="surface_infestee_totale",
            field=models.FloatField(blank=True, null=True, verbose_name="Surface infestée totale"),
        ),
        migrations.AddConstraint(
            model_name="fichedetection",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("hors_zone_infestee__isnull", True), ("zone_infestee__isnull", True)),
                    models.Q(("hors_zone_infestee__isnull", True), ("zone_infestee__isnull", False)),
                    models.Q(("hors_zone_infestee__isnull", False), ("zone_infestee__isnull", True)),
                    _connector="OR",
                ),
                name="check_hors_zone_infestee_or_zone_infestee_or_none",
            ),
        ),
    ]
