# Generated by Django 5.0.3 on 2024-10-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sv", "0027_zoneinfestee_rayon_zoneinfestee_unite_rayon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zoneinfestee",
            name="numero",
        ),
        migrations.AlterField(
            model_name="fichezonedelimitee",
            name="rayon_zone_tampon",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Rayon tampon réglementaire ou arbitré",
            ),
        ),
    ]
