# Generated by Django 5.0.3 on 2024-11-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_message_message_type"),
        ("sv", "0027_remove_zoneinfestee_numero_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichezonedelimitee",
            name="contacts",
            field=models.ManyToManyField(blank=True, to="core.contact", verbose_name="Contacts"),
        ),
    ]
