# Generated by Django 5.0.3 on 2024-11-04 15:27

import django.db.models.deletion
import sv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sv", "0027_remove_zoneinfestee_numero_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichezonedelimitee",
            name="etat",
            field=models.ForeignKey(
                default=sv.models.Etat.get_etat_initial,
                on_delete=django.db.models.deletion.PROTECT,
                to="sv.etat",
                verbose_name="État de la fiche",
            ),
        ),
    ]
