# Generated by Django 5.0.3 on 2024-11-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0028_fichezonedelimitee_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichezonedelimitee",
            name="visibilite",
            field=models.CharField(
                choices=[
                    ("brouillon", "Vous seul pourrez voir la fiche et la modifier"),
                    (
                        "local",
                        "Seul votre structure et l'administration centrale pourront consulter et modifier la fiche",
                    ),
                    (
                        "national",
                        "La fiche sera et modifiable par toutes les structures",
                    ),
                ],
                default="brouillon",
                max_length=100,
            ),
        ),
    ]
