# Generated by Django 5.0.8 on 2024-11-13 10:08
import datetime
import django.db.models.deletion
from django.db import migrations, models, transaction


def set_numero_to_none_for_existing_fiches_in_brouillon(apps, schema_editor):
    FicheDetection = apps.get_model("sv", "FicheDetection")
    FicheDetection.objects.filter(visibilite="brouillon").update(numero=None)


def reverse_set_numero_to_none_for_existing_fiches_in_brouillon(apps, schema_editor):
    FicheDetection = apps.get_model("sv", "FicheDetection")
    NumeroFiche = apps.get_model("sv", "NumeroFiche")

    with transaction.atomic():
        annee_courante = datetime.datetime.now().year
        dernier_numero = NumeroFiche.objects.filter(annee=annee_courante).order_by("-numero").first()
        prochain_numero = 1 if not dernier_numero else dernier_numero.numero + 1

        for fiche in FicheDetection.objects.filter(visibilite="brouillon"):
            nouveau_numero = NumeroFiche.objects.create(annee=annee_courante, numero=prochain_numero)
            FicheDetection.objects.filter(id=fiche.id).update(numero=nouveau_numero)
            prochain_numero += 1


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_document_document_type"),
        ("sv", "0029_fichezonedelimitee_visibilite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichedetection",
            name="numero",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sv.numerofiche",
                verbose_name="Numéro de fiche",
            ),
        ),
        migrations.RunPython(
            set_numero_to_none_for_existing_fiches_in_brouillon,
            reverse_set_numero_to_none_for_existing_fiches_in_brouillon,
        ),
        migrations.AddConstraint(
            model_name="fichedetection",
            constraint=models.CheckConstraint(
                condition=models.Q(("visibilite", "brouillon"), ("numero__isnull", False), _negated=True),
                name="check_numero_fiche_is_null_when_visibilite_is_brouillon",
            ),
        ),
    ]
