# Generated by Django 5.0.8 on 2024-11-13 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0030_alter_fichedetection_numero_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichezonedelimitee",
            name="etat",
            field=models.ForeignKey(
                default="sv.models.Etat.get_etat_initial",
                on_delete=django.db.models.deletion.PROTECT,
                to="sv.etat",
                verbose_name="État de la fiche",
            ),
        ),
    ]
