# Generated by Django 5.0.8 on 2024-11-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0031_fichezonedelimitee_etat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichezonedelimitee",
            name="vegetaux_infestes",
        ),
        migrations.AddField(
            model_name="fichedetection",
            name="vegetaux_infestes",
            field=models.TextField(blank=True, verbose_name="Nombre ou volume de végétaux infestés"),
        ),
    ]
