# Generated by Django 5.0.8 on 2024-11-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0035_remove_lieu_type_exploitant_etablissement_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichezonedelimitee",
            name="caracteristiques_principales_zone_delimitee",
        ),
        migrations.AddField(
            model_name="zoneinfestee",
            name="caracteristique_principale",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "plein_air_zone_production_champ",
                        "(1) Plein air — zone de production (1.1) champ (culture, pâturage)",
                    ),
                    ("plein_air_zone_production_verger_vigne", "(1) Plein air — zone de production (1.2) verger/vigne"),
                    ("plein_air_zone_production_pepiniere", "(1) Plein air — zone de production (1.3) pépinière"),
                    ("plein_air_zone_production_foret", "(1) Plein air — zone de production (1.4) forêt"),
                    ("plein_air_autre_jardin_prive", "(2) Plein air — autre (2.1) jardin privé"),
                    ("plein_air_autre_sites_publics", "(2) Plein air — autre (2.2) sites publics"),
                    ("plein_air_autre_zone_protegee", "(2) Plein air — autre (2.3) zone protégée"),
                    (
                        "plein_air_autre_plantes_sauvages",
                        "(2) Plein air — autre (2.4) plantes sauvages dans des zones non protégées",
                    ),
                    ("plein_air_autre_autre", "(2) Plein air — autre (2.5) autre (veuillez préciser)"),
                    ("environnement_ferme_serre", "(3) Environnement fermé (3.1) serre"),
                    (
                        "environnement_ferme_autres_jardins_hiver",
                        "(3) Environnement fermé (3.2) autres jardins d’hiver",
                    ),
                    ("environnement_ferme_site_prive", "(3) Environnement fermé (3.3) site privé (autre qu’une serre)"),
                    (
                        "environnement_ferme_site_public",
                        "(3) Environnement fermé (3.4) site public (autre qu’une serre)",
                    ),
                    ("environnement_ferme_autre", "(3) Environnement fermé (3.5) autre (veuillez préciser)"),
                ],
                max_length=50,
                verbose_name="Caractéristique principale",
            ),
        ),
    ]
