# Generated by Django 5.0.8 on 2024-11-18 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0037_auto_20241115_1506"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichezonedelimitee",
            name="is_zone_tampon_toute_commune",
        ),
    ]
