# Generated by Django 5.0.8 on 2024-11-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0038_remove_fichezonedelimitee_is_zone_tampon_toute_commune"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lieu", old_name="code_inpp_etablissement", new_name="code_inupp_etablissement"
        ),
        migrations.AlterField(
            model_name="lieu",
            name="code_inupp_etablissement",
            field=models.CharField(blank=True, max_length=50, verbose_name="Code INUPP"),
        ),
    ]
