# Generated by Django 5.0.8 on 2024-11-22 20:45
import datetime

from django.db import migrations, models, transaction
import django.db.models.deletion


def set_numero_to_none_for_existing_fiche_zone_delimitee_in_brouillon(apps, schema_editor):
    FicheZoneDelimitee = apps.get_model("sv", "FicheZoneDelimitee")
    fiches_brouillon = FicheZoneDelimitee.objects.filter(visibilite="brouillon")
    for fiche in fiches_brouillon:
        if fiche.numero:
            numero = fiche.numero
            fiche.numero = None
            fiche.save()
            numero.delete()


def reverse_set_numero_to_none_for_existing_fiche_zone_delimitee_in_brouillon(apps, schema_editor):
    FicheZoneDelimitee = apps.get_model("sv", "FicheZoneDelimitee")
    NumeroFiche = apps.get_model("sv", "NumeroFiche")

    with transaction.atomic():
        annee_courante = datetime.datetime.now().year
        dernier_numero = NumeroFiche.objects.filter(annee=annee_courante).order_by("-numero").first()
        prochain_numero = 1 if not dernier_numero else dernier_numero.numero + 1

        for fiche in FicheZoneDelimitee.objects.filter(visibilite="brouillon"):
            nouveau_numero = NumeroFiche.objects.create(annee=annee_courante, numero=prochain_numero)
            FicheZoneDelimitee.objects.filter(id=fiche.id).update(numero=nouveau_numero)
            prochain_numero += 1


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_create_access_admin_group"),
        ("sv", "0040_rename_OE_prefix_20241119_1541"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichezonedelimitee",
            name="numero",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sv.numerofiche",
                verbose_name="Numéro de fiche",
            ),
        ),
        migrations.RunPython(
            set_numero_to_none_for_existing_fiche_zone_delimitee_in_brouillon,
            reverse_set_numero_to_none_for_existing_fiche_zone_delimitee_in_brouillon,
        ),
        migrations.AddConstraint(
            model_name="fichezonedelimitee",
            constraint=models.CheckConstraint(
                condition=models.Q(("visibilite", "brouillon"), ("numero__isnull", False), _negated=True),
                name="check_fiche_zone_delimitee_numero_fiche_is_null_when_visibilite_is_brouillon",
            ),
        ),
    ]
