# Generated by Django 5.0.8 on 2024-11-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0040_rename_OE_prefix_20241119_1541"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contexte",
            name="nom",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="especeechantillon",
            name="libelle",
            field=models.CharField(max_length=100, unique=True, verbose_name="Libellé"),
        ),
        migrations.AlterField(
            model_name="laboratoireagree",
            name="nom",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="laboratoireconfirmationofficielle",
            name="nom",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="matriceprelevee",
            name="libelle",
            field=models.CharField(max_length=100, unique=True, verbose_name="Libellé"),
        ),
        migrations.AlterField(
            model_name="organismenuisible",
            name="code_oepp",
            field=models.CharField(unique=True, verbose_name="Code OEPP"),
        ),
        migrations.AlterField(
            model_name="organismenuisible",
            name="libelle_court",
            field=models.CharField(max_length=255, unique=True, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="positionchainedistribution",
            name="libelle",
            field=models.CharField(max_length=100, unique=True, verbose_name="Libellé"),
        ),
        migrations.AlterField(
            model_name="siteinspection",
            name="nom",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="statutetablissement",
            name="libelle",
            field=models.CharField(max_length=100, unique=True, verbose_name="Libellé"),
        ),
        migrations.AlterField(
            model_name="statutevenement",
            name="libelle",
            field=models.CharField(max_length=100, unique=True, verbose_name="Libellé"),
        ),
        migrations.AlterField(
            model_name="statutreglementaire",
            name="code",
            field=models.CharField(max_length=10, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="statutreglementaire",
            name="libelle",
            field=models.CharField(max_length=100, unique=True, verbose_name="Libellé"),
        ),
        migrations.AlterField(
            model_name="structurepreleveur",
            name="nom",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nom"),
        ),
    ]
