# Generated by Django 5.0.8 on 2024-11-28 16:05

from django.db import migrations, models

import sv.models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0041_alter_fichezonedelimitee_numero_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lieu",
            name="nom",
            field=models.CharField(max_length=100, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="lieu",
            name="wgs84_latitude",
            field=models.FloatField(
                blank=True, null=True, validators=[sv.models.validate_wgs84_latitude], verbose_name="Latitude WGS84"
            ),
        ),
        migrations.AlterField(
            model_name="lieu",
            name="wgs84_longitude",
            field=models.FloatField(
                blank=True, null=True, validators=[sv.models.validate_wgs84_longitude], verbose_name="Longitude WGS84"
            ),
        ),
        migrations.AlterField(
            model_name="prelevement",
            name="resultat",
            field=models.CharField(
                choices=[("detecte", "Détecté"), ("non_detecte", "Non détecté")], max_length=50, verbose_name="Résultat"
            ),
        ),
    ]
