# Generated by Django 5.0.8 on 2024-11-29 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0042_alter_lieu_nom_alter_lieu_wgs84_latitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lieu",
            name="lambert93_latitude",
        ),
        migrations.RemoveField(
            model_name="lieu",
            name="lambert93_longitude",
        ),
    ]
