# Generated by Django 5.1.2 on 2024-12-05 17:40

from django.db import migrations


def add_enquete_in_statut_evenement(apps, schema_editor):
    StatutEvenement = apps.get_model("sv", "StatutEvenement")
    StatutEvenement.objects.get_or_create(libelle="Enquête")


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0043_remove_lieu_lambert93_latitude_and_more"),
    ]

    operations = [
        migrations.RunPython(add_enquete_in_statut_evenement, migrations.RunPython.noop),
    ]
