# Generated by Django 5.1.2 on 2024-12-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0043_remove_lieu_lambert93_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichezonedelimitee",
            name="unite_surface_tampon_totale",
            field=models.CharField(
                choices=[("m2", "Metre Carre"), ("km2", "Kilometre Carre"), ("ha", "Hectare")],
                default="m2",
                max_length=3,
                verbose_name="Unité de la surface tampon totale",
            ),
        ),
    ]
