# Generated by Django 5.0.8 on 2024-12-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0043_remove_lieu_lambert93_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lieu",
            name="commune",
            field=models.CharField(blank=True, max_length=100, verbose_name="Commune"),
        ),
    ]
