# Generated by Django 5.1.2 on 2024-12-10 09:47

from django.db import migrations


def add_enquete_in_statut_evenement(apps, schema_editor):
    StatutEvenement = apps.get_model("sv", "StatutEvenement")
    StatutEvenement.objects.get_or_create(libelle="Enquête")


def reverse_add_enquete_in_statut_evenement(apps, schema_editor):
    StatutEvenement = apps.get_model("sv", "StatutEvenement")
    StatutEvenement.objects.filter(libelle="Enquête").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0044_alter_lieu_commune"),
    ]

    operations = [
        migrations.RunPython(add_enquete_in_statut_evenement, reverse_add_enquete_in_statut_evenement),
    ]
