# Generated by Django 5.0.8 on 2024-12-09 13:08

from django.db import migrations


def copy_numero_prelevement(apps, schema_editor):
    Prelevement = apps.get_model("sv", "Prelevement")
    for prelevement in Prelevement.objects.exclude(numero_phytopass=""):
        prelevement.numero_echantillon = prelevement.numero_phytopass
        prelevement.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0044_alter_lieu_commune"),
    ]

    operations = [
        migrations.RunPython(copy_numero_prelevement, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="prelevement",
            name="numero_phytopass",
        ),
    ]
