# Generated by Django 5.1.2 on 2024-12-10 11:00

from django.db import migrations


def add_salim_item_to_preleveur_list(apps, schema_editor):
    StructurePreleveur = apps.get_model("sv", "StructurePreleveur")
    StructurePreleveur.objects.get_or_create(nom="SALIM")


def reverse_add_salim_item_to_preleveur_list(apps, schema_editor):
    StructurePreleveur = apps.get_model("sv", "StructurePreleveur")
    StructurePreleveur.objects.filter(nom="SALIM").delete()


def replace_ovs_by_delegataire(apps, schema_editor):
    StructurePreleveur = apps.get_model("sv", "StructurePreleveur")
    StructurePreleveur.objects.filter(nom="OVS").update(nom="Délégataire")


def reverse_replace_ovs_by_delegataire(apps, schema_editor):
    StructurePreleveur = apps.get_model("sv", "StructurePreleveur")
    StructurePreleveur.objects.filter(nom="Délégataire").update(nom="OVS")


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0045_add_enquete_in_statut_evenement"),
    ]

    operations = [
        migrations.RunPython(add_salim_item_to_preleveur_list, reverse_add_salim_item_to_preleveur_list),
        migrations.RunPython(replace_ovs_by_delegataire, reverse_replace_ovs_by_delegataire),
    ]
