# Generated by Django 5.0.8 on 2024-12-10 15:42

from django.db import migrations


def prelevement_resultat_replace_blank_by_value(apps, schema_editor):
    Prelevement = apps.get_model("sv", "Prelevement")
    Prelevement.objects.filter(resultat="").update(resultat="detecte")


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0048_rename_structurepreleveur_structurepreleveuse_and_more"),
    ]

    operations = [
        migrations.RunPython(prelevement_resultat_replace_blank_by_value, migrations.RunPython.noop),
    ]
