# Generated by Django 5.1.2 on 2024-12-12 09:50

from django.db import migrations


def update_especes_echantillon_values(apps, schema_editor):
    EspeceEchantillon = apps.get_model("sv", "EspeceEchantillon")
    especes_echantillon_to_update = {
        "1CXQG": "Crataegomespilus",
        "CXQDA": "Crataegomespilus dardarii",
        "1LBUG": "Laburnocytisus",
        "LBUAD": "Laburnocytisus adamii",
        "LBUSS": "Laburnocytisus sp.",
    }
    for code_oepp, libelle in especes_echantillon_to_update.items():
        EspeceEchantillon.objects.filter(code_oepp=code_oepp).update(libelle=libelle)


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0050_remove_prelevement_numero_phytopass"),
    ]

    operations = [
        migrations.RunPython(update_especes_echantillon_values, reverse_code=migrations.RunPython.noop),
    ]
