# Generated by Django 5.1.2 on 2024-12-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0051_update_especes_echantillon_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zoneinfestee",
            name="unite_surface_infestee_totale",
            field=models.CharField(
                choices=[("m2", "Metre Carre"), ("km2", "Kilometre Carre"), ("ha", "Hectare")],
                default="m2",
                max_length=3,
                verbose_name="Unité de la surface infestée totale",
            ),
        ),
    ]
