# Generated by Django 5.0.8 on 2024-12-12 14:27

from django.db import migrations, models


def clear_prelevements_fields_if_needed(apps, schema_editor):
    Prelevement = apps.get_model("sv", "Prelevement")
    for prelevement in Prelevement.objects.filter(structure_preleveuse__nom="Exploitant", is_officiel=True):
        prelevement.is_officiel = False
        prelevement.save()

    for prelevement in Prelevement.objects.filter(is_officiel=False):
        prelevement.numero_rapport_inspection = ""
        prelevement.laboratoire_agree = None
        prelevement.laboratoire_confirmation_officielle = None
        prelevement.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0053_remove_prelevement_numero_resytal_and_more"),
    ]

    operations = [
        migrations.RunPython(clear_prelevements_fields_if_needed, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="prelevement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_officiel", True),
                    models.Q(
                        ("laboratoire_agree__isnull", True),
                        ("laboratoire_confirmation_officielle__isnull", True),
                        ("numero_rapport_inspection", ""),
                    ),
                    _connector="OR",
                ),
                name="check_officiel_fields_empty_or_null",
            ),
        ),
    ]
