# Generated by Django 5.1.2 on 2024-12-16 10:57

import django.db.models.deletion
from django.db import migrations, models


def create_new_laboratoires(apps, schema_editor):
    LaboratoireAgree = apps.get_model("sv", "LaboratoireAgree")
    LaboratoireConfirmationOfficielle = apps.get_model("sv", "LaboratoireConfirmationOfficielle")
    Laboratoire = apps.get_model("sv", "Laboratoire")
    Prelevement = apps.get_model("sv", "Prelevement")
    for labo in LaboratoireAgree.objects.all():
        Laboratoire.objects.create(nom=labo.nom, confirmation_officielle=False)
    for labo in LaboratoireConfirmationOfficielle.objects.all():
        Laboratoire.objects.create(nom=labo.nom, confirmation_officielle=True)

    for prelevement in Prelevement.objects.all():
        if prelevement.laboratoire_agree:
            prelevement.laboratoire = Laboratoire.objects.get(nom=prelevement.laboratoire_agree.nom)
            prelevement.save()
        elif prelevement.laboratoire_confirmation_officielle:
            prelevement.laboratoire = Laboratoire.objects.get(nom=prelevement.laboratoire_confirmation_officielle.nom)
            prelevement.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0054_prelevement_check_officiel_fields_empty_or_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="Laboratoire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "confirmation_officielle",
                    models.BooleanField(
                        default=False,
                        verbose_name="Peut fournir une confirmation officielle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Laboratoire",
                "verbose_name_plural": "Laboratoires",
                "ordering": ["nom"],
            },
        ),
        migrations.RunPython(create_new_laboratoires, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="prelevement",
            name="laboratoire_agree",
        ),
        migrations.RemoveField(
            model_name="prelevement",
            name="laboratoire_confirmation_officielle",
        ),
        migrations.AddField(
            model_name="prelevement",
            name="type_analyse",
            field=models.CharField(
                choices=[
                    ("premiere_intention", "De première intention"),
                    ("confirmation", "De confirmation"),
                ],
                default="premiere_intention",
                max_length=50,
                verbose_name="Type d'analyse",
            ),
        ),
        migrations.AddField(
            model_name="prelevement",
            name="laboratoire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sv.laboratoire",
                verbose_name="Laboratoire",
            ),
        ),
        migrations.AddConstraint(
            model_name="prelevement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_officiel", True),
                    models.Q(("laboratoire__isnull", True), ("numero_rapport_inspection", "")),
                    _connector="OR",
                ),
                name="check_officiel_fields_empty_or_null",
            ),
        ),
        migrations.DeleteModel(
            name="LaboratoireAgree",
        ),
        migrations.DeleteModel(
            name="LaboratoireConfirmationOfficielle",
        ),
    ]
