# Generated by Django 5.1.2 on 2024-12-16 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0054_prelevement_check_officiel_fields_empty_or_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichezonedelimitee",
            name="rayon_zone_tampon",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Rayon tampon réglementaire ou arbitré",
            ),
        ),
        migrations.AlterField(
            model_name="fichezonedelimitee",
            name="surface_tampon_totale",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Surface tampon totale",
            ),
        ),
        migrations.AlterField(
            model_name="zoneinfestee",
            name="rayon",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Rayon de la zone infestée",
            ),
        ),
        migrations.AlterField(
            model_name="zoneinfestee",
            name="surface_infestee_totale",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Surface infestée totale",
            ),
        ),
    ]
