# Generated by Django 5.1.2 on 2024-12-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0055_alter_fichezonedelimitee_rayon_zone_tampon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contexte",
            name="nom",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="especeechantillon",
            name="libelle",
            field=models.CharField(max_length=100, unique=True, verbose_name="Libellé"),
        ),
        migrations.AlterField(
            model_name="laboratoireagree",
            name="nom",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="laboratoireconfirmationofficielle",
            name="nom",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="matriceprelevee",
            name="libelle",
            field=models.CharField(max_length=100, unique=True, verbose_name="Libellé"),
        ),
        migrations.AlterField(
            model_name="organismenuisible",
            name="code_oepp",
            field=models.CharField(unique=True, verbose_name="Code OEPP"),
        ),
        migrations.AlterField(
            model_name="organismenuisible",
            name="libelle_court",
            field=models.CharField(max_length=255, unique=True, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="positionchainedistribution",
            name="libelle",
            field=models.CharField(max_length=100, unique=True, verbose_name="Libellé"),
        ),
        migrations.AlterField(
            model_name="siteinspection",
            name="nom",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="statutetablissement",
            name="libelle",
            field=models.CharField(max_length=100, unique=True, verbose_name="Libellé"),
        ),
        migrations.AlterField(
            model_name="statutevenement",
            name="libelle",
            field=models.CharField(max_length=100, unique=True, verbose_name="Libellé"),
        ),
        migrations.AlterField(
            model_name="statutreglementaire",
            name="code",
            field=models.CharField(max_length=10, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="statutreglementaire",
            name="libelle",
            field=models.CharField(max_length=100, unique=True, verbose_name="Libellé"),
        ),
        migrations.AlterField(
            model_name="structurepreleveuse",
            name="nom",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nom"),
        ),
        migrations.AddConstraint(
            model_name="departement",
            constraint=models.UniqueConstraint(fields=("numero", "nom"), name="unique_departement_numero_nom"),
        ),
        migrations.AddConstraint(
            model_name="especeechantillon",
            constraint=models.UniqueConstraint(
                fields=("code_oepp", "libelle"), name="unique_espece_echantillon_codeoepp_libelle"
            ),
        ),
        migrations.AddConstraint(
            model_name="organismenuisible",
            constraint=models.UniqueConstraint(
                fields=("code_oepp", "libelle_court"), name="unique_organisme_nuisible_code_libelle"
            ),
        ),
        migrations.AddConstraint(
            model_name="statutreglementaire",
            constraint=models.UniqueConstraint(
                fields=("code", "libelle"), name="unique_statut_reglementaire_code_libelle"
            ),
        ),
    ]
