# Generated by Django 5.1.2 on 2024-12-16 14:50

from django.db import migrations


def add_organismes_nuisibles(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.get_or_create(code_oepp="XYLBAF", libelle_court="Xyleborus affinis")
    OrganismeNuisible.objects.get_or_create(code_oepp="XYLBFE", libelle_court="Xyleborus ferrugineus")
    OrganismeNuisible.objects.get_or_create(code_oepp="SCITGI", libelle_court="Scirtothrips ginkgoe")


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0055_alter_fichezonedelimitee_rayon_zone_tampon_and_more"),
    ]

    operations = [
        migrations.RunPython(add_organismes_nuisibles, reverse_code=migrations.RunPython.noop),
    ]
