# Generated by Django 5.1.2 on 2024-12-20 08:53

from django.db import migrations


def add_organismes_nuisibles(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.get_or_create(code_oepp="XYLBAF", libelle_court="Xyleborus affinis")
    OrganismeNuisible.objects.get_or_create(code_oepp="XYLBFE", libelle_court="Xyleborus ferrugineus")
    OrganismeNuisible.objects.get_or_create(code_oepp="SCITGI", libelle_court="Scirtothrips ginkgoe")


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0056_alter_contexte_nom_alter_especeechantillon_libelle_and_more"),
    ]

    operations = [
        migrations.RunPython(add_organismes_nuisibles, reverse_code=migrations.RunPython.noop),
    ]
