# Generated by Django 5.1.2 on 2024-12-16 10:57

from django.db import migrations, models
import django.db.models.deletion

from sv.constants import LABORATOIRES_AGREES, LABORATOIRES_CONFIRMATION_OFFICIELLE


def create_new_laboratoires(apps, schema_editor):
    Laboratoire = apps.get_model("sv", "Laboratoire")
    Prelevement = apps.get_model("sv", "Prelevement")

    for labo in LABORATOIRES_AGREES:
        Laboratoire.objects.create(nom=labo, confirmation_officielle=False)
    for labo in LABORATOIRES_CONFIRMATION_OFFICIELLE:
        Laboratoire.objects.create(nom=labo, confirmation_officielle=True)

    for prelevement in Prelevement.objects.all():
        prelevement.laboratoire = Laboratoire.objects.order_by("?").first()
        prelevement.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0057_update_organismes_nuisibles_data"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="prelevement",
            name="check_officiel_fields_empty_or_null",
        ),
        migrations.CreateModel(
            name="Laboratoire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("nom", models.CharField(max_length=100, verbose_name="Nom", unique=True)),
                (
                    "confirmation_officielle",
                    models.BooleanField(
                        default=False,
                        verbose_name="Peut fournir une confirmation officielle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Laboratoire",
                "verbose_name_plural": "Laboratoires",
                "ordering": ["nom"],
            },
        ),
        migrations.AddField(
            model_name="prelevement",
            name="type_analyse",
            field=models.CharField(
                choices=[
                    ("premiere_intention", "De première intention"),
                    ("confirmation", "De confirmation"),
                ],
                default="premiere_intention",
                max_length=50,
                verbose_name="Type d'analyse",
            ),
        ),
        migrations.AddField(
            model_name="prelevement",
            name="laboratoire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sv.laboratoire",
                verbose_name="Laboratoire",
            ),
        ),
        migrations.RunPython(create_new_laboratoires, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="prelevement",
            name="laboratoire_agree",
        ),
        migrations.RemoveField(
            model_name="prelevement",
            name="laboratoire_confirmation_officielle",
        ),
        migrations.AlterField(
            model_name="prelevement",
            name="matrice_prelevee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sv.matriceprelevee",
                verbose_name="Nature de l'objet",
            ),
        ),
        migrations.AlterField(
            model_name="prelevement",
            name="numero_echantillon",
            field=models.CharField(blank=True, max_length=100, verbose_name="N° d'échantillon"),
        ),
        migrations.AlterField(
            model_name="prelevement",
            name="type_analyse",
            field=models.CharField(
                choices=[
                    ("premiere_intention", "1ère intention"),
                    ("confirmation", "Confirmation"),
                ],
                default="premiere_intention",
                max_length=50,
                verbose_name="Type d'analyse",
            ),
        ),
        migrations.DeleteModel(
            name="LaboratoireAgree",
        ),
        migrations.DeleteModel(
            name="LaboratoireConfirmationOfficielle",
        ),
        migrations.AddConstraint(
            model_name="prelevement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_officiel", True),
                    ("numero_rapport_inspection", ""),
                    _connector="OR",
                ),
                name="check_numero_officiel_empty_or_null",
            ),
        ),
    ]
