# Generated by Django 5.1.4 on 2025-01-03 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0059_evenement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichezonedelimitee",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fichedetection",
            name="evenement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="detections",
                to="sv.evenement",
            ),
        ),
        migrations.AlterField(
            model_name="fichezonedelimitee",
            name="numero",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sv.numerofiche",
                verbose_name="Numéro de fiche",
            ),
        ),
    ]
