# Generated by Django 5.1.4 on 2025-01-09 19:02

from django.db import migrations


def update_laboratoires_data(apps, schema_editor):
    laboratoires_to_delete = {
        "ANSES 34 - Unité d'Entomologie et Plantes invasives",
        "ANSES 49 - Unité de Bactériologie Virologie et OGM",
        "ANSES 54b - Unité de Mycologie",
        "ANSES 35b - Unité de Nématologie",
        "ANSES 63 - Unité de Quarantaine et de virologie",
        "ANSES 974 - Unité des Ravageurs et agents pathogènes tropicaux",
        "SNES 49 - Laboratoire de l'unité technique détection de bioagresseurs",
    }

    Laboratoire = apps.get_model("sv", "Laboratoire")
    Prelevement = apps.get_model("sv", "Prelevement")

    for labo_nom in laboratoires_to_delete:
        labo = Laboratoire.objects.filter(nom=labo_nom).first()
        if labo:
            prelevements = Prelevement.objects.filter(laboratoire=labo)
            if prelevements.exists():
                prelevements.update(laboratoire=None)
            labo.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0060_fichezonedelimitee_is_deleted_and_more"),
    ]

    operations = [
        migrations.RunPython(update_laboratoires_data, migrations.RunPython.noop),
    ]
