# Generated by Django 5.1.4 on 2025-01-17 08:48

from django.db import migrations, models


def set_default_etat(apps, schema_editor):
    Evenement = apps.get_model("sv", "Evenement")
    Evenement.objects.update(etat="brouillon")


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0063_alter_evenement_organisme_nuisible_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenement",
            name="etat",
            field=models.CharField(
                choices=[
                    ("brouillon", "Brouillon"),
                    ("en_cours", "En cours"),
                    ("cloture", "Clôturé"),
                ],
                default="brouillon",
                max_length=100,
                verbose_name="État de l'événement",
            ),
        ),
        migrations.RunPython(set_default_etat, migrations.RunPython.noop),
    ]
