# Generated by Django 5.1.4 on 2025-01-17 09:24

from django.db import migrations

from sv.constants import LABORATOIRES_AGREES, LABORATOIRES_CONFIRMATION_OFFICIELLE


def set_confirmation_officielle(apps, schema_editor):
    Laboratoire = apps.get_model("sv", "Laboratoire")
    Laboratoire.objects.filter(nom__in=LABORATOIRES_CONFIRMATION_OFFICIELLE).update(confirmation_officielle=True)
    Laboratoire.objects.filter(nom__in=LABORATOIRES_AGREES).update(confirmation_officielle=False)


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0063_alter_evenement_organisme_nuisible_and_more"),
    ]

    operations = [
        migrations.RunPython(set_confirmation_officielle, reverse_code=migrations.RunPython.noop),
    ]
