# Generated by Django 5.1.4 on 2025-01-17 09:47

from django.db import migrations, models


def set_default_visibilite(apps, schema_editor):
    Evenement = apps.get_model("sv", "Evenement")
    Evenement.objects.update(visibilite="locale")


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0064_alter_evenement_etat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenement",
            name="visibilite",
            field=models.CharField(
                choices=[
                    (
                        "locale",
                        "Votre structure et l'administration centrale pourront consulter et modifier la fiche",
                    ),
                    (
                        "limitee",
                        "Les structures de votre choix pourront consulter et modifier la fiche",
                    ),
                    (
                        "nationale",
                        "La fiche sera visible et modifiable par toutes les structures",
                    ),
                ],
                default="locale",
                max_length=100,
            ),
        ),
        migrations.RunPython(set_default_visibilite, migrations.RunPython.noop),
    ]
