# Generated by Django 5.1.4 on 2025-01-21 14:46

from django.db import migrations, models


def set_default_etat(apps, schema_editor):
    Evenement = apps.get_model("sv", "Evenement")
    Evenement.objects.update(etat="brouillon")


def revert_default_etat(apps, schema_editor):
    Evenement = apps.get_model("sv", "Evenement")
    Etat = apps.get_model("sv", "Etat")
    etat, _ = Etat.objects.get_or_create(libelle="nouveau")
    Evenement.objects.update(etat=str(etat.pk))


def set_default_visibilite(apps, schema_editor):
    Evenement = apps.get_model("sv", "Evenement")
    Evenement.objects.update(visibilite="locale")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_alter_document_document_type"),
        ("sv", "0064_udpdate_labos_confirmation_officielle"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="evenement",
            name="check_evenement_numero_fiche_is_null_when_visibilite_is_brouillon",
        ),
        migrations.AddField(
            model_name="evenement",
            name="allowed_structures",
            field=models.ManyToManyField(related_name="allowed_structures", to="core.structure"),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="etat",
            field=models.CharField(
                choices=[
                    ("brouillon", "Brouillon"),
                    ("en_cours", "En cours"),
                    ("cloture", "Clôturé"),
                ],
                default="brouillon",
                max_length=100,
                verbose_name="État de l'événement",
            ),
        ),
        migrations.RunPython(set_default_etat, revert_default_etat),
        migrations.AlterField(
            model_name="evenement",
            name="visibilite",
            field=models.CharField(
                choices=[
                    (
                        "locale",
                        "Votre structure et l'administration centrale pourront consulter et modifier la fiche",
                    ),
                    (
                        "limitee",
                        "Les structures de votre choix pourront consulter et modifier la fiche",
                    ),
                    (
                        "nationale",
                        "La fiche sera visible et modifiable par toutes les structures",
                    ),
                ],
                default="locale",
                max_length=100,
            ),
        ),
        migrations.RunPython(set_default_visibilite, migrations.RunPython.noop),
    ]
