# Generated by Django 5.1.4 on 2025-01-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reversion", "0002_add_index_on_version_for_content_type_and_db"),
        ("sv", "0065_remove_evenement_check_evenement_numero_fiche_is_null_when_visibilite_is_brouillon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichezonedelimitee",
            name="is_deleted",
        ),
        migrations.AlterField(
            model_name="evenement",
            name="fiche_zone_delimitee",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sv.fichezonedelimitee",
                verbose_name="Fiche zone delimitée",
            ),
        ),
        migrations.CreateModel(
            name="VersionFicheZoneDelimitee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fiche_zone_delimitee_data", models.JSONField()),
                (
                    "revision",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="reversion.revision"),
                ),
            ],
        ),
    ]
