# Generated by Django 5.1.4 on 2025-01-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_alter_document_document_type"),
        ("sv", "0065_alter_evenement_visibilite"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="allowed_structures",
            field=models.ManyToManyField(related_name="allowed_structures", to="core.structure"),
        ),
    ]
