# Generated by Django 5.1.4 on 2025-01-23 20:40

from django.db import migrations


def assign_event_numero_to_zone(apps, schema_editor):
    Evenement = apps.get_model("sv", "Evenement")
    for event in Evenement.objects.filter(fiche_zone_delimitee__isnull=False):
        if event.fiche_zone_delimitee and not event.fiche_zone_delimitee.numero:
            event.fiche_zone_delimitee.numero = event.numero
            event.fiche_zone_delimitee.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0067_organismenuisible_libelle_long"),
    ]

    operations = [
        migrations.RunPython(assign_event_numero_to_zone, migrations.RunPython.noop),
    ]
