# Generated by Django 5.1.4 on 2025-01-24 09:05

from django.db import migrations

from sv.constants import POSITION_CHAINE_DISTRIBUTION


def set_position_chaine_distribution_to_null(apps, schema_editor):
    Lieu = apps.get_model("sv", "Lieu")
    Lieu.objects.all().update(position_chaine_distribution_etablissement=None)


def update_positions_chaine_distribution(apps, schema_editor):
    PositionChaineDistribution = apps.get_model("sv", "PositionChaineDistribution")
    PositionChaineDistribution.objects.all().delete()
    for libelle in POSITION_CHAINE_DISTRIBUTION:
        PositionChaineDistribution.objects.create(libelle=libelle)


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0068_assign_event_numero_to_zone"),
    ]

    operations = [
        migrations.RunPython(set_position_chaine_distribution_to_null, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(update_positions_chaine_distribution, reverse_code=migrations.RunPython.noop),
    ]
