# Generated by Django 5.1.5 on 2025-01-29 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0070_fix_fiche_zone_without_evenement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lieu",
            name="siret_etablissement",
            field=models.CharField(
                blank=True,
                max_length=14,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_siret",
                        message="Le SIRET doit contenir exactement 14 chiffres",
                        regex="^[0-9]{14}$",
                    )
                ],
                verbose_name="SIRET établissement",
            ),
        ),
    ]
