# Generated by Django 5.1.4 on 2025-01-31 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0071_alter_lieu_siret_etablissement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichezonedelimitee",
            name="numero",
        ),
    ]
