# Generated by Django 5.1.5 on 2025-02-06 15:38

from django.db import migrations


def fix_organisme_code_oepp(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    organisme = OrganismeNuisible.objects.filter(code_oepp="STEHHA:").first()
    if organisme:
        organisme.code_oepp = "STEHHA"
        organisme.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0073_alter_evenement_unique_together_and_more"),
    ]

    operations = [migrations.RunPython(fix_organisme_code_oepp, migrations.RunPython.noop)]
