# Generated by Django 5.1.5 on 2025-02-07 09:30

from django.db import migrations, models
import sv.validators


def migrate_numeros_fiche_detection(apps, schema_editor):
    FicheDetection = apps.get_model("sv", "FicheDetection")

    evenements = FicheDetection.objects.values_list("evenement_id", flat=True).distinct()
    for evenement_id in evenements:
        fiches = FicheDetection.objects.filter(evenement_id=evenement_id).order_by("numero__annee", "numero__numero")

        for index, fiche in enumerate(fiches, start=1):
            fiche.numero_detection = f"{fiche.evenement.numero_annee}.{fiche.evenement.numero_evenement}.{index}"
            fiche.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_document_is_infected"),
        ("sv", "0074_update_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichedetection",
            name="numero_detection",
            field=models.CharField(
                max_length=16,
                unique=True,
                null=True,
                validators=[sv.validators.validate_numero_detection],
                verbose_name="Numéro de détection",
            ),
        ),
        migrations.RunPython(migrate_numeros_fiche_detection, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="fichedetection",
            name="numero_detection",
            field=models.CharField(
                max_length=16,
                unique=True,
                null=False,
                validators=[sv.validators.validate_numero_detection],
                verbose_name="Numéro de détection",
            ),
        ),
        migrations.RemoveField(
            model_name="fichedetection",
            name="numero",
        ),
        migrations.DeleteModel(
            name="NumeroFiche",
        ),
    ]
