# Generated by Django 5.1.6 on 2025-02-13 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0075_fichedetection_numero_detection_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fichedetection",
            options={
                "ordering": ["numero_detection"],
                "verbose_name": "Fiche détection",
                "verbose_name_plural": "Fiches détection",
            },
        ),
    ]
