# Generated by Django 5.1.6 on 2025-02-13 10:08

from django.db import migrations, models


def clean_non_conclusif(apps, schema_editor):
    Prelevement = apps.get_model("sv", "Prelevement")
    Prelevement.objects.filter(resultat="non_conclusif").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0076_alter_fichedetection_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prelevement",
            name="resultat",
            field=models.CharField(
                choices=[("detecte", "Détecté"), ("non_detecte", "Non détecté"), ("non_conclusif", "Non conclusif")],
                max_length=50,
                verbose_name="Résultat",
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, clean_non_conclusif),
    ]
