# Generated by Django 5.1.6 on 2025-02-13 11:11

from django.db import migrations


def update_ornq_libelle(apps, schema_editor):
    StatutReglementaire = apps.get_model("sv", "StatutReglementaire")
    StatutReglementaire.objects.filter(
        code="ORNQ",
    ).update(libelle="organisme réglementé non quarantaine")


def reverse_ornq_libelle(apps, schema_editor):
    StatutReglementaire = apps.get_model("sv", "StatutReglementaire")
    StatutReglementaire.objects.filter(
        code="ORNQ",
    ).update(libelle="organisme réglementée non quarantaine")


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0077_alter_prelevement_resultat"),
    ]

    operations = [
        migrations.RunPython(update_ornq_libelle, reverse_code=reverse_ornq_libelle),
    ]
