# Generated by Django 5.1.7 on 2025-03-18 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0079_change_site_inspection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lieu",
            name="nom_etablissement",
        ),
    ]
