# Generated by Django 5.1.7 on 2025-03-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0081_alter_zoneinfestee_caracteristique_principale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lieu",
            name="code_inupp_etablissement",
            field=models.CharField(blank=True, max_length=10, verbose_name="Code INUPP"),
        ),
    ]
