# Generated by Django 5.1.7 on 2025-03-28 10:38

from django.db import migrations


def update_dsf_name(apps, schema_editor):
    apps.get_model("sv", "StructurePreleveuse").objects.filter(nom="DSF").update(nom="Correspondants observateurs DSF")


def revert_update_dsf_name(apps, schema_editor):
    apps.get_model("sv", "StructurePreleveuse").objects.filter(nom="Correspondants observateurs DSF").update(nom="DSF")


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0082_alter_lieu_code_inupp_etablissement"),
    ]

    operations = [
        migrations.RunPython(update_dsf_name, revert_update_dsf_name),
    ]
