# Generated by Django 5.1.7 on 2025-03-28 13:35

from django.db import migrations, transaction


def update_laboratoire_labocea_name(apps, schema_editor):
    Laboratoire = apps.get_model("sv", "Laboratoire")
    Prelevement = apps.get_model("sv", "Prelevement")

    labocea = Laboratoire._base_manager.filter(nom="Labocéa").first()
    lda22 = Laboratoire._base_manager.filter(nom="LDA 22").first()

    if labocea and lda22:
        with transaction.atomic():
            Prelevement.objects.filter(laboratoire=labocea).update(laboratoire=lda22)
            labocea.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0083_update_dsf_name"),
    ]

    operations = [
        migrations.RunPython(update_laboratoire_labocea_name, migrations.RunPython.noop),
    ]
