# Generated by Django 5.1.7 on 2025-04-01 08:54

from django.db import migrations


def set_laboratoire_lda22_is_active(apps, schema_editor):
    laboratoire_model = apps.get_model("sv", "Laboratoire")
    laboratoire_model._base_manager.filter(nom="LDA 22").update(is_active=True)


def unset_laboratoire_lda22_is_active(apps, schema_editor):
    laboratoire_model = apps.get_model("sv", "Laboratoire")
    laboratoire_model._base_manager.filter(nom="LDA 22").update(is_active=False)


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0084_update_laboratoire_labocea_name"),
    ]

    operations = [
        migrations.RunPython(set_laboratoire_lda22_is_active, unset_laboratoire_lda22_is_active),
    ]
