# Generated by Django 5.1.7 on 2025-04-04 11:10

from django.db import migrations


def add_organisme_nuisible(apps, schema_editor):
    organisme_nuisible_model = apps.get_model("sv", "OrganismeNuisible")
    organisme_nuisible_model.objects.get_or_create(
        code_oepp="PHYPPA",
        libelle_court="Candidatus Phytoplasma palmae",
        defaults={
            "libelle_long": "Candidatus Phytoplasma palmae (jaunissement mortel du palmier)",
        },
    )


def reverse_add_organisme_nuisible(apps, schema_editor):
    organisme_nuisible_model = apps.get_model("sv", "OrganismeNuisible")
    organisme_nuisible_model.objects.filter(code_oepp="PHYPPA").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0085_lda22_is_active"),
    ]

    operations = [
        migrations.RunPython(add_organisme_nuisible, reverse_add_organisme_nuisible),
    ]
