# Generated by Django 5.1.7 on 2025-04-04 12:27

from django.db import migrations, models


def migrate_numero_europhyt(apps, schema_editor):
    evenement_model = apps.get_model("sv", "Evenement")
    fiche_detection_model = apps.get_model("sv", "FicheDetection")

    for evenement in evenement_model.objects.all():
        detection_with_europhyt = fiche_detection_model.objects.filter(
            evenement=evenement, numero_europhyt__gt=""
        ).first()

        if detection_with_europhyt:
            evenement.numero_europhyt = detection_with_europhyt.numero_europhyt
            evenement.save()


def reverse_migrate_numero_europhyt(apps, schema_editor):
    evenement_model = apps.get_model("sv", "Evenement")
    fiche_detection_model = apps.get_model("sv", "FicheDetection")
    for evenement in evenement_model.objects.exclude(numero_europhyt=""):
        first_detection = fiche_detection_model.objects.filter(evenement=evenement).first()
        if first_detection:
            first_detection.numero_europhyt = evenement.numero_europhyt
            first_detection.save()


def migrate_numero_rasff(apps, schema_editor):
    evenement_model = apps.get_model("sv", "Evenement")
    fiche_detection_model = apps.get_model("sv", "FicheDetection")

    for evenement in evenement_model.objects.all():
        detection_with_rasff = fiche_detection_model.objects.filter(evenement=evenement, numero_rasff__gt="").first()

        if detection_with_rasff:
            evenement.numero_rasff = detection_with_rasff.numero_rasff
            evenement.save()


def reverse_migrate_numero_rasff(apps, schema_editor):
    evenement_model = apps.get_model("sv", "Evenement")
    fiche_detection_model = apps.get_model("sv", "FicheDetection")
    for evenement in evenement_model.objects.exclude(numero_rasff=""):
        first_detection = fiche_detection_model.objects.filter(evenement=evenement).first()
        if first_detection:
            first_detection.numero_rasff = evenement.numero_rasff
            first_detection.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0085_lda22_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="numero_europhyt",
            field=models.CharField(blank=True, max_length=8, verbose_name="Numéro Europhyt"),
        ),
        migrations.AddField(
            model_name="evenement",
            name="numero_rasff",
            field=models.CharField(blank=True, max_length=9, verbose_name="Numéro RASFF"),
        ),
        migrations.RunPython(migrate_numero_europhyt, reverse_migrate_numero_europhyt),
        migrations.RunPython(migrate_numero_rasff, reverse_migrate_numero_rasff),
        migrations.RemoveField(
            model_name="fichedetection",
            name="numero_europhyt",
        ),
        migrations.RemoveField(
            model_name="fichedetection",
            name="numero_rasff",
        ),
    ]
