# Generated by Django 5.1.7 on 2025-04-08 09:27

from django.db import migrations, models


def migrate_numero_europhyt(apps, schema_editor):
    Evenement = apps.get_model("sv", "Evenement")
    for evenement in Evenement._base_manager.all():
        if detection_with_europhyt := evenement.detections.exclude(numero_europhyt="").first():
            evenement.numero_europhyt = detection_with_europhyt.numero_europhyt
            evenement.save()


def reverse_migrate_numero_europhyt(apps, schema_editor):
    Evenement = apps.get_model("sv", "Evenement")
    for evenement in Evenement._base_manager.exclude(numero_europhyt=""):
        if first_detection := evenement.detections.first():
            first_detection.numero_europhyt = evenement.numero_europhyt
            first_detection.save()


def migrate_numero_rasff(apps, schema_editor):
    Evenement = apps.get_model("sv", "Evenement")
    for evenement in Evenement._base_manager.all():
        if detection_with_rasff := evenement.detections.exclude(numero_rasff="").first():
            evenement.numero_rasff = detection_with_rasff.numero_rasff
            evenement.save()


def reverse_migrate_numero_rasff(apps, schema_editor):
    Evenement = apps.get_model("sv", "Evenement")
    for evenement in Evenement._base_manager.exclude(numero_rasff=""):
        if first_detection := evenement.detections.first():
            first_detection.numero_rasff = evenement.numero_rasff
            first_detection.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0086_add_on_candidatus_phytoplasma_palmea"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="numero_europhyt",
            field=models.CharField(blank=True, max_length=8, verbose_name="Numéro Europhyt"),
        ),
        migrations.AddField(
            model_name="evenement",
            name="numero_rasff",
            field=models.CharField(blank=True, max_length=9, verbose_name="Numéro RASFF"),
        ),
        migrations.RunPython(migrate_numero_europhyt, reverse_migrate_numero_europhyt),
        migrations.RunPython(migrate_numero_rasff, reverse_migrate_numero_rasff),
        migrations.RemoveField(
            model_name="fichedetection",
            name="numero_europhyt",
        ),
        migrations.RemoveField(
            model_name="fichedetection",
            name="numero_rasff",
        ),
    ]
