# Generated by Django 5.1.8 on 2025-04-11 09:31

from django.db import migrations


def add_on_xanthomonas(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.get_or_create(
        code_oepp="XXXXXX",
        libelle_court="Xanthomonas axonopodis pv. spondiae",
        defaults={
            "libelle_long": "Xanthomonas axonopodis pv. spondiae",
        },
    )


def reverse_add_on_xanthomonas(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.filter(code_oepp="XXXXXX", libelle_court="Xanthomonas axonopodis pv. spondiae").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0087_evenement_numero_europhyt_evenement_numero_rasff"),
    ]

    operations = [
        migrations.RunPython(add_on_xanthomonas, reverse_add_on_xanthomonas),
    ]
