# Generated by Django 5.1.8 on 2025-04-17 15:51

from django.db import migrations


organismes_nuisibles = [
    {
        "code_oepp": "MELASP",
        "libelle_court": "Melanaspis sp.",
        "libelle_long": "Melanaspis sp.",
    },
    {
        "code_oepp": "CHRYCO",
        "libelle_court": "Melanaspis corticosa",
        "libelle_long": "Melanaspis corticosa",
    },
    {
        "code_oepp": "MEGEPU",
        "libelle_court": "Megastes pusialis",
        "libelle_long": "Megastes pusialis",
    },
    {
        "code_oepp": "ZTMV00",
        "libelle_court": "ZTMV",
        "libelle_long": "Potyvirus pepotigris (Zucchini tigre mosaic virus)",
    },
    {
        "code_oepp": "SAISHE",
        "libelle_court": "Saissetia coffeae",
        "libelle_long": "Saissetia coffeae (cochenille brune du caféier)",
    },
]


def add_organismes_nuisibles(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    for organisme in organismes_nuisibles:
        OrganismeNuisible.objects.get_or_create(
            code_oepp=organisme["code_oepp"],
            defaults={
                "libelle_court": organisme["libelle_court"],
                "libelle_long": organisme["libelle_long"],
            },
        )


def reverse_add_organismes_nuisibles(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    for organisme in organismes_nuisibles:
        OrganismeNuisible.objects.filter(code_oepp=organisme["code_oepp"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0088_add_on_xanthomonas"),
    ]

    operations = [
        migrations.RunPython(add_organismes_nuisibles, reverse_add_organismes_nuisibles),
    ]
