# Generated by Django 5.1.8 on 2025-04-22 08:31

from django.db import migrations


def update_code_oepp_xantso(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.filter(libelle_court="Xanthomonas axonopodis pv. spondiae").update(
        code_oepp="XANTSO",
    )


def reverse_code_oepp_xantso(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.filter(code_oepp="XANTSO").update(
        code_oepp="XXXXXX",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0089_add_organismes_nuisibles"),
    ]

    operations = [
        migrations.RunPython(update_code_oepp_xantso, reverse_code_oepp_xantso),
    ]
