# Generated by Django 5.1.8 on 2025-04-18 13:43

from django.db import migrations
from django.db.models import Q, Exists, OuterRef

from core.constants import REGION_STRUCTURE_MAPPING


def update_createur_import_historique(apps, schema_editor):
    Evenement = apps.get_model("sv", "Evenement")
    Lieu = apps.get_model("sv", "Lieu")
    Structure = apps.get_model("core", "Structure")

    # événements de l'import de historique dont le createur est MUS
    # ayant au moins un lieu avec département (donc avec région)
    condition_historique = Q(numero_annee__lt=2025) | Q(numero_annee=2025, numero_evenement__lte=11)
    condition_mus = Q(createur__niveau2="MUS")
    lieux_avec_dept = Lieu.objects.filter(fiche_detection__evenement=OuterRef("pk"), departement__isnull=False)
    evenements_with_region = Evenement.objects.filter(condition_historique, condition_mus, Exists(lieux_avec_dept))

    for evenement in evenements_with_region:
        first_lieu_with_dept = Lieu.objects.filter(
            fiche_detection__evenement=evenement, departement__isnull=False
        ).first()
        if first_lieu_with_dept and (
            structure_name := REGION_STRUCTURE_MAPPING.get(first_lieu_with_dept.departement.region.nom)
        ):
            try:
                structure = Structure.objects.get(niveau2=structure_name)
                evenement.createur = structure
                evenement.save()
            except Structure.DoesNotExist:
                pass


def reverse_update_createur(apps, schema_editor):
    Evenement = apps.get_model("sv", "Evenement")
    Structure = apps.get_model("core", "Structure")
    try:
        mus_structure = Structure.objects.get(niveau2="MUS")
        condition_historique = Q(numero_annee__lt=2025) | Q(numero_annee=2025, numero_evenement__lte=11)
        condition_non_mus = ~Q(createur__niveau2="MUS")
        evenements_modifies = Evenement.objects.filter(condition_historique, condition_non_mus)
        for evenement in evenements_modifies:
            evenement.createur = mus_structure
            evenement.save()
    except Structure.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0089_add_organismes_nuisibles"),
    ]

    operations = [
        migrations.RunPython(update_createur_import_historique, reverse_update_createur),
    ]
