# Generated by Django 5.1.8 on 2025-04-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0090_update_code_oepp_xantso"),
    ]

    operations = [
        migrations.AddField(
            model_name="prelevement",
            name="date_rapport_analyse",
            field=models.DateField(blank=True, null=True, verbose_name="Date rapport d'analyse"),
        ),
    ]
