# Generated by Django 5.1.8 on 2025-05-02 12:29

from django.db import migrations


def add_on_hercae(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.get_or_create(
        code_oepp="HERCAE",
        defaults={
            "libelle_court": "Hercinothrips aethiopiae",
            "libelle_long": "Hercinothrips aethiopiae",
        },
    )


def reverse_add_on_hercae(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.filter(code_oepp="HERCAE").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0092_evenement_date_derniere_mise_a_jour"),
    ]

    operations = [
        migrations.RunPython(add_on_hercae, reverse_add_on_hercae),
    ]
