# Generated by Django 5.1.8 on 2025-05-06 09:28

from django.db import migrations
import django_countries.fields


def convert_country_names_to_codes(apps, schema_editor):
    Lieu = apps.get_model("sv", "Lieu")

    country_mapping = {
        "france": "FR",
    }

    unknown_countries = set()
    lieux_with_pays_etablissement = (
        Lieu.objects.exclude(pays_etablissement="").values_list("pays_etablissement", flat=True).distinct()
    )
    for lieu_pays in lieux_with_pays_etablissement:
        if lieu_pays.lower() not in country_mapping:
            unknown_countries.add(lieu_pays)
    if unknown_countries:
        raise Exception(f"Unknown country names: {', '.join(unknown_countries)}")

    for country_name, iso_code in country_mapping.items():
        Lieu.objects.filter(pays_etablissement__iexact=country_name).update(pays_etablissement=iso_code)


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0093_add_on_hercae"),
    ]

    operations = [
        migrations.RunPython(convert_country_names_to_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="lieu",
            name="pays_etablissement",
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name="Pays établissement"),
        ),
    ]
