# Generated by Django 5.1.8 on 2025-05-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0094_alter_lieu_pays_etablissement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prelevement",
            name="resultat",
            field=models.CharField(
                choices=[
                    ("detecte", "Détecté"),
                    ("non_detecte", "Non détecté"),
                    ("non_conclusif", "Non conclusif"),
                    ("en_attente", "En attente"),
                ],
                max_length=50,
                verbose_name="Résultat",
            ),
        ),
    ]
