# Generated by Django 5.1.8 on 2025-05-06 19:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0095_alter_prelevement_resultat"),
    ]

    operations = [
        migrations.AddField(
            model_name="lieu",
            name="code_insee_etablissement",
            field=models.CharField(
                blank=True,
                max_length=5,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_code_insee",
                        message="Le code INSEE doit contenir exactement 5 chiffres",
                        regex="^[0-9]{5}$",
                    )
                ],
                verbose_name="Code INSEE de la commune",
            ),
        ),
        migrations.AddField(
            model_name="lieu",
            name="commune_etablissement",
            field=models.CharField(blank=True, max_length=100, verbose_name="Commune"),
        ),
        migrations.AddField(
            model_name="lieu",
            name="departement_etablissement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departement_etablissement",
                to="sv.departement",
                verbose_name="Département",
            ),
        ),
    ]
