# Generated by Django 5.1.8 on 2025-05-20 19:09

from django.db import migrations


def add_on_contmu(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.get_or_create(
        code_oepp="CONTMU", libelle_court="Contarinia maculipennis", libelle_long="Contarinia maculipennis"
    )


def reverse_add_on_contmu(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    organisme = OrganismeNuisible.objects.get(code_oepp="CONTMU")
    organisme.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0096_lieu_code_insee_etablissement_and_more"),
    ]

    operations = [
        migrations.RunPython(add_on_contmu, reverse_add_on_contmu),
    ]
