# Generated by Django 5.1.8 on 2025-05-21 16:52

from django.db import migrations


def add_on_crtzbr(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.get_or_create(
        code_oepp="CRTZBR", libelle_court="Ceratothripoides brunneus", libelle_long="Ceratothripoides brunneus"
    )


def reverse_add_on_crtzbr(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    organisme = OrganismeNuisible.objects.get(code_oepp="CRTZBR")
    organisme.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0097_add_on_contmu"),
    ]

    operations = [
        migrations.RunPython(add_on_crtzbr, reverse_add_on_crtzbr),
    ]
