# Generated by Django 5.1.8 on 2025-05-22 09:58

from django.db import migrations, transaction


def add_existing_contacts_to_allowed_structures(apps, schema_editor):
    Evenement = apps.get_model("sv", "Evenement")
    Group = apps.get_model("auth", "Group")

    referent_national_group = Group.objects.get(name="referent_national")

    for evenement in Evenement._base_manager.exclude(etat="brouillon"):
        contacts_structures = [
            contact.structure for contact in evenement.contacts.all().exclude(structure__isnull=True)
        ]
        contacts_agents_structures = [
            contact_agent.agent.structure
            for contact_agent in evenement.contacts.all()
            .exclude(agent__isnull=True)
            .exclude(agent__user__groups=referent_national_group)
        ]
        all_structures = set(contacts_structures + contacts_agents_structures)

        with transaction.atomic():
            if not evenement.visibilite == "nationale":
                evenement.allowed_structures.add(*all_structures)
            if evenement.visibilite == "locale":
                evenement.visibilite = "limitee"
                evenement.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0098_add_on_crtzbr"),
    ]

    operations = [
        migrations.RunPython(add_existing_contacts_to_allowed_structures, migrations.RunPython.noop),
    ]
