# Generated by Django 5.2.2 on 2025-06-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_alter_document_document_type"),
        ("sv", "0100_update_createur_import_historique"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable(
                    name="departement",
                    table="core_departement",
                ),
                migrations.AlterModelTable(
                    name="region",
                    table="core_region",
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="departement",
                    name="region",
                ),
                migrations.AlterField(
                    model_name="lieu",
                    name="departement",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.PROTECT,
                        to="core.departement",
                        verbose_name="Département",
                    ),
                ),
                migrations.AlterField(
                    model_name="lieu",
                    name="departement_etablissement",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.PROTECT,
                        related_name="departement_etablissement",
                        to="core.departement",
                        verbose_name="Département",
                    ),
                ),
                migrations.DeleteModel(
                    name="Region",
                ),
                migrations.DeleteModel(
                    name="Departement",
                ),
            ],
        ),
    ]
