# Generated by Django 5.2.2 on 2025-06-19 08:23

from django.db import migrations

organismes_nuisibles = [
    {
        "code_oepp": "THRIHA",
        "libelle_court": "Thrips hawaiiensis",
        "libelle_long": "Thrips hawaiiensis",
    },
    {
        "code_oepp": "EMPOBI",
        "libelle_court": "Amrasca biguttula",
        "libelle_long": "Amrasca biguttula",
    },
    {
        "code_oepp": "SPFMV0",
        "libelle_court": "Sweet Potato Feathery Mottle Virus (Potyvirus batataplumei)",
        "libelle_long": "Potyvirus batataplumei",
    },
    {
        "code_oepp": "CYMMV0",
        "libelle_court": "Cymbidium mosaic virus (Potexvirus cymbidii)",
        "libelle_long": "Potexvirus cymbidii",
    },
    {
        "code_oepp": "TAKAJA",
        "libelle_court": "Takahashia japonica",
        "libelle_long": "Takahashia japonica",
    },
]


def add_organismes_nuisibles(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    for organisme in organismes_nuisibles:
        OrganismeNuisible.objects.get_or_create(
            code_oepp=organisme["code_oepp"],
            defaults={
                "libelle_court": organisme["libelle_court"],
                "libelle_long": organisme["libelle_long"],
            },
        )


def reverse_add_organismes_nuisibles(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    for organisme in organismes_nuisibles:
        OrganismeNuisible.objects.filter(code_oepp=organisme["code_oepp"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0101_move_departement_and_region_to_core"),
    ]

    operations = [
        migrations.RunPython(add_organismes_nuisibles, reverse_add_organismes_nuisibles),
    ]
