# Generated by Django 5.2.4 on 2025-08-27 08:27

from django.db import migrations

organismes_nuisibles = [
    {
        "code_oepp": "BCTRCO",
        "libelle_court": "Bactrocera correcta",
        "libelle_long": "Bactrocera correcta",
    },
    {
        "code_oepp": "COCOCR",
        "libelle_court": "Coccotrypes cardamomi",
        "libelle_long": "Coccotrypes cardamomi",
    },
]


def add_organismes_nuisibles(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    for organisme in organismes_nuisibles:
        OrganismeNuisible.objects.get_or_create(
            code_oepp=organisme["code_oepp"],
            defaults={
                "libelle_court": organisme["libelle_court"],
                "libelle_long": organisme["libelle_long"],
            },
        )


def reverse_add_organismes_nuisibles(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    for organisme in organismes_nuisibles:
        OrganismeNuisible.objects.filter(code_oepp=organisme["code_oepp"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0103_add_new_organismes_nuisibles"),
    ]

    operations = [
        migrations.RunPython(add_organismes_nuisibles, reverse_add_organismes_nuisibles),
    ]
