# Generated by Django 5.2.6 on 2025-09-09 07:45

from django.db import migrations


def add_organismes_nuisibles(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.get_or_create(
        code_oepp="EIDPJA", libelle_court="Eidophelus jalappae", libelle_long="Eidophelus jalappae"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0104_auto_20250827_1027"),
    ]

    operations = [
        migrations.RunPython(add_organismes_nuisibles, reverse_code=migrations.RunPython.noop),
    ]
