# Generated by Django 5.2.6 on 2025-09-15 08:16

from django.db import migrations


def add_new_status(apps, schema_editor):
    StatutReglementaire = apps.get_model("sv", "StatutReglementaire")
    StatutReglementaire.objects.get_or_create(code="END", libelle="en cours de détermination")
    StatutReglementaire.objects.get_or_create(code="NR", libelle="non réglementé")


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0105_auto_20250909_0945"),
    ]

    operations = [
        migrations.RunPython(add_new_status, migrations.RunPython.noop),
    ]
