# Generated by Django 5.2.7 on 2025-10-10 09:18

from django.db import migrations


def add_organismes_nuisibles(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.get_or_create(
        code_oepp="BBWV20",
        libelle_long="Broad bean wilt virus 2 (Fabavirus betaviciae)",
        libelle_court="Broad bean wilt virus 2",
    )

    OrganismeNuisible.objects.get_or_create(
        code_oepp="DACUFR",
        libelle_long="Dacus frontalis",
        libelle_court="Dacus frontalis",
    )


def reverse_add_organismes_nuisibles(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.filter(code_oepp="BBWV20").delete()
    OrganismeNuisible.objects.filter(code_oepp="DACUFR").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0106_auto_20250915_1016"),
    ]

    operations = [
        migrations.RunPython(add_organismes_nuisibles, reverse_add_organismes_nuisibles),
    ]
