# Generated by Django 5.2.7 on 2025-11-06 14:25

from django.db import migrations


def add_organismes_nuisibles(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.get_or_create(
        code_oepp="PHLBLI",
        libelle_long="Phloeotribus liminaris",
        libelle_court="Phloeotribus liminaris",
    )


def reverse_add_organismes_nuisibles(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.filter(code_oepp="PHLBLI").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0107_auto_20251010_1118"),
    ]

    operations = [
        migrations.RunPython(add_organismes_nuisibles, reverse_add_organismes_nuisibles),
    ]
