# Generated by Django 5.2.8 on 2025-12-15 08:37

from django.db import migrations


def add_on(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.get_or_create(
        code_oepp="CLCUGV",
        libelle_court="Begomovirus gossypigeziraense",
        defaults={
            "libelle_long": "Cotton leaf curl Gezira virus",
        },
    )


def reverse_add_on(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.filter(code_oepp="CLCUGV", libelle_court="Begomovirus gossypigeziraense").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0109_alter_lieu_code_insee"),
    ]

    operations = [
        migrations.RunPython(add_on, reverse_add_on),
    ]
