# Generated by Django 5.2.8 on 2026-01-08 12:16

from django.db import migrations


def add_on(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.get_or_create(
        code_oepp="XYLBVA",
        libelle_court="Euwallacea validus",
        defaults={
            "libelle_long": "Euwallacea validus",
        },
    )


def reverse_add_on(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.filter(code_oepp="XYLBVA", libelle_court="Euwallacea validus").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0110_auto_20251215_0937"),
    ]

    operations = [
        migrations.RunPython(add_on, reverse_add_on),
    ]
