# Generated by Django 5.2.8 on 2026-01-14 13:35

from django.db import migrations


def add_on(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.get_or_create(
        code_oepp="AGRBVA",
        libelle_court="Agrobacterium vaccinii",
        defaults={
            "libelle_long": "Agrobacterium vaccinii",
        },
    )


def reverse_add_on(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.filter(code_oepp="AGRBVA", libelle_court="Agrobacterium vaccinii").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0111_auto_20260108_1316"),
    ]

    operations = [
        migrations.RunPython(add_on, reverse_add_on),
    ]
