# Generated by Django 5.2.11 on 2026-03-03 14:50

from django.db import migrations


def add_organisme_nuisible(apps, schema_editor):
    organisme_nuisible_model = apps.get_model("sv", "OrganismeNuisible")
    organisme_nuisible_model.objects.get_or_create(
        code_oepp="MELAPA",
        libelle_court="Acutaspis paulista",
        defaults={
            "libelle_long": "Acutaspis paulista",
        },
    )


def reverse_add_organisme_nuisible(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.filter(code_oepp="MELAPA").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0112_auto_20260114_1435"),
    ]

    operations = [
        migrations.RunPython(add_organisme_nuisible, reverse_add_organisme_nuisible),
    ]
