# Generated by Django 5.2.10 on 2026-02-23 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_commune"),
        ("sv", "0112_auto_20260114_1435"),
    ]

    operations = [
        migrations.AddField(
            model_name="lieu",
            name="new_commune",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.commune",
                verbose_name="Commune",
            ),
        ),
    ]
