# Generated by Django 5.2.11 on 2026-03-09 10:14

from django.db import migrations


def add_organisme_nuisible(apps, schema_editor):
    organisme_nuisible_model = apps.get_model("sv", "OrganismeNuisible")
    organisme_nuisible_model.objects.get_or_create(
        code_oepp="ERWIZE",
        libelle_court="Dickeya zeae",
        defaults={
            "libelle_long": "Dickeya zeae",
        },
    )


def reverse_add_organisme_nuisible(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.filter(code_oepp="ERWIZE").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0113_auto_20260303_1550"),
    ]

    operations = [
        migrations.RunPython(add_organisme_nuisible, reverse_add_organisme_nuisible),
    ]
