# Generated by Django 5.2.11 on 2026-03-23 08:21

from django.db import migrations


def change_structure_preleveuse(apps, schema_editor):
    StructurePreleveuse = apps.get_model("sv", "StructurePreleveuse")
    StructurePreleveuse.objects.filter(nom="SEMAE").update(nom="SocFrance")


def revert_change_structure_preleveuse(apps, schema_editor):
    StructurePreleveuse = apps.get_model("sv", "StructurePreleveuse")
    StructurePreleveuse.objects.filter(nom="SocFrance").update(nom="SEMAE")


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0115_lieu_code_postal"),
    ]

    operations = [
        migrations.RunPython(change_structure_preleveuse, revert_change_structure_preleveuse),
    ]
