# Generated by Django 5.2.11 on 2026-03-27 09:45

from django.db import migrations, models

from core.mixins import WithEtatMixin


def copy_date_creation_to_date_publication(apps, schema_editor):
    Evenement = apps.get_model("sv", "Evenement")
    Evenement.objects.exclude(etat=WithEtatMixin.Etat.BROUILLON).update(date_publication=models.F("date_creation"))


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0117_auto_20260311_1603"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="date_publication",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de publication"),
        ),
        migrations.RunPython(copy_date_creation_to_date_publication, migrations.RunPython.noop),
    ]
