# Generated by Django 6.0.3 on 2026-04-10 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0118_evenement_date_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zoneinfestee",
            name="fiche_zone_delimitee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zones_infestees",
                to="sv.fichezonedelimitee",
                verbose_name="Fiche zone",
            ),
        ),
    ]
