# Generated by Django 6.0.3 on 2026-04-24 08:58

from django.db import migrations


def add_organisme_nuisible(apps, schema_editor):
    organisme_nuisible_model = apps.get_model("sv", "OrganismeNuisible")
    organisme_nuisible_model.objects.get_or_create(
        code_oepp="AGRBRU",
        libelle_court="Rhizobium rubi",
        defaults={
            "libelle_long": "Agrobacterium rubi",
        },
    )


def reverse_add_organisme_nuisible(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.filter(code_oepp="AGRBRU").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0119_alter_zoneinfestee_fiche_zone_delimitee"),
    ]

    operations = [
        migrations.RunPython(add_organisme_nuisible, reverse_add_organisme_nuisible),
    ]
