# Generated by Django 6.0.3 on 2026-05-04 12:24


from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models
from django.db.models import CharField, Max, OuterRef, Subquery
from django.db.models.functions import Cast
from reversion.models import Version


def update_last_updated(apps, schema_editor):
    Evenement = apps.get_model("sv", "Evenement")

    content_type = ContentType.objects.get_for_model(Evenement)

    latest = (
        Version.objects.filter(content_type=content_type, db="default")
        .values("object_id")
        .annotate(last_date=Max("revision__date_created"))
        .filter(object_id=Cast(OuterRef("pk"), CharField()))
        .values("last_date")[:1]
    )

    Evenement.objects.update(last_updated=Subquery(latest))


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0124_auto_20260504_1643"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evenement",
            old_name="date_derniere_mise_a_jour",
            new_name="last_updated",
        ),
        migrations.RemoveField(
            model_name="fichedetection",
            name="date_derniere_mise_a_jour",
        ),
        migrations.RemoveField(
            model_name="fichezonedelimitee",
            name="date_derniere_mise_a_jour",
        ),
        migrations.AlterField(
            model_name="evenement",
            name="last_updated",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Date de dernière mise à jour",
            ),
        ),
        migrations.RunPython(update_last_updated, migrations.RunPython.noop),
    ]
