# Generated by Django 6.0.5 on 2026-05-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0126_elementinfeste"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenement",
            name="numero_rasff",
            field=models.CharField(blank=True, max_length=255, verbose_name="Numéro RASFF"),
        ),
    ]
