# Generated by Django 6.0.5 on 2026-06-10 08:36

from django.db import migrations


def add_organisme_nuisible(apps, schema_editor):
    organisme_nuisible_model = apps.get_model("sv", "OrganismeNuisible")
    organisme_nuisible_model.objects.get_or_create(
        code_oepp="ACIZSP",
        libelle_court="Acizzia sp.",
        defaults={
            "libelle_long": "Acizzia sp.",
        },
    )


def reverse_add_organisme_nuisible(apps, schema_editor):
    organisme_nuisible_model = apps.get_model("sv", "OrganismeNuisible")
    organisme_nuisible_model.objects.filter(code_oepp="ACIZSP").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0127_alter_evenement_numero_rasff"),
    ]

    operations = [
        migrations.RunPython(add_organisme_nuisible, reverse_add_organisme_nuisible),
    ]
