# Generated by Django 6.0.6 on 2026-06-19 13:21

from django.db import migrations


def add_organisme_nuisible(apps, schema_editor):
    organisme_nuisible_model = apps.get_model("sv", "OrganismeNuisible")
    organisme_nuisible_model.objects.get_or_create(
        code_oepp="CSYV00",
        libelle_court="Potexvirus citriflavivenae",
        defaults={
            "libelle_long": "Citrus yellow vein clearing virus",
        },
    )


def reverse_add_organisme_nuisible(apps, schema_editor):
    organisme_nuisible_model = apps.get_model("sv", "OrganismeNuisible")
    organisme_nuisible_model.objects.filter(code_oepp="CSYV00").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0128_auto_20260610_1036"),
    ]

    operations = [
        migrations.RunPython(add_organisme_nuisible, reverse_add_organisme_nuisible),
    ]
