# Generated by Django 6.0.7 on 2026-09-11 12:32

from django.db import migrations


def add_on(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.get_or_create(
        code_oepp="EARIRO",
        libelle_court="Earias roseifera",
        defaults={
            "libelle_long": "Earias roseifera",
        },
    )


def reverse_add_on(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.filter(code_oepp="EARIRO", libelle_court="Earias roseifera").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0130_on_puccinia_kuehnii"),
    ]

    operations = [
        migrations.RunPython(add_on, reverse_add_on),
    ]
