# Generated by Django 6.0.7 on 2026-07-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0130_on_puccinia_kuehnii"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="need_notification_contact_added",
            field=models.BooleanField(default=True),
        ),
    ]
