# Generated by Django 6.0.7 on 2026-09-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0132_on_xylotrechus_rufilius"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenement",
            name="numero_europhyt",
            field=models.CharField(blank=True, max_length=50, verbose_name="Numéro Europhyt"),
        ),
    ]
