# Generated by Django 6.0.7 on 2026-09-28 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0133_alter_evenement_numero_europhyt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lieu",
            name="code_insee_etablissement",
            field=models.CharField(
                blank=True,
                max_length=5,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_code_insee",
                        message="Le code INSEE doit contenir exactement 5 chiffres",
                        regex="^(?:\\d{5}|2A\\d{3}|2B\\d{3})$",
                    )
                ],
                verbose_name="Code INSEE de la commune",
            ),
        ),
    ]
