# Generated by Django 6.0.7 on 2026-10-09 06:43

from django.db import migrations


def add_on(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.get_or_create(
        code_oepp="AGRLBL",
        libelle_court="Agrilus bilineatus",
        defaults={
            "libelle_long": "Agrilus bilineatus",
        },
    )
    OrganismeNuisible.objects.get_or_create(
        code_oepp="ECDYAU",
        libelle_court="Gymnandrosoma aurantianum",
        defaults={
            "libelle_long": "Gymnandrosoma aurantianum",
        },
    )
    OrganismeNuisible.objects.get_or_create(
        code_oepp="NAUPXA",
        libelle_court="Naupactus xanthographus",
        defaults={
            "libelle_long": "Naupactus xanthographus",
        },
    )


def reverse_add_on(apps, schema_editor):
    OrganismeNuisible = apps.get_model("sv", "OrganismeNuisible")
    OrganismeNuisible.objects.filter(code_oepp="AGRLBL", libelle_court="Agrilus bilineatus").delete()
    OrganismeNuisible.objects.filter(code_oepp="ECDYAU", libelle_court="Gymnandrosoma aurantianum").delete()
    OrganismeNuisible.objects.filter(code_oepp="NAUPXA", libelle_court="Naupactus xanthographus").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sv", "0135_on_papilio_demodocus"),
    ]

    operations = [
        migrations.RunPython(add_on, reverse_add_on),
    ]
