# Generated by Django 5.1.8 on 2025-04-07 08:23

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementproduit",
            name="numeros_rappel_conso",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=12,
                    validators=[
                        django.core.validators.RegexValidator(
                            message="Le format doit être AAAA-XX-YYYY",
                            regex="^\\d{4}-\\d{2}-\\d{4}$",
                        )
                    ],
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
