# Generated by Django 5.1.7 on 2025-04-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_auto_20250327_1433"),
        ("ssa", "0002_evenementproduit_numeros_rappel_conso"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="evenementproduit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source", "autre"),
                    models.Q(
                        ("type_evenement", "investigation_cas_humain"),
                        ("source__in", ["do_listeriose", "cas_groupes", "tiacs"]),
                    ),
                    models.Q(
                        models.Q(
                            ("type_evenement", "investigation_cas_humain"),
                            _negated=True,
                        ),
                        models.Q(
                            ("source__in", ["do_listeriose", "cas_groupes", "tiacs"]),
                            _negated=True,
                        ),
                    ),
                    _connector="OR",
                ),
                name="type_evenement_source_constraint",
            ),
        ),
    ]
