# Generated by Django 5.1.8 on 2025-04-10 05:52

import ssa.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0004_etablissement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenementproduit",
            name="numero_rasff",
            field=models.CharField(
                blank=True,
                max_length=9,
                validators=[ssa.models.validators.validate_numero_rasff],
                verbose_name="N° RASFF/AAC",
            ),
        ),
        migrations.AlterField(
            model_name="evenementproduit",
            name="type_evenement",
            field=models.CharField(
                choices=[
                    ("alerte_produit_nationale", "Alerte produit nationale"),
                    ("alerte_produit_locale", "Alerte produit locale"),
                    ("non_alerte", "Non alerte"),
                    ("alerte_produit_ue", "Alerte produit UE/INT (RASFF)"),
                    ("non_alerte_ue", "Non alerte UE/INT (AAC)"),
                    ("investigation_cas_humain", "Investigation cas humains"),
                ],
                max_length=100,
                verbose_name="Type d'événement",
            ),
        ),
    ]
