# Generated by Django 5.1.8 on 2025-04-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_alter_document_file"),
        ("ssa", "0005_alter_evenementproduit_numero_rasff_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="evenementproduit",
            name="type_evenement_source_constraint",
        ),
        migrations.AddConstraint(
            model_name="evenementproduit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source", "autre"),
                    ("source", ""),
                    models.Q(
                        ("type_evenement", "investigation_cas_humain"),
                        ("source__in", ["do_listeriose", "cas_groupes", "tiacs"]),
                    ),
                    models.Q(
                        models.Q(
                            ("type_evenement", "investigation_cas_humain"),
                            _negated=True,
                        ),
                        models.Q(
                            ("source__in", ["do_listeriose", "cas_groupes", "tiacs"]),
                            _negated=True,
                        ),
                    ),
                    _connector="OR",
                ),
                name="type_evenement_source_constraint",
            ),
        ),
    ]
