# Generated by Django 5.1.8 on 2025-04-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0008_alter_evenementproduit_quantification_unite"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementproduit",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
