# Generated by Django 5.1.8 on 2025-04-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_alter_document_file"),
        ("ssa", "0008_alter_evenementproduit_quantification_unite"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="evenementproduit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("quantification__isnull", True), ("quantification_unite", "")),
                    models.Q(
                        ("quantification__isnull", False),
                        models.Q(("quantification_unite", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="quantification_must_have_unit",
                violation_error_message="Quantification et unité de quantification doivent être tous les deux renseignés ou tous les deux vides.",
            ),
        ),
    ]
