# Generated by Django 5.1.8 on 2025-04-29 08:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0009_evenementproduit_quantification_must_have_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="etablissement",
            name="quantite_en_stock",
        ),
    ]
