# Generated by Django 5.1.8 on 2025-05-02 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "00011_evenementproduit_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evenementproduit",
            name="cerfa_recu",
        ),
    ]
