# Generated by Django 5.1.8 on 2025-05-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_create_referent_national_group"),
        ("ssa", "0012_remove_evenementproduit_cerfa_recu"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementproduit",
            name="contacts",
            field=models.ManyToManyField(blank=True, to="core.contact", verbose_name="Contacts"),
        ),
    ]
