# Generated by Django 5.2.1 on 2025-05-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0016_alter_evenementproduit_quantification_unite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementproduit",
            name="categorie_produit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Produit carné de boucherie", "Produit carné > De boucherie"),
                    (
                        "Viande, os et abat rouge de boucherie",
                        "Produit carné > De boucherie > Viande, os et abat rouge de boucherie",
                    ),
                    (
                        "Viande hachée de boucherie",
                        "Produit carné > De boucherie > Viande hachée de boucherie",
                    ),
                    (
                        "VSM de boucherie",
                        "Produit carné > De boucherie > VSM de boucherie",
                    ),
                    (
                        "Abat blanc de boucherie",
                        "Produit carné > De boucherie > Abat blanc de boucherie",
                    ),
                    (
                        "PV de boucherie",
                        "Produit carné > De boucherie > PV de boucherie",
                    ),
                    (
                        "PABV de boucherie cru",
                        "Produit carné > De boucherie > PABV de boucherie cru",
                    ),
                    (
                        "PABV de boucherie cuit",
                        "Produit carné > De boucherie > PABV de boucherie cuit",
                    ),
                    (
                        "Produit carné de volaille/lagomorphe",
                        "Produit carné > De volaille/lagomorphe",
                    ),
                    (
                        "Viande, os et abat de volaille/lagomorphe",
                        "Produit carné > De volaille/lagomorphe > Viande, os et abat de volaille/lagomorphe",
                    ),
                    (
                        "Viande hachée de volaille/lagomorphe",
                        "Produit carné > De volaille/lagomorphe > Viande hachée de volaille/lagomorphe",
                    ),
                    (
                        "VSM de volaille/lagomorphe",
                        "Produit carné > De volaille/lagomorphe > VSM de volaille/lagomorphe",
                    ),
                    (
                        "PV de volaille/lagomorphe",
                        "Produit carné > De volaille/lagomorphe > PV de volaille/lagomorphe",
                    ),
                    (
                        "PABV de volaille/lagomorphe",
                        "Produit carné > De volaille/lagomorphe > PABV de volaille/lagomorphe",
                    ),
                    ("Produit carné de gibier", "Produit carné > De gibier"),
                    (
                        "Viande et produits de grand gibier",
                        "Produit carné > De gibier > Viande et produits de grand gibier",
                    ),
                    (
                        "Viande et produits de petit gibier (mammifères)",
                        "Produit carné > De gibier > Viande et produits de petit gibier (mammifères)",
                    ),
                    (
                        "Viande et produits de petit gibier (oiseaux)",
                        "Produit carné > De gibier > Viande et produits de petit gibier (oiseaux)",
                    ),
                    (
                        "Produit de la pêche de poisson",
                        "Produit de la pêche > de poisson",
                    ),
                    (
                        "Poisson cru entier ou fileté",
                        "Produit de la pêche > de poisson > Poisson cru entier ou fileté",
                    ),
                    (
                        "Poisson fumé salé ou mariné",
                        "Produit de la pêche > de poisson > Poisson fumé salé ou mariné",
                    ),
                    (
                        "Conserves de poisson",
                        "Produit de la pêche > de poisson > Conserves de poisson",
                    ),
                    (
                        "Produit de la pêche de céphalopode",
                        "Produit de la pêche > de céphalopode",
                    ),
                    (
                        "Céphalopode cru entier ou coupé",
                        "Produit de la pêche > de céphalopode > Céphalopode cru entier ou coupé",
                    ),
                    (
                        "Produit de céphalopode",
                        "Produit de la pêche > de céphalopode > Produit de céphalopode",
                    ),
                    (
                        "Produit de la pêche de coquillage",
                        "Produit de la pêche > de coquillage",
                    ),
                    (
                        "Coquillage vivant",
                        "Produit de la pêche > de coquillage > Coquillage vivant",
                    ),
                    (
                        "Produit de coquillage",
                        "Produit de la pêche > de coquillage > Produit de coquillage",
                    ),
                    (
                        "Produit de la pêche de crustacé",
                        "Produit de la pêche > de crustacé",
                    ),
                    (
                        "Crustacé vivant ou cru",
                        "Produit de la pêche > de crustacé > Crustacé vivant ou cru",
                    ),
                    (
                        "Produit de crustacé",
                        "Produit de la pêche > de crustacé > Produit de crustacé",
                    ),
                    (
                        "Produit de la pêche d'escargot",
                        "Produit de la pêche > d'escargot",
                    ),
                    ("Escargot cru", "Produit de la pêche > d'escargot > Escargot cru"),
                    (
                        "Produit d'escargot",
                        "Produit de la pêche > d'escargot > Produit d'escargot",
                    ),
                    (
                        "Produit de la pêche grenouille",
                        "Produit de la pêche > de grenouille",
                    ),
                    ("Grenouille", "Produit de la pêche > de grenouille > Grenouille"),
                    (
                        "Produit de grenouille",
                        "Produit de la pêche > de grenouille > Produit de grenouille",
                    ),
                    ("Oeuf", "Produit d'oeuf > Oeuf"),
                    ("oeuf coquille", "Produit d'oeuf > Oeuf > Oeuf coquille"),
                    ("Ovoproduit", "Produit d'oeuf > Ovoproduit"),
                    (
                        "Coule fraiche d'oeuf",
                        "Produit d'oeuf > Ovoproduit > Coule fraiche d'oeuf",
                    ),
                    (
                        "oeuf liquide pasteurisé (jaune, blanc, entier)",
                        "Produit d'oeuf > Ovoproduit > Oeuf liquide pasteurisé (jaune, blanc, entier)",
                    ),
                    ("Poudre d'oeuf", "Produit d'oeuf > Ovoproduit > Poudre d'oeuf"),
                    (
                        "Oeufs durs (écalés ou non)",
                        "Produit d'oeuf > Ovoproduit > Oeufs durs (écalés ou non)",
                    ),
                    ("Autre", "Produit d'oeuf > Ovoproduit > Autre"),
                    ("Produit laitiier lait", "Produit laitier > Lait "),
                    (
                        "Lait cru (matière 1ère ou de consommation)",
                        "Produit laitier > Lait > Lait cru (matière 1ère ou de consommation)",
                    ),
                    (
                        "Lait traité (pasteurisé, microfilté, stérilisé), hors infantile",
                        "Produit laitier > Lait > Lait traité (pasteurisé, microfilté, stérilisé), hors infantile",
                    ),
                    ("Poudre de lait", "Produit laitier > Poudre de lait"),
                    (
                        "Poudre de lait et dérivés (poudre de sérum, caséïne, lactose, minéraux...), hors infantile",
                        "Produit laitier > Poudre de lait > Poudre de lait et dérivés (poudre de sérum, caséïne, lactose, minéraux...), hors infantile",
                    ),
                    (
                        "Produit laitier fermentes",
                        "Produit laitier > Produits laitiers fermentés",
                    ),
                    (
                        "Yaourt",
                        "Produit laitier > Produits laitiers fermentés > Yaourt",
                    ),
                    (
                        "Lait fermenté",
                        "Produit laitier > Produits laitiers fermentés > Lait fermenté",
                    ),
                    ("Produit laitier fromage", "Produit laitier > Fromage"),
                    (
                        "Fromage lait cru à pâtes fraiches",
                        "Produit laitier > Fromage > Fromage lait cru à pâtes fraiches",
                    ),
                    (
                        "Fromage lait cru à pâtes lactiques",
                        "Produit laitier > Fromage > Fromage lait cru à pâtes lactiques",
                    ),
                    (
                        "Fromage lait cru à pâtes molles",
                        "Produit laitier > Fromage > Fromage lait cru à pâtes molles",
                    ),
                    (
                        "Fromage lait cru à pâtes pressées non cuites",
                        "Produit laitier > Fromage > Fromage lait cru à pâtes pressées non cuites",
                    ),
                    (
                        "Fromage lait cru à pâtes pressées cuites",
                        "Produit laitier > Fromage > Fromage lait cru à pâtes pressées cuites",
                    ),
                    (
                        "Fromage lait traité",
                        "Produit laitier > Fromage > Fromage lait traité",
                    ),
                    (
                        "Fromage fondu et autre",
                        "Produit laitier > Fromage > Fromage fondu et autre",
                    ),
                    (
                        "Produit laitier creme beurre",
                        "Produit laitier > Créme et beurre",
                    ),
                    ("Crème crue", "Produit laitier > Créme et beurre > Crème crue"),
                    (
                        "Crème traitée",
                        "Produit laitier > Créme et beurre > Crème traitée",
                    ),
                    ("Beurre cru", "Produit laitier > Créme et beurre > Beurre cru"),
                    (
                        "Beurre traité",
                        "Produit laitier > Créme et beurre > Beurre traité",
                    ),
                    (
                        "Produit ruche",
                        "Produit de la ruche > Miel et produit de la ruche",
                    ),
                    (
                        "Miel",
                        "Produit de la ruche > Miel et produit de la ruche > Miel",
                    ),
                    (
                        "Produit de la ruche (sauf miel)",
                        "Produit de la ruche > Miel et produit de la ruche > Produit de la ruche (sauf miel)",
                    ),
                    ("Collagène", "Autres produits animaux > Collagène"),
                    ("Gélatine", "Autres produits animaux > Gélatine"),
                    (
                        "Graisse et fonte DOA (sauf beurre et crème)",
                        "Autres produits animaux > Graisse et fonte DOA (sauf beurre et crème)",
                    ),
                    (
                        "Autres produits raffinés DOA",
                        "Autres produits animaux > Autres produits raffinés DOA",
                    ),
                    (
                        "Fruit charnu",
                        "Fruits et légumes > Fruit charnu, légume ou champignon",
                    ),
                    (
                        "Fruit, légume ou champignon frais ou non transformé",
                        "Fruits et légumes > Fruit charnu, légume ou champignon > Fruit, légume ou champignon frais ou non transformé",
                    ),
                    (
                        "Fruits, légumes ou champignons séchés (yc chips, sauf herboristerie)",
                        "Fruits et légumes > Fruit charnu, légume ou champignon > Fruits, légumes ou champignons séchés (yc chips, sauf herboristerie)",
                    ),
                    (
                        "Soupe à base de fruit, légume ou champignon",
                        "Fruits et légumes > Fruit charnu, légume ou champignon > Soupe à base de fruit, légume ou champignon",
                    ),
                    (
                        "Jus de fruit, légume ou champignon",
                        "Fruits et légumes > Fruit charnu, légume ou champignon > Jus de fruit, légume ou champignon",
                    ),
                    (
                        "Fruit, légume ou champignon transformé",
                        "Fruits et légumes > Fruit charnu, légume ou champignon > Fruit, légume ou champignon transformé",
                    ),
                    (
                        "Graine non transformée (protéagineuse, oléagineuse)",
                        "Noix, graine et grain > Graine non transformée (protéagineuse, oléagineuse)",
                    ),
                    (
                        "Préparation et dérivé de graine ou noix (hors huile et graine germée, hors céréale)",
                        "Noix, graine et grain > Préparation et dérivé de graine ou noix (hors huile et graine germée, hors céréale)",
                    ),
                    (
                        "Graine germée ou à germer",
                        "Noix, graine et grain > Graine germée ou à germer",
                    ),
                    (
                        "Fruit à coque non transformé",
                        "Noix, graine et grain > Fruit à coque non transformé",
                    ),
                    (
                        "Préparation et dérivé de fruit à coque (hors huile)",
                        "Noix, graine et grain > Préparation et dérivé de fruit à coque (hors huile)",
                    ),
                    (
                        "Graisse et huile végétale",
                        "Noix, graine et grain > Graisse et huile végétale",
                    ),
                    (
                        "Produit de céréale entière ou moulue, farine",
                        "Produit de céréale > Produit de céréale entière ou moulue, farine",
                    ),
                    (
                        "Préparation de céréale (yc pâte sans oeuf ou vermicelle)",
                        "Produit de céréale > Préparation de céréale (yc pâte sans oeuf ou vermicelle)",
                    ),
                    (
                        "Produit de la boulangerie (pain et viennoiserie)",
                        "Produit de céréale > Produit de la boulangerie (pain et viennoiserie)",
                    ),
                    (
                        "Substitut produit laitier",
                        "Analogue végétal > Subtitut végétal de produit laitier",
                    ),
                    (
                        "Substitut de lait infantile végétal",
                        "Analogue végétal > Subtitut végétal de produit laitier > Substitut de lait infantile végétal",
                    ),
                    (
                        "Substitut de lait",
                        "Analogue végétal > Subtitut végétal de produit laitier > Substitut de lait",
                    ),
                    (
                        "Substitut de fromage",
                        "Analogue végétal > Subtitut végétal de produit laitier > Substitut de fromage",
                    ),
                    (
                        "Substitut de yaourt",
                        "Analogue végétal > Subtitut végétal de produit laitier > Substitut de yaourt",
                    ),
                    (
                        "Substitut végétal de produit carné",
                        "Analogue végétal > Subtitut végétal de produit carné",
                    ),
                    (
                        "Substitut végétal de produit de la mer",
                        "Analogue végétal > Subtitut végétal de produit de la mer",
                    ),
                    ("Sucre", "Condiment > Sucre"),
                    (
                        "Moutarde, vinaigre et vinaigrette",
                        "Condiment > Moutarde, vinaigre et vinaigrette",
                    ),
                    ("Fines herbes et épices", "Condiment > Fines herbes et épices"),
                    (
                        "Bouillon ou sauce (mayonnaise, pesto, tomate)",
                        "Condiment > Bouillon ou sauce (mayonnaise, pesto, tomate)",
                    ),
                    ("Sel", "Condiment > Sel"),
                    (
                        "Confiserie (yc chewing gum)",
                        "Produit sucré, salé, snack > Confiserie (yc chewing gum)",
                    ),
                    (
                        "Chocolat (bouchée, tablette)",
                        "Produit sucré, salé, snack > Chocolat (bouchée, tablette)",
                    ),
                    (
                        "Dessert Frais",
                        "Produit sucré, salé, snack > Dessert frais (hors yaourt)",
                    ),
                    (
                        "Crème glacée",
                        "Produit sucré, salé, snack > Dessert frais (hors yaourt) > Crème glacée",
                    ),
                    (
                        "Crème dessert, riz au lait, mousse au chocolat...",
                        "Produit sucré, salé, snack > Dessert frais (hors yaourt) > Crème dessert, riz au lait, mousse au chocolat...",
                    ),
                    (
                        "Dessert patissier, pâtisserie",
                        "Produit sucré, salé, snack > Dessert patissier, pâtisserie",
                    ),
                    (
                        "Dessert sec (biscuit, cake, produit petit-dejeuner, snack)",
                        "Produit sucré, salé, snack > Dessert sec (biscuit, cake, produit petit-dejeuner, snack)",
                    ),
                    (
                        "Pâtes à tartiner",
                        "Produit sucré, salé, snack > Pâtes à tartiner",
                    ),
                    (
                        "Biscuit, cake, snack salé\xa0 (hors chips ou noix/graine)",
                        "Produit sucré, salé, snack > Biscuit, cake, snack salé\xa0 (hors chips ou noix/graine)",
                    ),
                    ("Salade composée", "Cuisiné ou composé > Salade composée"),
                    (
                        "Plat ou soupe composé (hors soupe de légumes/fruits/champignons)",
                        "Cuisiné ou composé > Plat ou soupe composé (hors soupe de légumes/fruits/champignons)",
                    ),
                    (
                        "Boisson alcoolisée (dont vin, bière, hydromel)",
                        "Boisson > Boisson alcoolisée (dont vin, bière, hydromel)",
                    ),
                    ("Boisson alcoolisée", "Boisson > Boisson non alcoolisée"),
                    (
                        "Soda, kombucha (hors jus de fruit, produit lacté, analogue lacté)",
                        "Boisson > Boisson non alcoolisée > Soda, kombucha (hors jus de fruit, produit lacté, analogue lacté)",
                    ),
                    (
                        "Préparation pour boisson chaude (chocolaté, café, thé, tisane)",
                        "Boisson > Boisson non alcoolisée > Préparation pour boisson chaude (chocolaté, café, thé, tisane)",
                    ),
                    (
                        "Préparation pour boisson froide (sirop, base à soda)",
                        "Boisson > Boisson non alcoolisée > Préparation pour boisson froide (sirop, base à soda)",
                    ),
                    (
                        "Eau minérale et naturelle, eau embouteillée",
                        "Boisson > Eau minérale et naturelle, eau embouteillée",
                    ),
                    ("Eau aromatisée", "Boisson > Eau aromatisée"),
                    ("Eau potable autre", "Boisson > Eau potable autre"),
                    ("Alimentation infantile", "DADFMS > Alimentation Infantile"),
                    (
                        "Lait infantile 0-1an",
                        "DADFMS > Alimentation Infantile > Lait infantile 0-1an",
                    ),
                    (
                        "Lait infantile 1-3ans",
                        "DADFMS > Alimentation Infantile > Lait infantile 1-3ans",
                    ),
                    (
                        "Autre aliment infantile 0-3ans",
                        "DADFMS > Alimentation Infantile > Autre aliment infantile 0-3ans",
                    ),
                    (
                        "Aliment pour personne de plus de 36 mois",
                        "DADFMS > Aliment pour personne de plus de 36 mois",
                    ),
                    (
                        "Additif alimentaire",
                        "Améliorant ou auxiliaire > Additif alimentaire",
                    ),
                    ("Arome", "Améliorant ou auxiliaire > Arome"),
                    ("Ferment, enzyme", "Améliorant ou auxiliaire > Ferment, enzyme"),
                    (
                        "Additif et pré-mélange pour animaux",
                        "Alimentation animale > Additif et pré-mélange pour animaux",
                    ),
                    (
                        "Aliment composé pour animaux",
                        "Alimentation animale > Aliment composé pour animaux",
                    ),
                    (
                        "Matière première végétale pour animaux",
                        "Alimentation animale > Matière première végétale pour animaux",
                    ),
                    ("Petfood", "Alimentation animale > Petfood"),
                    ("Autre aliment pour animaux", "Alimentation animale"),
                    ("Herbes et huiles essentielles", "Herbes et huiles essentielles"),
                    ("Complément alimentaire", "Complément alimentaire"),
                    (
                        "Produit alimentaire indéterminé",
                        "Produit alimentaire indéterminé",
                    ),
                    ("Sous-produit animal", "Sous-produit animal"),
                    ("Autre produit non alimentaire", "Autre produit non alimentaire"),
                    ("Sans objet", "Sans objet"),
                ],
                max_length=255,
                verbose_name="Catégorie de produit",
            ),
        ),
    ]
