# Generated by Django 5.2.1 on 2025-05-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0018_evenementproduit_categorie_danger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etablissement",
            name="position_dossier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("detection_non_conformite", "Détection de la non-conformité"),
                    ("survenue_non_conformite", "Survenue de la non-conformité"),
                    (
                        "detection_et_survenue_non_conformite",
                        "Détection et survenue de la non-conformité",
                    ),
                    (
                        "autre_maillon_chaine_distribution",
                        "Autre maillon de la chaîne de distribution",
                    ),
                    ("autre", "Autre"),
                ],
                max_length=100,
                verbose_name="Position dossier",
            ),
        ),
        migrations.AlterField(
            model_name="etablissement",
            name="type_exploitant",
            field=models.CharField(
                blank=True,
                choices=[
                    ("producteur_primaire", "A - Producteur primaire"),
                    (
                        "hotellerie_restauration_cafe",
                        "B - Hôtellerie/restauration/café",
                    ),
                    ("restauration_collective", "B - Restauration collective"),
                    ("autre_detaillant", "B - Autre détaillant"),
                    (
                        "producteur_fabricant",
                        "C - Producteur / fabricant (hors restauration)",
                    ),
                    ("plateforme_distribution", "D - Plateforme de distribution"),
                    ("autre_entrepot", "D - Autre entrepôt"),
                    ("transporteur", "D - Transporteur"),
                    ("negociant", "D - Négociant"),
                    ("site_vente_en_ligne", "E - Site de vente en ligne"),
                    (
                        "expediteur_fournisseur_hors_ue",
                        "F - Expéditeur / fournisseur hors UE",
                    ),
                    (
                        "importateur_ue_de_pays_tiers",
                        "F - Importateur UE de pays tiers",
                    ),
                    (
                        "exportateur_ue_vers_pays_tiers",
                        "F - Exportateur UE vers pays tiers",
                    ),
                    ("autre", "Y - Autre"),
                    ("sans_objet", "Z - Sans objet"),
                ],
                max_length=100,
                verbose_name="Type exploitant",
            ),
        ),
        migrations.AlterField(
            model_name="evenementproduit",
            name="produit_pret_a_manger",
            field=models.CharField(
                blank=True,
                choices=[("oui", "Oui"), ("non", "Non"), ("sans_objet", "Sans objet")],
                max_length=100,
                verbose_name="Produit Prêt à manger (PAM)",
            ),
        ),
        migrations.AlterField(
            model_name="evenementproduit",
            name="quantification_unite",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cm", "cm"),
                    ("mm", "mm"),
                    ("°C", "°C"),
                    ("pH", "pH"),
                    ("Aw", "Aw"),
                    ("g", "g"),
                    ("mg", "mg"),
                    ("mg/g", "mg/g"),
                    ("mgeq/g", "mgeq/g"),
                    ("µg/g", "µg/g"),
                    ("ng/g", "ng/g"),
                    ("g/100 g", "g/100 g"),
                    ("mg/100 g", "mg/100 g"),
                    ("g/kg", "g/kg"),
                    ("mg/kg", "mg/kg"),
                    ("µg/kg", "µg/kg"),
                    ("ng/kg", "ng/kg"),
                    ("pg/kg", "pg/kg"),
                    ("/1 g", "/1 g"),
                    ("/10 g", "/10 g"),
                    ("/25 g", "/25 g"),
                    ("/100 g", "/100 g"),
                    ("/kg", "/kg"),
                    ("UFC", "UFC"),
                    ("UFC/g", "UFC/g"),
                    ("UFC/10 g", "UFC/10 g"),
                    ("UFC/25 g", "UFC/25 g"),
                    ("UFC/mL", "UFC/mL"),
                    ("NPP/100 g", "NPP/100 g"),
                    ("mL", "mL"),
                    ("mmol/L", "mmol/L"),
                    ("µL/L", "µL/L"),
                    ("mL/100 mL", "mL/100 mL"),
                    ("/mL", "/mL"),
                    ("/100 mL", "/100 mL"),
                    ("/250 mL", "/250 mL"),
                    ("µL/kg", "µL/kg"),
                    ("mmol/kg", "mmol/kg"),
                    ("mL/10 g", "mL/10 g"),
                    ("mL/100 g", "mL/100 g"),
                    ("µL/g", "µL/g"),
                    ("g/mL", "g/mL"),
                    ("g/L", "g/L"),
                    ("mg/L", "mg/L"),
                    ("µg/L", "µg/L"),
                    ("g/100 mL", "g/100 mL"),
                    ("mg/100 mL", "mg/100 mL"),
                    ("%/25 g", "%/25 g"),
                    ("%/100 g", "%/100 g"),
                    ("%", "%"),
                    ("‰", "‰"),
                    ("bq/kg", "bq/kg"),
                    ("autre unite", "autre unité"),
                ],
                max_length=100,
                verbose_name="Unité",
            ),
        ),
    ]
