# Generated by Django 5.2.1 on 2025-05-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_alter_message_options"),
        ("ssa", "0019_alter_etablissement_position_dossier_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="evenementproduit",
            name="type_evenement_source_constraint",
        ),
        migrations.AlterField(
            model_name="evenementproduit",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("autocontrole_notifie_produit", "Autocontrôle notifié (produit)"),
                    (
                        "autocontrole_notifie_environnement",
                        "Autocontrôle notifié (environnement)",
                    ),
                    ("autocontrole_non_notifie", "Autocontrôle non notifié"),
                    ("prelevement_pspc", "Prélèvement PSPC"),
                    ("autre_prelevement_officiel", "Autre prélèvement officiel"),
                    ("autre_constat_officiel", "Autre constat officiel"),
                    ("investigation_cas_humains", "Investigation de cas humains"),
                    ("do_listeriose", "DO Listériose"),
                    ("cas_groupes", "Cas groupés"),
                    ("signalement_consommateur", "Signalement consommateur"),
                    ("autre", "Autre"),
                ],
                max_length=100,
                verbose_name="Source",
            ),
        ),
        migrations.AddConstraint(
            model_name="evenementproduit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source", "autre"),
                    ("source", ""),
                    models.Q(
                        ("type_evenement", "investigation_cas_humain"),
                        ("source__in", ["do_listeriose", "cas_groupes"]),
                    ),
                    models.Q(
                        models.Q(
                            ("type_evenement", "investigation_cas_humain"),
                            _negated=True,
                        ),
                        models.Q(
                            ("source__in", ["do_listeriose", "cas_groupes"]),
                            _negated=True,
                        ),
                    ),
                    _connector="OR",
                ),
                name="type_evenement_source_constraint",
            ),
        ),
    ]
