# Generated by Django 5.2.1 on 2025-05-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0020_remove_evenementproduit_type_evenement_source_constraint_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="evenementproduit",
            name="quantification_must_have_unit",
        ),
        migrations.AddField(
            model_name="evenementproduit",
            name="precision_danger",
            field=models.CharField(blank=True, max_length=255, verbose_name="Précision danger"),
        ),
        migrations.AlterField(
            model_name="evenementproduit",
            name="quantification",
            field=models.CharField(
                blank=True,
                null=True,
                verbose_name="Quantification maximale à l'origine de l'événement",
            ),
        ),
    ]
