# Generated by Django 5.2.1 on 2025-05-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0022_alter_evenementproduit_categorie_produit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenementproduit",
            name="denomination",
            field=models.CharField(blank=True, max_length=255, verbose_name="Dénomination"),
        ),
    ]
