# Generated by Django 5.2.1 on 2025-05-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_alter_message_options"),
        ("ssa", "0023_alter_evenementproduit_denomination"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="evenementproduit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("produit_pret_a_manger", ""),
                    (
                        "categorie_danger__in",
                        [
                            "Bacillus",
                            "Bacillus anthracis",
                            "Bacillus cereus",
                            "Bacillus thurigiensis",
                            "Brucella",
                            "Brucella melitensis",
                            "Brucella suis",
                            "Brucella abortus",
                            "Campylobacter",
                            "Campylobacter jejuni",
                            "Campylobacter coli",
                            "Clostridium",
                            "Clostridium botulinum",
                            "Clostridium perfringens",
                            "Coxiella",
                            "Coxiella burnetii (fièvre Q)",
                            "Cronobacter",
                            "Cronobacter sakazakii",
                            "Cronobacter malonaticus",
                            "Escherichia coli",
                            "Escherichia coli (non STEC - EHEC)",
                            "Escherichia coli shigatoxinogène (STEC - EHEC)",
                            "Listeria",
                            "Listeria monocytogenes",
                            "Mycobacterium",
                            "Mycobacterium tuberculosis",
                            "Mycobacterium bovis",
                            "Mycobacterium suis",
                            "Salmonella",
                            "Salmonella, autre (à préciser)",
                            "Salmonella dublin",
                            "Salmonella enteritidis",
                            "Salmonella hadar",
                            "Salmonella infantis",
                            "Salmonella kentucky",
                            "Salmonella mambaka",
                            "Salmonella typhimurium",
                            "Salmonella virchow",
                            "Staphylococcus",
                            "Staphylococcus aureus et/ou sa toxine",
                            "Vibrio",
                            "Vibrio vulnificus",
                            "Vibrio parahaemolyticus",
                            "Vibrio cholerae",
                            "Yersinia",
                            "Yersinia enterocolitica",
                            "Bactérie (autre ou indéterminée)",
                        ],
                    ),
                    _connector="OR",
                ),
                name="pam_requires_danger_bacterien",
            ),
        ),
    ]
