# Generated by Django 5.2.2 on 2025-06-17 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("core", "0036_alter_document_document_type"),
        ("ssa", "0025_remove_evenementproduit_pam_requires_danger_bacterien_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AddField(
                    model_name="etablissement",
                    name="departement2",
                    field=models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="etablissements",
                        to="core.departement",
                        verbose_name="Département",
                        blank=True,
                        null=True,
                    ),
                    preserve_default=False,
                ),
                migrations.RunSQL(
                    """
                    update ssa_etablissement
                        set departement2_id = d.id
                    from core_departement as d
                    where upper(departement) = upper(d.nom);
                    """,
                    reverse_sql="""
                    update ssa_etablissement
                        set departement = d.nom
                    from core_departement as d
                    where departement2_id = d.id;
                    """,
                ),
                migrations.RemoveField(
                    model_name="etablissement",
                    name="departement",
                ),
                migrations.RenameField(
                    model_name="etablissement",
                    old_name="departement2",
                    new_name="departement",
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="etablissement",
                    name="departement",
                ),
                migrations.AddField(
                    model_name="etablissement",
                    name="departement",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="etablissements",
                        to="core.departement",
                        verbose_name="Département",
                    ),
                ),
            ],
        )
    ]
