# Generated by Django 5.2.2 on 2025-06-17 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_alter_departement_region"),
        ("ssa", "0025_remove_evenementproduit_pam_requires_danger_bacterien_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AddField(
                    model_name="etablissement",
                    name="departement2",
                    field=models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="etablissements",
                        to="core.departement",
                        verbose_name="Département",
                        blank=True,
                        null=True,
                    ),
                    preserve_default=False,
                ),
                migrations.RunSQL(
                    """
                    update ssa_etablissement
                    set departement2_id = d.id
                        from ssa_etablissement as e
                        inner join core_departement as d
                    on upper(e.departement) = upper(d.nom);
                    """
                ),
                migrations.RemoveField(
                    model_name="etablissement",
                    name="departement",
                ),
                migrations.RenameField(
                    model_name="etablissement",
                    old_name="departement2",
                    new_name="departement",
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="etablissement",
                    name="departement",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="etablissements",
                        to="core.departement",
                        verbose_name="Département",
                    ),
                ),
            ],
        )
    ]
