# Generated by Django 5.2.2 on 2025-06-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0026_etablissement_departement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenementproduit",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("autocontrole_notifie_produit", "Autocontrôle notifié (produit)"),
                    (
                        "autocontrole_notifie_environnement",
                        "Autocontrôle notifié (environnement)",
                    ),
                    ("prelevement_pspc", "Prélèvement PSPC"),
                    ("autre_prelevement_officiel", "Autre prélèvement officiel"),
                    ("autre_constat_officiel", "Autre constat officiel"),
                    ("investigation_cas_humains", "Investigation de cas humains"),
                    ("do_listeriose", "DO Listériose"),
                    ("cas_groupes", "Cas groupés"),
                    ("signalement_consommateur", "Signalement consommateur"),
                    ("autre", "Signalement autre"),
                ],
                max_length=100,
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="evenementproduit",
            name="type_evenement",
            field=models.CharField(
                choices=[
                    ("alerte_produit_nationale", "Alerte produit nationale"),
                    ("alerte_produit_locale", "Alerte produit locale"),
                    ("non_alerte", "Non alerte"),
                    ("alerte_produit_ue", "Alerte produit UE/INT (RASFF)"),
                    ("non_alerte_ue", "Non alerte UE/INT (AAC)"),
                    ("investigation_cas_humain", "Investigation cas humains"),
                    ("autre_action_coordonnee", "Autre action coordonnée"),
                ],
                max_length=100,
                verbose_name="Type d'événement",
            ),
        ),
    ]
