# Generated by Django 5.2.4 on 2025-08-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0029_alter_etablissement_type_exploitant"),
    ]

    operations = [
        migrations.AddField(
            model_name="etablissement",
            name="numeros_resytal",
            field=models.CharField(blank=True, max_length=255, verbose_name="Numéros d’inspection Resytal"),
        ),
    ]
