# Generated by Django 5.2.4 on 2025-08-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0030_etablissement_numeros_resytal"),
    ]

    operations = [
        migrations.AddField(
            model_name="etablissement",
            name="enseigne_usuelle",
            field=models.CharField(blank=True, max_length=100, verbose_name="Enseigne usuelle"),
        ),
    ]
