# Generated by Django 5.2.4 on 2025-08-19 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_alter_document_document_type"),
        ("ssa", "0031_etablissement_enseigne_usuelle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etablissement",
            name="departement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_etablissements",
                to="core.departement",
                verbose_name="Département",
            ),
        ),
    ]
