# Generated by Django 5.2.4 on 2025-09-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0032_alter_etablissement_departement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenementproduit",
            name="type_evenement",
            field=models.CharField(
                choices=[
                    ("alerte_produit_nationale", "Alerte produit nationale"),
                    ("alerte_produit_locale", "Alerte produit locale"),
                    ("non_alerte", "Non alerte (non mis sur le marché)"),
                    ("non_alerte_non_dangereux", "Non alerte (non dangereux)"),
                    ("investigation_cas_humain", "Investigation cas humains"),
                    ("autre_action_coordonnee", "Autre action coordonnée"),
                ],
                max_length=100,
                verbose_name="Type d'événement",
            ),
        ),
    ]
