# Generated by Django 5.2.4 on 2025-09-01 11:40

import core.mixins
import django.db.models.deletion
import ssa.models.validators
from django.db import migrations, models


def forwards(apps, schema_editor):
    Etablissement = apps.get_model("ssa", "Etablissement")
    EvenementProduit = apps.get_model("ssa", "EvenementProduit")
    ContentType = apps.get_model("contenttypes", "ContentType")

    content_type = ContentType.objects.get_for_model(EvenementProduit)

    for etablissement in Etablissement.objects.all():
        etablissement.content_type_id = content_type.id
        etablissement.object_id = etablissement.evenement_produit_id
        etablissement.save(update_fields=["content_type", "object_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0038_alter_document_document_type"),
        ("ssa", "0032_alter_etablissement_departement"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestigationCasHumain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("en_cours", "En cours"),
                            ("cloture", "Clôturé"),
                        ],
                        default="brouillon",
                        max_length=100,
                        verbose_name="État de l'événement",
                    ),
                ),
                ("numero_annee", models.IntegerField(verbose_name="Année")),
                ("numero_evenement", models.IntegerField(verbose_name="Numéro")),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date de création"),
                ),
                (
                    "numero_rasff",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        validators=[ssa.models.validators.validate_numero_rasff],
                        verbose_name="N° RASFF/AAC",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Description de l'événement"),
                ),
                (
                    "categorie_danger",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bacillus", "Bactérie > Bacillus"),
                            (
                                "Bacillus anthracis",
                                "Bactérie > Bacillus > Bacillus anthracis",
                            ),
                            (
                                "Bacillus cereus",
                                "Bactérie > Bacillus > Bacillus cereus",
                            ),
                            (
                                "Bacillus thurigiensis",
                                "Bactérie > Bacillus > Bacillus thurigiensis",
                            ),
                            ("Brucella", "Bactérie > Brucella"),
                            (
                                "Brucella melitensis",
                                "Bactérie > Brucella > Brucella melitensis",
                            ),
                            ("Brucella suis", "Bactérie > Brucella > Brucella suis"),
                            (
                                "Brucella abortus",
                                "Bactérie > Brucella > Brucella abortus",
                            ),
                            ("Campylobacter", "Bactérie > Campylobacter"),
                            (
                                "Campylobacter jejuni",
                                "Bactérie > Campylobacter > Campylobacter jejuni",
                            ),
                            (
                                "Campylobacter coli",
                                "Bactérie > Campylobacter > Campylobacter coli",
                            ),
                            ("Clostridium", "Bactérie > Clostridium"),
                            (
                                "Clostridium botulinum",
                                "Bactérie > Clostridium > Clostridium botulinum",
                            ),
                            (
                                "Clostridium perfringens",
                                "Bactérie > Clostridium > Clostridium perfringens",
                            ),
                            ("Coxiella", "Bactérie > Coxiella"),
                            (
                                "Coxiella burnetii (fièvre Q)",
                                "Bactérie > Coxiella > Coxiella burnetii (fièvre Q)",
                            ),
                            ("Cronobacter", "Bactérie > Cronobacter"),
                            (
                                "Cronobacter sakazakii",
                                "Bactérie > Cronobacter > Cronobacter sakazakii",
                            ),
                            (
                                "Cronobacter malonaticus",
                                "Bactérie > Cronobacter > Cronobacter malonaticus",
                            ),
                            ("Coliformes", "Bactérie > Coliformes"),
                            ("Escherichia coli", "Bactérie > Escherichia Coli"),
                            (
                                "Escherichia coli (non STEC - EHEC)",
                                "Bactérie > Escherichia Coli > Escherichia coli (non STEC - EHEC)",
                            ),
                            (
                                "Escherichia coli shigatoxinogène (STEC - EHEC)",
                                "Bactérie > Escherichia Coli > Escherichia coli shigatoxinogène (STEC - EHEC)",
                            ),
                            ("Entérobactéries", "Bactérie > Entérobactéries"),
                            ("Leptospira", "Bactérie > Leptospira"),
                            ("Listeria", "Bactérie > Listeria"),
                            (
                                "Listeria monocytogenes",
                                "Bactérie > Listeria > Listeria monocytogenes",
                            ),
                            ("Mycobacterium", "Bactérie > Mycobacterium"),
                            (
                                "Mycobacterium tuberculosis",
                                "Bactérie > Mycobacterium > Mycobacterium tuberculosis",
                            ),
                            (
                                "Mycobacterium bovis",
                                "Bactérie > Mycobacterium > Mycobacterium bovis",
                            ),
                            (
                                "Mycobacterium suis",
                                "Bactérie > Mycobacterium > Mycobacterium suis",
                            ),
                            ("Pseudomonas", "Bactérie > Pseudomonas"),
                            ("Salmonella", "Bactérie > Salmonella"),
                            (
                                "Salmonella, autre (à préciser)",
                                "Bactérie > Salmonella > Salmonella, autre (à préciser)",
                            ),
                            (
                                "Salmonella dublin",
                                "Bactérie > Salmonella > Salmonella dublin",
                            ),
                            (
                                "Salmonella enteritidis",
                                "Bactérie > Salmonella > Salmonella enteritidis",
                            ),
                            (
                                "Salmonella hadar",
                                "Bactérie > Salmonella > Salmonella hadar",
                            ),
                            (
                                "Salmonella infantis",
                                "Bactérie > Salmonella > Salmonella infantis",
                            ),
                            (
                                "Salmonella kentucky",
                                "Bactérie > Salmonella > Salmonella kentucky",
                            ),
                            (
                                "Salmonella mambaka",
                                "Bactérie > Salmonella > Salmonella mambaka",
                            ),
                            (
                                "Salmonella typhimurium",
                                "Bactérie > Salmonella > Salmonella typhimurium",
                            ),
                            (
                                "Salmonella virchow",
                                "Bactérie > Salmonella > Salmonella virchow",
                            ),
                            ("Shigella", "Bactérie > Shigella"),
                            ("Staphylococcus", "Bactérie > Staphylococcus"),
                            (
                                "Staphylococcus aureus et/ou sa toxine",
                                "Bactérie > Staphylococcus > Staphylococcus aureus et/ou sa toxine",
                            ),
                            ("Vibrio", "Bactérie > Vibrio"),
                            (
                                "Vibrio vulnificus",
                                "Bactérie > Vibrio > Vibrio vulnificus",
                            ),
                            (
                                "Vibrio parahaemolyticus",
                                "Bactérie > Vibrio > Vibrio parahaemolyticus",
                            ),
                            ("Vibrio cholerae", "Bactérie > Vibrio > Vibrio cholerae"),
                            ("Yersinia", "Bactérie > Yersinia"),
                            (
                                "Yersinia enterocolitica",
                                "Bactérie > Yersinia > Yersinia enterocolitica",
                            ),
                            (
                                "Bactérie (autre ou indéterminée)",
                                "Bactérie > Bactérie (autre ou indéterminée)",
                            ),
                            (
                                "Levure Moisissure",
                                "Levure Moisissure > Levure Moisissure",
                            ),
                            (
                                "Virus de l'encéphalite à tique (TBEV)",
                                "Virus > Virus de l'encéphalite à tique (TBEV)",
                            ),
                            ("Virus de l'hépatite A", "Virus > Virus de l'hépatite A"),
                            ("Virus de l'hépatite E", "Virus > Virus de l'hépatite E"),
                            (
                                "Virus de la gastroentérite aigüe (GEA)",
                                "Virus > Virus de la gastroentérite aigüe (GEA)",
                            ),
                            (
                                "Virus de la gastroentérite aigüe (GEA) details",
                                "Virus > Virus de la gastroentérite aigüe (GEA) > Calivirus, Norovirus, Sapovirus, Rotavirus, Astrovirus, Adénovirus",
                            ),
                            ("Virus Nipah", "Virus > Virus Nipah"),
                            ("Entérovirus", "Virus > Entérovirus"),
                            (
                                "Virus influenza zoonotique par voie alimentaire",
                                "Virus > Virus influenza zoonotique par voie alimentaire",
                            ),
                            (
                                "Virus alimentaire (autre ou indéterminé)",
                                "Virus > Virus alimentaire (autre ou indéterminé)",
                            ),
                            (
                                "Encéphalopathie spongiforme bovine",
                                "Prion > Encéphalopathie spongiforme bovine",
                            ),
                            ("Tremblante", "Prion > Tremblante"),
                            (
                                "Prion (autre ou indéterminé)",
                                "Prion > Prion (autre ou indéterminé)",
                            ),
                            ("Echinococcus", "Parasite > Echinococcus"),
                            ("Anisakis", "Parasite > Anisakis"),
                            ("Pseudoterranova", "Parasite > Pseudoterranova"),
                            ("Diphyllobothrium", "Parasite > Diphyllobothrium"),
                            (
                                "Clinostomum complanatum",
                                "Parasite > Clinostomum complanatum",
                            ),
                            ("Toxacara", "Parasite > Toxacara"),
                            ("Toxoplasma", "Parasite > Toxoplasma"),
                            ("Trichine", "Parasite > Trichine"),
                            ("Alaria alata", "Parasite > Alaria alata"),
                            (
                                "Parasite (autre ou indéterminé)",
                                "Parasite > Parasite (autre ou indéterminé)",
                            ),
                            (
                                "Insecte - vers - rongeur - autre indésirable",
                                "Corps étranger > Insecte - vers - rongeur - autre indésirable",
                            ),
                            (
                                "Verre - cailloux - autre blessant",
                                "Corps étranger > Verre - cailloux - autre blessant",
                            ),
                            (
                                "Corps étranger (autre ou indéterminé)",
                                "Corps étranger > Corps étranger (autre ou indéterminé)",
                            ),
                            ("Mycotoxine", "Toxine > Mycotoxine"),
                            ("Aflatoxine", "Toxine > Mycotoxine > Aflatoxine"),
                            ("Ochratoxine A", "Toxine > Mycotoxine > Ochratoxine A"),
                            ("Patuline", "Toxine > Mycotoxine > Patuline"),
                            (
                                "Sclérotes d'ergot - Alcaloïdes de l'ergot",
                                "Toxine > Mycotoxine > Sclérotes d'ergot - Alcaloïdes de l'ergot",
                            ),
                            (
                                "Déoxynivalénol (DON)",
                                "Toxine > Mycotoxine > Déoxynivalénol (DON)",
                            ),
                            ("Zéaralénone", "Toxine > Mycotoxine > Zéaralénone"),
                            ("Fumonisines", "Toxine > Mycotoxine > Fumonisines"),
                            ("Citrinine", "Toxine > Mycotoxine > Citrinine"),
                            ("Toxine T2 HT2", "Toxine > Mycotoxine > Toxine T2 HT2"),
                            (
                                "Alternariol (AOH) Alternariol monométhyl éther (AME) Acide ténuazonique (TeA)",
                                "Toxine > Mycotoxine > Alternariol (AOH) Alternariol monométhyl éther (AME) Acide ténuazonique (TeA)",
                            ),
                            (
                                "Mycotoxine (autre ou indéterminée)",
                                "Toxine > Mycotoxine > Mycotoxine (autre ou indéterminée)",
                            ),
                            ("Toxine DSP", "Toxine > Phycotoxine et cyanotoxine"),
                            (
                                "Toxine DSP (toxines lipophiles)",
                                "Toxine > Phycotoxine et cyanotoxine > Toxine DSP (toxines lipophiles)",
                            ),
                            (
                                "Histamine",
                                "Toxine > Phycotoxine et cyanotoxine > Histamine",
                            ),
                            (
                                "Toxine ASP",
                                "Toxine > Phycotoxine et cyanotoxine > Toxine ASP",
                            ),
                            (
                                "Toxine PSP",
                                "Toxine > Phycotoxine et cyanotoxine > Toxine PSP",
                            ),
                            (
                                "Ciguatoxine",
                                "Toxine > Phycotoxine et cyanotoxine > Ciguatoxine",
                            ),
                            (
                                "Phycotoxine et cyanotoxine (autre ou indéterminée)",
                                "Toxine > Phycotoxine et cyanotoxine > Phycotoxine et cyanotoxine (autre ou indéterminée)",
                            ),
                            (
                                "Phytotoxine et phyto-estrogène",
                                "Toxine > Phytotoxine et phyto-estrogène",
                            ),
                            (
                                "Datura (alcaloïdes tropaniques)",
                                "Toxine > Phytotoxine et phyto-estrogène > Datura (alcaloïdes tropaniques)",
                            ),
                            (
                                "Cucurbitacine et autres toxines de courges",
                                "Toxine > Phytotoxine et phyto-estrogène > Cucurbitacine et autres toxines de courges",
                            ),
                            (
                                "Betterave crue : toxine indéterminée",
                                "Toxine > Phytotoxine et phyto-estrogène > Betterave crue : toxine indéterminée",
                            ),
                            (
                                "Pignon de pin amer (dysgueusie)",
                                "Toxine > Phytotoxine et phyto-estrogène > Pignon de pin amer (dysgueusie)",
                            ),
                            (
                                "Champignons toxiques (divers)",
                                "Toxine > Phytotoxine et phyto-estrogène > Champignons toxiques (divers)",
                            ),
                            (
                                "Acide cyanhydrique",
                                "Toxine > Phytotoxine et phyto-estrogène > Acide cyanhydrique",
                            ),
                            (
                                "Acide érucique",
                                "Toxine > Phytotoxine et phyto-estrogène > Acide érucique",
                            ),
                            (
                                "Alcaloïdes pyrrolizidiniques",
                                "Toxine > Phytotoxine et phyto-estrogène > Alcaloïdes pyrrolizidiniques",
                            ),
                            (
                                "Alcaloïdes opioïdes",
                                "Toxine > Phytotoxine et phyto-estrogène > Alcaloïdes opioïdes",
                            ),
                            (
                                "Phyto-estrogène",
                                "Toxine > Phytotoxine et phyto-estrogène > Phyto-estrogène",
                            ),
                            (
                                "Autres toxines végétales",
                                "Toxine > Phytotoxine et phyto-estrogène > Autres toxines végétales",
                            ),
                            (
                                "Allergène (autre ou indéterminé)",
                                "Allergène - composition ou étiquetage > Allergène (autre ou indéterminé)",
                            ),
                            (
                                "Allergène - Arachide",
                                "Allergène - composition ou étiquetage > Allergène - Arachide",
                            ),
                            (
                                "Allergène - Céleri",
                                "Allergène - composition ou étiquetage > Allergène - Céleri",
                            ),
                            (
                                "Allergène - Crustacés",
                                "Allergène - composition ou étiquetage > Allergène - Crustacés",
                            ),
                            (
                                "Allergène - Fruits à coques",
                                "Allergène - composition ou étiquetage > Allergène - Fruits à coques",
                            ),
                            (
                                "Allergène - Gluten",
                                "Allergène - composition ou étiquetage > Allergène - Gluten",
                            ),
                            (
                                "Allergène - Lait",
                                "Allergène - composition ou étiquetage > Allergène - Lait",
                            ),
                            (
                                "Allergène - Lupin",
                                "Allergène - composition ou étiquetage > Allergène - Lupin",
                            ),
                            (
                                "Allergène - Mollusques",
                                "Allergène - composition ou étiquetage > Allergène - Mollusques",
                            ),
                            (
                                "Allergène - Moutarde",
                                "Allergène - composition ou étiquetage > Allergène - Moutarde",
                            ),
                            (
                                "Allergène - Oeufs",
                                "Allergène - composition ou étiquetage > Allergène - Oeufs",
                            ),
                            (
                                "Allergène - Poisson",
                                "Allergène - composition ou étiquetage > Allergène - Poisson",
                            ),
                            (
                                "Allergène - Sésame",
                                "Allergène - composition ou étiquetage > Allergène - Sésame",
                            ),
                            (
                                "Allergène - Soja",
                                "Allergène - composition ou étiquetage > Allergène - Soja",
                            ),
                            (
                                "Allergène - Sulfites",
                                "Allergène - composition ou étiquetage > Allergène - Sulfites",
                            ),
                            (
                                "SA - Peste porcine africaine",
                                "Santé animale > SA - Peste porcine africaine",
                            ),
                            (
                                "SA - Peste porcine classique",
                                "Santé animale > SA - Peste porcine classique",
                            ),
                            (
                                "SA - Fièvre aphteuse",
                                "Santé animale > SA - Fièvre aphteuse",
                            ),
                            (
                                "SA - Influenza aviaire hautement pathogène",
                                "Santé animale > SA - Influenza aviaire hautement pathogène",
                            ),
                            (
                                "SA - Santé animale (autre)",
                                "Santé animale > SA - Santé animale (autre)",
                            ),
                            ("Etiquetage / DLC", "Etiquetage > Etiquetage / DLC"),
                            (
                                "Etiquetage / température de conservation",
                                "Etiquetage > Etiquetage / température de conservation",
                            ),
                            (
                                "Etiquetage / composition (sauf allergène)",
                                "Etiquetage > Etiquetage / composition (sauf allergène)",
                            ),
                            (
                                "Etiquetage / mention de bon usage",
                                "Etiquetage > Etiquetage / mention de bon usage",
                            ),
                            (
                                "Etiquetage / allégation",
                                "Etiquetage > Etiquetage / allégation",
                            ),
                            (
                                "Etiquetage / ionisation",
                                "Etiquetage > Etiquetage / ionisation",
                            ),
                            (
                                "Activité interdite (mesure administrative)",
                                "Activité établissement non autorisée > Activité interdite (mesure administrative)",
                            ),
                            (
                                "Irradiation",
                                "Activité établissement non autorisée > Irradiation",
                            ),
                            (
                                "Activité non agréée (défaut d'agrément)",
                                "Activité établissement non autorisée > Activité non agréée (défaut d'agrément)",
                            ),
                            (
                                "Activité non autorisée (autre autorisation)",
                                "Activité établissement non autorisée > Activité non autorisée (autre autorisation)",
                            ),
                            (
                                "Perte de maîtrise autre procédé",
                                "Perte de maîtrise procédé > Perte de maîtrise autre procédé",
                            ),
                            (
                                "Défaut de stérilisation",
                                "Perte de maîtrise procédé > Défaut de stérilisation",
                            ),
                            (
                                "Défaut de pasteurisation",
                                "Perte de maîtrise procédé > Défaut de pasteurisation",
                            ),
                            (
                                "Défaut du conditionnement",
                                "Perte de maîtrise procédé > Défaut du conditionnement",
                            ),
                            (
                                "Défaut de composition (sauf allergène)",
                                "Perte de maîtrise procédé > Défaut de composition (sauf allergène)",
                            ),
                            (
                                "Ionisation non conforme (hors étiquetage)",
                                "Perte de maîtrise procédé > Ionisation non conforme (hors étiquetage)",
                            ),
                            (
                                "Défaut organoleptique (toute cause)",
                                "Perte de maîtrise procédé > Défaut organoleptique (toute cause)",
                            ),
                            (
                                "Rupture de la chaîne du froid",
                                "Perte de maîtrise procédé > Rupture de la chaîne du froid",
                            ),
                            (
                                "Mauvaises conditions d'hygiène",
                                "Perte de maîtrise procédé > Mauvaises conditions d'hygiène",
                            ),
                            (
                                "Défaut de traçabilité",
                                "Perte de maîtrise procédé > Défaut de traçabilité",
                            ),
                            ("Cobalt", "MCDA > Cobalt"),
                            ("Formaldéhyde", "MCDA > Formaldéhyde"),
                            ("Mélamine", "MCDA > Mélamine"),
                            (
                                "Perturbateur endocrinien (autre)",
                                "MCDA > Perturbateur endocrinien (autre)",
                            ),
                            ("Phtalates", "MCDA > Phtalates"),
                            ("Bisphénol A", "MCDA > Bisphénol A"),
                            (
                                "MCDA (autre contaminant)",
                                "MCDA > MCDA (autre contaminant)",
                            ),
                            (
                                "3MCPD et esters d'acides gras de 3-MCPD",
                                "Contaminant des procédés > 3MCPD et esters d'acides gras de 3-MCPD",
                            ),
                            (
                                "3MCPD Acrylamide",
                                "Contaminant des procédés > Acrylamide",
                            ),
                            (
                                "Esters d'acides gras de glycidol",
                                "Contaminant des procédés > Esters d'acides gras de glycidol",
                            ),
                            ("HAP", "Contaminant des procédés > HAP"),
                            ("AAH", "Contaminant des procédés > AAH"),
                            (
                                "Hydrocarbures d'huile minérale (MOAH et MOSH)",
                                "Contaminant des procédés > Hydrocarbures d'huile minérale (MOAH et MOSH)",
                            ),
                            (
                                "Furane et dérivés méthylés du furane",
                                "Contaminant des procédés > Furane et dérivés méthylés du furane",
                            ),
                            ("Nitrosamines", "Contaminant des procédés > Nitrosamines"),
                            (
                                "Contaminant des procédés (autre sauf pesticide biocide)",
                                "Contaminant des procédés > Autre sauf pesticide/biocide",
                            ),
                            (
                                "Plomb (Pb)",
                                "Elément trace métallique / inorganique > Plomb (Pb)",
                            ),
                            (
                                "Cadmium (Cd)",
                                "Elément trace métallique / inorganique > Cadmium (Cd)",
                            ),
                            (
                                "Arsenic (As)",
                                "Elément trace métallique / inorganique > Arsenic (As)",
                            ),
                            (
                                "Mercure (Hg)",
                                "Elément trace métallique / inorganique > Mercure (Hg)",
                            ),
                            (
                                "Nickel (Ni)",
                                "Elément trace métallique / inorganique > Nickel (Ni)",
                            ),
                            (
                                "Elément trace métallique ou composé inorganique (autre)",
                                "Elément trace métallique / inorganique > Elément trace métallique ou composé inorganique (autre)",
                            ),
                            (
                                "Dioxines et PCB",
                                "Polluant organique persistant > Dioxines et PCB",
                            ),
                            (
                                "Substances perfluoroalkylées (PFAS)",
                                "Polluant organique persistant > Substances perfluoroalkylées (PFAS)",
                            ),
                            (
                                "Polluant organique persistant (autre)",
                                "Polluant organique persistant > Polluant organique persistant (autre)",
                            ),
                            ("Radionucléides", "Contaminant physique > Radionucléides"),
                            (
                                "Résidu médicament - Groupe A - substance interdite ou non autorisée, traitement illégal",
                                "Médicament vétérinaire > Résidu médicament - Groupe A - substance interdite ou non autorisée, traitement illégal",
                            ),
                            (
                                "Résidu médicament - Groupe B - substance autorisée",
                                "Médicament vétérinaire > Résidu médicament - Groupe B - substance autorisée",
                            ),
                            (
                                "Résidu de médicament vétérinaire (autre ou indéterminé)",
                                "Médicament vétérinaire > Résidu de médicament vétérinaire (autre ou indéterminé)",
                            ),
                            (
                                "Résidu de Pesticide Biocide",
                                "Pesticide Biocide > Résidu de Pesticide Biocide",
                            ),
                            (
                                "Novel food",
                                "Denrée ou ingrédient non autorisé ou dangereux > Novel food",
                            ),
                            (
                                "Novel food - CBD/autres cannabinoïdes",
                                "Denrée ou ingrédient non autorisé ou dangereux > Novel food > CBD/autres cannabinoïdes",
                            ),
                            (
                                "Novel food - Surdosage / AMM",
                                "Denrée ou ingrédient non autorisé ou dangereux > Novel food > Surdosage / AMM",
                            ),
                            (
                                "Novel food - Non-respect catégorie denrée / AMM",
                                "Denrée ou ingrédient non autorisé ou dangereux > Novel food > Non-respect catégorie denrée / AMM",
                            ),
                            (
                                "Novel food - Non-respect population cible / AMM",
                                "Denrée ou ingrédient non autorisé ou dangereux > Novel food > Non-respect population cible / AMM",
                            ),
                            (
                                "OGM",
                                "Denrée ou ingrédient non autorisé ou dangereux > OGM",
                            ),
                            (
                                "OGM - Plantes GM",
                                "Denrée ou ingrédient non autorisé ou dangereux > OGM > Plantes GM",
                            ),
                            (
                                "OGM - Microorganismes GM",
                                "Denrée ou ingrédient non autorisé ou dangereux > OGM > Microorganismes GM",
                            ),
                            (
                                "OGM - Animaux GM",
                                "Denrée ou ingrédient non autorisé ou dangereux > OGM > Animaux GM",
                            ),
                            (
                                "Sildénafil",
                                "Denrée ou ingrédient non autorisé ou dangereux > Sildénafil",
                            ),
                            (
                                "Sibutramine",
                                "Denrée ou ingrédient non autorisé ou dangereux > Sibutramine",
                            ),
                            (
                                "Substance médicamenteuse (autre)",
                                "Denrée ou ingrédient non autorisé ou dangereux > Substance médicamenteuse (autre)",
                            ),
                            (
                                "Stupéfiant",
                                "Denrée ou ingrédient non autorisé ou dangereux > Stupéfiant",
                            ),
                            (
                                "Psychoactif",
                                "Denrée ou ingrédient non autorisé ou dangereux > Psychoactif",
                            ),
                            (
                                "Psychoactif - Muscimol",
                                "Denrée ou ingrédient non autorisé ou dangereux > Psychoactif > Muscimol (ou autre non médicament non stupéfiant non novel food)",
                            ),
                            (
                                "Substances interdites ou restriction (denrées enrichies)",
                                "Denrée ou ingrédient non autorisé ou dangereux > Substances interdites ou restriction (denrées enrichies)",
                            ),
                            (
                                "Surdosage nutriment",
                                "Denrée ou ingrédient non autorisé ou dangereux > Surdosage nutriment (vitamines, minéraux, autres / denrées enrichies ou CA)",
                            ),
                            (
                                "Complément alimentaire non télédéclaré",
                                "Denrée ou ingrédient non autorisé ou dangereux > Complément alimentaire non télédéclaré",
                            ),
                            ("Indéterminé", "Indéterminé > Indéterminé"),
                        ],
                        max_length=255,
                        verbose_name="Catégorie de danger",
                    ),
                ),
                (
                    "precision_danger",
                    models.CharField(blank=True, max_length=255, verbose_name="Précision danger"),
                ),
                (
                    "reference_souches",
                    models.CharField(blank=True, max_length=255, verbose_name="Références souches"),
                ),
                (
                    "reference_clusters",
                    models.CharField(blank=True, max_length=255, verbose_name="Références clusters"),
                ),
                ("evaluation", models.TextField(blank=True, verbose_name="Évaluation")),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("do_listeriose", "DO Listériose"),
                            ("cas_groupes", "Cas groupés"),
                            ("autre", "Signalement autre"),
                        ],
                        max_length=100,
                        verbose_name="Source",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                core.mixins.WithDocumentPermissionMixin,
                core.mixins.WithMessageUrlsMixin,
                core.mixins.EmailNotificationMixin,
                core.mixins.WithContactPermissionMixin,
                core.mixins.WithFreeLinkIdsMixin,
                models.Model,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="evenementproduit",
            name="type_evenement_source_constraint",
        ),
        migrations.AddField(
            model_name="etablissement",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="etablissements",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="etablissement",
            name="object_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="etablissement",
            name="evenement_produit",
        ),
        migrations.AlterField(
            model_name="etablissement",
            name="content_type",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="etablissements",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="etablissement",
            name="object_id",
            field=models.PositiveIntegerField(null=False),
        ),
        migrations.AlterField(
            model_name="evenementproduit",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("autocontrole_notifie_produit", "Autocontrôle notifié (produit)"),
                    (
                        "autocontrole_notifie_environnement",
                        "Autocontrôle notifié (environnement)",
                    ),
                    ("prelevement_pspc", "Prélèvement PSPC"),
                    ("autre_prelevement_officiel", "Autre prélèvement officiel"),
                    ("autre_constat_officiel", "Autre constat officiel"),
                    ("investigation_cas_humains", "Investigation de cas humains"),
                    ("signalement_consommateur", "Signalement consommateur"),
                    ("autre", "Signalement autre"),
                ],
                max_length=100,
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="evenementproduit",
            name="type_evenement",
            field=models.CharField(
                choices=[
                    ("alerte_produit_nationale", "Alerte produit nationale"),
                    ("alerte_produit_locale", "Alerte produit locale"),
                    ("non_alerte", "Non alerte"),
                    ("alerte_produit_ue", "Alerte produit UE/INT (RASFF)"),
                    ("non_alerte_ue", "Non alerte UE/INT (AAC)"),
                    ("autre_action_coordonnee", "Autre action coordonnée"),
                ],
                max_length=100,
                verbose_name="Type d'événement",
            ),
        ),
        migrations.AddField(
            model_name="investigationcashumain",
            name="contacts",
            field=models.ManyToManyField(blank=True, to="core.contact", verbose_name="Contacts"),
        ),
        migrations.AddField(
            model_name="investigationcashumain",
            name="createur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.structure",
                verbose_name="Structure créatrice",
            ),
        ),
    ]
