# Generated by Django 5.2.4 on 2025-09-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0033_alter_evenementproduit_type_evenement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenementproduit",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("autocontrole_notifie_produit", "Autocontrôle notifié (produit)"),
                    (
                        "autocontrole_notifie_environnement",
                        "Autocontrôle notifié (environnement)",
                    ),
                    ("prelevement_pspc", "Prélèvement PSPC (hors PCF)"),
                    (
                        "autre_prelevement_officiel",
                        "Prélèvement officiel autre (hors PCF)",
                    ),
                    ("autre_constat_officiel", "Autre constat officiel (hors PCF)"),
                    ("investigation_cas_humains", "Investigation de cas ou TIAC"),
                    ("signalement_consommateur", "Signalement de consommateur"),
                    ("notification_rasff", "Notification RASFF"),
                    ("notification_aac", "Notification AAC"),
                    ("tout_droit", "Tout droit"),
                    ("prelevement_pspc_pcf", "Prélèvement PSPC (en PCF)"),
                    (
                        "prelevement_officiel_autre",
                        "Prélèvement officiel autre (en PCF)",
                    ),
                    ("autre_constat_officiel_pcf", "Autre constat officiel (en PCF)"),
                    ("do_listeriose", "DO Listériose"),
                    ("cas_groupes", "Cas groupés"),
                    ("autre", "Signalement autre"),
                ],
                max_length=100,
                verbose_name="Source",
            ),
        ),
    ]
