# Generated by Django 5.2.5 on 2025-09-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0036_remove_evenementproduit_pam_requires_danger_bacterien_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenementproduit",
            name="categorie_produit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Fromage au lait cru", "Produit laitier > Fromage au lait cru"),
                    (
                        "Fromage lait cru à pâtes fraiches (caillé, fromage blanc, faisselle, tomme fraiche, brousse…)",
                        "Produit laitier > Fromage au lait cru > Fromage lait cru à pâtes fraiches (caillé, fromage blanc, faisselle, tomme fraiche, brousse…)",
                    ),
                    (
                        "Fromage lait cru à pâtes lactiques (chèvre frais, cendré, affiné, chaource, neuchatel...)",
                        "Produit laitier > Fromage au lait cru > Fromage lait cru à pâtes lactiques (chèvre frais, cendré, affiné, chaource, neuchatel...)",
                    ),
                    (
                        "Fromage lait cru à pâtes molles à croûte fleurie (camembert, brie…)",
                        "Produit laitier > Fromage au lait cru > Fromage lait cru à pâtes molles à croûte fleurie (camembert, brie…)",
                    ),
                    (
                        "Fromage lait cru à pâtes molles à croûte lavée (munster, pont-lévêque…)",
                        "Produit laitier > Fromage au lait cru > Fromage lait cru à pâtes molles à croûte lavée (munster, pont-lévêque…)",
                    ),
                    (
                        "Fromage lait cru à pâtes pressées non cuites (reblochon, saint-nectaire, cantal, ossau-iraty…)",
                        "Produit laitier > Fromage au lait cru > Fromage lait cru à pâtes pressées non cuites (reblochon, saint-nectaire, cantal, ossau-iraty…)",
                    ),
                    (
                        "Fromage lait cru à pâtes pressées cuites (comté, gruyère, emmental, parmesan…)",
                        "Produit laitier > Fromage au lait cru > Fromage lait cru à pâtes pressées cuites (comté, gruyère, emmental, parmesan…)",
                    ),
                    (
                        "Fromage au lait traité ou transformé",
                        "Produit laitier > Fromage au lait traité ou transformé",
                    ),
                    (
                        "Fromage lait traité (microfiltré, pasteurisé, stérilisé)",
                        "Produit laitier > Fromage au lait traité ou transformé > Fromage lait traité (microfiltré, pasteurisé, stérilisé)",
                    ),
                    (
                        "Fromage fondu, tartinade et autre (cancoillotte...)",
                        "Produit laitier > Fromage au lait traité ou transformé > Fromage fondu, tartinade et autre (cancoillotte...)",
                    ),
                    ("Fromage indéterminé", "Produit laitier > Fromage indéterminé"),
                    (
                        "Yaourt et produit laitier fermenté",
                        "Produit laitier > Yaourt et produit laitier fermenté",
                    ),
                    (
                        "Yaourt",
                        "Produit laitier > Yaourt et produit laitier fermenté > Yaourt",
                    ),
                    (
                        "Lait fermenté, boisson lactée fermentée, kefir de lait",
                        "Produit laitier > Yaourt et produit laitier fermenté > Lait fermenté, boisson lactée fermentée, kefir de lait",
                    ),
                    (
                        "Matière grasse du lait",
                        "Produit laitier > Matière grasse du lait",
                    ),
                    (
                        "Crème crue",
                        "Produit laitier > Matière grasse du lait > Crème crue",
                    ),
                    (
                        "Crème traitée (pasteurisée, stérilisée)",
                        "Produit laitier > Matière grasse du lait > Crème traitée (pasteurisée, stérilisée)",
                    ),
                    (
                        "Beurre cru",
                        "Produit laitier > Matière grasse du lait > Beurre cru",
                    ),
                    (
                        "Beurre traité (pasteurisé, stérilisé) et MGLA",
                        "Produit laitier > Matière grasse du lait > Beurre traité (pasteurisé, stérilisé) et MGLA",
                    ),
                    ("Lait", "Produit laitier > Lait"),
                    (
                        "Lait cru (matière première ou de consommation)",
                        "Produit laitier > Lait > Lait cru (matière première ou de consommation)",
                    ),
                    (
                        "Lait traité (microfiltré, pasteurisé, stérilisé) (hors infantile)",
                        "Produit laitier > Lait > Lait traité (microfiltré, pasteurisé, stérilisé) (hors infantile)",
                    ),
                    (
                        "Poudre de lait et dérivés (poudre de lactosérum, caséïne, lactose, minéraux...) (hors infantile)",
                        "Produit laitier > Lait > Poudre de lait et dérivés (poudre de lactosérum, caséïne, lactose, minéraux...) (hors infantile)",
                    ),
                    ("Concentré laitier", "Produit laitier > Lait > Concentré laitier"),
                    ("Lactosérum liquide", "Produit laitier > Lactosérum liquide"),
                    (
                        "Carcasse, viande, os et abat rouge",
                        "Produit carné > Carcasse, viande, os et abat rouge",
                    ),
                    (
                        "V - Bovin",
                        "Produit carné > Carcasse, viande, os et abat rouge > V - Bovin",
                    ),
                    (
                        "V - Ovin",
                        "Produit carné > Carcasse, viande, os et abat rouge > V - Ovin",
                    ),
                    (
                        "V - Caprin",
                        "Produit carné > Carcasse, viande, os et abat rouge > V - Caprin",
                    ),
                    (
                        "V - Porcin",
                        "Produit carné > Carcasse, viande, os et abat rouge > V - Porcin",
                    ),
                    (
                        "V - Chevalin",
                        "Produit carné > Carcasse, viande, os et abat rouge > V - Chevalin",
                    ),
                    (
                        "V - Grand gibier (cerf, chevreuil, sanglier…)",
                        "Produit carné > Carcasse, viande, os et abat rouge > V - Grand gibier (cerf, chevreuil, sanglier…)",
                    ),
                    (
                        "V - De boucherie (indéterminé ou mélange) (yc camélidé, bovidé)",
                        "Produit carné > Carcasse, viande, os et abat rouge > V - De boucherie (indéterminé ou mélange) (yc camélidé, bovidé)",
                    ),
                    (
                        "V - Volaille (yc autruche)",
                        "Produit carné > Carcasse, viande, os et abat rouge > V - Volaille (yc autruche)",
                    ),
                    (
                        "V - Lapin",
                        "Produit carné > Carcasse, viande, os et abat rouge > V - Lapin",
                    ),
                    (
                        "V - Reptile",
                        "Produit carné > Carcasse, viande, os et abat rouge > V - Reptile",
                    ),
                    (
                        "V - De volaille, lagomorphe ou reptile (indéterminé ou mélange)",
                        "Produit carné > Carcasse, viande, os et abat rouge > V - De volaille, lagomorphe ou reptile (indéterminé ou mélange)",
                    ),
                    (
                        "V - Petit gibier (mammifères - lapin, lièvre...)",
                        "Produit carné > Carcasse, viande, os et abat rouge > V - Petit gibier (mammifères - lapin, lièvre...)",
                    ),
                    (
                        "V - Petit gibier (oiseaux - caille, perdrix, faisan...)",
                        "Produit carné > Carcasse, viande, os et abat rouge > V - Petit gibier (oiseaux - caille, perdrix, faisan...)",
                    ),
                    (
                        "V - De gibier (indéterminé ou mélange)",
                        "Produit carné > Carcasse, viande, os et abat rouge > V - De gibier (indéterminé ou mélange)",
                    ),
                    ("Viande hachée", "Produit carné > Viande hachée"),
                    ("VH - Bovin", "Produit carné > Viande hachée > VH - Bovin"),
                    ("VH - Ovin", "Produit carné > Viande hachée > VH - Ovin"),
                    ("VH - Caprin", "Produit carné > Viande hachée > VH - Caprin"),
                    ("VH - Porcin", "Produit carné > Viande hachée > VH - Porcin"),
                    ("VH - Chevalin", "Produit carné > Viande hachée > VH - Chevalin"),
                    (
                        "VH - Grand gibier (cerf, chevreuil, sanglier…)",
                        "Produit carné > Viande hachée > VH - Grand gibier (cerf, chevreuil, sanglier…)",
                    ),
                    (
                        "VH - De boucherie (indéterminé ou mélange) (yc camélidé, bovidé)",
                        "Produit carné > Viande hachée > VH - De boucherie (indéterminé ou mélange) (yc camélidé, bovidé)",
                    ),
                    (
                        "VH - Volaille (yc autruche)",
                        "Produit carné > Viande hachée > VH - Volaille (yc autruche)",
                    ),
                    ("VH - Lapin", "Produit carné > Viande hachée > VH - Lapin"),
                    ("VH - Reptile", "Produit carné > Viande hachée > VH - Reptile"),
                    (
                        "VH - De volaille, lagomorphe ou reptile (indéterminé ou mélange)",
                        "Produit carné > Viande hachée > VH - De volaille, lagomorphe ou reptile (indéterminé ou mélange)",
                    ),
                    (
                        "VH - Petit gibier (mammifères - lapin, lièvre...)",
                        "Produit carné > Viande hachée > VH - Petit gibier (mammifères - lapin, lièvre...)",
                    ),
                    (
                        "VH - Petit gibier (oiseaux - caille, perdrix, faisan...)",
                        "Produit carné > Viande hachée > VH - Petit gibier (oiseaux - caille, perdrix, faisan...)",
                    ),
                    (
                        "VH - De gibier (indéterminé ou mélange)",
                        "Produit carné > Viande hachée > VH - De gibier (indéterminé ou mélange)",
                    ),
                    (
                        "VSM - viande séparée mécaniquement",
                        "Produit carné > VSM - viande séparée mécaniquement",
                    ),
                    (
                        "VSM - Bovin",
                        "Produit carné > VSM - viande séparée mécaniquement > VSM - Bovin",
                    ),
                    (
                        "VSM - Ovin",
                        "Produit carné > VSM - viande séparée mécaniquement > VSM - Ovin",
                    ),
                    (
                        "VSM - Caprin",
                        "Produit carné > VSM - viande séparée mécaniquement > VSM - Caprin",
                    ),
                    (
                        "VSM - Porcin",
                        "Produit carné > VSM - viande séparée mécaniquement > VSM - Porcin",
                    ),
                    (
                        "VSM - Chevalin",
                        "Produit carné > VSM - viande séparée mécaniquement > VSM - Chevalin",
                    ),
                    (
                        "VSM - Grand gibier (cerf, chevreuil, sanglier…)",
                        "Produit carné > VSM - viande séparée mécaniquement > VSM - Grand gibier (cerf, chevreuil, sanglier…)",
                    ),
                    (
                        "VSM - De boucherie (indéterminé ou mélange) (yc camélidé, bovidé)",
                        "Produit carné > VSM - viande séparée mécaniquement > VSM - De boucherie (indéterminé ou mélange) (yc camélidé, bovidé)",
                    ),
                    (
                        "VSM - Volaille (yc autruche)",
                        "Produit carné > VSM - viande séparée mécaniquement > VSM - Volaille (yc autruche)",
                    ),
                    (
                        "VSM - Lapin",
                        "Produit carné > VSM - viande séparée mécaniquement > VSM - Lapin",
                    ),
                    (
                        "VSM - Reptile",
                        "Produit carné > VSM - viande séparée mécaniquement > VSM - Reptile",
                    ),
                    (
                        "VSM - De volaille, lagomorphe ou reptile (indéterminé ou mélange)",
                        "Produit carné > VSM - viande séparée mécaniquement > VSM - De volaille, lagomorphe ou reptile (indéterminé ou mélange)",
                    ),
                    (
                        "VSM - Petit gibier (mammifères - lapin, lièvre...)",
                        "Produit carné > VSM - viande séparée mécaniquement > VSM - Petit gibier (mammifères - lapin, lièvre...)",
                    ),
                    (
                        "VSM - Petit gibier (oiseaux - caille, perdrix, faisan...)",
                        "Produit carné > VSM - viande séparée mécaniquement > VSM - Petit gibier (oiseaux - caille, perdrix, faisan...)",
                    ),
                    (
                        "VSM - De gibier (indéterminé ou mélange)",
                        "Produit carné > VSM - viande séparée mécaniquement > VSM - De gibier (indéterminé ou mélange)",
                    ),
                    (
                        "Abat blanc (non cuit, non saumuré si porc)",
                        "Produit carné > Abat blanc (non cuit, non saumuré si porc)",
                    ),
                    (
                        "ABATB - Bovin",
                        "Produit carné > Abat blanc (non cuit, non saumuré si porc) > ABATB - Bovin",
                    ),
                    (
                        "ABATB - Ovin",
                        "Produit carné > Abat blanc (non cuit, non saumuré si porc) > ABATB - Ovin",
                    ),
                    (
                        "ABATB - Caprin",
                        "Produit carné > Abat blanc (non cuit, non saumuré si porc) > ABATB - Caprin",
                    ),
                    (
                        "ABATB - Porcin",
                        "Produit carné > Abat blanc (non cuit, non saumuré si porc) > ABATB - Porcin",
                    ),
                    (
                        "ABATB - Chevalin",
                        "Produit carné > Abat blanc (non cuit, non saumuré si porc) > ABATB - Chevalin",
                    ),
                    (
                        "ABATB - Grand gibier (cerf, chevreuil, sanglier…)",
                        "Produit carné > Abat blanc (non cuit, non saumuré si porc) > ABATB - Grand gibier (cerf, chevreuil, sanglier…)",
                    ),
                    (
                        "ABATB - De boucherie (indéterminé ou mélange) (yc camélidé, bovidé)",
                        "Produit carné > Abat blanc (non cuit, non saumuré si porc) > ABATB - De boucherie (indéterminé ou mélange) (yc camélidé, bovidé)",
                    ),
                    (
                        "ABATB - Volaille (yc autruche)",
                        "Produit carné > Abat blanc (non cuit, non saumuré si porc) > ABATB - Volaille (yc autruche)",
                    ),
                    (
                        "ABATB - Lapin",
                        "Produit carné > Abat blanc (non cuit, non saumuré si porc) > ABATB - Lapin",
                    ),
                    (
                        "ABATB - Reptile",
                        "Produit carné > Abat blanc (non cuit, non saumuré si porc) > ABATB - Reptile",
                    ),
                    (
                        "ABATB - De volaille, lagomorphe ou reptile (indéterminé ou mélange)",
                        "Produit carné > Abat blanc (non cuit, non saumuré si porc) > ABATB - De volaille, lagomorphe ou reptile (indéterminé ou mélange)",
                    ),
                    (
                        "ABATB - Petit gibier (mammifères - lapin, lièvre...)",
                        "Produit carné > Abat blanc (non cuit, non saumuré si porc) > ABATB - Petit gibier (mammifères - lapin, lièvre...)",
                    ),
                    (
                        "ABATB - Petit gibier (oiseaux - caille, perdrix, faisan...)",
                        "Produit carné > Abat blanc (non cuit, non saumuré si porc) > ABATB - Petit gibier (oiseaux - caille, perdrix, faisan...)",
                    ),
                    (
                        "ABATB - De gibier (indéterminé ou mélange)",
                        "Produit carné > Abat blanc (non cuit, non saumuré si porc) > ABATB - De gibier (indéterminé ou mélange)",
                    ),
                    ("Boyau traité", "Produit carné > Boyau traité"),
                    (
                        "PV - préparation de viande",
                        "Produit carné > PV - préparation de viande",
                    ),
                    (
                        "PV - Bovin",
                        "Produit carné > PV - préparation de viande > PV - Bovin",
                    ),
                    (
                        "PV - Ovin",
                        "Produit carné > PV - préparation de viande > PV - Ovin",
                    ),
                    (
                        "PV - Caprin",
                        "Produit carné > PV - préparation de viande > PV - Caprin",
                    ),
                    (
                        "PV - Porcin",
                        "Produit carné > PV - préparation de viande > PV - Porcin",
                    ),
                    (
                        "PV - Chevalin",
                        "Produit carné > PV - préparation de viande > PV - Chevalin",
                    ),
                    (
                        "PV - Grand gibier (cerf, chevreuil, sanglier…)",
                        "Produit carné > PV - préparation de viande > PV - Grand gibier (cerf, chevreuil, sanglier…)",
                    ),
                    (
                        "PV - De boucherie (indéterminé ou mélange) (yc camélidé, bovidé)",
                        "Produit carné > PV - préparation de viande > PV - De boucherie (indéterminé ou mélange) (yc camélidé, bovidé)",
                    ),
                    (
                        "PV - Volaille (yc autruche)",
                        "Produit carné > PV - préparation de viande > PV - Volaille (yc autruche)",
                    ),
                    (
                        "PV - Lapin",
                        "Produit carné > PV - préparation de viande > PV - Lapin",
                    ),
                    (
                        "PV - Reptile",
                        "Produit carné > PV - préparation de viande > PV - Reptile",
                    ),
                    (
                        "PV - De volaille, lagomorphe ou reptile (indéterminé ou mélange)",
                        "Produit carné > PV - préparation de viande > PV - De volaille, lagomorphe ou reptile (indéterminé ou mélange)",
                    ),
                    (
                        "PV - Petit gibier (mammifères - lapin, lièvre...)",
                        "Produit carné > PV - préparation de viande > PV - Petit gibier (mammifères - lapin, lièvre...)",
                    ),
                    (
                        "PV - Petit gibier (oiseaux - caille, perdrix, faisan...)",
                        "Produit carné > PV - préparation de viande > PV - Petit gibier (oiseaux - caille, perdrix, faisan...)",
                    ),
                    (
                        "PV - De gibier (indéterminé ou mélange)",
                        "Produit carné > PV - préparation de viande > PV - De gibier (indéterminé ou mélange)",
                    ),
                    (
                        "PABV cru - produit à base de viande cru",
                        "Produit carné > PABV cru - produit à base de viande cru",
                    ),
                    (
                        "PABV cru - Bovin",
                        "Produit carné > PABV cru - produit à base de viande cru > PABV cru - Bovin",
                    ),
                    (
                        "PABV cru - Ovin",
                        "Produit carné > PABV cru - produit à base de viande cru > PABV cru - Ovin",
                    ),
                    (
                        "PABV cru - Caprin",
                        "Produit carné > PABV cru - produit à base de viande cru > PABV cru - Caprin",
                    ),
                    (
                        "PABV cru - Porcin",
                        "Produit carné > PABV cru - produit à base de viande cru > PABV cru - Porcin",
                    ),
                    (
                        "PABV cru - Chevalin",
                        "Produit carné > PABV cru - produit à base de viande cru > PABV cru - Chevalin",
                    ),
                    (
                        "PABV cru - Grand gibier (cerf, chevreuil, sanglier…)",
                        "Produit carné > PABV cru - produit à base de viande cru > PABV cru - Grand gibier (cerf, chevreuil, sanglier…)",
                    ),
                    (
                        "PABV cru - De boucherie (indéterminé ou mélange) (yc camélidé, bovidé)",
                        "Produit carné > PABV cru - produit à base de viande cru > PABV cru - De boucherie (indéterminé ou mélange) (yc camélidé, bovidé)",
                    ),
                    (
                        "PABV cru - Volaille (yc autruche)",
                        "Produit carné > PABV cru - produit à base de viande cru > PABV cru - Volaille (yc autruche)",
                    ),
                    (
                        "PABV cru - Lapin",
                        "Produit carné > PABV cru - produit à base de viande cru > PABV cru - Lapin",
                    ),
                    (
                        "PABV cru - Reptile",
                        "Produit carné > PABV cru - produit à base de viande cru > PABV cru - Reptile",
                    ),
                    (
                        "PABV cru - De volaille, lagomorphe ou reptile (indéterminé ou mélange)",
                        "Produit carné > PABV cru - produit à base de viande cru > PABV cru - De volaille, lagomorphe ou reptile (indéterminé ou mélange)",
                    ),
                    (
                        "PABV cru - Petit gibier (mammifères - lapin, lièvre...)",
                        "Produit carné > PABV cru - produit à base de viande cru > PABV cru - Petit gibier (mammifères - lapin, lièvre...)",
                    ),
                    (
                        "PABV cru - Petit gibier (oiseaux - caille, perdrix, faisan...)",
                        "Produit carné > PABV cru - produit à base de viande cru > PABV cru - Petit gibier (oiseaux - caille, perdrix, faisan...)",
                    ),
                    (
                        "PABV cru - De gibier (indéterminé ou mélange)",
                        "Produit carné > PABV cru - produit à base de viande cru > PABV cru - De gibier (indéterminé ou mélange)",
                    ),
                    (
                        "PABV cuit - produit à base de viande cuit",
                        "Produit carné > PABV cuit - produit à base de viande cuit",
                    ),
                    (
                        "PABV cuit - Bovin",
                        "Produit carné > PABV cuit - produit à base de viande cuit > PABV cuit - Bovin",
                    ),
                    (
                        "PABV cuit - Ovin",
                        "Produit carné > PABV cuit - produit à base de viande cuit > PABV cuit - Ovin",
                    ),
                    (
                        "PABV cuit - Caprin",
                        "Produit carné > PABV cuit - produit à base de viande cuit > PABV cuit - Caprin",
                    ),
                    (
                        "PABV cuit - Porcin",
                        "Produit carné > PABV cuit - produit à base de viande cuit > PABV cuit - Porcin",
                    ),
                    (
                        "PABV cuit - Chevalin",
                        "Produit carné > PABV cuit - produit à base de viande cuit > PABV cuit - Chevalin",
                    ),
                    (
                        "PABV cuit - Grand gibier (cerf, chevreuil, sanglier…)",
                        "Produit carné > PABV cuit - produit à base de viande cuit > PABV cuit - Grand gibier (cerf, chevreuil, sanglier…)",
                    ),
                    (
                        "PABV cuit - De boucherie (indéterminé ou mélange) (yc camélidé, bovidé)",
                        "Produit carné > PABV cuit - produit à base de viande cuit > PABV cuit - De boucherie (indéterminé ou mélange) (yc camélidé, bovidé)",
                    ),
                    (
                        "PABV cuit - Volaille (yc autruche)",
                        "Produit carné > PABV cuit - produit à base de viande cuit > PABV cuit - Volaille (yc autruche)",
                    ),
                    (
                        "PABV cuit - Lapin",
                        "Produit carné > PABV cuit - produit à base de viande cuit > PABV cuit - Lapin",
                    ),
                    (
                        "PABV cuit - Reptile",
                        "Produit carné > PABV cuit - produit à base de viande cuit > PABV cuit - Reptile",
                    ),
                    (
                        "PABV cuit - De volaille, lagomorphe ou reptile (indéterminé ou mélange)",
                        "Produit carné > PABV cuit - produit à base de viande cuit > PABV cuit - De volaille, lagomorphe ou reptile (indéterminé ou mélange)",
                    ),
                    (
                        "PABV cuit - Petit gibier (mammifères - lapin, lièvre...)",
                        "Produit carné > PABV cuit - produit à base de viande cuit > PABV cuit - Petit gibier (mammifères - lapin, lièvre...)",
                    ),
                    (
                        "PABV cuit - Petit gibier (oiseaux - caille, perdrix, faisan...)",
                        "Produit carné > PABV cuit - produit à base de viande cuit > PABV cuit - Petit gibier (oiseaux - caille, perdrix, faisan...)",
                    ),
                    (
                        "PABV cuit - De gibier (indéterminé ou mélange)",
                        "Produit carné > PABV cuit - produit à base de viande cuit > PABV cuit - De gibier (indéterminé ou mélange)",
                    ),
                    (
                        "Etat de transformation indéterminé (catégorie à éviter)",
                        "Produit carné > Etat de transformation indéterminé (catégorie à éviter)",
                    ),
                    ("Produit vivant", "Produit aquatique > Produit vivant"),
                    ("Poisson", "Produit aquatique > Produit vivant > Poisson"),
                    ("Céphalopode", "Produit aquatique > Produit vivant > Céphalopode"),
                    (
                        "Coquillage (bivalve, gastéropode marin)",
                        "Produit aquatique > Produit vivant > Coquillage (bivalve, gastéropode marin)",
                    ),
                    ("Crustacé", "Produit aquatique > Produit vivant > Crustacé"),
                    (
                        "Tunicier, échinoderme (oursin)",
                        "Produit aquatique > Produit vivant > Tunicier, échinoderme (oursin)",
                    ),
                    ("Escargot", "Produit aquatique > Produit vivant > Escargot"),
                    ("Grenouille", "Produit aquatique > Produit vivant > Grenouille"),
                    (
                        "Algue (macroalgue)",
                        "Produit aquatique > Produit vivant > Algue (macroalgue)",
                    ),
                    (
                        "Microalgue (spiruline)",
                        "Produit aquatique > Produit vivant > Microalgue (spiruline)",
                    ),
                    (
                        "Produit cru entier, fileté, coupé, os, peau, œuf",
                        "Produit aquatique > Produit cru entier, fileté, coupé, os, peau, œuf",
                    ),
                    (
                        "PC - Poisson",
                        "Produit aquatique > Produit cru entier, fileté, coupé, os, peau, œuf > PC - Poisson",
                    ),
                    (
                        "PC - Céphalopode",
                        "Produit aquatique > Produit cru entier, fileté, coupé, os, peau, œuf > PC - Céphalopode",
                    ),
                    (
                        "PC - Coquillage (bivalve, gastéropode marin)",
                        "Produit aquatique > Produit cru entier, fileté, coupé, os, peau, œuf > PC - Coquillage (bivalve, gastéropode marin)",
                    ),
                    (
                        "PC - Crustacé",
                        "Produit aquatique > Produit cru entier, fileté, coupé, os, peau, œuf > PC - Crustacé",
                    ),
                    (
                        "PC - Tunicier, échinoderme (oursin)",
                        "Produit aquatique > Produit cru entier, fileté, coupé, os, peau, œuf > PC - Tunicier, échinoderme (oursin)",
                    ),
                    (
                        "PC - Escargot",
                        "Produit aquatique > Produit cru entier, fileté, coupé, os, peau, œuf > PC - Escargot",
                    ),
                    (
                        "PC - Grenouille",
                        "Produit aquatique > Produit cru entier, fileté, coupé, os, peau, œuf > PC - Grenouille",
                    ),
                    (
                        "Produit fermenté, fumé, salé, mariné, cuit",
                        "Produit aquatique > Produit fermenté, fumé, salé, mariné, cuit",
                    ),
                    (
                        "PT - Poisson",
                        "Produit aquatique > Produit fermenté, fumé, salé, mariné, cuit > PT - Poisson",
                    ),
                    (
                        "PT - Céphalopode",
                        "Produit aquatique > Produit fermenté, fumé, salé, mariné, cuit > PT - Céphalopode",
                    ),
                    (
                        "PT - Coquillage (bivalve, gastéropode marin)",
                        "Produit aquatique > Produit fermenté, fumé, salé, mariné, cuit > PT - Coquillage (bivalve, gastéropode marin)",
                    ),
                    (
                        "PT - Crustacé",
                        "Produit aquatique > Produit fermenté, fumé, salé, mariné, cuit > PT - Crustacé",
                    ),
                    (
                        "PT - Tunicier, échinoderme (oursin)",
                        "Produit aquatique > Produit fermenté, fumé, salé, mariné, cuit > PT - Tunicier, échinoderme (oursin)",
                    ),
                    (
                        "PT - Escargot",
                        "Produit aquatique > Produit fermenté, fumé, salé, mariné, cuit > PT - Escargot",
                    ),
                    (
                        "PT - Grenouille",
                        "Produit aquatique > Produit fermenté, fumé, salé, mariné, cuit > PT - Grenouille",
                    ),
                    (
                        "PT - Algue (macroalgue)",
                        "Produit aquatique > Produit fermenté, fumé, salé, mariné, cuit > PT - Algue (macroalgue)",
                    ),
                    (
                        "PT - Microalgue (spiruline)",
                        "Produit aquatique > Produit fermenté, fumé, salé, mariné, cuit > PT - Microalgue (spiruline)",
                    ),
                    (
                        "Produit séparé mécaniquement",
                        "Produit aquatique > Produit séparé mécaniquement",
                    ),
                    (
                        "PSM - Poisson",
                        "Produit aquatique > Produit séparé mécaniquement > PSM - Poisson",
                    ),
                    (
                        "PSM - Céphalopode",
                        "Produit aquatique > Produit séparé mécaniquement > PSM - Céphalopode",
                    ),
                    (
                        "PSM - Coquillage (bivalve, gastéropode marin)",
                        "Produit aquatique > Produit séparé mécaniquement > PSM - Coquillage (bivalve, gastéropode marin)",
                    ),
                    (
                        "PSM - Crustacé",
                        "Produit aquatique > Produit séparé mécaniquement > PSM - Crustacé",
                    ),
                    (
                        "PSM - Tunicier, échinoderme (oursin)",
                        "Produit aquatique > Produit séparé mécaniquement > PSM - Tunicier, échinoderme (oursin)",
                    ),
                    (
                        "PSM - Escargot",
                        "Produit aquatique > Produit séparé mécaniquement > PSM - Escargot",
                    ),
                    (
                        "PSM - Grenouille",
                        "Produit aquatique > Produit séparé mécaniquement > PSM - Grenouille",
                    ),
                    ("Oeuf coquille", "Produit d'œuf > Oeuf coquille"),
                    ("Ovoproduit", "Produit d'œuf > Ovoproduit"),
                    (
                        "Coule d'œuf fraîche non pasteurisée (entier, jaune, blanc)",
                        "Produit d'œuf > Ovoproduit > Coule d'œuf fraîche non pasteurisée (entier, jaune, blanc)",
                    ),
                    (
                        "Oeuf liquide pasteurisé (jaune, blanc, entier)",
                        "Produit d'œuf > Ovoproduit > Oeuf liquide pasteurisé (jaune, blanc, entier)",
                    ),
                    ("Poudre d'oeuf", "Produit d'œuf > Ovoproduit > Poudre d'oeuf"),
                    (
                        "Oeufs durs (écalés ou non) et ovoproduits durcis (barre, omelette nature)",
                        "Produit d'œuf > Ovoproduit > Oeufs durs (écalés ou non) et ovoproduits durcis (barre, omelette nature)",
                    ),
                    (
                        "Produit de la ruche",
                        "Autre produit animal > Produit de la ruche",
                    ),
                    (
                        "Miel (hors bonbon, hydromel)",
                        "Autre produit animal > Produit de la ruche > Miel (hors bonbon, hydromel)",
                    ),
                    (
                        "Pollen, propolys, gelée royale, rayon",
                        "Autre produit animal > Produit de la ruche > Pollen, propolys, gelée royale, rayon",
                    ),
                    ("Produit d'insecte", "Autre produit animal > Produit d'insecte"),
                    ("Collagène", "Autre produit animal > Collagène"),
                    (
                        "Gélatine (yc capsule)",
                        "Autre produit animal > Gélatine (yc capsule)",
                    ),
                    (
                        "Graisse et fonte d'origine animale (hors beurre et crème)",
                        "Autre produit animal > Graisse et fonte d'origine animale (hors beurre et crème)",
                    ),
                    (
                        "Produits raffinés d'origine animale (hors complément alimentaire)",
                        "Autre produit animal > Produits raffinés d'origine animale (hors complément alimentaire)",
                    ),
                    (
                        "Huile de poisson (hors feed)",
                        "Autre produit animal > Produits raffinés d'origine animale (hors complément alimentaire) > Huile de poisson (hors feed)",
                    ),
                    (
                        "Substitut de lait (hors infantile)",
                        "Analogue végétal > Substitut de lait (hors infantile)",
                    ),
                    ("Substitut de fromage", "Analogue végétal > Substitut de fromage"),
                    (
                        "Substitut de dessert lacté, de yaourt",
                        "Analogue végétal > Substitut de dessert lacté, de yaourt",
                    ),
                    (
                        "Subtitut de produit carné",
                        "Analogue végétal > Subtitut de produit carné",
                    ),
                    (
                        "Subtitut de produit aquatique",
                        "Analogue végétal > Subtitut de produit aquatique",
                    ),
                    ("Substitut d'oeuf", "Analogue végétal > Substitut d'oeuf"),
                    (
                        "Sandwich (avec ou sans DAOA)",
                        "Composé ou cuisiné > Sandwich (avec ou sans DAOA)",
                    ),
                    (
                        "Pizza (avec ou sans DAOA)",
                        "Composé ou cuisiné > Pizza (avec ou sans DAOA)",
                    ),
                    (
                        "Tourte, tarte salée (avec ou sans DAOA)",
                        "Composé ou cuisiné > Tourte, tarte salée (avec ou sans DAOA)",
                    ),
                    (
                        "Assortiment, amuse-bouches (avec ou sans DAOA)",
                        "Composé ou cuisiné > Assortiment, amuse-bouches (avec ou sans DAOA)",
                    ),
                    (
                        "Nouille, pâte, pâte à tarte, pâte à crêpe (avec œuf)",
                        "Composé ou cuisiné > Nouille, pâte, pâte à tarte, pâte à crêpe (avec œuf)",
                    ),
                    (
                        "Plat à base de salade (crudité ou cuidité, avec ou sans DAOA)",
                        "Composé ou cuisiné > Plat à base de salade (crudité ou cuidité, avec ou sans DAOA)",
                    ),
                    (
                        "Plat à base de pâte, de riz ou d’autre céréale (yc ravioli)",
                        "Composé ou cuisiné > Plat à base de pâte, de riz ou d’autre céréale (yc ravioli)",
                    ),
                    (
                        "Plat à base de viande",
                        "Composé ou cuisiné > Plat à base de viande",
                    ),
                    (
                        "Plat à base de poisson et fruit de mer (yc soupe)",
                        "Composé ou cuisiné > Plat à base de poisson et fruit de mer (yc soupe)",
                    ),
                    ("Plat à base d'œuf", "Composé ou cuisiné > Plat à base d'œuf"),
                    (
                        "Plat à base de fromage",
                        "Composé ou cuisiné > Plat à base de fromage",
                    ),
                    (
                        "Plat à base de légume (yc soupe)",
                        "Composé ou cuisiné > Plat à base de légume (yc soupe)",
                    ),
                    (
                        "Plat mixte de divers végétaux, œuf, viande, poisson et/ou fromage (yc en poudre) (hors infantile)",
                        "Composé ou cuisiné > Plat mixte de divers végétaux, œuf, viande, poisson et/ou fromage (yc en poudre) (hors infantile)",
                    ),
                    (
                        "Plat indéterminé (catégorie à éviter)",
                        "Composé ou cuisiné > Plat indéterminé (catégorie à éviter)",
                    ),
                    (
                        "Entremet lacté, crème, mousse",
                        "Entremet salé, dessert ou confiserie > Entremet lacté, crème, mousse",
                    ),
                    (
                        "Sorbet, glace, crème glacée",
                        "Entremet salé, dessert ou confiserie > Sorbet, glace, crème glacée",
                    ),
                    (
                        "Entremet pâtissier, pâtisserie, tarte fraîche (yc en poudre)",
                        "Entremet salé, dessert ou confiserie > Entremet pâtissier, pâtisserie, tarte fraîche (yc en poudre)",
                    ),
                    (
                        "Biscuit sec, barre",
                        "Entremet salé, dessert ou confiserie > Biscuit sec, barre",
                    ),
                    (
                        "Pâte à tartiner composée (hors simple pâte d'oléagineux) (yc confiture de lait)",
                        "Entremet salé, dessert ou confiserie > Pâte à tartiner composée (hors simple pâte d'oléagineux) (yc confiture de lait)",
                    ),
                    (
                        "Mélange petit déjeuner (muesli) (hors simple céréale)",
                        "Entremet salé, dessert ou confiserie > Mélange petit déjeuner (muesli) (hors simple céréale)",
                    ),
                    (
                        "Bonbon, chewing gum, caramel (hors simple fruit confit, hors complément alimentaire)",
                        "Entremet salé, dessert ou confiserie > Bonbon, chewing gum, caramel (hors simple fruit confit, hors complément alimentaire)",
                    ),
                    (
                        "Chocolat (bouchée, tablette) (hors boisson)",
                        "Entremet salé, dessert ou confiserie > Chocolat (bouchée, tablette) (hors boisson)",
                    ),
                    (
                        "Huile végétale",
                        "Noix, graine, grain et dérivé > Huile végétale",
                    ),
                    ("Margarine", "Noix, graine, grain et dérivé > Margarine"),
                    (
                        "Fruit à coque (amande, noisette, noix, pistache, châtaigne…)",
                        "Fruit à coque, graine, céréale et dérivé > Fruit à coque (amande, noisette, noix, pistache, châtaigne…)",
                    ),
                    (
                        "FC - Non transformé (yc mélange)",
                        "Fruit à coque, graine, céréale et dérivé > Fruit à coque (amande, noisette, noix, pistache, châtaigne…) > FC - Non transformé (yc mélange)",
                    ),
                    (
                        "FC - Séché, cuit, fermenté (yc aromatisé, pâte, farine) (hors huile)",
                        "Fruit à coque, graine, céréale et dérivé > Fruit à coque (amande, noisette, noix, pistache, châtaigne…) > FC - Séché, cuit, fermenté (yc aromatisé, pâte, farine) (hors huile)",
                    ),
                    (
                        "FC - Confit, en confiture, en vinaigre, en saumure, en alcool",
                        "Fruit à coque, graine, céréale et dérivé > Fruit à coque (amande, noisette, noix, pistache, châtaigne…) > FC - Confit, en confiture, en vinaigre, en saumure, en alcool",
                    ),
                    (
                        "Graine légumineuse (soja, lentille, haricot grain, pois…)",
                        "Fruit à coque, graine, céréale et dérivé > Graine légumineuse (soja, lentille, haricot grain, pois…)",
                    ),
                    (
                        "GL - Non transformé (yc mélange)",
                        "Fruit à coque, graine, céréale et dérivé > Graine légumineuse (soja, lentille, haricot grain, pois…) > GL - Non transformé (yc mélange)",
                    ),
                    (
                        "GL - Séché, cuit, fermenté (yc aromatisé, farine) (hors germé) (yc chips)",
                        "Fruit à coque, graine, céréale et dérivé > Graine légumineuse (soja, lentille, haricot grain, pois…) > GL - Séché, cuit, fermenté (yc aromatisé, farine) (hors germé) (yc chips)",
                    ),
                    (
                        "GL - Confit, en confiture, en vinaigre, en saumure, en alcool",
                        "Fruit à coque, graine, céréale et dérivé > Graine légumineuse (soja, lentille, haricot grain, pois…) > GL - Confit, en confiture, en vinaigre, en saumure, en alcool",
                    ),
                    (
                        "Graine ou fruit oléagineux (olive, coco, pignon, sésame, tournesol, lin, courge, arachide...)",
                        "Fruit à coque, graine, céréale et dérivé > Graine ou fruit oléagineux (olive, coco, pignon, sésame, tournesol, lin, courge, arachide...)",
                    ),
                    (
                        "GO - Non transformé (yc mélange)",
                        "Fruit à coque, graine, céréale et dérivé > Graine ou fruit oléagineux (olive, coco, pignon, sésame, tournesol, lin, courge, arachide...) > GO - Non transformé (yc mélange)",
                    ),
                    (
                        "GO - Séché, cuit, fermenté (yc aromatisé) (hors huile, germé)",
                        "Fruit à coque, graine, céréale et dérivé > Graine ou fruit oléagineux (olive, coco, pignon, sésame, tournesol, lin, courge, arachide...) > GO - Séché, cuit, fermenté (yc aromatisé) (hors huile, germé)",
                    ),
                    (
                        "GO - Confit, en confiture, en vinaigre, en saumure, en alcool",
                        "Fruit à coque, graine, céréale et dérivé > Graine ou fruit oléagineux (olive, coco, pignon, sésame, tournesol, lin, courge, arachide...) > GO - Confit, en confiture, en vinaigre, en saumure, en alcool",
                    ),
                    (
                        "Céréale (riz, blé, avoine, épeautre…)",
                        "Fruit à coque, graine, céréale et dérivé > Céréale (riz, blé, avoine, épeautre…)",
                    ),
                    (
                        "GC - Non transformé (yc mélange)",
                        "Fruit à coque, graine, céréale et dérivé > Céréale (riz, blé, avoine, épeautre…) > GC - Non transformé (yc mélange)",
                    ),
                    (
                        "GC - Séché, cuit, fermenté  (yc aromatisé) (hors germé) (hors farine)",
                        "Fruit à coque, graine, céréale et dérivé > Céréale (riz, blé, avoine, épeautre…) > GC - Séché, cuit, fermenté  (yc aromatisé) (hors germé) (hors farine)",
                    ),
                    (
                        "GC - Préparation à base de céréale et d'eau (pâte, nouille ou vermiGClle, sans œuf)",
                        "Fruit à coque, graine, céréale et dérivé > Céréale (riz, blé, avoine, épeautre…) > GC - Préparation à base de céréale et d'eau (pâte, nouille ou vermiGClle, sans œuf)",
                    ),
                    (
                        "GC - Produit de la boulangerie (pain et viennoiserie)",
                        "Fruit à coque, graine, céréale et dérivé > Céréale (riz, blé, avoine, épeautre…) > GC - Produit de la boulangerie (pain et viennoiserie)",
                    ),
                    (
                        "GC - Ecrasé, moulu, farine, son, flocon",
                        "Fruit à coque, graine, céréale et dérivé > Céréale (riz, blé, avoine, épeautre…) > GC - Ecrasé, moulu, farine, son, flocon",
                    ),
                    (
                        "Baie ou petit fruit (myrtille, fraise…)",
                        "Fruit charnu et dérivé > Baie ou petit fruit (myrtille, fraise…)",
                    ),
                    (
                        "FB - Non transformé (yc mélange)",
                        "Fruit charnu et dérivé > Baie ou petit fruit (myrtille, fraise…) > FB - Non transformé (yc mélange)",
                    ),
                    (
                        "FB - Séché, cuit, fermenté",
                        "Fruit charnu et dérivé > Baie ou petit fruit (myrtille, fraise…) > FB - Séché, cuit, fermenté",
                    ),
                    (
                        "FB - Confit, en confiture, en vinaigre, en saumure, en alcool",
                        "Fruit charnu et dérivé > Baie ou petit fruit (myrtille, fraise…) > FB - Confit, en confiture, en vinaigre, en saumure, en alcool",
                    ),
                    ("Agrume", "Fruit charnu et dérivé > Agrume"),
                    (
                        "FA - Non transformé (yc mélange)",
                        "Fruit charnu et dérivé > Agrume > FA - Non transformé (yc mélange)",
                    ),
                    (
                        "FA - Séché, cuit, fermenté",
                        "Fruit charnu et dérivé > Agrume > FA - Séché, cuit, fermenté",
                    ),
                    (
                        "FA - Confit, en confiture, en vinaigre, en saumure, en alcool",
                        "Fruit charnu et dérivé > Agrume > FA - Confit, en confiture, en vinaigre, en saumure, en alcool",
                    ),
                    (
                        "Autre fruit charnu ou mélange de fruit",
                        "Fruit charnu et dérivé > Autre fruit charnu ou mélange de fruit",
                    ),
                    (
                        "FF - Non transformé (yc mélange) (yc salade crue)",
                        "Fruit charnu et dérivé > Autre fruit charnu ou mélange de fruit > FF - Non transformé (yc mélange) (yc salade crue)",
                    ),
                    (
                        "FF - Séché, cuit, fermenté (yc salade cuite)",
                        "Fruit charnu et dérivé > Autre fruit charnu ou mélange de fruit > FF - Séché, cuit, fermenté (yc salade cuite)",
                    ),
                    (
                        "FF - Confit, en confiture, en vinaigre, en saumure, en alcool",
                        "Fruit charnu et dérivé > Autre fruit charnu ou mélange de fruit > FF - Confit, en confiture, en vinaigre, en saumure, en alcool",
                    ),
                    (
                        "Légume-feuille (salade, épinard…)",
                        "Légume et dérivé > Légume-feuille (salade, épinard…)",
                    ),
                    (
                        "LF - Non transformé (yc mélange)",
                        "Légume et dérivé > Légume-feuille (salade, épinard…) > LF - Non transformé (yc mélange)",
                    ),
                    (
                        "LF - Séché, cuit, fermenté",
                        "Légume et dérivé > Légume-feuille (salade, épinard…) > LF - Séché, cuit, fermenté",
                    ),
                    (
                        "LF - Confit, en confiture, en vinaigre, en saumure, en alcool",
                        "Légume et dérivé > Légume-feuille (salade, épinard…) > LF - Confit, en confiture, en vinaigre, en saumure, en alcool",
                    ),
                    (
                        "Légume-tige (céleri branche, asperge...)",
                        "Légume et dérivé > Légume-tige (céleri branche, asperge...)",
                    ),
                    (
                        "LT- Non transformé (yc mélange)",
                        "Légume et dérivé > Légume-tige (céleri branche, asperge...) > LT- Non transformé (yc mélange)",
                    ),
                    (
                        "LT- Séché, cuit, fermenté",
                        "Légume et dérivé > Légume-tige (céleri branche, asperge...) > LT- Séché, cuit, fermenté",
                    ),
                    (
                        "LT- Confit, en confiture, en vinaigre, en saumure, en alcool",
                        "Légume et dérivé > Légume-tige (céleri branche, asperge...) > LT- Confit, en confiture, en vinaigre, en saumure, en alcool",
                    ),
                    (
                        "Légume-bulbe (oignon, échalotte...)",
                        "Légume et dérivé > Légume-bulbe (oignon, échalotte...)",
                    ),
                    (
                        "LB - Non transformé (yc mélange)",
                        "Légume et dérivé > Légume-bulbe (oignon, échalotte...) > LB - Non transformé (yc mélange)",
                    ),
                    (
                        "LB - Séché, cuit, fermenté",
                        "Légume et dérivé > Légume-bulbe (oignon, échalotte...) > LB - Séché, cuit, fermenté",
                    ),
                    (
                        "LB - Confit, en confiture, en vinaigre, en saumure, en alcool",
                        "Légume et dérivé > Légume-bulbe (oignon, échalotte...) > LB - Confit, en confiture, en vinaigre, en saumure, en alcool",
                    ),
                    (
                        "Légume-fleur (choux fleur, choux de Bruxelles, fleur comestible...)",
                        "Légume et dérivé > Légume-fleur (choux fleur, choux de Bruxelles, fleur comestible...)",
                    ),
                    (
                        "LFL - Non transformé (yc mélange)",
                        "Légume et dérivé > Légume-fleur (choux fleur, choux de Bruxelles, fleur comestible...) > LFL - Non transformé (yc mélange)",
                    ),
                    (
                        "LFL - Séché, cuit, fermenté",
                        "Légume et dérivé > Légume-fleur (choux fleur, choux de Bruxelles, fleur comestible...) > LFL - Séché, cuit, fermenté",
                    ),
                    (
                        "LFL - Confit, en confiture, en vinaigre, en saumure, en alcool",
                        "Légume et dérivé > Légume-fleur (choux fleur, choux de Bruxelles, fleur comestible...) > LFL - Confit, en confiture, en vinaigre, en saumure, en alcool",
                    ),
                    (
                        "Légume-fruit : solanacée (tomate, aubergine…)",
                        "Légume et dérivé > Légume-fruit : solanacée (tomate, aubergine…)",
                    ),
                    (
                        "LFRS - Non transformé (yc mélange)",
                        "Légume et dérivé > Légume-fruit : solanacée (tomate, aubergine…) > LFRS - Non transformé (yc mélange)",
                    ),
                    (
                        "LFRS - Séché, cuit, fermenté",
                        "Légume et dérivé > Légume-fruit : solanacée (tomate, aubergine…) > LFRS - Séché, cuit, fermenté",
                    ),
                    (
                        "LFRS - Confit, en confiture, en vinaigre, en saumure, en alcool",
                        "Légume et dérivé > Légume-fruit : solanacée (tomate, aubergine…) > LFRS - Confit, en confiture, en vinaigre, en saumure, en alcool",
                    ),
                    (
                        "Légume-fruit : cucurbitacée à peau fine (courgette, concombre…)",
                        "Légume et dérivé > Légume-fruit : cucurbitacée à peau fine (courgette, concombre…)",
                    ),
                    (
                        "LFRCF - Non transformé (yc mélange)",
                        "Légume et dérivé > Légume-fruit : cucurbitacée à peau fine (courgette, concombre…) > LFRCF - Non transformé (yc mélange)",
                    ),
                    (
                        "LFRCF - Séché, cuit, fermenté",
                        "Légume et dérivé > Légume-fruit : cucurbitacée à peau fine (courgette, concombre…) > LFRCF - Séché, cuit, fermenté",
                    ),
                    (
                        "LFRCF - Confit, en confiture, en vinaigre, en saumure, en alcool",
                        "Légume et dérivé > Légume-fruit : cucurbitacée à peau fine (courgette, concombre…) > LFRCF - Confit, en confiture, en vinaigre, en saumure, en alcool",
                    ),
                    (
                        "Légume-fruit : cucurbitacée à peau épaisse (courge, potiron…)",
                        "Légume et dérivé > Légume-fruit : cucurbitacée à peau épaisse (courge, potiron…)",
                    ),
                    (
                        "LFRCE - Non transformé (yc mélange)",
                        "Légume et dérivé > Légume-fruit : cucurbitacée à peau épaisse (courge, potiron…) > LFRCE - Non transformé (yc mélange)",
                    ),
                    (
                        "LFRCE - Séché, cuit, fermenté",
                        "Légume et dérivé > Légume-fruit : cucurbitacée à peau épaisse (courge, potiron…) > LFRCE - Séché, cuit, fermenté",
                    ),
                    (
                        "LFRCE - Confit, en confiture, en vinaigre, en saumure, en alcool",
                        "Légume et dérivé > Légume-fruit : cucurbitacée à peau épaisse (courge, potiron…) > LFRCE - Confit, en confiture, en vinaigre, en saumure, en alcool",
                    ),
                    ("Légume-fruit : maïs", "Légume et dérivé > Légume-fruit : maïs"),
                    (
                        "LFRM - Non transformé (yc mélange)",
                        "Légume et dérivé > Légume-fruit : maïs > LFRM - Non transformé (yc mélange)",
                    ),
                    (
                        "LFRM - Séché, cuit, fermenté (yc pop corn, flocon)",
                        "Légume et dérivé > Légume-fruit : maïs > LFRM - Séché, cuit, fermenté (yc pop corn, flocon)",
                    ),
                    (
                        "LFRM - Confit, en confiture, en vinaigre, en saumure, en alcool",
                        "Légume et dérivé > Légume-fruit : maïs > LFRM - Confit, en confiture, en vinaigre, en saumure, en alcool",
                    ),
                    (
                        "Légume-gousse (haricot vert) (hors graine de légumineuse)",
                        "Légume et dérivé > Légume-gousse (haricot vert) (hors graine de légumineuse)",
                    ),
                    (
                        "LG - Non transformé (yc mélange)",
                        "Légume et dérivé > Légume-gousse (haricot vert) (hors graine de légumineuse) > LG - Non transformé (yc mélange)",
                    ),
                    (
                        "LG - Séché, cuit, fermenté",
                        "Légume et dérivé > Légume-gousse (haricot vert) (hors graine de légumineuse) > LG - Séché, cuit, fermenté",
                    ),
                    (
                        "LG - Confit, en confiture, en vinaigre, en saumure, en alcool",
                        "Légume et dérivé > Légume-gousse (haricot vert) (hors graine de légumineuse) > LG - Confit, en confiture, en vinaigre, en saumure, en alcool",
                    ),
                    (
                        "Légume-racine et tubercule (radis, pomme-de-terre, carotte…)",
                        "Légume et dérivé > Légume-racine et tubercule (radis, pomme-de-terre, carotte…)",
                    ),
                    (
                        "LR - Non transformé (yc mélange)",
                        "Légume et dérivé > Légume-racine et tubercule (radis, pomme-de-terre, carotte…) > LR - Non transformé (yc mélange)",
                    ),
                    (
                        "LR - Séché, cuit, fermenté (yc chips)",
                        "Légume et dérivé > Légume-racine et tubercule (radis, pomme-de-terre, carotte…) > LR - Séché, cuit, fermenté (yc chips)",
                    ),
                    (
                        "LR - Confit, en confiture, en vinaigre, en saumure, en alcool",
                        "Légume et dérivé > Légume-racine et tubercule (radis, pomme-de-terre, carotte…) > LR - Confit, en confiture, en vinaigre, en saumure, en alcool",
                    ),
                    ("Champignon", "Légume et dérivé > Champignon"),
                    (
                        "CH - Non transformé (yc mélange)",
                        "Légume et dérivé > Champignon > CH - Non transformé (yc mélange)",
                    ),
                    (
                        "CH - Séché, cuit, fermenté",
                        "Légume et dérivé > Champignon > CH - Séché, cuit, fermenté",
                    ),
                    (
                        "CH - Confit, en confiture, en vinaigre, en saumure, en alcool",
                        "Légume et dérivé > Champignon > CH - Confit, en confiture, en vinaigre, en saumure, en alcool",
                    ),
                    ("Mélange de légume", "Légume et dérivé > Mélange de légume"),
                    (
                        "LL - Non transformé (yc mélange) ou peu transformé (yc salade de crudité)",
                        "Légume et dérivé > Mélange de légume > LL - Non transformé (yc mélange) ou peu transformé (yc salade de crudité)",
                    ),
                    (
                        "LL - Séché, cuit, fermenté, en soupe, yc salade de cuidité",
                        "Légume et dérivé > Mélange de légume > LL - Séché, cuit, fermenté, en soupe, yc salade de cuidité",
                    ),
                    (
                        "LL - Confit, en confiture, en vinaigre, en saumure, en alcool",
                        "Légume et dérivé > Mélange de légume > LL - Confit, en confiture, en vinaigre, en saumure, en alcool",
                    ),
                    (
                        "Graine germée et pousse",
                        "Légume et dérivé > Graine germée et pousse",
                    ),
                    (
                        "Graine germée (avec agrément)",
                        "Légume et dérivé > Graine germée et pousse > Graine germée (avec agrément)",
                    ),
                    (
                        "Pousse, jeune pousse (sans agrément)",
                        "Légume et dérivé > Graine germée et pousse > Pousse, jeune pousse (sans agrément)",
                    ),
                    (
                        "Sucre, pur sirop de sucre, mélasse",
                        "Condiment et herboristerie > Sucre, pur sirop de sucre, mélasse",
                    ),
                    (
                        "Sel, sel aromatisé",
                        "Condiment et herboristerie > Sel, sel aromatisé",
                    ),
                    (
                        "Epice, mélange épicé",
                        "Condiment et herboristerie > Epice, mélange épicé",
                    ),
                    (
                        "Herbe ou graine aromatique, mélange aromatique",
                        "Condiment et herboristerie > Herbe ou graine aromatique, mélange aromatique",
                    ),
                    (
                        "Moutarde, vinaigre et vinaigrette",
                        "Condiment et herboristerie > Moutarde, vinaigre et vinaigrette",
                    ),
                    (
                        "Sauce à base végétale (yc tomate, pesto) (yc avec DAOA)",
                        "Condiment et herboristerie > Sauce à base végétale (yc tomate, pesto) (yc avec DAOA)",
                    ),
                    (
                        "Sauce à base œuf (mayonnaise, hollandaise)",
                        "Condiment et herboristerie > Sauce à base œuf (mayonnaise, hollandaise)",
                    ),
                    (
                        "Bouillon (cube, poudre) (yc avec DAOA)",
                        "Condiment et herboristerie > Bouillon (cube, poudre) (yc avec DAOA)",
                    ),
                    (
                        "Huile essentielle",
                        "Condiment et herboristerie > Huile essentielle",
                    ),
                    (
                        "Eau minérale et naturelle, eau embouteillée",
                        "Boisson > Eau minérale et naturelle, eau embouteillée",
                    ),
                    ("Eau aromatisée", "Boisson > Eau aromatisée"),
                    (
                        "Eau potable autre (yc glaçon)",
                        "Boisson > Eau potable autre (yc glaçon)",
                    ),
                    ("Jus de fruit ou légume", "Boisson > Jus de fruit ou légume"),
                    (
                        "Pour boisson chaude ou cuisine (chocolaté, cacao, café, thé, tisane, yc en grain, feuile, poudre)",
                        "Boisson > Pour boisson chaude ou cuisine (chocolaté, cacao, café, thé, tisane, yc en grain, feuile, poudre)",
                    ),
                    (
                        "Pour boisson froide (sirop aromatisé, base à soda)",
                        "Boisson > Pour boisson froide (sirop aromatisé, base à soda)",
                    ),
                    (
                        "Soda, kombucha (hors jus de fruit, kefir, produit lacté, analogue lacté)",
                        "Boisson > Soda, kombucha (hors jus de fruit, kefir, produit lacté, analogue lacté)",
                    ),
                    (
                        "Boisson alcoolisée (dont vin, bière, hydromel, spiritueux)",
                        "Boisson > Boisson alcoolisée (dont vin, bière, hydromel, spiritueux)",
                    ),
                    (
                        "Boisson désalcoolisée (vin, bière sans alcool)",
                        "Boisson > Boisson désalcoolisée (vin, bière sans alcool)",
                    ),
                    (
                        "Préparation en poudre pour enfant de 0-36 mois (hors DADFMS)",
                        "Aliment infantile > Préparation en poudre pour enfant de 0-36 mois (hors DADFMS)",
                    ),
                    (
                        "Préparation liquide pour enfant de 0-36 mois (hors DADFMS)",
                        "Aliment infantile > Préparation liquide pour enfant de 0-36 mois (hors DADFMS)",
                    ),
                    (
                        "Préparation à base de céréale pour enfant de 0-36 mois (hors DADFMS) (hors poudre) (hors liquide)",
                        "Aliment infantile > Préparation à base de céréale pour enfant de 0-36 mois (hors DADFMS) (hors poudre) (hors liquide)",
                    ),
                    (
                        "Autre aliment pour enfant de 0-36 mois (hors DADFMS)",
                        "Aliment infantile > Autre aliment pour enfant de 0-36 mois (hors DADFMS)",
                    ),
                    (
                        "DADFMS pour enfant 0-36 mois",
                        "DADFMS > DADFMS pour enfant 0-36 mois",
                    ),
                    (
                        "DADFMS pour personne de plus de 3 ans",
                        "DADFMS > DADFMS pour personne de plus de 3 ans",
                    ),
                    (
                        "Additif alimentaire",
                        "Améliorant ou auxiliaire > Additif alimentaire",
                    ),
                    ("Arome", "Améliorant ou auxiliaire > Arome"),
                    ("Ferment, enzyme", "Améliorant ou auxiliaire > Ferment, enzyme"),
                    (
                        "Complément alimentaire",
                        "Complément alimentaire > Complément alimentaire",
                    ),
                    (
                        "Feed - MP céréale et dérivé",
                        "Alimentation animale - matière première végétale > Feed - MP céréale et dérivé",
                    ),
                    (
                        "Feed - MP oléagineux et dérivé",
                        "Alimentation animale - matière première végétale > Feed - MP oléagineux et dérivé",
                    ),
                    (
                        "Feed - MP légumineuse (pois, féverole, lupin…) et dérivé",
                        "Alimentation animale - matière première végétale > Feed - MP légumineuse (pois, féverole, lupin…) et dérivé",
                    ),
                    (
                        "Feed - MP tubercule, racine (betterave, pomme de terre…) et dérivé",
                        "Alimentation animale - matière première végétale > Feed - MP tubercule, racine (betterave, pomme de terre…) et dérivé",
                    ),
                    (
                        "Feed - MP fourrage (herbe, foin, paille, ensilage, luzerne, trèfle…)",
                        "Alimentation animale - matière première végétale > Feed - MP fourrage (herbe, foin, paille, ensilage, luzerne, trèfle…)",
                    ),
                    (
                        "Feed - MP autre (coproduit, algue, bois, DVOV déclassée...)",
                        "Alimentation animale - matière première végétale > Feed - MP autre (coproduit, algue, bois, DVOV déclassée...)",
                    ),
                    (
                        "Feed - MP d'origine minérale",
                        "Alimentation animale - matière première autre > Feed - MP d'origine minérale",
                    ),
                    (
                        "Feed - MP d'origine autre (micro-organisme inactivé...)",
                        "Alimentation animale - matière première autre > Feed - MP d'origine autre (micro-organisme inactivé...)",
                    ),
                    (
                        "Feed - MP lait et produit laitier",
                        "Alimentation animale - matière première animale > Feed - MP lait et produit laitier",
                    ),
                    (
                        "Feed - MP produit d'animaux terrestres",
                        "Alimentation animale - matière première animale > Feed - MP produit d'animaux terrestres",
                    ),
                    (
                        "AAMPAT - Protéine animale transformée (PAT)",
                        "Alimentation animale - matière première animale > Feed - MP produit d'animaux terrestres > AAMPAT - Protéine animale transformée (PAT)",
                    ),
                    (
                        "AAMPAT - Autre",
                        "Alimentation animale - matière première animale > Feed - MP produit d'animaux terrestres > AAMPAT - Autre",
                    ),
                    (
                        "Feed - MP produit d'animaux aquatiques",
                        "Alimentation animale - matière première animale > Feed - MP produit d'animaux aquatiques",
                    ),
                    (
                        "AAMPAA - Protéine animale transformée (PAT)",
                        "Alimentation animale - matière première animale > Feed - MP produit d'animaux aquatiques > AAMPAA - Protéine animale transformée (PAT)",
                    ),
                    (
                        "AAMPAA - Autre",
                        "Alimentation animale - matière première animale > Feed - MP produit d'animaux aquatiques > AAMPAA - Autre",
                    ),
                    (
                        "Feed - additif",
                        "Alimentation animale - additif, prémélange > Feed - additif",
                    ),
                    (
                        "Feed - prémélange pour animaux d'élevage",
                        "Alimentation animale - additif, prémélange > Feed - prémélange pour animaux d'élevage",
                    ),
                    (
                        "Feed - prémélange pour animaux familiers",
                        "Alimentation animale - additif, prémélange > Feed - prémélange pour animaux familiers",
                    ),
                    (
                        "Feed - Aliment composé pour animaux familiers",
                        "Alimentation animale - aliment composé > Feed - Aliment composé pour animaux familiers",
                    ),
                    (
                        "AACOMP - Pour carnivore domestique (chien, chat, furet...)",
                        "Alimentation animale - aliment composé > Feed - Aliment composé pour animaux familiers > AACOMP - Pour carnivore domestique (chien, chat, furet...)",
                    ),
                    (
                        "AACOMP - Pour oiseau d'ornement ou oiseau du ciel (hors volaille)",
                        "Alimentation animale - aliment composé > Feed - Aliment composé pour animaux familiers > AACOMP - Pour oiseau d'ornement ou oiseau du ciel (hors volaille)",
                    ),
                    (
                        "AACOMP - Pour poisson d'ornement et autre animal aquatique d'ornement",
                        "Alimentation animale - aliment composé > Feed - Aliment composé pour animaux familiers > AACOMP - Pour poisson d'ornement et autre animal aquatique d'ornement",
                    ),
                    (
                        "AACOMP - Pour autre animal familier (rongeur, hérisson, reptile…) (hors lapin)",
                        "Alimentation animale - aliment composé > Feed - Aliment composé pour animaux familiers > AACOMP - Pour autre animal familier (rongeur, hérisson, reptile…) (hors lapin)",
                    ),
                    (
                        "Feed - Aliment composé pour animaux d'élevage",
                        "Alimentation animale - aliment composé > Feed - Aliment composé pour animaux d'élevage",
                    ),
                    (
                        "AACOMP - Pour porcin",
                        "Alimentation animale - aliment composé > Feed - Aliment composé pour animaux d'élevage > AACOMP - Pour porcin",
                    ),
                    (
                        "AACOMP - Pour volaille",
                        "Alimentation animale - aliment composé > Feed - Aliment composé pour animaux d'élevage > AACOMP - Pour volaille",
                    ),
                    (
                        "AACOMP - Pour ruminant",
                        "Alimentation animale - aliment composé > Feed - Aliment composé pour animaux d'élevage > AACOMP - Pour ruminant",
                    ),
                    (
                        "AACOMP - Pour animaux d'élevage aquatiques (poisson, invertébré) (yc appâts)",
                        "Alimentation animale - aliment composé > Feed - Aliment composé pour animaux d'élevage > AACOMP - Pour animaux d'élevage aquatiques (poisson, invertébré) (yc appâts)",
                    ),
                    (
                        "AACOMP - Pour léporidé (lapin, lièvre)",
                        "Alimentation animale - aliment composé > Feed - Aliment composé pour animaux d'élevage > AACOMP - Pour léporidé (lapin, lièvre)",
                    ),
                    (
                        "AACOMP - Pour équin",
                        "Alimentation animale - aliment composé > Feed - Aliment composé pour animaux d'élevage > AACOMP - Pour équin",
                    ),
                    (
                        "AACOMP - Pour autre (abeille, camélidé, animaux à fourrure …)",
                        "Alimentation animale - aliment composé > Feed - Aliment composé pour animaux d'élevage > AACOMP - Pour autre (abeille, camélidé, animaux à fourrure …)",
                    ),
                    (
                        "Feed - Aliment médicamenteux",
                        "Alimentation animale - médicamenteux > Feed - Aliment médicamenteux",
                    ),
                    (
                        "Feed - Produit intermédiaire",
                        "Alimentation animale - médicamenteux > Feed - Produit intermédiaire",
                    ),
                    (
                        "Feed - Alimentation animale - autre (catégorie à éviter)",
                        "Alimentation animale - autre > Feed - Alimentation animale - autre (catégorie à éviter)",
                    ),
                    (
                        "Produit alimentaire indéterminé",
                        "Produit alimentaire indéterminé > Produit alimentaire indéterminé",
                    ),
                    (
                        "Sous-produit animal technique (non destiné à l'alimentation animale)",
                        "Produit non alimentaire > Sous-produit animal technique (non destiné à l'alimentation animale)",
                    ),
                    (
                        "Autre produit non alimentaire",
                        "Produit non alimentaire > Autre produit non alimentaire",
                    ),
                    (
                        "Produit indéterminé",
                        "Produit indéterminé > Produit indéterminé",
                    ),
                    (
                        "Environnement - surface",
                        "Environnement - surface > Environnement - surface",
                    ),
                    ("Sans objet", "Sans objet > Sans objet"),
                ],
                max_length=255,
                verbose_name="Catégorie de produit",
            ),
        ),
    ]
