# Generated by Django 5.2.6 on 2025-09-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0038_remove_evenementproduit_pam_requires_danger_bacterien_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementproduit",
            name="aliments_animaux",
            field=models.BooleanField(null=True, verbose_name="Inclut des aliments pour animaux"),
        ),
    ]
