# Generated by Django 5.2.7 on 2025-11-10 15:34

from django.db import migrations, models
from django.db.models import F


def populate_date_reception(apps, schema_editor):
    EvenementProduit = apps.get_model("ssa", "EvenementProduit")
    EvenementProduit.objects.update(date_reception=F("date_creation"))


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0040_alter_etablissement_code_insee"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementproduit",
            name="date_reception",
            field=models.DateField(null=True, verbose_name="Date de réception"),
        ),
        migrations.RunPython(populate_date_reception, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="evenementproduit",
            name="date_reception",
            field=models.DateField(null=False, verbose_name="Date de réception"),
        ),
    ]
