# Generated by Django 5.2.7 on 2025-11-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0041_evenementproduit_date_reception"),
    ]

    operations = [
        migrations.AddField(
            model_name="etablissement",
            name="autre_identifiant",
            field=models.CharField(blank=True, max_length=255, verbose_name="Autre identifiant"),
        ),
    ]
