# Generated by Django 5.2.7 on 2025-11-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0042_etablissement_autre_identifiant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenementproduit",
            name="actions_engagees",
            field=models.CharField(
                choices=[
                    ("pas_de_mesure", "Pas de mesure de retrait ou rappel"),
                    (
                        "retrait_marche",
                        "Retrait du marché sans information des consommateurs",
                    ),
                    (
                        "retrait_rappel",
                        "Retrait et information du consommateur / rappel ",
                    ),
                    (
                        "retrait_rappel_communique_presse",
                        "Retrait et rappel avec communiqué de presse",
                    ),
                    (
                        "retrait_rappel_controle_effectivite",
                        "Retrait et rappel avec contrôle de l'effectivité",
                    ),
                ],
                max_length=100,
                verbose_name="Action engagées",
            ),
        ),
    ]
