# Generated by Django 5.2.7 on 2025-11-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0044_remove_evenementproduit_type_evenement_source_constraint_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenementproduit",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("autocontrole_notifie_produit", "Autocontrôle notifié (produit)"),
                    ("autocontrole_notifie_environnement", "Autocontrôle notifié (environnement)"),
                    ("prelevement_pspc", "Prélèvement PSPC (hors PCF)"),
                    ("autre_prelevement_officiel", "Prélèvement officiel autre (hors PCF)"),
                    ("autre_constat_officiel", "Autre constat officiel (hors PCF)"),
                    ("investigation_cas_humains", "Investigation de cas ou TIAC"),
                    ("signalement_consommateur", "Signalement de consommateur"),
                    ("notification_rasff", "Notification RASFF"),
                    ("notification_aac", "Notification AAC"),
                    ("tout_droit", "Tout droit"),
                    ("prelevement_pspc_pcf", "Prélèvement PSPC (en PCF)"),
                    ("prelevement_officiel_autre", "Prélèvement officiel autre (en PCF)"),
                    ("autre_constat_officiel_pcf", "Autre constat officiel (en PCF)"),
                    ("autre", "Signalement autre"),
                ],
                max_length=100,
                verbose_name="Source",
            ),
        ),
    ]
