# Generated by Django 5.2.7 on 2025-12-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0046_create_investigation_cas_humain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evenementinvestigationcashumain",
            name="aliments_animaux",
        ),
        migrations.AddField(
            model_name="evenementinvestigationcashumain",
            name="numero_annee",
            field=models.IntegerField(default=2025, verbose_name="Année"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evenementinvestigationcashumain",
            name="numero_evenement",
            field=models.IntegerField(default=1, verbose_name="Numéro"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="evenementinvestigationcashumain",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DO_LISTERIOSE", "DO listériose"),
                    ("CAS_GROUPES", "Cas groupés"),
                    ("SIGNALEMENT_AUTRE", "Signalement autre"),
                ],
                max_length=100,
                verbose_name="Source",
            ),
        ),
    ]
