# Generated by Django 5.2.7 on 2025-12-01 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_customrevisionmetadata"),
        (
            "ssa",
            "0047_remove_evenementinvestigationcashumain_aliments_animaux_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investigationcashumainsetablissement",
            name="departement",
        ),
        migrations.RemoveField(
            model_name="investigationcashumainsetablissement",
            name="investigation_cas_humain",
        ),
        migrations.AddField(
            model_name="etablissement",
            name="investigation_cas_humain",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="etablissements",
                to="ssa.evenementinvestigationcashumain",
            ),
        ),
        migrations.AlterField(
            model_name="etablissement",
            name="evenement_produit",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="etablissements",
                to="ssa.evenementproduit",
            ),
        ),
        migrations.AddConstraint(
            model_name="etablissement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("evenement_produit__isnull", False),
                        ("investigation_cas_humain__isnull", True),
                    ),
                    models.Q(
                        ("evenement_produit__isnull", True),
                        ("investigation_cas_humain__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="either_evenement_produit_or_investigation_cas_humain",
            ),
        ),
        migrations.DeleteModel(
            name="InvestigationCasHumainsEtablissement",
        ),
    ]
