# Generated by Django 5.2.8 on 2025-12-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_customrevisionmetadata"),
        ("ssa", "0048_remove_investigationcashumainsetablissement_departement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementinvestigationcashumain",
            name="contacts",
            field=models.ManyToManyField(blank=True, to="core.contact", verbose_name="Contacts"),
        ),
    ]
