# Generated by Django 5.2.8 on 2025-12-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0049_evenementinvestigationcashumain_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="etablissement",
            name="historical_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="evenementinvestigationcashumain",
            name="historical_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="evenementproduit",
            name="historical_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
