# Generated by Django 5.2.8 on 2025-12-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0050_etablissement_historical_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evenementinvestigationcashumain",
            name="type_evenement",
        ),
        migrations.AddField(
            model_name="evenementinvestigationcashumain",
            name="produit_pret_a_manger",
            field=models.CharField(
                blank=True,
                choices=[("oui", "Oui"), ("non", "Non"), ("sans_objet", "Sans objet")],
                max_length=100,
                verbose_name="Produit Prêt à manger (PAM)",
            ),
        ),
    ]
