# Generated by Django 5.2.8 on 2025-12-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0051_ich_remove_type_evenement_add_pam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenementproduit",
            name="temperature_conservation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("refrigere", "Réfrigéré"),
                    ("surgele", "Surgelé"),
                    ("temperature_ambiante", "Température ambiante"),
                ],
                max_length=100,
                verbose_name="Température de conservation",
            ),
        ),
    ]
