# Generated by Django 5.2.8 on 2025-12-22 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0053_alter_evenementproduit_actions_engagees"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evenementinvestigationcashumain",
            name="produit_pret_a_manger",
        ),
    ]
