# Generated by Django 5.2.8 on 2025-12-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0054_remove_evenementinvestigationcashumain_produit_pret_a_manger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenementinvestigationcashumain",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DO_LISTERIOSE", "DO listériose"),
                    ("CAS_GROUPES", "Cas groupés"),
                    ("autre", "Signalement autre"),
                ],
                max_length=100,
                verbose_name="Source",
            ),
        ),
    ]
