# Generated by Django 5.2.8 on 2026-01-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0057_alter_evenementinvestigationcashumain_categorie_danger_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenementinvestigationcashumain",
            name="numero_rasff",
            field=models.CharField(blank=True, max_length=255, verbose_name="N° RASFF/AAC"),
        ),
        migrations.AlterField(
            model_name="evenementproduit",
            name="numero_rasff",
            field=models.CharField(blank=True, max_length=255, verbose_name="N° RASFF/AAC"),
        ),
    ]
