# Generated by Django 5.2.8 on 2026-01-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0059_alter_evenementproduit_categorie_produit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenementproduit",
            name="actions_engagees",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pas_de_mesure", "Pas de mesure de retrait ou rappel"),
                    ("retrait_marche", "Retrait du marché sans information des consommateurs"),
                    ("retrait_rappel", "Retrait et information du consommateur / rappel "),
                    ("retrait_rappel_communique_presse", "Retrait et rappel avec communiqué de presse"),
                    ("retrait_rappel_controle_effectivite", "Retrait et rappel avec contrôle de l'effectivité"),
                    (
                        "retrait_rappel_cp_controle_effectivite",
                        "Retrait et rappel avec communiqué de presse et contrôle de l'effectivité",
                    ),
                ],
                max_length=100,
                verbose_name="Action engagées",
            ),
        ),
    ]
