# Generated by Django 5.2.8 on 2026-02-05 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0060_alter_evenementproduit_actions_engagees"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvenementProduitReadOnly",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("ssa.evenementproduit",),
        ),
    ]
