# Generated by Django 5.2.11 on 2026-03-13 13:20

from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models
from django.db.models import CharField, Max, OuterRef, Subquery
from django.db.models.functions import Cast
from reversion.models import Version


def update_last_updated(apps, schema_editor):
    EvenementProduit = apps.get_model("ssa", "EvenementProduit")
    EvenementInvestigationCasHumain = apps.get_model("ssa", "EvenementInvestigationCasHumain")

    for model in (EvenementProduit, EvenementInvestigationCasHumain):
        content_type = ContentType.objects.get_for_model(model)

        latest = (
            Version.objects.filter(content_type=content_type, db="default")
            .values("object_id")
            .annotate(last_date=Max("revision__date_created"))
            .filter(object_id=Cast(OuterRef("pk"), CharField()))
            .values("last_date")[:1]
        )

        model.objects.update(last_updated=Subquery(latest))


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0063_etablissement_code_postal"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementinvestigationcashumain",
            name="last_updated",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Date de dernière mise à jour",
            ),
        ),
        migrations.AddField(
            model_name="evenementproduit",
            name="last_updated",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Date de dernière mise à jour",
            ),
        ),
        migrations.RunPython(update_last_updated, migrations.RunPython.noop),
    ]
