# Generated by Django 5.2.11 on 2026-03-27 09:45

from django.db import migrations, models

from core.mixins import WithEtatMixin


def copy_date_creation_to_date_publication(apps, schema_editor):
    EvenementProduit = apps.get_model("ssa", "EvenementProduit")
    EvenementProduit.objects.exclude(etat=WithEtatMixin.Etat.BROUILLON).update(
        date_publication=models.F("date_creation")
    )

    EvenementInvestigationCasHumain = apps.get_model("ssa", "EvenementInvestigationCasHumain")
    EvenementInvestigationCasHumain.objects.exclude(etat=WithEtatMixin.Etat.BROUILLON).update(
        date_publication=models.F("date_creation")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0064_evenementinvestigationcashumain_last_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementinvestigationcashumain",
            name="date_publication",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de publication"),
        ),
        migrations.AddField(
            model_name="evenementproduit",
            name="date_publication",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de publication"),
        ),
        migrations.RunPython(copy_date_creation_to_date_publication, migrations.RunPython.noop),
    ]
