# Generated by Django 6.0.3 on 2026-05-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssa", "0066_alter_evenementproduit_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementproduit",
            name="maestro_reference",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Référence MAESTRO"),
        ),
    ]
