from .produit import EvenementProduitCreateView as EvenementProduitCreateView
from .produit import EvenementProduitDetailView as EvenementProduitDetailView
from .produit import EvenementProduitListView as EvenementProduitListView
from .api import FindNumeroAgrementView as FindNumeroAgrementView
