AC_STRUCTURE = "AC/DAC/DGAL"
MUS_STRUCTURE = "MUS"
BSV_STRUCTURE = "SAS/SDSPV/BSV"
SERVICE_ACCOUNT_NAME = "service_account"
SV_DOMAIN = "Santé des végétaux"
SSA_DOMAIN = "Sécurité sanitaire des aliments"
