AC_STRUCTURE = "AC/DAC/DGAL"
MUS_STRUCTURE = "MUS"
BSV_STRUCTURE = "SAS/SDSPV/BSV"
SERVICE_ACCOUNT_NAME = "service_account"
SSA_STRUCTURES = [
    MUS_STRUCTURE,
    "BEAD",
    "BETD",
    "BPMED",
    "BAMRA",
    "BEPIAS",
    "BIB",
    "SIVEP",
    "BICMA",
]
