from django.urls import path
from . import auth_views
from .views import (
    DocumentUploadView,
    DocumentDeleteView,
    DocumentUpdateView,
    ContactDeleteView,
    MessageCreateView,
    SoftDeleteView,
    ACNotificationView,
    PublishView,
    StructureAddView,
    AgentAddView,
)

urlpatterns = [
    path(
        "document-upload/",
        DocumentUploadView.as_view(),
        name="document-upload",
    ),
    path(
        "document-delete/<int:pk>/",
        DocumentDeleteView.as_view(),
        name="document-delete",
    ),
    path(
        "document-update/<int:pk>/",
        DocumentUpdateView.as_view(),
        name="document-update",
    ),
    path(
        "login",
        auth_views.LoginView.as_view(),
        name="login",
    ),
    path(
        "logout",
        auth_views.logout,
        name="logout",
    ),
    path(
        "contacts/suppression/",
        ContactDeleteView.as_view(),
        name="contact-delete",
    ),
    path(
        "message-add/<int:obj_type_pk>/<int:obj_pk>/",
        MessageCreateView.as_view(),
        name="message-add",
    ),
    path(
        "suppression/",
        SoftDeleteView.as_view(),
        name="soft-delete",
    ),
    path(
        "publication/",
        PublishView.as_view(),
        name="publish",
    ),
    path(
        "notify-ac/",
        ACNotificationView.as_view(),
        name="notify-ac",
    ),
    path(
        "structures/ajout",
        StructureAddView.as_view(),
        name="structure-add",
    ),
    path(
        "agents/ajout",
        AgentAddView.as_view(),
        name="agent-add",
    ),
]
