from django.urls import path
from django.views.generic import TemplateView

from . import auth_views
from .views import (
    ACNotificationView,
    AgentAddView,
    CloturerView,
    ContactDeleteView,
    DocumentDeleteView,
    DocumentUpdateView,
    DocumentUploadView,
    EvenementOuvrirView,
    FinDeSuiviHandlingView,
    MessageCreateView,
    MessageDetailsView,
    MessageUpdateView,
    PublishAndACNotificationView,
    PublishView,
    RevisionsListView,
    SoftDeleteView,
    StructureAddView,
    sirene_api,
)

urlpatterns = [
    path(
        "document-upload/",
        DocumentUploadView.as_view(),
        name="document-upload",
    ),
    path(
        "document-delete/<int:pk>/",
        DocumentDeleteView.as_view(),
        name="document-delete",
    ),
    path(
        "document-update/<int:pk>/",
        DocumentUpdateView.as_view(),
        name="document-update",
    ),
    path(
        "login",
        auth_views.LoginView.as_view(),
        name="login",
    ),
    path(
        "logout",
        auth_views.logout,
        name="logout",
    ),
    path(
        "contacts/suppression/",
        ContactDeleteView.as_view(),
        name="contact-delete",
    ),
    path(
        "message-add/<int:obj_type_pk>/<int:obj_pk>/",
        MessageCreateView.as_view(),
        name="message-add",
    ),
    path(
        "message/<int:pk>/update/",
        MessageUpdateView.as_view(),
        name="message-update",
    ),
    path(
        "suppression/",
        SoftDeleteView.as_view(),
        name="soft-delete",
    ),
    path(
        "publication/",
        PublishView.as_view(),
        name="publish",
    ),
    path(
        "publier-notifier-ac/",
        PublishAndACNotificationView.as_view(),
        name="publish-and-ac-notification",
    ),
    path(
        "notify-ac/",
        ACNotificationView.as_view(),
        name="notify-ac",
    ),
    path(
        "structures/ajout",
        StructureAddView.as_view(),
        name="structure-add",
    ),
    path(
        "agents/ajout",
        AgentAddView.as_view(),
        name="agent-add",
    ),
    path(
        "cloturer/<int:pk>",
        CloturerView.as_view(),
        name="cloturer",
    ),
    path(
        "evenement/<int:pk>/ouvrir/",
        EvenementOuvrirView.as_view(),
        name="evenement-ouvrir",
    ),
    path(
        "evenement/fin-de-suivi/",
        FinDeSuiviHandlingView.as_view(),
        name="evenement-fin-de-suivi",
    ),
    path(
        "siret/<str:siret>/",
        sirene_api,
        name="siret-api",
    ),
    path(
        "revisions/<int:content_type>/<int:pk>/",
        RevisionsListView.as_view(),
        name="revision-list",
    ),
    path(
        "message/<int:pk>/",
        MessageDetailsView.as_view(),
        name="message-view",
    ),
    path(
        "mentions-legales/",
        TemplateView.as_view(template_name="mentions-legales.html"),
        name="mentions-legales",
    ),
    path(
        "politique-de-confidentialite/",
        TemplateView.as_view(template_name="politique-de-confidentialite.html"),
        name="politique-de-confidentialite",
    ),
]
