# Generated by Django 6.0.6 on 2026-07-24 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_auto_20260706_1125"),
        ("sa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Espece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Nom"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvenementAnimal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("en_cours", "En cours"),
                            ("cloture", "Clôturé"),
                        ],
                        default="brouillon",
                        max_length=100,
                        verbose_name="État de l'événement",
                    ),
                ),
                ("numero_annee", models.IntegerField(verbose_name="Année")),
                ("numero_evenement", models.IntegerField(verbose_name="Numéro")),
                (
                    "statut_evenement",
                    models.CharField(
                        choices=[
                            ("SUSPECT", "Suspect"),
                            ("CONFIRME", "Confirmé"),
                            ("INFIRME", "Infirmé"),
                            ("NON_RETENU", "Non retenu"),
                        ],
                        max_length=100,
                        verbose_name="Statut de l'événement",
                    ),
                ),
                (
                    "date_statut_changed",
                    models.DateField(verbose_name="Date à prendre en compte pour le changement de statut"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date de création"),
                ),
                (
                    "date_publication",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date de publication"),
                ),
                (
                    "decert_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="N° de la fiche dans DECERT",
                    ),
                ),
                (
                    "statut_animal",
                    models.CharField(
                        choices=[("SAUVAGE", "Sauvage"), ("DETENU", "Détenu")],
                        max_length=100,
                        verbose_name="Statut de l'animal",
                    ),
                ),
                (
                    "createur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.structure",
                        verbose_name="Structure créatrice",
                    ),
                ),
                (
                    "espece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases",
                        to="sa.espece",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Maladie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Nom"),
                ),
                ("featured", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="Evenement",
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="maladie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cases",
                to="sa.maladie",
            ),
        ),
    ]
