# Generated by Django 6.0.6 on 2026-07-27 12:08

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import Point
import django.core.validators
from django.db import migrations, models


def set_default(apps, _):
    EvenementAnimal = apps.get_model("sa", "EvenementAnimal")
    EvenementAnimal.objects.all().update(type_lieu="SAUVAGE", coordinates=Point(1, 1, srid=4326))


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0002_espece_evenementanimal_maladie_delete_evenement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementanimal",
            name="adresse_lieu_dit",
            field=models.CharField(blank=True, max_length=255, verbose_name="Adresse ou lieu-dit"),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="code_insee",
            field=models.CharField(
                blank=True,
                max_length=5,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_code_insee",
                        message="Le code INSEE doit contenir exactement 5 chiffres",
                        regex="^[0-9]{5}$",
                    )
                ],
                verbose_name="Code INSEE de la commune",
            ),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="commune",
            field=models.CharField(blank=True, max_length=100, verbose_name="Commune"),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name="Coordonnées"),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="numero_identifiant",
            field=models.CharField(blank=True, max_length=255, verbose_name="Identifiant parcelle, culture"),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="type_lieu",
            field=models.CharField(
                choices=[("SAUVAGE", "Sauvage"), ("DETENU", "Détenu")],
                max_length=100,
                null=True,
                verbose_name="Type de lieu",
            ),
        ),
        migrations.RunPython(set_default, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="evenementanimal",
            name="type_lieu",
            field=models.CharField(
                choices=[("SAUVAGE", "Sauvage"), ("DETENU", "Détenu")],
                max_length=100,
                null=False,
                verbose_name="Type de lieu",
            ),
        ),
        migrations.AlterField(
            model_name="evenementanimal",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(null=False, srid=4326, verbose_name="Coordonnées"),
        ),
    ]
