# Generated by Django 6.0.6 on 2026-07-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0003_evenementanimal_adresse_lieu_dit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementanimal",
            name="context_suspicion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INVESTIGATION_CAS_HUMAIN", "Investigation cas humain"),
                    ("PROPHYLAXIE", "Prophylaxie"),
                ],
                max_length=100,
                null=True,
                verbose_name="Contexte de la suspicion",
            ),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="date_first_symptoms",
            field=models.DateField(null=True, verbose_name="Date d'apparition des éventuels 1ers symptômes"),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description de la situation"),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="human_involved",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OUI", "Oui"),
                    ("NON", "Non"),
                    ("NE_SAIS_PAS", "Je ne sais pas"),
                ],
                max_length=100,
                null=True,
                verbose_name="Humains exposés pour lesquels des actions sont engagées ?",
            ),
        ),
    ]
