# Generated by Django 6.0.6 on 2026-07-30 09:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_auto_20260727_1357"),
        ("sa", "0004_evenementanimal_context_suspicion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementanimal",
            name="adresse_lieu_dit_etablissement",
            field=models.CharField(blank=True, max_length=255, verbose_name="Adresse ou lieu-dit"),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="adresse_particulier",
            field=models.CharField(blank=True, max_length=255, verbose_name="Adresse"),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="autre_identifiant_etablissement",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Autre identifiant / Numagrit",
            ),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="code_insee_etablissement",
            field=models.CharField(
                blank=True,
                max_length=5,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_code_insee",
                        message="Le code INSEE doit contenir exactement 5 chiffres",
                        regex="^[0-9]{5}$",
                    )
                ],
                verbose_name="Code INSEE",
            ),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="code_insee_particulier",
            field=models.CharField(
                blank=True,
                max_length=5,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_code_insee",
                        message="Le code INSEE doit contenir exactement 5 chiffres",
                        regex="^[0-9]{5}$",
                    )
                ],
                verbose_name="Code INSEE",
            ),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="commune_etablissement",
            field=models.CharField(blank=True, max_length=100, verbose_name="Commune"),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="commune_particulier",
            field=models.CharField(blank=True, max_length=100, verbose_name="Commune"),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="departement_etablissement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sa_evenements_etablissements",
                to="core.departement",
                verbose_name="Département",
            ),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="departement_particulier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sa_evenements_particuliers",
                to="core.departement",
                verbose_name="Département",
            ),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="email_particulier",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Courriel"),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="nom_particulier",
            field=models.CharField(max_length=255, null=True, verbose_name="Nom"),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="numero_identifiant_etablissement",
            field=models.CharField(max_length=255, null=True, verbose_name="N° identifiant"),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="pays_etablissement",
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="prenom_particulier",
            field=models.CharField(blank=True, max_length=255, verbose_name="Prénom"),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="raison_sociale_etablissement",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Raison sociale"),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="siret_etablissement",
            field=models.CharField(
                blank=True,
                max_length=14,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_siret",
                        message="Le SIRET doit contenir exactement 14 chiffres",
                        regex="^[0-9]{14}$",
                    )
                ],
                verbose_name="SIRET",
            ),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="telephone_particulier",
            field=models.CharField(blank=True, max_length=20, verbose_name="Numéro de téléphone"),
        ),
        migrations.AddConstraint(
            model_name="evenementanimal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(("numero_identifiant_etablissement", ""), _negated=True),
                        ("numero_identifiant_etablissement__isnull", False),
                        models.Q(
                            ("nom_particulier", ""),
                            ("nom_particulier__isnull", True),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        models.Q(
                            ("numero_identifiant_etablissement", ""),
                            ("numero_identifiant_etablissement__isnull", True),
                            _connector="OR",
                        ),
                        models.Q(("nom_particulier", ""), _negated=True),
                        ("nom_particulier__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="evenementanimal_detenteur_etablissement_or_particulier",
                violation_error_message="Un détenteur établissement ou un détenteur particulier doit être renseigné (l'un ou l'autre)",
            ),
        ),
    ]
