# Generated by Django 6.0.7 on 2026-08-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0006_auto_20260825_1059"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementanimal",
            name="date_apdi",
            field=models.DateField(blank=True, null=True, verbose_name="Date APDI"),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="date_apms",
            field=models.DateField(blank=True, null=True, verbose_name="Date APMS"),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="date_levee",
            field=models.DateField(blank=True, null=True, verbose_name="Date levée APMS ou APDI"),
        ),
    ]
