# Generated by Django 6.0.7 on 2026-08-31 08:00

from django.db import migrations, models

METHODES_ANALYSE = [
    "ELISA ; ELISA (gB et gE) ; ELISA Stimulation Interféron Gamma",
    "Interféron Gamma",
    "PCR temps réel ; RT-PCR ; RT-PCR temps réel ; RT-PCR en temps réel",
    "Bactériologie et isolement ; Bactériologie : Isolement et identification ; Bactériologie : Recherche et isolement",
    "Séroneutralisation virale ; Neutralisation virale",
    "Immunofluorescence indirect ; Isolement sur culture cellulaire et identification par immunofluorescence",
    "Histologie ; Histopathologie : Coloration à l'hémalun-éosine-safran et coloration de Ziehl-Neelsen",
    "IHA (Inhibition de l'hémagglutination)",
    "IDG (Immunodiffusion en gélose)",
    "EAT",
    "FC ; Fixation du complément",
    "Ovoculture",
    "Microscopie",
    "Examen macroscopique",
    "Digestion artificielle de prélèvements musculaires et observation microscopique",
    "SAW",
    "test ESB 1 Biorad TeSeE SAP ; test ESB 2 Prionics® Check Western ; test ESB 4 Prionics® Check PrioSTRIP ; test ESB 5 Herdchek- antigen EIA IDEXX",
    "test ESST 1 BioradTeSsE Sheep/Goat ; test ESST 2 BioradTeSsE SAP ; test ESST 3 Herdchek-Antigen EIA IDEXX",
]


def populate_methodes_analyse(apps, schema_editor):
    MethodeAnalyse = apps.get_model("sa", "MethodeAnalyse")
    for libelle in METHODES_ANALYSE:
        MethodeAnalyse.objects.update_or_create(libelle=libelle)


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0008_laboratoire"),
    ]

    operations = [
        migrations.CreateModel(
            name="MethodeAnalyse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(max_length=255, verbose_name="Libellé(s) source(s)"),
                ),
                (
                    "laboratoires",
                    models.ManyToManyField(
                        blank=True,
                        related_name="methodes_analyse",
                        to="sa.laboratoire",
                        verbose_name="Laboratoires",
                    ),
                ),
            ],
            options={
                "verbose_name": "Méthode d'analyse",
                "verbose_name_plural": "Méthodes d'analyse",
                "ordering": ["libelle"],
            },
        ),
        migrations.RunPython(populate_methodes_analyse, migrations.RunPython.noop),
    ]
