# Generated by Django 6.0.7 on 2026-08-19 12:41

from django.db import migrations, models

VALID_TYPE_LIEU_VALUES = [
    "Apiary",
    "Backyard",
    "Cage (aquatic environment)",
    "Coastal area - marine area",
    "Estuary",
    "Farm (terrestrial or aquatic, including educational farm, excluding backyard)",
    "Forest (excluding farming)",
    "Lake",
    "Livestock market - fair - exhibition - transport",
    "Natural park - nature reserve - game park",
    "Not applicable",
    "Other",
    "Pond - small pond",
    "Reservoir - dam",
    "River system - running waters",
    "Shellfish bed",
    "Slaughterhouse",
    "Zoo",
]


def fix_invalid_type_lieu(apps, _):
    EvenementAnimal = apps.get_model("sa", "EvenementAnimal")
    EvenementAnimal.objects.exclude(type_lieu__in=VALID_TYPE_LIEU_VALUES).update(type_lieu="Other")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_auto_20260727_1357"),
        ("sa", "0008_laboratoire"),
    ]

    operations = [
        migrations.RunPython(fix_invalid_type_lieu, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="evenementanimal",
            name="type_lieu",
            field=models.CharField(
                choices=[
                    ("Apiary", "Ruche"),
                    ("Backyard", "Basse-cour"),
                    ("Cage (aquatic environment)", "Cage (milieu aquatique)"),
                    ("Coastal area - marine area", "Zone côtière - zone maritime"),
                    ("Estuary", "Estuaire"),
                    (
                        "Farm (terrestrial or aquatic, including educational farm, excluding backyard)",
                        "Élevage (terrestre ou aquatique, y compris ferme pédagogique, hors basse-cour)",
                    ),
                    ("Forest (excluding farming)", "Forêt (hors élevage)"),
                    ("Lake", "Lac"),
                    (
                        "Livestock market - fair - exhibition - transport",
                        "Marché aux bestiaux - foire - exposition - transport",
                    ),
                    ("Natural park - nature reserve - game park", "Parc naturel - réserve - parc de chasse"),
                    ("Not applicable", "Non applicable"),
                    ("Other", "Autre"),
                    ("Pond - small pond", "Étang - mare"),
                    ("Reservoir - dam", "Réservoir - barrage"),
                    ("River system - running waters", "Réseau hydrographique - eaux courantes"),
                    ("Shellfish bed", "Banc de coquillage"),
                    ("Slaughterhouse", "Abattoir"),
                    ("Zoo", "Parc zoologique"),
                ],
                max_length=100,
                verbose_name="Type de lieu",
            ),
        ),
        migrations.AddConstraint(
            model_name="evenementanimal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("statut_animal", "DETENU"),
                        (
                            "type_lieu__in",
                            [
                                "Slaughterhouse",
                                "Other",
                                "Shellfish bed",
                                "Backyard",
                                "Cage (aquatic environment)",
                                "Farm (terrestrial or aquatic, including educational farm, excluding backyard)",
                                "Estuary",
                                "Pond - small pond",
                                "Lake",
                                "Livestock market - fair - exhibition - transport",
                                "Not applicable",
                                "Natural park - nature reserve - game park",
                                "Zoo",
                                "Apiary",
                                "Coastal area - marine area",
                            ],
                        ),
                    ),
                    models.Q(
                        ("statut_animal", "SAUVAGE"),
                        (
                            "type_lieu__in",
                            [
                                "Other",
                                "Shellfish bed",
                                "Estuary",
                                "Pond - small pond",
                                "Forest (excluding farming)",
                                "Lake",
                                "Not applicable",
                                "Natural park - nature reserve - game park",
                                "River system - running waters",
                                "Reservoir - dam",
                                "Coastal area - marine area",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                name="evenementanimal_type_lieu_consistent_with_statut_animal",
                violation_error_message="Le type de lieu n'est pas compatible avec le statut de l'animal sélectionné",
            ),
        ),
    ]
