# Generated by Django 6.0.7 on 2026-08-26 07:05

from django.db import migrations, models


def populate_maladies(apps, schema_editor):
    Maladie = apps.get_model("sa", "Maladie")
    Maladie.objects.filter(
        name__in=[
            "Brucellose",
            "Dermatose nodulaire contagieuse",
            "Fièvre catarrhale ovine",
            "Fièvre charbonneuse - charbon (Bacillus anthracis)",
            "Fièvre de West Nile",
            "Fièvre Q",
            "Maladie d'Aujeszky",
            "Maladie hémorragique épizootique",
            "Paratuberculose",
            "Tuberculose",
        ]
    ).update(is_highlighted=True)


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0009_alter_evenementanimal_type_lieu_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maladie",
            name="is_highlighted",
            field=models.BooleanField(default=False, verbose_name="Est ce que c'est une maladie fréquente"),
        ),
        migrations.RunPython(populate_maladies, migrations.RunPython.noop),
    ]
