# Generated by Django 6.0.7 on 2026-08-31 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0009_methode_analyse"),
        ("sa", "0010_maladie_is_highlighted"),
    ]

    operations = []
