# Generated by Django 6.0.7 on 2026-08-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0065_create_sa_group"),
        ("sa", "0010_maladie_is_highlighted"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementanimal",
            name="date_d_zero",
            field=models.DateField(blank=True, null=True, verbose_name="Date D zéro"),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="date_nd1",
            field=models.DateField(blank=True, null=True, verbose_name="Date ND1"),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="date_nd2",
            field=models.DateField(blank=True, null=True, verbose_name="Date ND2"),
        ),
        migrations.AddConstraint(
            model_name="evenementanimal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("date_d_zero__isnull", True),
                        ("date_nd1__isnull", True),
                        ("date_d_zero__lte", models.F("date_nd1")),
                        _connector="OR",
                    ),
                    models.Q(
                        ("date_nd1__isnull", True),
                        ("date_nd2__isnull", True),
                        ("date_nd1__lte", models.F("date_nd2")),
                        _connector="OR",
                    ),
                    models.Q(
                        ("date_d_zero__isnull", True),
                        ("date_nd2__isnull", True),
                        ("date_d_zero__lte", models.F("date_nd2")),
                        _connector="OR",
                    ),
                ),
                name="evenementanimal_dates_desinfection_order",
                violation_error_message="Les dates D0, ND1 et ND2 doivent respecter l'ordre D0 ≤ ND1 ≤ ND2.",
            ),
        ),
    ]
