# Generated by Django 6.0.7 on 2026-09-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0011_evenementanimal_date_d_zero_evenementanimal_date_nd1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementanimal",
            name="date_nd",
            field=models.DateField(blank=True, null=True, verbose_name="Date ND"),
        ),
    ]
