# Generated by Django 6.0.7 on 2026-09-01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0011_evenementanimal_date_d_zero_evenementanimal_date_nd1_and_more"),
        ("sa", "0011_merge_20260831_1633"),
    ]

    operations = []
