# Generated by Django 6.0.7 on 2026-08-31 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0012_methode_analyse"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analyse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_prelevement", models.DateField(verbose_name="Date du prélèvement")),
                ("date_resultat", models.DateField(blank=True, null=True, verbose_name="Date du résultat")),
                (
                    "resultat",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("detecte", "Détecté"),
                            ("detecte_faible", "Détecté faible"),
                            ("non_detecte", "Non détecté"),
                            ("non_interpretable", "Non interprétable"),
                        ],
                        max_length=50,
                        verbose_name="Résultat",
                    ),
                ),
                (
                    "resultat_confirmation",
                    models.BooleanField(default=False, verbose_name="Résultat valant confirmation"),
                ),
                (
                    "evenement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="sa.evenementanimal",
                        verbose_name="Événement",
                    ),
                ),
                (
                    "laboratoire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analyses",
                        to="sa.laboratoire",
                        verbose_name="Laboratoire",
                    ),
                ),
                (
                    "maladie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analyses",
                        to="sa.maladie",
                        verbose_name="Maladie",
                    ),
                ),
                (
                    "methode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analyses",
                        to="sa.methodeanalyse",
                        verbose_name="Méthode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analyse",
                "verbose_name_plural": "Analyses",
            },
        ),
    ]
