# Generated by Django 6.0.7 on 2026-09-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0066_remove_contact_contact_agent_email_only_and_more"),
        ("sa", "0012_methode_analyse"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementanimal",
            name="contacts",
            field=models.ManyToManyField(blank=True, to="core.contact", verbose_name="Contacts"),
        ),
    ]
