# Generated by Django 6.0.7 on 2026-09-01 09:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0010_analyse"),
        ("sa", "0012_merge_20260901_0953"),
    ]

    operations = []
