# Sync Laboratoire display data and seed the Laboratoire <-> MethodeAnalyse mapping
# from the "Mapping laboratoires x methodes" reference dataset.
from django.db import migrations

# Renames the compound source labels seeded by 0009_methode_analyse into the clean,
# single display labels used by the reference dataset.
RENAME_METHODES = {
    "ELISA ; ELISA (gB et gE) ; ELISA Stimulation Interféron Gamma": "ELISA",
    "PCR temps réel ; RT-PCR ; RT-PCR temps réel ; RT-PCR en temps réel": "PCR",
    "Bactériologie et isolement ; Bactériologie : Isolement et identification ; Bactériologie : Recherche et isolement": "Bactériologie (isolement)",
    "Séroneutralisation virale ; Neutralisation virale": "Séroneutralisation virale",
    "Immunofluorescence indirect ; Isolement sur culture cellulaire et identification par immunofluorescence": "Immunofluorescence",
    "Histologie ; Histopathologie : Coloration à l'hémalun-éosine-safran et coloration de Ziehl-Neelsen": "Histologie",
    "IHA (Inhibition de l'hémagglutination)": "Inhibition de l’hémagglutination (IHA)",
    "IDG (Immunodiffusion en gélose)": "Immunodiffusion en gélose (IDG)",
    "EAT": "Épreuve à l’antigène tamponné (EAT)",
    "FC ; Fixation du complément": "Fixation du complément (FC)",
    "Digestion artificielle de prélèvements musculaires et observation microscopique": "Digestion artificielle",
    "test ESB 1 Biorad TeSeE SAP ; test ESB 2 Prionics® Check Western ; test ESB 4 Prionics® Check PrioSTRIP ; test ESB 5 Herdchek- antigen EIA IDEXX": "Tests ESB",
    "test ESST 1 BioradTeSsE Sheep/Goat ; test ESST 2 BioradTeSsE SAP ; test ESST 3 Herdchek-Antigen EIA IDEXX": "Tests ESST",
}

# (external_id, code, name, laboratoire_type)
LABORATOIRES = [
    ("LNR_CIRAD_MONTPELLIER_UMR_ASTRE", "LNR_CIRAD_MONTPELLIER_UMR_ASTRE", "CIRAD Montpellier (UMR ASTRE)", "lnr"),
    ("LNR_IFREMER_LA_TREMBLADE", "LNR_IFREMER_LA_TREMBLADE", "IFREMER La Tremblade", "lnr"),
    ("LNR_ANSES_LYON", "LNR_ANSES_LYON", "ANSES Lyon", "lnr"),
    (
        "LNR_ANSES_PLOUFRAGAN_PLOUZANE_NIORT",
        "LNR_ANSES_PLOUFRAGAN_PLOUZANE_NIORT",
        "ANSES Ploufragan - Plouzané - Niort",
        "lnr",
    ),
    ("LNR_ANSES_SOPHIA_ANTIPOLIS", "LNR_ANSES_SOPHIA_ANTIPOLIS", "ANSES Sophia-Antipolis", "lnr"),
    ("LNR_ANSES_NANCY", "LNR_ANSES_NANCY", "ANSES Nancy", "lnr"),
    (
        "LNR_ANSES_NORMANDIE_GOUSTRAINVILLE",
        "LNR_ANSES_NORMANDIE_GOUSTRAINVILLE",
        "ANSES Normandie (Goustrainville)",
        "lnr",
    ),
    ("LNR_ANSES_MAISONS_ALFORT", "LNR_ANSES_MAISONS_ALFORT", "ANSES Maisons-Alfort", "lnr"),
    ("LAB_AGREE_BIOCV_35", "BIOCV 35", "BIO Chêne Vert (BIOCV 35)", "lda"),
    ("LAB_AGREE_CIAL_32", "CIAL 32", "AGROLAB'S AUCH (CIAL 32)", "lda"),
    ("LAB_AGREE_CIRAD_971", "CIRAD 971", "CIRAD 971", "lda"),
    ("LAB_AGREE_LDA_03", "LDA 03", "Eurofins laboratoire coeur de France (LDA 03)", "lda"),
    ("LAB_AGREE_GALILAIT_63", "GALILAIT 63", "GALILAIT 63", "lda"),
    ("LAB_AGREE_LDA_12", "LDA 12", "GIP AVEYRON LABO (LDA 12)", "lda"),
    ("LAB_AGREE_GIR_49", "GIR 49", "GIRPA (GIR 49)", "lda"),
    ("LAB_AGREE_LDA_49", "LDA 49", "INOVALYS - Angers (LDA 49)", "lda"),
    ("LAB_AGREE_LDA_72", "LDA 72", "INOVALYS - Le Mans (LDA 72)", "lda"),
    ("LAB_AGREE_LDA_44", "LDA 44", "INOVALYS - Nantes (LDA 44)", "lda"),
    ("LAB_AGREE_LDA_37", "LDA 37", "INOVALYS - Tours (LDA 37)", "lda"),
    ("LAB_AGREE_LDA_56B", "LDA 56B", "INOVALYS - Lorient (LDA 56B)", "lda"),
    ("LAB_AGREE_LDA_56A", "LDA 56A", "INOVALYS - Vannes (LDA 56A)", "lda"),
    ("LAB_AGREE_LDA_27", "LDA 27", "LABEO Eure (LDA 27)", "lda"),
    ("LAB_AGREE_LDA_14", "LDA 14", "LABEO Frank DUNCOMBE (LDA 14)", "lda"),
    ("LAB_AGREE_LDA_50", "LDA 50", "LABEO Manche (LDA 50)", "lda"),
    ("LAB_AGREE_LDA_61", "LDA 61", "LABEO Orne (LDA 61)", "lda"),
    ("LAB_AGREE_LABI_76", "LABI 76", "LABONOR (LABI 76)", "lda"),
    ("LAB_AGREE_LDA_22", "LDA 22", "LABOCEA (LDA 22)", "lda"),
    ("LAB_AGREE_LDA_29A", "LDA 29A", "LABOCEA (LDA 29A)", "lda"),
    ("LAB_AGREE_LDA_35", "LDA 35", "LABOCEA (LDA 35)", "lda"),
    ("LAB_AGREE_LDA_01A", "LDA 01A", "LDA 01A", "lda"),
    ("LAB_AGREE_LDA_01B", "LDA 01B", "LDA 01B", "lda"),
    ("LAB_AGREE_LDA_02", "LDA 02", "LDA 02", "lda"),
    ("LAB_AGREE_LDA_04", "LDA 04", "LDA 04", "lda"),
    ("LAB_AGREE_LDA_05", "LDA 05", "LDA 05", "lda"),
    ("LAB_AGREE_LDA_06", "LDA 06", "LDA 06", "lda"),
    ("LAB_AGREE_LDA_08", "LDA 08", "LDA 08", "lda"),
    ("LAB_AGREE_LDA_09", "LDA 09", "LDA 09", "lda"),
    ("LAB_AGREE_LDA_10", "LDA 10", "LDA 10", "lda"),
    ("LAB_AGREE_LDA_11", "LDA 11", "LDA 11", "lda"),
    ("LAB_AGREE_LDA_13", "LDA 13", "LDA 13", "lda"),
    ("LAB_AGREE_LDA_16", "LDA 16", "LDA 16", "lda"),
    ("LAB_AGREE_LDA_20A", "LDA 20a", "Laboratoire d’Analyses Pumonte (LA2A) (LDA 20a)", "lda"),
    ("LAB_AGREE_LDA_20B", "LDA 20b", "Laboratoire d’Analyses CISMONTE (LDA 20b)", "lda"),
    ("LAB_AGREE_LDA_21", "LDA 21", "LDA 21", "lda"),
    ("LAB_AGREE_LDA_24", "LDA 24", "LDA 24", "lda"),
    ("LAB_AGREE_LDA_25", "LDA 25", "LDA 25", "lda"),
    ("LAB_AGREE_LDA_30", "LDA 30", "LDA 30", "lda"),
    ("LAB_AGREE_LDA_31", "LDA 31", "LDA 31", "lda"),
    ("LAB_AGREE_LDA_33A", "LDA 33A", "LDA 33A", "lda"),
    ("LAB_AGREE_LDA_33B", "LDA 33B", "LDA 33B", "lda"),
    ("LAB_AGREE_LDA_34", "LDA 34", "LDA 34", "lda"),
    ("LAB_AGREE_LDA_38", "LDA 38", "LDA 38", "lda"),
    ("LAB_AGREE_LDA_39", "LDA 39", "LDA 39", "lda"),
    ("LAB_AGREE_LDA_41", "LDA 41", "LDA 41", "lda"),
    ("LAB_AGREE_LDA_48", "LDA 48", "LDA 48", "lda"),
    ("LAB_AGREE_LDA_52", "LDA 52", "LDA 52", "lda"),
    ("LAB_AGREE_LDA_53", "LDA 53", "LDA 53", "lda"),
    ("LAB_AGREE_LDA_54", "LDA 54", "LDA 54", "lda"),
    ("LAB_AGREE_LDA_55", "LDA 55", "LDA 55", "lda"),
    ("LAB_AGREE_LDA_59", "LDA 59", "LDA 59", "lda"),
    ("LAB_AGREE_LDA_62", "LDA 62", "LDA 62", "lda"),
    ("LAB_AGREE_LDA_66", "LDA 66", "Centre d’analyses Méditerranée Pyrénées Tecnosud (LDA 66)", "lda"),
    ("LAB_AGREE_LDA_70", "LDA 70", "LDA 70", "lda"),
    ("LAB_AGREE_LDA_71", "LDA 71", "SEML AGRIVALYS - LDA 71", "lda"),
    ("LAB_AGREE_LDA_73", "LDA 73", "LDA 73", "lda"),
    ("LAB_AGREE_LDA_74", "LDA 74", "LIDAL - LDA 74", "lda"),
    ("LAB_AGREE_LDA_76", "LDA 76", "LDA 76", "lda"),
    ("LAB_AGREE_LDA_80", "LDA 80", "LDA 80", "lda"),
    ("LAB_AGREE_LDA_82", "LDA 82", "LDA 82", "lda"),
    ("LAB_AGREE_LDA_83", "LDA 83", "LDA 83", "lda"),
    ("LAB_AGREE_LDA_85", "LDA 85", "LEAV (LDA 85)", "lda"),
    ("LAB_AGREE_LDA_87", "LDA 87", "LDA 87", "lda"),
    ("LAB_AGREE_LDA_88", "LDA 88", "LDA 88", "lda"),
    ("LAB_AGREE_LDA_972", "LDA 972", "LDA 972", "lda"),
    ("LAB_AGREE_LDA_974", "LDA 974", "LDA 974", "lda"),
    ("LAB_AGREE_LIAL_15", "LIAL 15", "AGROLAB'S AURILLAC (LIAL 15)", "lda"),
    ("LAB_AGREE_LIAL_RIOZ_70", "LIAL RIOZ 70", "LIAL RIOZ 70", "lda"),
    ("LAB_AGREE_LILANO_50", "LILANO 50", "LILANO 50", "lda"),
    ("LAB_AGREE_LILCO_17", "LILCO 17", "LILCO 17", "lda"),
    ("LAB_AGREE_LILLAB_35", "LILLAB 35", "MYLAB JANZE (LILLAB 35)", "lda"),
    ("LAB_AGREE_LDA_67", "LDA 67", "Laboratoire Alsacien d'Analyses - Strasbourg (L2A) (LDA 67)", "lda"),
    ("LAB_AGREE_LDA_68", "LDA 68", "Laboratoire Alsacien d'Analyses - Colmar (L2A) (LDA 68)", "lda"),
    ("LAB_AGREE_LNCR_94", "LNCR 94", "Laboratoire National des Contrôles des Reproducteurs (LNCR 94)", "lda"),
    ("LAB_AGREE_LDA_40", "LDA 40", "Laboratoire des Pyrénées et des Landes - Mont-de-Marsan (LDA 40)", "lda"),
    ("LAB_AGREE_LDA_64", "LDA 64", "Laboratoires des Pyrénées et des Landes - Lagor (LDA 64)", "lda"),
    ("LAB_AGREE_LDA_65", "LDA 65", "Laboratoires des Pyrénées et des Landes - Tarbes (LDA 65)", "lda"),
    ("LAB_AGREE_PROGENUS", "PROGENUS", "Progenus", "lda"),
    ("LAB_AGREE_LDA_32", "LDA 32", "Public Labos - Gers (LDA 32)", "lda"),
    ("LAB_AGREE_LDA_46", "LDA 46", "Public Labos - Lot (LDA 46)", "lda"),
    ("LAB_AGREE_LDA_81", "LDA 81", "Public Labos - Tarn (LDA 81)", "lda"),
    ("LAB_AGREE_LDA_79", "LDA 79", "QUALYSE - Champdeniers (LDA 79)", "lda"),
    ("LAB_AGREE_LDA_19", "LDA 19", "QUALYSE - Tulle (LDA 19)", "lda"),
    ("LAB_AGREE_SCL_69", "SCL 69", "SCL 69", "lda"),
    ("LAB_AGREE_LDA_23", "LDA 23", "LDA 23", "lda"),
    ("LAB_AGREE_LDA_15", "LDA 15", "TERANA CANTAL (LDA 15)", "lda"),
    ("LAB_AGREE_LDA_18", "LDA 18", "TERANA CHER (LDA 18)", "lda"),
    ("LAB_AGREE_LDA_26", "LDA 26", "TERANA Drôme (LDA 26)", "lda"),
    ("LAB_AGREE_LDA_43", "LDA 43", "TERANA HAUTE-LOIRE (LDA 43)", "lda"),
    ("LAB_AGREE_LDA_36", "LDA 36", "TERANA INDRE (LDA 36)", "lda"),
    ("LAB_AGREE_LDA_42", "LDA 42", "TERANA LOIRE (LDA 42)", "lda"),
    ("LAB_AGREE_LDA_58", "LDA 58", "TERANA NIEVRE (LDA 58)", "lda"),
    ("LAB_AGREE_LDA_63", "LDA 63", "TERANA PUY-DE-DÔME (LDA 63)", "lda"),
    ("LAB_AGREE_URIA_02", "URIA 02", "LABONOR - URIA 02", "lda"),
    ("LAB_AGREE_VET_LAP_69", "VET LAP 69", "VET AGRO SUP (VET LAP 69)", "lda"),
    ("LAB_AUTRE", "AUTRE", "AUTRE", "autre"),
]

# external_id -> list of MethodeAnalyse display labels (after renaming) available at that laboratoire
LABORATOIRE_METHODES = {
    "LNR_CIRAD_MONTPELLIER_UMR_ASTRE": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Séroneutralisation virale",
        "Immunofluorescence",
        "Histologie",
        "Inhibition de l’hémagglutination (IHA)",
        "Immunodiffusion en gélose (IDG)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Ovoculture",
        "Microscopie",
        "Examen macroscopique",
        "Digestion artificielle",
        "SAW",
        "Tests ESB",
        "Tests ESST",
    ],
    "LNR_IFREMER_LA_TREMBLADE": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Séroneutralisation virale",
        "Immunofluorescence",
        "Histologie",
        "Inhibition de l’hémagglutination (IHA)",
        "Immunodiffusion en gélose (IDG)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Ovoculture",
        "Microscopie",
        "Examen macroscopique",
        "Digestion artificielle",
        "SAW",
        "Tests ESB",
        "Tests ESST",
    ],
    "LNR_ANSES_LYON": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Séroneutralisation virale",
        "Immunofluorescence",
        "Histologie",
        "Inhibition de l’hémagglutination (IHA)",
        "Immunodiffusion en gélose (IDG)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Ovoculture",
        "Microscopie",
        "Examen macroscopique",
        "Digestion artificielle",
        "SAW",
        "Tests ESB",
        "Tests ESST",
    ],
    "LNR_ANSES_PLOUFRAGAN_PLOUZANE_NIORT": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Séroneutralisation virale",
        "Immunofluorescence",
        "Histologie",
        "Inhibition de l’hémagglutination (IHA)",
        "Immunodiffusion en gélose (IDG)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Ovoculture",
        "Microscopie",
        "Examen macroscopique",
        "Digestion artificielle",
        "SAW",
        "Tests ESB",
        "Tests ESST",
    ],
    "LNR_ANSES_SOPHIA_ANTIPOLIS": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Séroneutralisation virale",
        "Immunofluorescence",
        "Histologie",
        "Inhibition de l’hémagglutination (IHA)",
        "Immunodiffusion en gélose (IDG)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Ovoculture",
        "Microscopie",
        "Examen macroscopique",
        "Digestion artificielle",
        "SAW",
        "Tests ESB",
        "Tests ESST",
    ],
    "LNR_ANSES_NANCY": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Séroneutralisation virale",
        "Immunofluorescence",
        "Histologie",
        "Inhibition de l’hémagglutination (IHA)",
        "Immunodiffusion en gélose (IDG)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Ovoculture",
        "Microscopie",
        "Examen macroscopique",
        "Digestion artificielle",
        "SAW",
        "Tests ESB",
        "Tests ESST",
    ],
    "LNR_ANSES_NORMANDIE_GOUSTRAINVILLE": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Séroneutralisation virale",
        "Immunofluorescence",
        "Histologie",
        "Inhibition de l’hémagglutination (IHA)",
        "Immunodiffusion en gélose (IDG)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Ovoculture",
        "Microscopie",
        "Examen macroscopique",
        "Digestion artificielle",
        "SAW",
        "Tests ESB",
        "Tests ESST",
    ],
    "LNR_ANSES_MAISONS_ALFORT": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Séroneutralisation virale",
        "Immunofluorescence",
        "Histologie",
        "Inhibition de l’hémagglutination (IHA)",
        "Immunodiffusion en gélose (IDG)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Ovoculture",
        "Microscopie",
        "Examen macroscopique",
        "Digestion artificielle",
        "SAW",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_BIOCV_35": ["ELISA", "Inhibition de l’hémagglutination (IHA)"],
    "LAB_AGREE_CIAL_32": ["ELISA"],
    "LAB_AGREE_CIRAD_971": ["ELISA"],
    "LAB_AGREE_LDA_03": [
        "ELISA",
        "PCR",
        "Bactériologie (isolement)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Digestion artificielle",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_GALILAIT_63": ["ELISA"],
    "LAB_AGREE_LDA_12": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Digestion artificielle",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_49": [
        "ELISA",
        "PCR",
        "Bactériologie (isolement)",
        "Inhibition de l’hémagglutination (IHA)",
        "Immunodiffusion en gélose (IDG)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_72": [
        "ELISA",
        "PCR",
        "Bactériologie (isolement)",
        "Séroneutralisation virale",
        "Inhibition de l’hémagglutination (IHA)",
        "Immunodiffusion en gélose (IDG)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Digestion artificielle",
    ],
    "LAB_AGREE_LDA_44": [
        "ELISA",
        "PCR",
        "Bactériologie (isolement)",
        "Inhibition de l’hémagglutination (IHA)",
        "Immunodiffusion en gélose (IDG)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
    ],
    "LAB_AGREE_LDA_37": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Digestion artificielle",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_56B": ["PCR"],
    "LAB_AGREE_LDA_56A": [
        "ELISA",
        "PCR",
        "Bactériologie (isolement)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Digestion artificielle",
    ],
    "LAB_AGREE_LDA_27": ["ELISA", "PCR", "Épreuve à l’antigène tamponné (EAT)"],
    "LAB_AGREE_LDA_14": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Séroneutralisation virale",
        "Histologie",
        "Immunodiffusion en gélose (IDG)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
    ],
    "LAB_AGREE_LDA_50": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Séroneutralisation virale",
        "Épreuve à l’antigène tamponné (EAT)",
        "Digestion artificielle",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_61": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Séroneutralisation virale",
        "Immunofluorescence",
        "Immunodiffusion en gélose (IDG)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Microscopie",
        "Examen macroscopique",
        "Digestion artificielle",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LABI_76": ["ELISA"],
    "LAB_AGREE_LDA_22": [
        "ELISA",
        "PCR",
        "Bactériologie (isolement)",
        "Séroneutralisation virale",
        "Histologie",
        "Inhibition de l’hémagglutination (IHA)",
        "Immunodiffusion en gélose (IDG)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Ovoculture",
        "Digestion artificielle",
        "SAW",
    ],
    "LAB_AGREE_LDA_29A": [
        "ELISA",
        "PCR",
        "Bactériologie (isolement)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Digestion artificielle",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_01A": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Inhibition de l’hémagglutination (IHA)",
        "Immunodiffusion en gélose (IDG)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Ovoculture",
    ],
    "LAB_AGREE_LDA_01B": ["Digestion artificielle"],
    "LAB_AGREE_LDA_02": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Digestion artificielle",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_04": [
        "ELISA",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Digestion artificielle",
    ],
    "LAB_AGREE_LDA_05": [
        "ELISA",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Digestion artificielle",
    ],
    "LAB_AGREE_LDA_06": ["ELISA", "PCR", "Épreuve à l’antigène tamponné (EAT)"],
    "LAB_AGREE_LDA_08": ["ELISA", "Interféron Gamma", "Épreuve à l’antigène tamponné (EAT)", "Digestion artificielle"],
    "LAB_AGREE_LDA_09": [
        "ELISA",
        "PCR",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Digestion artificielle",
    ],
    "LAB_AGREE_LDA_10": ["ELISA", "PCR", "Épreuve à l’antigène tamponné (EAT)", "Digestion artificielle"],
    "LAB_AGREE_LDA_11": [
        "ELISA",
        "PCR",
        "Épreuve à l’antigène tamponné (EAT)",
        "Digestion artificielle",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_13": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
    ],
    "LAB_AGREE_LDA_16": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Digestion artificielle",
    ],
    "LAB_AGREE_LDA_20A": [
        "ELISA",
        "Interféron Gamma",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Digestion artificielle",
    ],
    "LAB_AGREE_LDA_20B": [
        "ELISA",
        "Interféron Gamma",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Digestion artificielle",
    ],
    "LAB_AGREE_LDA_21": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Digestion artificielle",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_24": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Séroneutralisation virale",
        "Inhibition de l’hémagglutination (IHA)",
        "Immunodiffusion en gélose (IDG)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Examen macroscopique",
        "Digestion artificielle",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_25": [
        "ELISA",
        "PCR",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Digestion artificielle",
    ],
    "LAB_AGREE_LDA_30": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Examen macroscopique",
        "Digestion artificielle",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_31": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Séroneutralisation virale",
        "Inhibition de l’hémagglutination (IHA)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Digestion artificielle",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_33A": ["PCR"],
    "LAB_AGREE_LDA_33B": [
        "ELISA",
        "Interféron Gamma",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
    ],
    "LAB_AGREE_LDA_34": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Immunofluorescence",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Examen macroscopique",
    ],
    "LAB_AGREE_LDA_38": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Examen macroscopique",
        "Digestion artificielle",
    ],
    "LAB_AGREE_LDA_39": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Épreuve à l’antigène tamponné (EAT)",
        "Microscopie",
        "Examen macroscopique",
        "Digestion artificielle",
    ],
    "LAB_AGREE_LDA_41": ["Digestion artificielle"],
    "LAB_AGREE_LDA_48": [
        "ELISA",
        "PCR",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Digestion artificielle",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_52": [
        "ELISA",
        "PCR",
        "Épreuve à l’antigène tamponné (EAT)",
        "Digestion artificielle",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_53": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Séroneutralisation virale",
        "Immunodiffusion en gélose (IDG)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Digestion artificielle",
    ],
    "LAB_AGREE_LDA_54": [
        "ELISA",
        "PCR",
        "Bactériologie (isolement)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Digestion artificielle",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_55": [
        "ELISA",
        "PCR",
        "Épreuve à l’antigène tamponné (EAT)",
        "Digestion artificielle",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_59": [
        "ELISA",
        "PCR",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Digestion artificielle",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_62": ["ELISA", "PCR", "Bactériologie (isolement)", "Épreuve à l’antigène tamponné (EAT)"],
    "LAB_AGREE_LDA_66": [
        "ELISA",
        "PCR",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Digestion artificielle",
    ],
    "LAB_AGREE_LDA_70": [
        "ELISA",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Digestion artificielle",
    ],
    "LAB_AGREE_LDA_71": ["ELISA", "PCR", "Épreuve à l’antigène tamponné (EAT)"],
    "LAB_AGREE_LDA_73": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Microscopie",
        "Examen macroscopique",
        "Digestion artificielle",
    ],
    "LAB_AGREE_LDA_74": ["ELISA", "Épreuve à l’antigène tamponné (EAT)", "Fixation du complément (FC)"],
    "LAB_AGREE_LDA_76": [
        "ELISA",
        "PCR",
        "Bactériologie (isolement)",
        "Séroneutralisation virale",
        "Immunodiffusion en gélose (IDG)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Digestion artificielle",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_80": [
        "ELISA",
        "PCR",
        "Bactériologie (isolement)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Digestion artificielle",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_82": [
        "ELISA",
        "PCR",
        "Bactériologie (isolement)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Digestion artificielle",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_83": ["ELISA", "PCR", "Épreuve à l’antigène tamponné (EAT)", "Examen macroscopique"],
    "LAB_AGREE_LDA_85": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_87": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Examen macroscopique",
        "Digestion artificielle",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_88": ["ELISA", "PCR", "Épreuve à l’antigène tamponné (EAT)", "Digestion artificielle"],
    "LAB_AGREE_LDA_972": [
        "ELISA",
        "Bactériologie (isolement)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Digestion artificielle",
    ],
    "LAB_AGREE_LDA_974": ["ELISA", "Épreuve à l’antigène tamponné (EAT)", "Digestion artificielle"],
    "LAB_AGREE_LIAL_15": ["ELISA"],
    "LAB_AGREE_LIAL_RIOZ_70": ["ELISA"],
    "LAB_AGREE_LILANO_50": ["ELISA"],
    "LAB_AGREE_LILCO_17": ["ELISA"],
    "LAB_AGREE_LILLAB_35": ["ELISA"],
    "LAB_AGREE_LDA_67": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Séroneutralisation virale",
        "Immunodiffusion en gélose (IDG)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Examen macroscopique",
        "Digestion artificielle",
    ],
    "LAB_AGREE_LDA_68": ["ELISA", "PCR", "Microscopie", "Examen macroscopique", "Digestion artificielle"],
    "LAB_AGREE_LNCR_94": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Séroneutralisation virale",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "SAW",
    ],
    "LAB_AGREE_LDA_40": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Immunofluorescence",
        "Inhibition de l’hémagglutination (IHA)",
        "Immunodiffusion en gélose (IDG)",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_64": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Séroneutralisation virale",
        "Immunodiffusion en gélose (IDG)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Microscopie",
        "Examen macroscopique",
        "Digestion artificielle",
    ],
    "LAB_AGREE_LDA_65": [
        "ELISA",
        "Interféron Gamma",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
    ],
    "LAB_AGREE_LDA_32": ["ELISA", "Interféron Gamma", "Épreuve à l’antigène tamponné (EAT)", "Digestion artificielle"],
    "LAB_AGREE_LDA_46": ["ELISA", "Interféron Gamma", "PCR", "Épreuve à l’antigène tamponné (EAT)"],
    "LAB_AGREE_LDA_81": [
        "ELISA",
        "PCR",
        "Bactériologie (isolement)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Digestion artificielle",
        "Tests ESB",
    ],
    "LAB_AGREE_LDA_79": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Examen macroscopique",
        "Digestion artificielle",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_19": ["ELISA", "Interféron Gamma", "PCR", "Bactériologie (isolement)", "Examen macroscopique"],
    "LAB_AGREE_LDA_23": [
        "ELISA",
        "PCR",
        "Bactériologie (isolement)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_LDA_15": [
        "ELISA",
        "PCR",
        "Bactériologie (isolement)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Digestion artificielle",
    ],
    "LAB_AGREE_LDA_18": ["ELISA", "PCR", "Épreuve à l’antigène tamponné (EAT)"],
    "LAB_AGREE_LDA_26": [
        "ELISA",
        "PCR",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Examen macroscopique",
        "Digestion artificielle",
    ],
    "LAB_AGREE_LDA_43": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
    ],
    "LAB_AGREE_LDA_36": ["ELISA", "Épreuve à l’antigène tamponné (EAT)", "Digestion artificielle"],
    "LAB_AGREE_LDA_42": [
        "ELISA",
        "PCR",
        "Bactériologie (isolement)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Digestion artificielle",
    ],
    "LAB_AGREE_LDA_58": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Séroneutralisation virale",
        "Immunodiffusion en gélose (IDG)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Digestion artificielle",
    ],
    "LAB_AGREE_LDA_63": [
        "ELISA",
        "PCR",
        "Bactériologie (isolement)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Microscopie",
        "Examen macroscopique",
        "Digestion artificielle",
        "Tests ESB",
        "Tests ESST",
    ],
    "LAB_AGREE_URIA_02": ["ELISA"],
    "LAB_AGREE_VET_LAP_69": ["Histologie"],
    "LAB_AUTRE": [
        "ELISA",
        "Interféron Gamma",
        "PCR",
        "Bactériologie (isolement)",
        "Séroneutralisation virale",
        "Immunofluorescence",
        "Histologie",
        "Inhibition de l’hémagglutination (IHA)",
        "Immunodiffusion en gélose (IDG)",
        "Épreuve à l’antigène tamponné (EAT)",
        "Fixation du complément (FC)",
        "Ovoculture",
        "Microscopie",
        "Examen macroscopique",
        "Digestion artificielle",
        "SAW",
        "Tests ESB",
        "Tests ESST",
    ],
}


def populate_laboratoire_methode_mapping(apps, schema_editor):
    Laboratoire = apps.get_model("sa", "Laboratoire")
    MethodeAnalyse = apps.get_model("sa", "MethodeAnalyse")

    for old_label, new_label in RENAME_METHODES.items():
        MethodeAnalyse.objects.filter(libelle=old_label).update(libelle=new_label)

    for external_id, code, name, laboratoire_type in LABORATOIRES:
        Laboratoire.objects.filter(external_id=external_id).update(
            code=code, name=name, laboratoire_type=laboratoire_type
        )

    for external_id, libelles in LABORATOIRE_METHODES.items():
        laboratoire = Laboratoire.objects.get(external_id=external_id)
        methodes = MethodeAnalyse.objects.filter(libelle__in=libelles)
        laboratoire.methodes_analyse.set(methodes)


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0013_analyse"),
    ]

    operations = [
        migrations.RunPython(populate_laboratoire_methode_mapping, migrations.RunPython.noop),
    ]
