# Generated by Django 6.0.7 on 2026-09-04 13:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0014_populate_laboratoire_methode_mapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementanimal",
            name="date_cloture_adis",
            field=models.DateField(blank=True, null=True, verbose_name="Date clôture ADIS"),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="date_notification_adis",
            field=models.DateField(blank=True, null=True, verbose_name="Date de notification ADIS"),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="effectif_retenu",
            field=models.IntegerField(blank=True, null=True, verbose_name="Effectif retenu notification ADIS"),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="foyer",
            field=models.CharField(
                blank=True,
                choices=[("primaire", "Primaire"), ("secondaire", "Secondaire")],
                max_length=100,
                verbose_name="Foyer",
            ),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="mesures_controle",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        (
                            "Ante and post-mortem inspections",
                            "Inspections ante mortem et post mortem",
                        ),
                        ("Compartmentalisation", "Compartimentation"),
                        ("Control of vectors", "Contrôle des vecteurs"),
                        (
                            "Control of wildlife reservoirs",
                            "Contrôle des réservoirs de la faune sauvage",
                        ),
                        (
                            "Decontamination of premises / Disinfection",
                            "Décontamination des locaux / désinfection",
                        ),
                        (
                            "Dipping / Spraying for control of vectors or parasites",
                            "Bains / pulvérisations pour lutter contre les vecteurs ou les parasites",
                        ),
                        ("Disease notification", "Notification d’une maladie"),
                        ("Disinfection", "Désinfection"),
                        (
                            "Disinfection / Disinfestation",
                            "Désinfection / désinfestation",
                        ),
                        ("Disinfestation", "Désinfestation"),
                        ("Emergency harvest", "Récolte d’urgence"),
                        ("General Surveillance", "Surveillance générale"),
                        (
                            "Killing for commercial use or own use",
                            "Abattage à des fins commerciales ou pour usage personnel",
                        ),
                        ("Monitoring", "Suivi"),
                        ("Movement control", "Contrôle des mouvements"),
                        (
                            "Official destruction of animal products",
                            "Destruction officielle des produits animaux",
                        ),
                        (
                            "Official disposal of carcasses, by-products and waste",
                            "Élimination officielle des carcasses, sous-produits animaux et déchets",
                        ),
                        ("Official vaccination", "Vaccination officielle"),
                        (
                            "Precautions at the borders",
                            "Mesures de précaution aux frontières",
                        ),
                        (
                            "Process to inactivate the pathogenic agent in products or by-products",
                            "Procédé d’inactivation de l’agent pathogène dans les produits ou sous-produits animaux",
                        ),
                        ("Quarantine", "Quarantaine"),
                        ("Screening", "Dépistage"),
                        (
                            "Selective killing and disposal",
                            "Abattage sélectif et élimination",
                        ),
                        ("Slaughter", "Abattage ciblé d’animaux infectés ou suspects"),
                        ("Stamping out", "Abattage sanitaire total du foyer"),
                        (
                            "Surveillance outside the restricted zone",
                            "Surveillance hors de la zone de restriction",
                        ),
                        (
                            "Surveillance within the restricted zone",
                            "Surveillance à l’intérieur de la zone de restriction",
                        ),
                        ("Targeted Surveillance", "Surveillance ciblée"),
                        ("Traceability", "Traçabilité"),
                        ("Treatment", "Traitement"),
                        ("Vaccination", "Vaccination"),
                        (
                            "Vaccination in response to the outbreak(s)",
                            "Vaccination en réponse à un ou plusieurs foyers",
                        ),
                        ("Vaccination prohibited", "Vaccination interdite"),
                        ("Vector surveillance", "Surveillance des vecteurs"),
                        ("Zoning", "Zonage"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
            ),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="numero_adis",
            field=models.CharField(blank=True, max_length=255, verbose_name="Numéro ADIS"),
        ),
        migrations.AddField(
            model_name="evenementanimal",
            name="origine_infection",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CONTACT_DIRECT", "Contact direct"),
                    ("IMPORTATION", "Importation"),
                    ("INCONNUE", "Inconnue"),
                    ("INTERVENTION_HUMAINE", "Intervention humaine"),
                    ("VECTEUR", "Vecteur"),
                ],
                max_length=100,
                verbose_name="Origine de l'infection",
            ),
        ),
    ]
