# Generated by Django 6.0.7 on 2026-09-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0015_populate_espece"),
    ]

    operations = [
        migrations.AddField(
            model_name="espece",
            name="is_highlighted",
            field=models.BooleanField(default=False, verbose_name="Espèce courante"),
        ),
        migrations.AddField(
            model_name="maladie",
            name="especes_concernees",
            field=models.ManyToManyField(
                blank=True, related_name="maladies_concernees", to="sa.espece", verbose_name="Espèces concernées"
            ),
        ),
    ]
