# Generated by Django 6.0.7 on 2026-09-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0066_remove_contact_contact_agent_email_only_and_more"),
        ("sa", "0016_populate_espece"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementanimal",
            name="contacts",
            field=models.ManyToManyField(blank=True, to="core.contact", verbose_name="Contacts"),
        ),
    ]
