# Generated by Django 6.0.7 on 2026-09-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0017_evenementanimal_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementanimal",
            name="date_nd",
            field=models.DateField(blank=True, null=True, verbose_name="Date ND"),
        ),
    ]
