# Generated by Django 6.0.7 on 2026-09-04 12:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0065_create_sa_group"),
        ("sa", "0017_evenementanimal_contacts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Veterinaire",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type_veterinaire",
                    models.CharField(
                        choices=[("sanitaire", "Sanitaire"), ("mandate", "Mandaté")],
                        default="sanitaire",
                        max_length=20,
                        verbose_name="Type de vétérinaire",
                    ),
                ),
                ("nom_structure", models.CharField(max_length=255, verbose_name="Nom de la structure")),
                ("numero_dpe", models.CharField(blank=True, max_length=255, verbose_name="N° DPE")),
                ("adresse_lieu_dit", models.CharField(blank=True, max_length=255, verbose_name="Adresse ou lieu-dit")),
                ("commune", models.CharField(blank=True, max_length=100, verbose_name="Commune")),
                (
                    "code_insee",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_code_insee",
                                message="Le code INSEE doit contenir exactement 5 chiffres",
                                regex="^[0-9]{5}$",
                            )
                        ],
                        verbose_name="Code INSEE",
                    ),
                ),
                (
                    "telephone_structure",
                    models.CharField(blank=True, max_length=20, verbose_name="Numéro de téléphone"),
                ),
                ("courriel_structure", models.EmailField(blank=True, max_length=254, verbose_name="Courriel")),
                ("nom", models.CharField(blank=True, max_length=255, verbose_name="Nom")),
                ("prenom", models.CharField(blank=True, max_length=255, verbose_name="Prénom")),
                ("telephone", models.CharField(blank=True, max_length=20, verbose_name="Numéro de téléphone")),
                ("courriel", models.EmailField(blank=True, max_length=254, verbose_name="Courriel")),
                (
                    "departement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sa_veterinaires",
                        to="core.departement",
                        verbose_name="Département",
                    ),
                ),
                (
                    "especes",
                    models.ManyToManyField(
                        blank=True, related_name="veterinaires", to="sa.espece", verbose_name="Espèces"
                    ),
                ),
                (
                    "evenement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veterinaires",
                        to="sa.evenementanimal",
                        verbose_name="Événement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vétérinaire",
                "verbose_name_plural": "Vétérinaires",
            },
        ),
    ]
