from django.db import migrations

MALADIE_ESPECES = {
    "Acarapiose des abeilles (Acarapis woodi)": ["Abeille mellifère (Apis mellifera)"],
    "Adénomatose pulmonaire ovine": ["Ovin (Ovis aries)"],
    "Agalaxie contagieuse": ["Ovin (Ovis aries)", "Caprin (Capra hircus)"],
    "Anaplasmose bovine": ["Bovin (Bos taurus)", "Buffle (Bubalus bubalis)"],
    "Anémie infectieuse des équidés": ["Cheval (Equus caballus)", "Âne (Equus asinus)"],
    "Artérite virale équine": ["Cheval (Equus caballus)", "Âne (Equus asinus)"],
    "Arthrite-encéphalite caprine": ["Caprin (Capra hircus)"],
    "Babésiose bovine": ["Bovin (Bos taurus)", "Buffle (Bubalus bubalis)"],
    "Botulisme": [
        "Bovin (Bos taurus)",
        "Cheval (Equus caballus)",
        "Ovin (Ovis aries)",
        "Poule/poulet (Gallus gallus)",
        "Canard colvert (Anas platyrhynchos)",
    ],
    "Bronchite infectieuse aviaire": ["Poule/poulet (Gallus gallus)"],
    "Brucellose": [
        "Bovin (Bos taurus)",
        "Buffle (Bubalus bubalis)",
        "Ovin (Ovis aries)",
        "Caprin (Capra hircus)",
        "Porc (Sus scrofa domesticus)",
        "Sanglier (Sus scrofa)",
    ],
    "Brucellose canine": ["Chien (Canis lupus familiaris)"],
    "Bursite infectieuse - Maladie de Gumboro": ["Poule/poulet (Gallus gallus)"],
    "Campylobactériose génitale bovine": ["Bovin (Bos taurus)", "Buffle (Bubalus bubalis)"],
    "Chlamydiose abortive (Chlamydia abortus)": ["Ovin (Ovis aries)", "Caprin (Capra hircus)"],
    "Chlamydiose aviaire": [
        "Pigeon biset (Columba livia)",
        "Dinde (Meleagris gallopavo)",
        "Canard colvert (Anas platyrhynchos)",
        "Canard de Pékin (Anas platyrhynchos domesticus)",
        "Poule/poulet (Gallus gallus)",
    ],
    "Choléra aviaire (Pasteurella multocida)": [
        "Poule/poulet (Gallus gallus)",
        "Dinde (Meleagris gallopavo)",
        "Canard colvert (Anas platyrhynchos)",
        "Canard de Pékin (Anas platyrhynchos domesticus)",
        "Oie domestique (Anser anser)",
        "Caille commune (Coturnix coturnix)",
        "Faisan commun (Phasianus colchicus)",
    ],
    "Clavelée et variole caprine": ["Ovin (Ovis aries)", "Caprin (Capra hircus)"],
    "Coryza gangreneux": [
        "Bovin (Bos taurus)",
        "Buffle (Bubalus bubalis)",
        "Cerf (Cervus elaphus)",
        "Ovin (Ovis aries)",
    ],
    "Cowdriose": ["Bovin (Bos taurus)", "Buffle (Bubalus bubalis)", "Ovin (Ovis aries)", "Caprin (Capra hircus)"],
    "Cysticercose porcine": ["Porc (Sus scrofa domesticus)"],
    "Dermatophilose": ["Bovin (Bos taurus)", "Ovin (Ovis aries)", "Caprin (Capra hircus)", "Cheval (Equus caballus)"],
    "Dermatose nodulaire contagieuse": ["Bovin (Bos taurus)", "Buffle (Bubalus bubalis)"],
    "Diarrhée épizootique porcine": ["Porc (Sus scrofa domesticus)"],
    "Diarrhée virale bovine": ["Bovin (Bos taurus)", "Buffle (Bubalus bubalis)"],
    "Dourine": ["Cheval (Equus caballus)", "Âne (Equus asinus)"],
    "Echinococcose": [
        "Chien (Canis lupus familiaris)",
        "Ovin (Ovis aries)",
        "Bovin (Bos taurus)",
        "Caprin (Capra hircus)",
    ],
    "Encéphalite à virus Nipah": ["Porc (Sus scrofa domesticus)"],
    "Encéphalite japonaise": ["Porc (Sus scrofa domesticus)", "Cheval (Equus caballus)", "Âne (Equus asinus)"],
    "Encéphalomyélite à entérovirus - Maladie de Teschen": ["Porc (Sus scrofa domesticus)", "Sanglier (Sus scrofa)"],
    "Encéphalomyélite équine": ["Cheval (Equus caballus)", "Âne (Equus asinus)"],
    "Encéphalomyélite équine vénézuélienne": ["Cheval (Equus caballus)", "Âne (Equus asinus)"],
    "Encéphalopathie spongiforme bovine": ["Bovin (Bos taurus)"],
    "Entérite virale du canard": [
        "Canard colvert (Anas platyrhynchos)",
        "Canard de Barbarie (Musqué) (Cairina moschata)",
        "Canard de Pékin (Anas platyrhynchos domesticus)",
        "Canard mulard",
        "Oie domestique (Anser anser)",
        "Oie de Chine (Anser cygnoides)",
    ],
    "Épididymite ovine (Brucella ovis)": ["Ovin (Ovis aries)"],
    "Fièvre aphteuse": [
        "Bovin (Bos taurus)",
        "Buffle (Bubalus bubalis)",
        "Ovin (Ovis aries)",
        "Caprin (Capra hircus)",
        "Porc (Sus scrofa domesticus)",
        "Sanglier (Sus scrofa)",
        "Cerf (Cervus elaphus)",
        "Chevreuil (Capreolus capreolus)",
    ],
    "Fièvre catarrhale ovine": [
        "Ovin (Ovis aries)",
        "Bovin (Bos taurus)",
        "Caprin (Capra hircus)",
        "Cerf (Cervus elaphus)",
        "Chevreuil (Capreolus capreolus)",
    ],
    "Fièvre charbonneuse - charbon (Bacillus anthracis)": [
        "Bovin (Bos taurus)",
        "Buffle (Bubalus bubalis)",
        "Ovin (Ovis aries)",
        "Caprin (Capra hircus)",
        "Cheval (Equus caballus)",
        "Cerf (Cervus elaphus)",
        "Chameau (Camelus bactrianus)",
        "Dromadaire (Camelus dromedarius)",
    ],
    "Fièvre de la vallée du Rift": [
        "Bovin (Bos taurus)",
        "Buffle (Bubalus bubalis)",
        "Ovin (Ovis aries)",
        "Caprin (Capra hircus)",
        "Chameau (Camelus bactrianus)",
        "Dromadaire (Camelus dromedarius)",
    ],
    "Fièvre de West Nile": [
        "Cheval (Equus caballus)",
        "Âne (Equus asinus)",
        "Pigeon biset (Columba livia)",
        "Canard colvert (Anas platyrhynchos)",
        "Oie domestique (Anser anser)",
    ],
    "Fièvre hémorragique de Crimée-Congo": [
        "Bovin (Bos taurus)",
        "Buffle (Bubalus bubalis)",
        "Ovin (Ovis aries)",
        "Caprin (Capra hircus)",
        "Chameau (Camelus bactrianus)",
        "Dromadaire (Camelus dromedarius)",
    ],
    "Fièvre Q": ["Bovin (Bos taurus)", "Ovin (Ovis aries)", "Caprin (Capra hircus)"],
    "Gale du cheval": ["Cheval (Equus caballus)", "Âne (Equus asinus)"],
    "Gastro-entérite transmissible des porcs": ["Porc (Sus scrofa domesticus)", "Sanglier (Sus scrofa)"],
    "Grippe équine": ["Cheval (Equus caballus)", "Âne (Equus asinus)"],
    "Hépatite virale du canard": [
        "Canard colvert (Anas platyrhynchos)",
        "Canard de Pékin (Anas platyrhynchos domesticus)",
        "Canard mulard",
    ],
    "Hypodermose clinique": ["Bovin (Bos taurus)"],
    "Infestation par le petit coléoptère des ruches (Aethina tumida)": ["Abeille mellifère (Apis mellifera)"],
    "Influenza aviaire faiblement pathogène": [
        "Poule/poulet (Gallus gallus)",
        "Dinde (Meleagris gallopavo)",
        "Canard colvert (Anas platyrhynchos)",
        "Canard de Barbarie (Musqué) (Cairina moschata)",
        "Canard de Pékin (Anas platyrhynchos domesticus)",
        "Canard mulard",
        "Oie domestique (Anser anser)",
        "Oie de Chine (Anser cygnoides)",
        "Caille commune (Coturnix coturnix)",
    ],
    "Influenza aviaire hautement pathogène": [
        "Poule/poulet (Gallus gallus)",
        "Dinde (Meleagris gallopavo)",
        "Canard colvert (Anas platyrhynchos)",
        "Canard de Barbarie (Musqué) (Cairina moschata)",
        "Canard de Pékin (Anas platyrhynchos domesticus)",
        "Canard mulard",
        "Oie domestique (Anser anser)",
        "Oie de Chine (Anser cygnoides)",
        "Caille commune (Coturnix coturnix)",
        "Faisan commun (Phasianus colchicus)",
        "Pintade commune (Numida meleagris)",
        "Pigeon biset (Columba livia)",
        "Autruche (Struthio camelus)",
        "Émeu (Dromaius novaehollandiae)",
    ],
    "Laryngotrachéite infectieuse aviaire": ["Poule/poulet (Gallus gallus)", "Faisan commun (Phasianus colchicus)"],
    "Leishmaniose": ["Chien (Canis lupus familiaris)", "Chat domestique (Felis catus)"],
    "Leucose bovine enzootique": ["Bovin (Bos taurus)", "Buffle (Bubalus bubalis)"],
    "Loque américaine des abeilles (Paenibacillus larvae)": ["Abeille mellifère (Apis mellifera)"],
    "Loque européenne des abeilles (Melissococcus plutonius)": ["Abeille mellifère (Apis mellifera)"],
    "Lucilie bouchère (Cochliomyia hominivorax)": [
        "Bovin (Bos taurus)",
        "Ovin (Ovis aries)",
        "Caprin (Capra hircus)",
        "Porc (Sus scrofa domesticus)",
        "Cheval (Equus caballus)",
        "Chien (Canis lupus familiaris)",
    ],
    "Lymphangite épizootique des équidés": ["Cheval (Equus caballus)", "Âne (Equus asinus)"],
    "Maedi-visna": ["Ovin (Ovis aries)"],
    "Maladie d'Aujeszky": [
        "Porc (Sus scrofa domesticus)",
        "Sanglier (Sus scrofa)",
        "Chien (Canis lupus familiaris)",
        "Chat domestique (Felis catus)",
    ],
    "Maladie de Marek": ["Poule/poulet (Gallus gallus)"],
    "Maladie de Newcastle": [
        "Poule/poulet (Gallus gallus)",
        "Dinde (Meleagris gallopavo)",
        "Pigeon biset (Columba livia)",
        "Caille commune (Coturnix coturnix)",
        "Faisan commun (Phasianus colchicus)",
        "Pintade commune (Numida meleagris)",
        "Canard colvert (Anas platyrhynchos)",
        "Canard de Pékin (Anas platyrhynchos domesticus)",
        "Oie domestique (Anser anser)",
        "Autruche (Struthio camelus)",
        "Émeu (Dromaius novaehollandiae)",
    ],
    "Maladie des moutons de Nairobi": ["Ovin (Ovis aries)", "Caprin (Capra hircus)"],
    "Maladie hémorragique épizootique": [
        "Cerf (Cervus elaphus)",
        "Chevreuil (Capreolus capreolus)",
        "Bovin (Bos taurus)",
    ],
    "Maladie hémorragique virale du lapin": ["Lapin européen (Oryctolagus cuniculus)"],
    "Maladie vésiculeuse du porc": ["Porc (Sus scrofa domesticus)", "Sanglier (Sus scrofa)"],
    "MERS-CoV": ["Dromadaire (Camelus dromedarius)", "Chameau (Camelus bactrianus)"],
    "Métrite contagieuse équine": ["Cheval (Equus caballus)", "Âne (Equus asinus)"],
    "Morve (Burkholderia mallei)": ["Cheval (Equus caballus)", "Âne (Equus asinus)"],
    "Mycoplasmose aviaire": [
        "Poule/poulet (Gallus gallus)",
        "Dinde (Meleagris gallopavo)",
        "Caille commune (Coturnix coturnix)",
        "Faisan commun (Phasianus colchicus)",
    ],
    "Myiase à Chrysomya bezziana": [
        "Bovin (Bos taurus)",
        "Ovin (Ovis aries)",
        "Caprin (Capra hircus)",
        "Porc (Sus scrofa domesticus)",
        "Cheval (Equus caballus)",
        "Chameau (Camelus bactrianus)",
        "Dromadaire (Camelus dromedarius)",
        "Chien (Canis lupus familiaris)",
    ],
    "Myxomatose": ["Lapin européen (Oryctolagus cuniculus)"],
    "Nosémose des abeilles": ["Abeille mellifère (Apis mellifera)"],
    "Paratuberculose": [
        "Bovin (Bos taurus)",
        "Buffle (Bubalus bubalis)",
        "Ovin (Ovis aries)",
        "Caprin (Capra hircus)",
        "Cerf (Cervus elaphus)",
        "Alpaga (Vicugna pacos)",
        "Lama (Lama glama)",
    ],
    "Peste bovine": ["Bovin (Bos taurus)", "Buffle (Bubalus bubalis)", "Cerf (Cervus elaphus)"],
    "Peste des petits ruminants": ["Ovin (Ovis aries)", "Caprin (Capra hircus)"],
    "Peste équine": ["Cheval (Equus caballus)", "Âne (Equus asinus)"],
    "Peste porcine africaine": ["Porc (Sus scrofa domesticus)", "Sanglier (Sus scrofa)"],
    "Peste porcine classique": ["Porc (Sus scrofa domesticus)", "Sanglier (Sus scrofa)"],
    "Piroplasmose équine": ["Cheval (Equus caballus)", "Âne (Equus asinus)"],
    "Péripneumonie contagieuse bovine": ["Bovin (Bos taurus)"],
    "Pleuropneumonie contagieuse caprine": ["Caprin (Capra hircus)"],
    "Rage": [
        "Chien (Canis lupus familiaris)",
        "Chat domestique (Felis catus)",
        "Bovin (Bos taurus)",
        "Cheval (Equus caballus)",
        "Ovin (Ovis aries)",
        "Caprin (Capra hircus)",
    ],
    "Rhinite atrophique du porc": ["Porc (Sus scrofa domesticus)"],
    "Rhinopneumonie équine": ["Cheval (Equus caballus)", "Âne (Equus asinus)"],
    "Rhinotrachéite de la dinde": ["Dinde (Meleagris gallopavo)", "Poule/poulet (Gallus gallus)"],
    "Rhinotrachéite infectieuse bovine": ["Bovin (Bos taurus)", "Buffle (Bubalus bubalis)"],
    "Salmonellose (Salmonella)": [
        "Bovin (Bos taurus)",
        "Ovin (Ovis aries)",
        "Caprin (Capra hircus)",
        "Porc (Sus scrofa domesticus)",
        "Sanglier (Sus scrofa)",
        "Poule/poulet (Gallus gallus)",
        "Dinde (Meleagris gallopavo)",
        "Canard colvert (Anas platyrhynchos)",
        "Oie domestique (Anser anser)",
        "Cheval (Equus caballus)",
        "Chien (Canis lupus familiaris)",
        "Chat domestique (Felis catus)",
    ],
    "Septicémie hémorragique du bovin (Pasteurella multocida)": ["Bovin (Bos taurus)", "Buffle (Bubalus bubalis)"],
    "Stomatite vésiculeuse du porc": ["Porc (Sus scrofa domesticus)", "Bovin (Bos taurus)", "Cheval (Equus caballus)"],
    "Surra (Trypanosoma evansi)": [
        "Cheval (Equus caballus)",
        "Âne (Equus asinus)",
        "Chameau (Camelus bactrianus)",
        "Dromadaire (Camelus dromedarius)",
        "Bovin (Bos taurus)",
        "Buffle (Bubalus bubalis)",
        "Chien (Canis lupus familiaris)",
    ],
    "Syndrome dysgénésique et respiratoire porcin": ["Porc (Sus scrofa domesticus)", "Sanglier (Sus scrofa)"],
    "Trypanosomose": [
        "Bovin (Bos taurus)",
        "Buffle (Bubalus bubalis)",
        "Ovin (Ovis aries)",
        "Caprin (Capra hircus)",
        "Cheval (Equus caballus)",
        "Âne (Equus asinus)",
        "Chameau (Camelus bactrianus)",
        "Dromadaire (Camelus dromedarius)",
    ],
    "Theilériose (Theileria)": [
        "Bovin (Bos taurus)",
        "Buffle (Bubalus bubalis)",
        "Ovin (Ovis aries)",
        "Caprin (Capra hircus)",
    ],
    "Tremblante": ["Ovin (Ovis aries)", "Caprin (Capra hircus)"],
    "Trichinellose": ["Porc (Sus scrofa domesticus)", "Sanglier (Sus scrofa)", "Cheval (Equus caballus)"],
    "Trichomonose": ["Bovin (Bos taurus)", "Buffle (Bubalus bubalis)"],
    "Tropilaelaps des abeilles": ["Abeille mellifère (Apis mellifera)"],
    "Tuberculose": [
        "Bovin (Bos taurus)",
        "Buffle (Bubalus bubalis)",
        "Cerf (Cervus elaphus)",
        "Chevreuil (Capreolus capreolus)",
        "Caprin (Capra hircus)",
        "Sanglier (Sus scrofa)",
    ],
    "Tularémie": ["Lapin européen (Oryctolagus cuniculus)", "Chat domestique (Felis catus)"],
    "Typhoïde aviaire": [
        "Poule/poulet (Gallus gallus)",
        "Dinde (Meleagris gallopavo)",
        "Pintade commune (Numida meleagris)",
        "Caille commune (Coturnix coturnix)",
    ],
    "Variole aviaire": [
        "Poule/poulet (Gallus gallus)",
        "Dinde (Meleagris gallopavo)",
        "Pigeon biset (Columba livia)",
        "Caille commune (Coturnix coturnix)",
        "Faisan commun (Phasianus colchicus)",
    ],
    "Variole du chameau": ["Chameau (Camelus bactrianus)", "Dromadaire (Camelus dromedarius)"],
    "Variole du cheval - gourme": ["Cheval (Equus caballus)", "Âne (Equus asinus)"],
    "Varroose des abeilles": ["Abeille mellifère (Apis mellifera)"],
}


def populate_especes_concernees(apps, schema_editor):
    Maladie = apps.get_model("sa", "Maladie")
    Espece = apps.get_model("sa", "Espece")

    missing_maladies = []
    missing_especes = set()
    for maladie_name, espece_names in MALADIE_ESPECES.items():
        try:
            maladie = Maladie.objects.get(name=maladie_name)
        except Maladie.DoesNotExist:
            missing_maladies.append(maladie_name)
            continue

        especes = list(Espece.objects.filter(name__in=espece_names))
        found_names = {espece.name for espece in especes}
        missing_especes.update(set(espece_names) - found_names)
        maladie.especes_concernees.set(especes)

    if missing_maladies or missing_especes:
        raise RuntimeError(
            f"Maladies introuvables: {sorted(missing_maladies)}; Espèces introuvables: {sorted(missing_especes)}"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0017_populate_espece_is_highlighted"),
    ]

    operations = [
        migrations.RunPython(populate_especes_concernees, migrations.RunPython.noop),
    ]
