# Generated by Django 6.0.7 on 2026-09-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0018_veterinaire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenementanimal",
            name="context_suspicion",
            field=models.CharField(
                blank=True,
                choices=[("ANALYTIQUE", "Analytique"), ("CLINIQUE", "Clinique")],
                max_length=100,
                null=True,
                verbose_name="Contexte de la suspicion",
            ),
        ),
    ]
