# Generated by Django 6.0.7 on 2026-09-09 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0018_veterinaire"),
    ]

    operations = [
        migrations.CreateModel(
            name="EspeceConcernee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifiant",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Identifiant",
                    ),
                ),
                (
                    "presents",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Présents"),
                ),
                (
                    "morts",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Morts"),
                ),
                (
                    "cas",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Cas"),
                ),
                (
                    "abattus",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Abattus"),
                ),
                (
                    "depeuples",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Dépeuplés/Euthanasiés"),
                ),
                (
                    "vaccines",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Vaccinés"),
                ),
                (
                    "espece",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="sa.espece"),
                ),
                (
                    "evenement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="especes_exposees",
                        to="sa.evenementanimal",
                        verbose_name="Événement",
                    ),
                ),
            ],
        ),
    ]
