# Generated by Django 6.0.7 on 2026-09-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0066_remove_contact_contact_agent_email_only_and_more"),
        ("sa", "0018_veterinaire"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="evenementanimal",
            name="evenementanimal_detenteur_etablissement_or_particulier",
        ),
        migrations.AddConstraint(
            model_name="evenementanimal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("statut_animal", "DETENU"), _negated=True),
                    models.Q(
                        models.Q(("numero_identifiant_etablissement", ""), _negated=True),
                        ("numero_identifiant_etablissement__isnull", False),
                        models.Q(
                            ("nom_particulier", ""),
                            ("nom_particulier__isnull", True),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        models.Q(
                            ("numero_identifiant_etablissement", ""),
                            ("numero_identifiant_etablissement__isnull", True),
                            _connector="OR",
                        ),
                        models.Q(("nom_particulier", ""), _negated=True),
                        ("nom_particulier__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="evenementanimal_detenteur_etablissement_or_particulier",
                violation_error_message="Un détenteur établissement ou un détenteur particulier doit être renseigné (l'un ou l'autre)",
            ),
        ),
    ]
