# Generated by Django 6.0.7 on 2026-09-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0018_veterinaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementanimal",
            name="commentaire",
            field=models.TextField(blank=True, verbose_name="Commentaire"),
        ),
    ]
