# Generated by Django 6.0.7 on 2026-09-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0021_alter_evenementanimal_context_suspicion"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementanimal",
            name="date_nd",
            field=models.DateField(blank=True, null=True, verbose_name="Date ND"),
        ),
    ]
