# Generated by Django 6.0.7 on 2026-09-16 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0023_remove_evenementanimal_evenementanimal_detenteur_etablissement_or_particulier_and_more"),
        ("sa", "0025_populate_maladie_especes_concernees"),
    ]

    operations = []
