# Generated by Django 6.0.7 on 2026-09-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0026_merge_20260916_1739"),
    ]

    operations = [
        migrations.AddField(
            model_name="espececoncernee",
            name="mode_elevage",
            field=models.CharField(blank=True, max_length=255, verbose_name="Mode d'élevage"),
        ),
        migrations.AddField(
            model_name="espececoncernee",
            name="type_elevage",
            field=models.CharField(blank=True, max_length=255, verbose_name="Type d'élevage"),
        ),
        migrations.AddField(
            model_name="espececoncernee",
            name="type_lieu",
            field=models.CharField(blank=True, max_length=255, verbose_name="Type de lieu"),
        ),
        migrations.AddField(
            model_name="espececoncernee",
            name="type_production",
            field=models.CharField(blank=True, max_length=255, verbose_name="Type de production"),
        ),
    ]
