# Generated by Django 6.0.7 on 2026-09-18 08:36

from django.db import migrations


def fix_errors_in_maladies(apps, schema_editor):
    Maladie = apps.get_model("sa", "Maladie")
    EvenementAnimal = apps.get_model("sa", "EvenementAnimal")

    Maladie.objects.filter(name="Encéphalopathie spongiforme bovine").update(needs_arrete=True)
    Maladie.objects.filter(name="Hypodermose clinique").update(name="Hypodermose bovine (varron)")
    Maladie.objects.filter(name="Variole du cheval - gourme").update(name="Variole du cheval")
    Maladie.objects.filter(name="Clavelée et variole caprine ").update(description_type="cartogip")
    Maladie.objects.filter(name="Peste des petits ruminants").update(description_type="cartogip")
    Maladie.objects.filter(name="Peste bovine").delete()
    Maladie.objects.filter(name="Fièvre hémorragique de Crimée-Congo").delete()

    maladie = Maladie.objects.filter(name="Porc").first()
    if maladie:
        new_maladie = Maladie.objects.get(name="Porc (Sus scrofa domesticus)")
        EvenementAnimal.objects.filter(maladie__id=maladie.id).update(maladie_id=new_maladie.id)
        maladie.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0026_merge_20260916_1739"),
    ]

    operations = [migrations.RunPython(fix_errors_in_maladies, migrations.RunPython.noop)]
