# Generated by Django 6.0.7 on 2026-09-18 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0027_espececoncernee_situation_unite"),
    ]

    operations = [
        migrations.CreateModel(
            name="SituationUniteRegle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type_lieu", models.CharField(max_length=255, verbose_name="Type de lieu")),
                ("mode_elevage", models.CharField(blank=True, max_length=255, verbose_name="Mode d'élevage")),
                ("type_production", models.CharField(blank=True, max_length=255, verbose_name="Type de production")),
                ("type_elevage", models.CharField(blank=True, max_length=255, verbose_name="Type d'élevage")),
                (
                    "espece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="situation_unite_regles",
                        to="sa.espece",
                    ),
                ),
            ],
            options={
                "verbose_name": "Règle de situation de l'unité",
                "verbose_name_plural": "Règles de situation de l'unité",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("espece", "type_lieu", "mode_elevage", "type_production", "type_elevage"),
                        name="unique_situation_unite_regle",
                    )
                ],
            },
        ),
    ]
