# Generated by Django 6.0.7 on 2026-09-23 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0031_update_laboratoires_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyse",
            name="methode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analyses",
                to="sa.methodeanalyse",
                verbose_name="Méthode",
            ),
        ),
    ]
