# Generated by Django 6.0.7 on 2026-09-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0032_alter_analyse_methode"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="analyse",
            constraint=models.CheckConstraint(
                condition=models.Q(("methode__isnull", False), ("resultat", "en_attente"), _connector="OR"),
                name="analyse_methode_required_unless_en_attente",
                violation_error_message="La méthode est obligatoire lorsque le résultat n'est pas « En attente ».",
            ),
        ),
    ]
