# Generated by Django 6.0.7 on 2026-09-28 09:31

from django.db import migrations, models

REMOVED_TYPE_LIEU_VALUES = [
    "Cage (aquatic environment)",
    "Coastal area - marine area",
    "Estuary",
    "Forest (excluding farming)",
    "Lake",
    "Pond - small pond",
    "Reservoir - dam",
]


def fix_invalid_type_lieu(apps, _):
    EvenementAnimal = apps.get_model("sa", "EvenementAnimal")
    EvenementAnimal.objects.filter(type_lieu__in=REMOVED_TYPE_LIEU_VALUES).update(type_lieu="Other")
    EvenementAnimal.objects.filter(statut_animal="DETENU", type_lieu="Shellfish bed").update(type_lieu="Other")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0067_alter_document_document_type"),
        ("sa", "0033_analyse_analyse_methode_required_unless_en_attente"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="evenementanimal",
            name="evenementanimal_type_lieu_consistent_with_statut_animal",
        ),
        migrations.RunPython(fix_invalid_type_lieu, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="evenementanimal",
            name="type_lieu",
            field=models.CharField(
                choices=[
                    ("Apiary", "Ruche"),
                    ("Backyard", "Basse-cour"),
                    (
                        "Farm (terrestrial or aquatic, including educational farm, excluding backyard)",
                        "Élevage (terrestre ou aquatique, y compris ferme pédagogique, hors basse-cour)",
                    ),
                    (
                        "Livestock market - fair - exhibition - transport",
                        "Marché aux bestiaux - foire - exposition - transport",
                    ),
                    ("Natural park - nature reserve - game park", "Forêt - parc naturel - réserve - parc de chasse"),
                    ("Not applicable", "Non applicable"),
                    ("Other", "Autre"),
                    ("River system - running waters", "Réseau hydrographique - eaux courantes"),
                    ("Shellfish bed", "Banc de coquillage"),
                    ("Slaughterhouse", "Abattoir"),
                    ("Zoo", "Parc zoologique"),
                ],
                max_length=100,
                verbose_name="Type de lieu",
            ),
        ),
        migrations.AddConstraint(
            model_name="evenementanimal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("statut_animal", "DETENU"),
                        (
                            "type_lieu__in",
                            [
                                "Slaughterhouse",
                                "Other",
                                "Backyard",
                                "Farm (terrestrial or aquatic, including educational farm, excluding backyard)",
                                "Natural park - nature reserve - game park",
                                "Livestock market - fair - exhibition - transport",
                                "Not applicable",
                                "Zoo",
                                "Apiary",
                            ],
                        ),
                    ),
                    models.Q(
                        ("statut_animal", "SAUVAGE"),
                        (
                            "type_lieu__in",
                            [
                                "Other",
                                "Shellfish bed",
                                "Natural park - nature reserve - game park",
                                "Not applicable",
                                "River system - running waters",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                name="evenementanimal_type_lieu_consistent_with_statut_animal",
                violation_error_message="Le type de lieu n'est pas compatible avec le statut de l'animal sélectionné",
            ),
        ),
    ]
