# Generated by Django 6.0.7 on 2026-09-28 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sa",
            "0034_remove_evenementanimal_evenementanimal_type_lieu_consistent_with_statut_animal_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenementanimal",
            name="code_insee",
            field=models.CharField(
                blank=True,
                max_length=5,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_code_insee",
                        message="Le code INSEE doit contenir exactement 5 chiffres",
                        regex="^(?:\\d{5}|2A\\d{3}|2B\\d{3})$",
                    )
                ],
                verbose_name="Code INSEE de la commune",
            ),
        ),
        migrations.AlterField(
            model_name="evenementanimal",
            name="code_insee_etablissement",
            field=models.CharField(
                blank=True,
                max_length=5,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_code_insee",
                        message="Le code INSEE doit contenir exactement 5 chiffres",
                        regex="^(?:\\d{5}|2A\\d{3}|2B\\d{3})$",
                    )
                ],
                verbose_name="Code INSEE",
            ),
        ),
        migrations.AlterField(
            model_name="evenementanimal",
            name="code_insee_particulier",
            field=models.CharField(
                blank=True,
                max_length=5,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_code_insee",
                        message="Le code INSEE doit contenir exactement 5 chiffres",
                        regex="^(?:\\d{5}|2A\\d{3}|2B\\d{3})$",
                    )
                ],
                verbose_name="Code INSEE",
            ),
        ),
        migrations.AlterField(
            model_name="veterinaire",
            name="code_insee",
            field=models.CharField(
                blank=True,
                max_length=5,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_code_insee",
                        message="Le code INSEE doit contenir exactement 5 chiffres",
                        regex="^(?:\\d{5}|2A\\d{3}|2B\\d{3})$",
                    )
                ],
                verbose_name="Code INSEE",
            ),
        ),
    ]
