# Generated by Django 6.0.7 on 2026-09-30 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0067_alter_document_document_type"),
        ("sa", "0035_alter_evenementanimal_code_insee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementanimal",
            name="departement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sa_evenements_localisation",
                to="core.departement",
                verbose_name="Département",
            ),
        ),
    ]
