# Generated by Django 6.0.7 on 2026-10-01 07:31

from django.db import migrations, models


def fix_errors_in_maladies(apps, schema_editor):
    Maladie = apps.get_model("sa", "Maladie")
    Espece = apps.get_model("sa", "Espece")
    EspeceConcernee = apps.get_model("sa", "EspeceConcernee")
    EvenementAnimal = apps.get_model("sa", "EvenementAnimal")

    Maladie.objects.filter(name="Clavelée et variole caprine").update(description_type="cartogip")

    espece = Espece.objects.filter(name="Porc").first()
    if espece:
        new_espece = Espece.objects.get(name="Porc (Sus scrofa domesticus)")
        EvenementAnimal.objects.filter(espece_id=espece.id).update(espece_id=new_espece.id)
        EspeceConcernee.objects.filter(espece=espece).update(espece=new_espece)
        espece.delete()

    Maladie.objects.update_or_create(
        name="Autre maladie zoonotique émergente",
        defaults={
            "acronym": "DIV",
            "description_type": "autre",
            "decert_id": "",
            "needs_arrete": False,
            "needs_dates_desinfection": False,
            "needs_date_nd": True,
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("sa", "0036_evenementanimal_departement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maladie",
            name="description_type",
            field=models.CharField(
                choices=[
                    (
                        "notify_asap",
                        "Cette maladie doit être notifiée dans Sèves dès le stade de la suspicion.",
                    ),
                    (
                        "notify_confirmed",
                        "Cette maladie doit être notifiée dans Sèves après confirmation. L’événement peut toutefois être créé dès le stade de la suspicion à des fins de suivi.",
                    ),
                    (
                        "new",
                        "Suspicion de maladie émergente. Le cas index doit être notifié dans Sèves dès le stade de la suspicion, avant le déploiement de CartoGIP.",
                    ),
                    (
                        "cartogip",
                        "Cette maladie doit être notifiée dans CartoGIP. Une interconnexion est prévue à terme avec Sèves.",
                    ),
                    (
                        "salmonelle",
                        "La notification de cette maladie ne fait pas encore partie du périmètre de Sèves. Elle sera intégrée prochainement.",
                    ),
                    (
                        "tuberculose",
                        "Les événements concernant une tuberculose peu commune ou dont on suspecte un impact zoonotique doivent être notifiés dans Sèves. Tous les autres événements restent traités dans SIGAL et CartoGIP.",
                    ),
                    (
                        "autre",
                        "Sélectionnez cette valeur si vous souhaitez échanger au sujet d’un événement lié à une maladie exotique, notamment zoonotique, qui ne figure pas dans la liste proposée.",
                    ),
                ],
                max_length=512,
                verbose_name="Type de description de l'action pour la maladie",
            ),
        ),
        migrations.RunPython(fix_errors_in_maladies, migrations.RunPython.noop),
    ]
