# Generated by Django 5.2.4 on 2025-07-23 13:27

import core.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0037_message_sender_structure_alter_message_sender"),
        ("ssa", "0028_alter_evenementproduit_categorie_produit"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvenementSimple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("en_cours", "En cours"),
                            ("cloture", "Clôturé"),
                        ],
                        default="brouillon",
                        max_length=100,
                        verbose_name="État de l'événement",
                    ),
                ),
                ("numero_annee", models.IntegerField(verbose_name="Année")),
                ("numero_evenement", models.IntegerField(verbose_name="Numéro")),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date de création"),
                ),
                (
                    "date_reception",
                    models.DateTimeField(verbose_name="Date de réception à la DD(ETS)PP"),
                ),
                (
                    "evenement_origin",
                    models.IntegerField(
                        choices=[
                            (1, "ARS"),
                            (2, "Consommateur"),
                            (3, "Établissement"),
                            (4, "Médecin"),
                            (5, "Autre"),
                        ],
                        verbose_name="Signalement déclaré par",
                    ),
                ),
                (
                    "modalites_declaration",
                    models.IntegerField(
                        choices=[(1, "SignalConso"), (2, "Autre")],
                        default=1,
                        verbose_name="Modalités de déclaration",
                    ),
                ),
                ("contenu", models.TextField(verbose_name="Contenu du signalement")),
                (
                    "notify_ars",
                    models.BooleanField(default=False, verbose_name="ARS informée"),
                ),
                (
                    "nb_sick_persons",
                    models.IntegerField(verbose_name="Nombre de malades total"),
                ),
                (
                    "follow_up",
                    models.IntegerField(
                        choices=[
                            (1, "Aucune suite"),
                            (2, "Programmation d’un futur contrôle"),
                        ],
                        default=1,
                        verbose_name="Suite donnée par la DD",
                    ),
                ),
                (
                    "createur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.structure",
                        verbose_name="Structure créatrice",
                    ),
                ),
                (
                    "etablissements",
                    models.ManyToManyField(to="ssa.etablissement", verbose_name="Établissements impliqués"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                core.mixins.WithContactPermissionMixin,
                core.mixins.WithFreeLinkIdsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="EvenementsLies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("releted_evenements_id", models.BigIntegerField()),
                (
                    "evenement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tiac.evenementsimple",
                    ),
                ),
                (
                    "releted_evenements_ct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
