# Generated by Django 5.2.4 on 2025-08-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenementsimple",
            name="evenement_origin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ars", "ARS"),
                    ("consommateur", "Consommateur"),
                    ("etablissement", "Établissement"),
                    ("medecin", "Médecin"),
                    ("autre", "Autre"),
                ],
                verbose_name="Signalement déclaré par",
            ),
        ),
        migrations.AlterField(
            model_name="evenementsimple",
            name="follow_up",
            field=models.CharField(
                choices=[
                    ("aucune suite", "Aucune suite"),
                    (
                        "programmation futur controle",
                        "Programmation d’un futur contrôle",
                    ),
                ],
                default="aucune suite",
                verbose_name="Suite donnée par la DD",
            ),
        ),
        migrations.AlterField(
            model_name="evenementsimple",
            name="modalites_declaration",
            field=models.CharField(
                blank=True,
                choices=[("signalconso", "SignalConso"), ("autre", "Autre")],
                default="signalconso",
                verbose_name="Modalités de déclaration",
            ),
        ),
        migrations.AlterField(
            model_name="evenementsimple",
            name="nb_sick_persons",
            field=models.IntegerField(null=True, verbose_name="Nombre de malades total"),
        ),
    ]
