# Generated by Django 5.2.4 on 2025-08-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_message_sender_structure_alter_message_sender"),
        ("tiac", "0002_alter_evenementsimple_evenement_origin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementsimple",
            name="contacts",
            field=models.ManyToManyField(blank=True, to="core.contact", verbose_name="Contacts"),
        ),
        migrations.AlterField(
            model_name="evenementsimple",
            name="date_reception",
            field=models.DateField(verbose_name="Date de réception à la DD(ETS)PP"),
        ),
    ]
