# Generated by Django 5.2.4 on 2025-08-19 14:04

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_alter_document_document_type"),
        ("tiac", "0003_evenementsimple_contacts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evenementsimple",
            name="etablissements",
        ),
        migrations.CreateModel(
            name="Etablissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "siret",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_siret",
                                message="Le SIRET doit contenir exactement 14 chiffres",
                                regex="^[0-9]{14}$",
                            )
                        ],
                        verbose_name="SIRET de l'établissement",
                    ),
                ),
                (
                    "raison_sociale",
                    models.CharField(max_length=100, verbose_name="Raison sociale"),
                ),
                (
                    "enseigne_usuelle",
                    models.CharField(blank=True, max_length=100, verbose_name="Enseigne usuelle"),
                ),
                (
                    "adresse_lieu_dit",
                    models.CharField(blank=True, max_length=100, verbose_name="Adresse ou lieu-dit"),
                ),
                (
                    "commune",
                    models.CharField(blank=True, max_length=100, verbose_name="Commune"),
                ),
                (
                    "code_insee",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_code_insee",
                                message="Le code INSEE doit contenir exactement 5 chiffres",
                                regex="^[0-9]{5}$",
                            )
                        ],
                        verbose_name="Code INSEE de la commune",
                    ),
                ),
                ("pays", django_countries.fields.CountryField(max_length=2, null=True)),
                (
                    "type_etablissement",
                    models.CharField(blank=True, max_length=45, verbose_name="Type d'établissement"),
                ),
                (
                    "has_inspection",
                    models.BooleanField(default=False, verbose_name="Inspection"),
                ),
                (
                    "numero_resytal",
                    models.CharField(blank=True, verbose_name="Numéro Resytal"),
                ),
                (
                    "evaluation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("satisfaisante", "A - Maîtrise des risques satisfaisante"),
                            ("acceptable", "B - Maîtrise des risques acceptable"),
                            (
                                "mise en demeure",
                                "C - Maîtrise des risques insatisfaisante - Mise en demeure",
                            ),
                            (
                                "restriction",
                                "C - Maîtrise des risques insatisfaisante - Restriction d'activité",
                            ),
                            (
                                "perte de maitrise",
                                "D - Perte de maîtrise des risques - Fermeture ou restriction d'activité",
                            ),
                        ],
                        verbose_name="Évaluation globale",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_etablissements",
                        to="core.departement",
                        verbose_name="Département",
                    ),
                ),
                (
                    "evenement_simple",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="etablissements",
                        to="tiac.evenementsimple",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("has_inspection", True),
                            models.Q(
                                ("numero_resytal", ""),
                                ("evaluation", ""),
                                ("commentaire", ""),
                            ),
                            _connector="OR",
                        ),
                        name="inspection_required_for_inspection_related_fields",
                    )
                ],
            },
        ),
    ]
