# Generated by Django 5.2.4 on 2025-08-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0004_remove_evenementsimple_etablissements_etablissement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenementsimple",
            name="evenement_origin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ars", "ARS"),
                    ("consommateur", "Consommateur"),
                    ("etablissement", "Établissement"),
                    ("medecin", "Médecin / Personnel médical"),
                    ("autre", "Autre"),
                ],
                verbose_name="Signalement déclaré par",
            ),
        ),
    ]
