# Generated by Django 5.2.5 on 2025-09-03 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_alter_document_document_type"),
        ("tiac", "0005_alter_evenementsimple_evenement_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementsimple",
            name="transfered_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfered",
                to="core.structure",
            ),
        ),
    ]
