# Generated by Django 5.2.6 on 2025-09-11 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0007_investigationtiac"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investigationtiac",
            name="datetime_first_symptoms",
            field=models.DateTimeField(
                null=True,
                verbose_name="Première date et heure d'apparition des symptômes",
            ),
        ),
        migrations.AlterField(
            model_name="investigationtiac",
            name="datetime_last_symptoms",
            field=models.DateTimeField(
                null=True,
                verbose_name="Dernière date et heure d'apparition des symptômes",
            ),
        ),
        migrations.AlterField(
            model_name="investigationtiac",
            name="numero_sivss",
            field=models.CharField(
                blank=True,
                max_length=6,
                validators=[django.core.validators.RegexValidator("^\\d{6}$", "Doit contenir exactement 6 chiffres")],
                verbose_name="N° SIVSS de l'ARS",
            ),
        ),
    ]
