# Generated by Django 5.2.6 on 2025-09-16 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_alter_document_document_type"),
        ("tiac", "0009_investigationtiac_analyses_sur_les_malades_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="etablissement",
            name="inspection_required_for_inspection_related_fields",
        ),
        migrations.AddField(
            model_name="etablissement",
            name="date_inspection",
            field=models.DateField(blank=True, default=None, null=True, verbose_name="Date d'inspection"),
        ),
        migrations.AlterField(
            model_name="etablissement",
            name="numero_resytal",
            field=models.CharField(
                blank=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_resytal",
                        message="Le numéro Resytal doit être au format AA-XXXXXX\xa0; par exemple\xa0: 19-067409",
                        regex="^\\d{2}-\\d{6}$",
                    )
                ],
                verbose_name="Numéro Resytal",
            ),
        ),
        migrations.AddConstraint(
            model_name="etablissement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("has_inspection", True),
                    models.Q(
                        ("numero_resytal", ""),
                        ("evaluation", ""),
                        ("commentaire", ""),
                        ("date_inspection", None),
                    ),
                    _connector="OR",
                ),
                name="inspection_required_for_inspection_related_fields",
            ),
        ),
    ]
