# Generated by Django 5.2.6 on 2025-09-16 13:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tiac",
            "0010_remove_etablissement_inspection_required_for_inspection_related_fields_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="investigationtiac",
            name="danger_syndromiques_suspectes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        (
                            "intoxination bacillus cereus",
                            "Intoxination à toxine émétique thermostable préformée dans l'aliment à <span class='danger-emphasis'>bacillus cereus - staphylococcus aureus</span> <div class=\"fr-hint-text\">Incubation courte (30min - 8h) - nausées vomissements prédominants</div>",
                        ),
                        (
                            "toxi infection bacillus cereus",
                            "Toxi-infection à toxine diarrhéique de <span class='danger-emphasis'>bacillus cereus - clostridium perfringens</span> <div class=\"fr-hint-text\">Incubation moyenne (6h - 24h) - diarrhées aqueuses et douleurs abdominales prédominantes</div>",
                        ),
                        (
                            "bactérie intestinale",
                            "Infection bactérienne intestinale à <span class='danger-emphasis'>salmonella - campylobacter - yersinia enterocolitica - shigella - E. Coli</span> pathogènes <div class=\"fr-hint-text\">Incubation longue (Salmonella: 6 à 72 heures, Campylobacter: 2 à 5 jours, Yersinia enterocolitica: 3 à 7 jours, Shigella : 1 à 4 jours) - fièvre et diarrhées prédominants</div>",
                        ),
                        (
                            "shu",
                            "Infection à <span class='danger-emphasis'>E. coli</span> STEC avec cas de syndrome hémolytique et urémique (SHU) <div class=\"fr-hint-text\">Incubation longue (1 à 10 jours) - diarrhées souvent sanglantes - puis complications en Syndrôme hémolytique et urémique</div>",
                        ),
                        (
                            "gastro-enterite",
                            "Gastro-entérite aigüe virale à norovirus, <span class='danger-emphasis'>sapovirus</span> etc. <div class=\"fr-hint-text\">Incubation longue (10h - 50h) - tous symptômes de gastro-entérite, vomissements très fréquents, fièvre ~50% des cas - cas secondaires fréquents (transmission inter-humaine)</div>",
                        ),
                        (
                            "vibrio parahmeolyticus",
                            "Infection à <span class='danger-emphasis'>vibrio parahaemolyticus</span> (poissons ou fruits de mer crus ou peu cuits) <div class=\"fr-hint-text\">Incubation variable (2h à 48h) - diarrhées, douleurs abdominales, vomissements</div>",
                        ),
                        (
                            "histamine",
                            'Intoxination à l\'histamine <div class="fr-hint-text">Incubation courte (1 minute à 3 heures) - urticaire, flush, sensation de brulure de la peau, de la bouche et/ou de la gorge, goût de poivre dans la bouche, palpitations cardiaques</div>',
                        ),
                        (
                            "toxine des coquillages",
                            'Intoxination par des coquillages : toxines lipophiles, PSP et autres toxines <div class="fr-hint-text">Incubation courte (30 minutes à 3 heures) - Consommation de coquillages ou plats cuisinés comportant des coquillages - Toxines lipophiles : nausées, diarrhées, douleurs abdominales - Toxines PSP : diarrhées, nausées, vomissements, paresthésie de la bouche, des lèvres, dysphasie, paralysie respiratoire</div>',
                        ),
                        (
                            "toxine des poissons",
                            'Intoxination par des poissons coralliens : ciguatoxine <div class="fr-hint-text">Incubation courte (2 à 6 heures) - douleurs abdominales, nausées, vomissements, diarrhées, prurit, hypotension artérielle, bradycardie, symptômes neurologiques (parésthésies, faiblesse musculaire, etc)</div>',
                        ),
                        (
                            "autre",
                            'Autres cas <div class="fr-hint-text">Préciser les symptômes et les investigations médicales dans la description de l\'évènement et dans le fil de suivi. </div>',
                        ),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
