# Generated by Django 5.2.6 on 2025-09-16 09:35

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_alter_document_document_type"),
        ("tiac", "0011_alter_investigationtiac_danger_syndromiques_suspectes"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepasSuspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "denomination",
                    models.CharField(max_length=255, verbose_name="Dénomination du repas"),
                ),
                ("menu", models.TextField(blank=True, verbose_name="Menu")),
                (
                    "motif_suspicion",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                (
                                    "repas partage",
                                    "Car repas partagé par la plupart des malades",
                                ),
                                (
                                    "repas compatible",
                                    "Car repas compatible avec les délais d'incubations",
                                ),
                                (
                                    "repas risque",
                                    "Car repas comportant un aliment à risque particulier",
                                ),
                            ],
                            max_length=255,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Motif de suspicion du repas",
                    ),
                ),
                (
                    "datetime_repas",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date et heure du repas"),
                ),
                (
                    "nombre_participant",
                    models.IntegerField(blank=True, null=True, verbose_name="Nombre de participant(e)s"),
                ),
                (
                    "type_repas",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("elabore a domicile", "Élaboré à domicile"),
                            (
                                "emballe a la demande",
                                "Élaboré à la demande à emporter ou livré",
                            ),
                            (
                                "préemballe",
                                "Préemballé consommé en l'état ou réchauffé",
                            ),
                            (
                                "restauration collective",
                                "Servi sur place restauration collective",
                            ),
                            (
                                "restauration commerciale",
                                "Servi sur place restauration commerciale",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.departement",
                        verbose_name="Département",
                    ),
                ),
                (
                    "investigation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repas",
                        to="tiac.investigationtiac",
                    ),
                ),
            ],
        ),
    ]
