# Generated by Django 5.2.6 on 2025-09-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_alter_document_document_type"),
        ("tiac", "0012_repassuspect"),
    ]

    operations = [
        migrations.AddField(
            model_name="repassuspect",
            name="type_collectivite",
            field=models.CharField(
                blank=True,
                choices=[
                    ("jeunes enfants", "Jeunes enfants (0-5)"),
                    ("enfants", "Enfants (6-16)"),
                    ("accueil medicalises", "Accueils médicalisés"),
                    ("entreprise", "Entreprise"),
                    ("personnes agees", "Personnes agées"),
                    ("divers publics sensibles", "Divers publics sensibles"),
                    ("divers publics", "Divers publics"),
                ],
                max_length=255,
            ),
        ),
        migrations.AddConstraint(
            model_name="repassuspect",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("type_repas", "restauration collective"),
                    ("type_collectivite", ""),
                    _connector="OR",
                ),
                name="collectivite_only_if_repas_restauration_collective",
            ),
        ),
    ]
