# Generated by Django 5.2.6 on 2025-10-02 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_alter_document_document_type"),
        ("tiac", "0014_alimentsuspect"),
    ]

    operations = [
        migrations.AddField(
            model_name="etablissement",
            name="investigation_tiac",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="etablissements",
                to="tiac.investigationtiac",
            ),
        ),
        migrations.AlterField(
            model_name="etablissement",
            name="evenement_simple",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="etablissements",
                to="tiac.evenementsimple",
            ),
        ),
        migrations.AddConstraint(
            model_name="etablissement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("evenement_simple__isnull", True),
                        ("investigation_tiac__isnull", False),
                    ),
                    models.Q(
                        ("evenement_simple__isnull", False),
                        ("investigation_tiac__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="is_related_to_either_evenement_simple_or_investigation_tiac",
            ),
        ),
    ]
