# Generated by Django 5.2.6 on 2025-10-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0016_investigationtiac_agents_confirmes_ars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenementsimple",
            name="follow_up",
            field=models.CharField(
                choices=[
                    ("aucune suite", "Aucune suite"),
                    (
                        "programmation futur controle",
                        "Programmation d’un futur contrôle",
                    ),
                    (
                        "programmation au delegataire pour controle",
                        "Transmission au délégataire pour contrôle",
                    ),
                    ("programmation a une autre DD", "Transmission à une autre DD"),
                ],
                default="aucune suite",
                verbose_name="Suite donnée par la DD",
            ),
        ),
    ]
