# Generated by Django 5.2.6 on 2025-10-07 13:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0017_alter_evenementsimple_follow_up"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repassuspect",
            name="motif_suspicion",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("repas partage", "Repas partagé par la plupart des malades"),
                        (
                            "repas compatible",
                            "Repas compatible avec les délais d'incubations",
                        ),
                        (
                            "repas risque",
                            "Repas comportant un aliment à risque particulier",
                        ),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Motif de suspicion du repas",
            ),
        ),
    ]
