# Generated by Django 5.2.7 on 2025-10-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0020_alter_analysealimentaire_categorie_danger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysealimentaire",
            name="etat_prelevement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ENVIRONNEMENT_SURFACE", "Environnement/surface"),
                    ("AUTRE_LOT", "Plat ou ingrédient autre lot"),
                    ("MEME_LOT", "Plat ou ingrédient même lot"),
                    ("PLAT_TEMOIN", "Plat témoin"),
                    ("RESTE_REPAS", "Reste de repas"),
                    ("RESTE_INGREDIENT", "Reste d'ingrédient"),
                ],
                verbose_name="État du prélèvement",
            ),
        ),
    ]
