# Generated by Django 5.2.7 on 2025-10-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0022_investigationtiac_conclusion_aliment_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="etablissement",
            name="is_related_to_either_evenement_simple_or_investigation_tiac",
        ),
        migrations.RenameField(
            model_name="etablissement",
            old_name="investigation_tiac",
            new_name="investigation",
        ),
        migrations.AddConstraint(
            model_name="etablissement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("evenement_simple__isnull", True),
                        ("investigation__isnull", False),
                    ),
                    models.Q(
                        ("evenement_simple__isnull", False),
                        ("investigation__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="is_related_to_either_evenement_simple_or_investigation_tiac",
            ),
        ),
    ]
