# Generated by Django 5.2.7 on 2025-10-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0023_rename_investigation_tiac_etablissement_investigation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investigationtiac",
            name="type_evenement",
        ),
        migrations.AddField(
            model_name="investigationtiac",
            name="follow_up",
            field=models.CharField(
                blank=True,
                choices=[
                    ("investigation par ma dd", "Investigation par ma DD"),
                    (
                        "investigation coordonnée",
                        "Investigation coordonnée / MUS informée",
                    ),
                ],
                max_length=100,
                verbose_name="Suite donnée par la DD",
            ),
        ),
    ]
