# Generated by Django 5.2.7 on 2025-10-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0027_remove_investigationtiac_selected_hazard_constraints_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repassuspect",
            name="nombre_participant",
            field=models.CharField(blank=True, null=True, verbose_name="Nombre de participant(e)s"),
        ),
    ]
