# Generated by Django 5.2.7 on 2025-10-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0028_alter_repassuspect_nombre_participant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenementsimple",
            name="follow_up",
            field=models.CharField(
                choices=[
                    ("aucune suite", "Aucune suite"),
                    ("programmation futur controle", "Futur contrôle programmé"),
                    (
                        "programmation au delegataire pour controle",
                        "Transmis au délégataire pour contrôle",
                    ),
                    ("programmation a une autre DD", "Transféré à une autre DD"),
                    ("investigation tiac", "Passé en investigation de TIAC"),
                ],
                default="aucune suite",
                verbose_name="Suite donnée par la DD",
            ),
        ),
    ]
