# Generated by Django 5.2.7 on 2025-11-07 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0029_alter_evenementsimple_follow_up"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etablissement",
            name="code_insee",
            field=models.CharField(
                blank=True,
                max_length=5,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_code_insee",
                        message="Le code INSEE doit être valide",
                        regex="^(?:\\d{5}|2A\\d{3}|2B\\d{3})$",
                    )
                ],
                verbose_name="Code INSEE de la commune",
            ),
        ),
    ]
