# Generated by Django 5.2.7 on 2025-11-25 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_message_is_deleted"),
        ("tiac", "0032_etablissement_autre_identifiant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etablissement",
            name="departement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)ss",
                to="core.departement",
                verbose_name="Département",
            ),
        ),
    ]
