# Generated by Django 5.2.8 on 2025-12-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0033_alter_etablissement_departement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenementsimple",
            name="date_reception",
            field=models.DateField(verbose_name="Date de réception"),
        ),
        migrations.AlterField(
            model_name="evenementsimple",
            name="follow_up",
            field=models.CharField(
                choices=[
                    ("aucune suite", "Aucune suite"),
                    ("programmation futur controle", "Futur contrôle programmé"),
                    ("programmation au delegataire pour controle", "Transmis au délégataire pour contrôle"),
                    ("programmation a une autre DD", "Transféré à une autre structure"),
                    ("investigation tiac", "Passé en investigation de TIAC"),
                ],
                default="aucune suite",
                verbose_name="Suite donnée",
            ),
        ),
        migrations.AlterField(
            model_name="investigationtiac",
            name="date_reception",
            field=models.DateField(verbose_name="Date de réception"),
        ),
        migrations.AlterField(
            model_name="investigationtiac",
            name="follow_up",
            field=models.CharField(
                blank=True,
                choices=[
                    ("investigation par ma dd", "Investigation locale"),
                    ("investigation coordonnée", "Investigation coordonnée / MUS informée"),
                ],
                max_length=100,
                verbose_name="Suite donnée",
            ),
        ),
    ]
