# Generated by Django 5.2.8 on 2025-12-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0034_alter_evenementsimple_date_reception_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenementsimple",
            name="evenement_origin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("anses", "ANSES"),
                    ("ars", "ARS"),
                    ("consommateur", "Consommateur"),
                    ("etablissement", "Établissement"),
                    ("medecin", "Médecin / Personnel médical"),
                    ("autre", "Autre"),
                ],
                verbose_name="Signalement déclaré par",
            ),
        ),
        migrations.AlterField(
            model_name="investigationtiac",
            name="evenement_origin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("anses", "ANSES"),
                    ("ars", "ARS"),
                    ("consommateur", "Consommateur"),
                    ("etablissement", "Établissement"),
                    ("medecin", "Médecin / Personnel médical"),
                    ("autre", "Autre"),
                ],
                verbose_name="Signalement déclaré par",
            ),
        ),
    ]
