# Generated by Django 5.2.8 on 2025-12-26 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0035_alter_evenementsimple_evenement_origin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investigationtiac",
            name="conclusion_analyse",
        ),
        migrations.RemoveField(
            model_name="investigationtiac",
            name="conclusion_etablissement",
        ),
    ]
