# Generated by Django 5.2.8 on 2026-01-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0036_remove_investigationtiac_conclusion_analyse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alimentsuspect",
            name="type_aliment",
            field=models.CharField(
                blank=True,
                choices=[("aliment cuisine", "Aliment cuisiné"), ("aliment simple", "Matières premières")],
                max_length=255,
            ),
        ),
    ]
