# Generated by Django 5.2.8 on 2026-01-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0039_remove_investigationtiac_selected_hazard_constraints_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alimentsuspect",
            name="type_aliment",
            field=models.CharField(
                blank=True,
                choices=[("aliment cuisine", "Aliment cuisiné"), ("aliment simple", "Matière première")],
                max_length=255,
            ),
        ),
    ]
