# Generated by Django 5.2.8 on 2026-01-14 10:36

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0040_alter_alimentsuspect_type_aliment"),
    ]

    operations = [
        migrations.AddField(
            model_name="etablissement",
            name="numero_agrement",
            field=models.CharField(
                blank=True,
                max_length=12,
                validators=[core.validators.validate_numero_agrement],
                verbose_name="Numéro d'agrément",
            ),
        ),
    ]
