# Generated by Django 5.2.8 on 2026-01-19 15:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0042_investigationtiac_repas_ailment_only_if_conclusion_known"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investigationtiac",
            name="selected_hazard",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("intoxination bacillus cereus", "Intoxination émétique bacillus cereus staphylococcus aureus"),
                        (
                            "toxi infection bacillus cereus",
                            "Toxi-infection diarrhéique bacillus cereus clostridium perfringens",
                        ),
                        ("bactérie intestinale", "Infection bactérienne salmonella campylobacter"),
                        ("shu", "Syndrome hémolytique et urémique SHU"),
                        ("gastro-enterite", "Gastro-entérite aiguë virale"),
                        ("vibrio parahmeolyticus", "Infection vibrio parahaemolyticus"),
                        ("histamine", "Intoxination histamine"),
                        ("toxine des coquillages", "Intoxination coquillages toxines lipophiles ASP PSP"),
                        ("toxine des poissons", "Intoxination ciguatoxine"),
                        ("autre", "Autres cas"),
                        ("Allergène - Arachide", "Allergène - composition ou étiquetage > Allergène - Arachide"),
                        ("Allergène - Céleri", "Allergène - composition ou étiquetage > Allergène - Céleri"),
                        ("Allergène - Crustacés", "Allergène - composition ou étiquetage > Allergène - Crustacés"),
                        (
                            "Allergène - Fruits à coques",
                            "Allergène - composition ou étiquetage > Allergène - Fruits à coques",
                        ),
                        ("Amande", "Allergène - composition ou étiquetage > Allergène - Fruits à coques > Amande"),
                        (
                            "Autre fruit à coque ou indéterminé",
                            "Allergène - composition ou étiquetage > Allergène - Fruits à coques > Autre fruit à coque ou indéterminé",
                        ),
                        ("Noisette", "Allergène - composition ou étiquetage > Allergène - Fruits à coques > Noisette"),
                        ("Noix", "Allergène - composition ou étiquetage > Allergène - Fruits à coques > Noix"),
                        (
                            "Noix de cajou",
                            "Allergène - composition ou étiquetage > Allergène - Fruits à coques > Noix de cajou",
                        ),
                        (
                            "Noix de Macadamia",
                            "Allergène - composition ou étiquetage > Allergène - Fruits à coques > Noix de Macadamia",
                        ),
                        (
                            "Noix de Pécan",
                            "Allergène - composition ou étiquetage > Allergène - Fruits à coques > Noix de Pécan",
                        ),
                        (
                            "Noix du Brésil",
                            "Allergène - composition ou étiquetage > Allergène - Fruits à coques > Noix du Brésil",
                        ),
                        (
                            "Noix du Queensland",
                            "Allergène - composition ou étiquetage > Allergène - Fruits à coques > Noix du Queensland",
                        ),
                        ("Pistache", "Allergène - composition ou étiquetage > Allergène - Fruits à coques > Pistache"),
                        ("Allergène - Gluten", "Allergène - composition ou étiquetage > Allergène - Gluten"),
                        ("Allergène - Lait", "Allergène - composition ou étiquetage > Allergène - Lait"),
                        ("Allergène - Lupin", "Allergène - composition ou étiquetage > Allergène - Lupin"),
                        ("Allergène - Mollusques", "Allergène - composition ou étiquetage > Allergène - Mollusques"),
                        ("Allergène - Moutarde", "Allergène - composition ou étiquetage > Allergène - Moutarde"),
                        ("Allergène - Oeufs", "Allergène - composition ou étiquetage > Allergène - Oeufs"),
                        ("Allergène - Poisson", "Allergène - composition ou étiquetage > Allergène - Poisson"),
                        ("Allergène - Sésame", "Allergène - composition ou étiquetage > Allergène - Sésame"),
                        ("Allergène - Soja", "Allergène - composition ou étiquetage > Allergène - Soja"),
                        ("Allergène - Sulfites", "Allergène - composition ou étiquetage > Allergène - Sulfites"),
                        (
                            "Autre allergène ou indéterminé",
                            "Allergène - composition ou étiquetage > Autre allergène ou indéterminé",
                        ),
                        ("Autre bactérie ou indéterminée", "Bactérie > Autre bactérie ou indéterminée"),
                        ("Bacillus", "Bactérie > Bacillus"),
                        ("Bacillus anthracis", "Bactérie > Bacillus > Bacillus anthracis"),
                        ("Bacillus cereus", "Bactérie > Bacillus > Bacillus cereus et/ou sa toxine"),
                        ("Bacillus thurigiensis", "Bactérie > Bacillus > Bacillus thurigiensis"),
                        ("Brucella", "Bactérie > Brucella"),
                        ("Brucella abortus", "Bactérie > Brucella > Brucella abortus"),
                        ("Brucella melitensis", "Bactérie > Brucella > Brucella melitensis"),
                        ("Brucella suis", "Bactérie > Brucella > Brucella suis"),
                        ("Campylobacter", "Bactérie > Campylobacter"),
                        ("Campylobacter coli", "Bactérie > Campylobacter > Campylobacter coli"),
                        ("Campylobacter jejuni", "Bactérie > Campylobacter > Campylobacter jejuni"),
                        ("Clostridium", "Bactérie > Clostridium"),
                        ("Clostridium botulinum", "Bactérie > Clostridium > Clostridium botulinum et/ou sa toxine"),
                        ("Clostridium perfringens", "Bactérie > Clostridium > Clostridium perfringens"),
                        ("Coliformes", "Bactérie > Coliformes"),
                        ("Coxiella", "Bactérie > Coxiella"),
                        ("Coxiella burnetii (fièvre Q)", "Bactérie > Coxiella > Coxiella burnetii (fièvre Q)"),
                        ("Cronobacter", "Bactérie > Cronobacter"),
                        ("Cronobacter malonaticus", "Bactérie > Cronobacter > Cronobacter malonaticus"),
                        ("Cronobacter sakazakii", "Bactérie > Cronobacter > Cronobacter sakazakii"),
                        ("Entérobactéries", "Bactérie > Entérobactéries"),
                        ("Escherichia Coli", "Bactérie > Escherichia Coli"),
                        (
                            "Escherichia coli (non STEC - EHEC)",
                            "Bactérie > Escherichia Coli > Escherichia coli (non STEC - EHEC)",
                        ),
                        (
                            "Escherichia coli shigatoxinogène (STEC - EHEC)",
                            "Bactérie > Escherichia Coli > Escherichia coli shigatoxinogène (STEC - EHEC)",
                        ),
                        ("Leptospira", "Bactérie > Leptospira"),
                        ("Listeria", "Bactérie > Listeria"),
                        ("Listeria monocytogenes", "Bactérie > Listeria > Listeria monocytogenes"),
                        ("Mycobacterium", "Bactérie > Mycobacterium"),
                        ("Mycobacterium bovis", "Bactérie > Mycobacterium > Mycobacterium bovis"),
                        ("Mycobacterium suis", "Bactérie > Mycobacterium > Mycobacterium suis"),
                        ("Mycobacterium tuberculosis", "Bactérie > Mycobacterium > Mycobacterium tuberculosis"),
                        ("Pseudomonas", "Bactérie > Pseudomonas"),
                        ("Salmonella", "Bactérie > Salmonella"),
                        ("Autre salmonella (à préciser)", "Bactérie > Salmonella > Autre salmonella (à préciser)"),
                        ("Salmonella dublin", "Bactérie > Salmonella > Salmonella dublin"),
                        ("Salmonella enteritidis", "Bactérie > Salmonella > Salmonella enteritidis"),
                        ("Salmonella hadar", "Bactérie > Salmonella > Salmonella hadar"),
                        ("Salmonella infantis", "Bactérie > Salmonella > Salmonella infantis"),
                        ("Salmonella kentucky", "Bactérie > Salmonella > Salmonella kentucky"),
                        ("Salmonella mbandaka", "Bactérie > Salmonella > Salmonella mbandaka"),
                        ("Salmonella typhimurium", "Bactérie > Salmonella > Salmonella typhimurium"),
                        ("Salmonella virchow", "Bactérie > Salmonella > Salmonella virchow"),
                        ("Shigella", "Bactérie > Shigella"),
                        ("Staphylococcus", "Bactérie > Staphylococcus"),
                        (
                            "Staphylococcus aureus et/ou sa toxine",
                            "Bactérie > Staphylococcus > Staphylococcus aureus et/ou sa toxine",
                        ),
                        ("Vibrio", "Bactérie > Vibrio"),
                        ("Vibrio cholerae", "Bactérie > Vibrio > Vibrio cholerae"),
                        ("Vibrio parahaemolyticus", "Bactérie > Vibrio > Vibrio parahaemolyticus"),
                        ("Vibrio vulnificus", "Bactérie > Vibrio > Vibrio vulnificus"),
                        ("Yersinia", "Bactérie > Yersinia"),
                        ("Yersinia enterocolitica", "Bactérie > Yersinia > Yersinia enterocolitica"),
                        (
                            "Autre contaminant de l'environnement",
                            "Contaminant - autre > Autre contaminant de l'environnement",
                        ),
                        ("Bisphénol (hors MCDA)", "Contaminant - autre > Bisphénol (hors MCDA)"),
                        ("Mélamine (hors MCDA)", "Contaminant - autre > Mélamine (hors MCDA)"),
                        ("Nitrate (hors additif)", "Contaminant - autre > Nitrate (hors additif)"),
                        ("Nitrite (hors additif)", "Contaminant - autre > Nitrite (hors additif)"),
                        ("Perchlorate", "Contaminant - autre > Perchlorate"),
                        ("Arsenic (As)", "Contaminant - métaux et autre élément > Arsenic (As)"),
                        (
                            "Autre élément trace métallique ou composé inorganique",
                            "Contaminant - métaux et autre élément > Autre élément trace métallique ou composé inorganique",
                        ),
                        ("Cadmium (Cd)", "Contaminant - métaux et autre élément > Cadmium (Cd)"),
                        ("Fluor (F)", "Contaminant - métaux et autre élément > Fluor (F)"),
                        ("Mercure (Hg)", "Contaminant - métaux et autre élément > Mercure (Hg)"),
                        ("Nickel (Ni)", "Contaminant - métaux et autre élément > Nickel (Ni)"),
                        ("Plomb (Pb)", "Contaminant - métaux et autre élément > Plomb (Pb)"),
                        ("Aflatoxine", "Contaminant - mycotoxine > Aflatoxine"),
                        (
                            "Alternariol (AOH) Alternariol monométhyl éther (AME) Acide ténuazonique (TeA)",
                            "Contaminant - mycotoxine > Alternariol (AOH) Alternariol monométhyl éther (AME) Acide ténuazonique (TeA)",
                        ),
                        (
                            "Autre mycotoxine ou indéterminée",
                            "Contaminant - mycotoxine > Autre mycotoxine ou indéterminée",
                        ),
                        ("Citrinine", "Contaminant - mycotoxine > Citrinine"),
                        ("Déoxynivalénol (DON)", "Contaminant - mycotoxine > Déoxynivalénol (DON)"),
                        ("Fumonisine", "Contaminant - mycotoxine > Fumonisine"),
                        ("Ochratoxine A", "Contaminant - mycotoxine > Ochratoxine A"),
                        ("Patuline", "Contaminant - mycotoxine > Patuline"),
                        (
                            "Sclérote d'ergot - Alcaloïde de l'ergot",
                            "Contaminant - mycotoxine > Sclérote d'ergot - Alcaloïde de l'ergot",
                        ),
                        ("Toxine T2 ou HT2", "Contaminant - mycotoxine > Toxine T2 ou HT2"),
                        ("Zéaralénone (ZEA)", "Contaminant - mycotoxine > Zéaralénone (ZEA)"),
                        (
                            "Autre polluant organique persistant",
                            "Contaminant - polluant organique persistant > Autre polluant organique persistant",
                        ),
                        ("Dioxines et PCB", "Contaminant - polluant organique persistant > Dioxines et PCB"),
                        (
                            "PBDE et autre retardateur de flamme bromé",
                            "Contaminant - polluant organique persistant > PBDE et autre retardateur de flamme bromé",
                        ),
                        (
                            "Substances perfluoroalkylées (PFAS)",
                            "Contaminant - polluant organique persistant > Substances perfluoroalkylées (PFAS)",
                        ),
                        (
                            "3MCPD et ester d'acide gras de 3-MCPD",
                            "Contaminant - procédé de transformation > 3MCPD et ester d'acide gras de 3-MCPD",
                        ),
                        ("AAH", "Contaminant - procédé de transformation > AAH"),
                        ("Acrylamide", "Contaminant - procédé de transformation > Acrylamide"),
                        (
                            "Autre contaminant des procédés",
                            "Contaminant - procédé de transformation > Autre contaminant des procédés",
                        ),
                        (
                            "Ester d'acide gras de glycidol",
                            "Contaminant - procédé de transformation > Ester d'acide gras de glycidol",
                        ),
                        (
                            "Furane et dérivé méthylé du furane",
                            "Contaminant - procédé de transformation > Furane et dérivé méthylé du furane",
                        ),
                        ("HAP", "Contaminant - procédé de transformation > HAP"),
                        (
                            "Hydrocarbure d'huile minérale (MOAH et MOSH)",
                            "Contaminant - procédé de transformation > Hydrocarbure d'huile minérale (MOAH et MOSH)",
                        ),
                        ("Nitrosamine", "Contaminant - procédé de transformation > Nitrosamine"),
                        ("Phycotoxine et cyanotoxine", "Contaminant - toxine > Phycotoxine et cyanotoxine"),
                        (
                            "Autre phycotoxine et cyanotoxine",
                            "Contaminant - toxine > Phycotoxine et cyanotoxine > Autre phycotoxine et cyanotoxine",
                        ),
                        ("Ciguatoxine", "Contaminant - toxine > Phycotoxine et cyanotoxine > Ciguatoxine"),
                        ("Histamine", "Contaminant - toxine > Histamine"),
                        ("Toxine ASP", "Contaminant - toxine > Phycotoxine et cyanotoxine > Toxine ASP"),
                        (
                            "Toxine DSP (toxines lipophiles)",
                            "Contaminant - toxine > Phycotoxine et cyanotoxine > Toxine DSP (toxines lipophiles)",
                        ),
                        ("Toxine PSP", "Contaminant - toxine > Phycotoxine et cyanotoxine > Toxine PSP"),
                        ("Phyto-estrogène", "Contaminant - toxine > Phyto-estrogène"),
                        ("Toxine végétale autre", "Contaminant - toxine > Toxine végétale autre"),
                        (
                            "Autre toxine végétale ou plante en contenant",
                            "Contaminant - toxine > Toxine végétale autre > Autre toxine végétale ou plante en contenant",
                        ),
                        (
                            "Betterave crue : toxine indéterminée",
                            "Contaminant - toxine > Toxine végétale autre > Betterave crue : toxine indéterminée",
                        ),
                        (
                            "Champignon toxique ou vénéneu(amanite, divers)",
                            "Contaminant - toxine > Toxine végétale autre > Champignon toxique ou vénéneu(amanite, divers)",
                        ),
                        (
                            "Cucurbitacine et autres toxines de courges",
                            "Contaminant - toxine > Toxine végétale autre > Cucurbitacine et autres toxines de courges",
                        ),
                        ("Gossypol", "Contaminant - toxine > Toxine végétale autre > Gossypol"),
                        (
                            "Pignon de pin amer (dysgueusie)",
                            "Contaminant - toxine > Toxine végétale autre > Pignon de pin amer (dysgueusie)",
                        ),
                        ("Théobromine", "Contaminant - toxine > Toxine végétale autre > Théobromine"),
                        ("Toxine végétale réglementée", "Contaminant - toxine > Toxine végétale réglementée"),
                        (
                            "Acide cyanhydrique",
                            "Contaminant - toxine > Toxine végétale réglementée > Acide cyanhydrique (HCN)",
                        ),
                        ("Acide érucique", "Contaminant - toxine > Toxine végétale réglementée > Acide érucique"),
                        ("Alcaloïde opioïde", "Contaminant - toxine > Toxine végétale réglementée > Alcaloïde opioïde"),
                        (
                            "Alcaloïde pyrrolizidinique",
                            "Contaminant - toxine > Toxine végétale réglementée > Alcaloïde pyrrolizidinique",
                        ),
                        (
                            "Alcaloïde tropanique (Datura) et graine de Datura",
                            "Contaminant - toxine > Toxine végétale réglementée > Alcaloïde tropanique (Datura) et graine de Datura",
                        ),
                        (
                            "Delta-9-THC (<=0,3%)",
                            "Contaminant - toxine > Toxine végétale réglementée > Delta-9-THC (<=0,3%)",
                        ),
                        ("Glycoalcaloïde", "Contaminant - toxine > Toxine végétale réglementée > Glycoalcaloïde"),
                        (
                            "Autre corps étranger ou indéterminé",
                            "Corps étranger et indésirable > Autre corps étranger ou indéterminé",
                        ),
                        (
                            "Impureté botanique - espèce végétale nuisible (yc Ambroisie)",
                            "Corps étranger et indésirable > Impureté botanique - espèce végétale nuisible (yc Ambroisie)",
                        ),
                        (
                            "Insecte - vers - rongeur - autre animal indésirable",
                            "Corps étranger et indésirable > Insecte - vers - rongeur - autre animal indésirable",
                        ),
                        (
                            "Verre - cailloux - métal - os - autre blessant",
                            "Corps étranger et indésirable > Verre - cailloux - métal - os - autre blessant",
                        ),
                        (
                            "Activité interdite (mesure administrative)",
                            "Etablissement - activité non autorisée > Activité interdite (mesure administrative)",
                        ),
                        (
                            "Activité non agréée (défaut d'agrément)",
                            "Etablissement - activité non autorisée > Activité non agréée (défaut d'agrément)",
                        ),
                        (
                            "Autre activité non autorisée",
                            "Etablissement - activité non autorisée > Autre activité non autorisée",
                        ),
                        (
                            "Irradiation Ionisation non autorisée",
                            "Etablissement - activité non autorisée > Irradiation Ionisation non autorisée",
                        ),
                        (
                            'Non présentation à un contrôle obligatoire (yc "tout droit")',
                            'Etablissement - activité non autorisée > Non présentation à un contrôle obligatoire (yc "tout droit")',
                        ),
                        (
                            "Anomalie documentaire sous-produit animal (DAC, DOCOM, CS)",
                            "Etablissement - perte de maîtrise sanitaire > Anomalie documentaire sous-produit animal (DAC, DOCOM, CS)",
                        ),
                        (
                            "Autre perte de maîtrise sanitaire",
                            "Etablissement - perte de maîtrise sanitaire > Autre perte de maîtrise sanitaire",
                        ),
                        (
                            "Défaut de composition (sauf allergène)",
                            "Etablissement - perte de maîtrise sanitaire > Défaut de composition (sauf allergène)",
                        ),
                        (
                            "Défaut de pasteurisation",
                            "Etablissement - perte de maîtrise sanitaire > Défaut de pasteurisation",
                        ),
                        (
                            "Défaut de stérilisation",
                            "Etablissement - perte de maîtrise sanitaire > Défaut de stérilisation",
                        ),
                        (
                            "Défaut de traçabilité",
                            "Etablissement - perte de maîtrise sanitaire > Défaut de traçabilité",
                        ),
                        (
                            "Défaut du conditionnement (herméticité, gaz…)",
                            "Etablissement - perte de maîtrise sanitaire > Défaut du conditionnement (herméticité, gaz…)",
                        ),
                        (
                            "Défaut organoleptique (toute cause)",
                            "Etablissement - perte de maîtrise sanitaire > Défaut organoleptique (toute cause dont ABVT)",
                        ),
                        (
                            "Feed - animal non-cible (contamination)",
                            "Etablissement - perte de maîtrise sanitaire > Feed - animal non-cible (contamination)",
                        ),
                        (
                            "Ionisation non conforme (hors étiquetage)",
                            "Etablissement - perte de maîtrise sanitaire > Ionisation non conforme (hors étiquetage)",
                        ),
                        (
                            "Mauvaises conditions d'hygiène, risques de contamination",
                            "Etablissement - perte de maîtrise sanitaire > Mauvaises conditions d'hygiène, risques de contamination",
                        ),
                        (
                            "Rupture de la chaîne du froid",
                            "Etablissement - perte de maîtrise sanitaire > Rupture de la chaîne du froid",
                        ),
                        (
                            "Autre étiquetage ou indéterminé (hors allergène)",
                            "Etiquetage > Autre étiquetage ou indéterminé (hors allergène)",
                        ),
                        ("Etiquetage / allégation", "Etiquetage > Etiquetage / allégation"),
                        (
                            "Etiquetage / composition (hors allergène)",
                            "Etiquetage > Etiquetage / composition (hors allergène)",
                        ),
                        ("Etiquetage / DLC", "Etiquetage > Etiquetage / DLC"),
                        ("Etiquetage / ionisation", "Etiquetage > Etiquetage / ionisation"),
                        (
                            "Etiquetage / mode d'emploi / mention de bon usage",
                            "Etiquetage > Etiquetage / mode d'emploi / mention de bon usage",
                        ),
                        (
                            "Etiquetage / température de conservation",
                            "Etiquetage > Etiquetage / température de conservation",
                        ),
                        ("Additif", "Ingrédient - additif et auxilliaire technologique > Additif"),
                        (
                            "Additif - nitré (nitrate/nitrite)",
                            "Ingrédient - additif et auxilliaire technologique > Additif > Additif - nitré (nitrate/nitrite)",
                        ),
                        (
                            "Additif - non-respect catégorie denrée / AMM",
                            "Ingrédient - additif et auxilliaire technologique > Additif > Additif - non-respect catégorie denrée / AMM",
                        ),
                        (
                            "Additif - non-respect dosage / AMM",
                            "Ingrédient - additif et auxilliaire technologique > Additif > Additif - non-respect dosage / AMM",
                        ),
                        (
                            "Additif - sulfite",
                            "Ingrédient - additif et auxilliaire technologique > Additif > Additif - sulfite",
                        ),
                        (
                            "Autre additif (yc additif non autorisé en UE)",
                            "Ingrédient - additif et auxilliaire technologique > Additif > Autre additif (yc additif non autorisé en UE)",
                        ),
                        (
                            "Résidu d'additif feed (yc coccidiostatique, histomonostatique)",
                            "Ingrédient - additif et auxilliaire technologique > Additif > Résidu d'additif feed (yc coccidiostatique, histomonostatique)",
                        ),
                        ("Additif - Feed", "Ingrédient - additif et auxilliaire technologique > Additif - Feed"),
                        (
                            "Feed - additif non autorisé",
                            "Ingrédient - additif et auxilliaire technologique > Additif - Feed > Feed - additif non autorisé",
                        ),
                        (
                            "Feed - non-respect condition d'autorisation",
                            "Ingrédient - additif et auxilliaire technologique > Additif - Feed > Feed - non-respect condition d'autorisation",
                        ),
                        (
                            "Auxilliaire technologique",
                            "Ingrédient - additif et auxilliaire technologique > Auxilliaire technologique",
                        ),
                        (
                            "Non-respect catégorie denrée / domaine d'application",
                            "Ingrédient - additif et auxilliaire technologique > Auxilliaire technologique > Non-respect catégorie denrée / domaine d'application",
                        ),
                        (
                            "Non-respect condition d'emploi / dose résiduelle",
                            "Ingrédient - additif et auxilliaire technologique > Auxilliaire technologique > Non-respect condition d'emploi / dose résiduelle",
                        ),
                        (
                            "Résidu d'auxilliaire technologique et impureté issue",
                            "Ingrédient - additif et auxilliaire technologique > Auxilliaire technologique > Résidu d'auxilliaire technologique et impureté issue",
                        ),
                        ("Enzyme", "Ingrédient - additif et auxilliaire technologique > Enzyme"),
                        (
                            "Complément alimentaire non télédéclaré",
                            "Ingrédient - non autorisé ou dangereux > Complément alimentaire non télédéclaré",
                        ),
                        (
                            "Déchet, produit technique non-alimentaire (yc feed)",
                            "Ingrédient - non autorisé ou dangereux > Déchet, produit technique non-alimentaire (yc feed)",
                        ),
                        ("Feed - MP interdite", "Ingrédient - non autorisé ou dangereux > Feed - MP interdite"),
                        (
                            "Feed - autre MP interdite",
                            "Ingrédient - non autorisé ou dangereux > Feed - MP interdite > Feed - autre MP interdite",
                        ),
                        (
                            "Feed - emballage de produit des IAA",
                            "Ingrédient - non autorisé ou dangereux > Feed - MP interdite > Feed - emballage de produit des IAA",
                        ),
                        (
                            "Feed - semence ou plant traité et dérivé",
                            "Ingrédient - non autorisé ou dangereux > Feed - MP interdite > Feed - semence ou plant traité et dérivé",
                        ),
                        (
                            "Feed - sous-produit animal",
                            "Ingrédient - non autorisé ou dangereux > Feed - sous-produit animal",
                        ),
                        (
                            "Feed - Produit animal interdit / feed ban (yc PAT)",
                            "Ingrédient - non autorisé ou dangereux > Feed - sous-produit animal > Feed - Produit animal interdit / feed ban (yc PAT)",
                        ),
                        (
                            "Feed - SPAn de catégorie 1 ou 2",
                            "Ingrédient - non autorisé ou dangereux > Feed - sous-produit animal > Feed - SPAn de catégorie 1 ou 2",
                        ),
                        (
                            "Feed - SPAn de catégorie 3 non-conforme",
                            "Ingrédient - non autorisé ou dangereux > Feed - sous-produit animal > Feed - SPAn de catégorie 3 non-conforme",
                        ),
                        ("Novel food", "Ingrédient - non autorisé ou dangereux > Novel food"),
                        (
                            "NF - CBD/autres cannabinoïdes",
                            "Ingrédient - non autorisé ou dangereux > Novel food > NF - CBD/autres cannabinoïdes",
                        ),
                        (
                            "NF - non-respect catégorie denrée / AMM",
                            "Ingrédient - non autorisé ou dangereux > Novel food > NF - non-respect catégorie denrée / AMM",
                        ),
                        (
                            "NF - non-respect population cible / AMM",
                            "Ingrédient - non autorisé ou dangereux > Novel food > NF - non-respect population cible / AMM",
                        ),
                        (
                            "NF - surdosage/AMM",
                            "Ingrédient - non autorisé ou dangereux > Novel food > NF - surdosage/AMM",
                        ),
                        ("OGM", "Ingrédient - non autorisé ou dangereux > OGM"),
                        ("Animal GM", "Ingrédient - non autorisé ou dangereux > OGM > Animal GM"),
                        ("Microorganisme GM", "Ingrédient - non autorisé ou dangereux > OGM > Microorganisme GM"),
                        ("Plante GM", "Ingrédient - non autorisé ou dangereux > OGM > Plante GM"),
                        (
                            "Sous-produit animal en alimentation humaine",
                            "Ingrédient - non autorisé ou dangereux > Sous-produit animal en alimentation humaine",
                        ),
                        (
                            "Stupéfiant et psychoactif",
                            "Ingrédient - non autorisé ou dangereux > Stupéfiant et psychoactif",
                        ),
                        (
                            "Psychoactif (hors médicament, stupéfiant, novel food)",
                            "Ingrédient - non autorisé ou dangereux > Stupéfiant et psychoactif > Psychoactif (hors médicament, stupéfiant, novel food)",
                        ),
                        (
                            "Stupéfiant (dont THC>0,3%)",
                            "Ingrédient - non autorisé ou dangereux > Stupéfiant et psychoactif > Stupéfiant (dont THC supérieur à 0,3%)",
                        ),
                        (
                            "Substance interdite ou restriction / denrée enrichie ou complément alimentaire",
                            "Ingrédient - non autorisé ou dangereux > Substance interdite ou restriction / denrée enrichie ou complément alimentaire",
                        ),
                        (
                            "Substance médicamenteuse",
                            "Ingrédient - non autorisé ou dangereux > Substance médicamenteuse",
                        ),
                        (
                            "Autre substance médicamenteuse",
                            "Ingrédient - non autorisé ou dangereux > Substance médicamenteuse > Autre substance médicamenteuse",
                        ),
                        (
                            "Sibutramine",
                            "Ingrédient - non autorisé ou dangereux > Substance médicamenteuse > Sibutramine",
                        ),
                        (
                            "Sildénafil",
                            "Ingrédient - non autorisé ou dangereux > Substance médicamenteuse > Sildénafil",
                        ),
                        (
                            "Surdosage nutriment / denrée enrichie ou complément alimentaire",
                            "Ingrédient - non autorisé ou dangereux > Surdosage nutriment / denrée enrichie ou complément alimentaire",
                        ),
                        (
                            "Levure Moisissure divers ou indéterminée",
                            "Levure Moisissure > Levure Moisissure divers ou indéterminée",
                        ),
                        (
                            "Autre résidu MV ou indéterminé (hors additif coccidiostatique et histomonostatique)",
                            "Médicament vétérinaire > Autre résidu MV ou indéterminé (hors additif coccidiostatique et histomonostatique)",
                        ),
                        ("Feed - MV - animal non-cible", "Médicament vétérinaire > Feed - MV - animal non-cible"),
                        (
                            "Feed - MV - non-respect dose / aliment médicamenteux",
                            "Médicament vétérinaire > Feed - MV - non-respect dose / aliment médicamenteux",
                        ),
                        (
                            "Résidu MV - Groupe A - substance interdite ou non autorisée, traitement illégal",
                            "Médicament vétérinaire > Résidu MV - Groupe A - substance interdite ou non autorisée, traitement illégal",
                        ),
                        (
                            "Autre - Résidu MV interdit ou non autorisé",
                            "Médicament vétérinaire > Résidu MV - Groupe A - substance interdite ou non autorisée, traitement illégal > Autre - Résidu MV interdit ou non autorisé",
                        ),
                        (
                            "Résidu MV - Substances à effet hormonal et thyréostatique et béta-agonistes",
                            "Médicament vétérinaire > Résidu MV - Groupe A - substance interdite ou non autorisée, traitement illégal > Résidu MV - Substances à effet hormonal et thyréostatique et béta-agonistes",
                        ),
                        (
                            "Résidu MV - Groupe B - substance autorisée",
                            "Médicament vétérinaire > Résidu MV - Groupe B - substance autorisée",
                        ),
                        ("Alaria alata", "Parasite > Alaria alata"),
                        ("Anisakis", "Parasite > Anisakis"),
                        ("Autre parasite ou indéterminé", "Parasite > Autre parasite ou indéterminé"),
                        ("Clinostomum complanatum", "Parasite > Clinostomum complanatum"),
                        ("Diphyllobothrium", "Parasite > Diphyllobothrium"),
                        ("Echinococcus", "Parasite > Echinococcus"),
                        ("Pseudoterranova", "Parasite > Pseudoterranova"),
                        ("Toxacara", "Parasite > Toxacara"),
                        ("Toxoplasma", "Parasite > Toxoplasma"),
                        ("Trichine", "Parasite > Trichine"),
                        ("Résidu de Pesticide Biocide", "Pesticide biocide > Résidu de Pesticide Biocide"),
                        ("Autre prion ou indéterminé", "Prion > Autre prion ou indéterminé"),
                        ("Encéphalopathie spongiforme bovine", "Prion > Encéphalopathie spongiforme bovine"),
                        ("Tremblante", "Prion > Tremblante"),
                        ("Radionucléide", "Radionucléide > Radionucléide"),
                        ("MCDA - Autre contaminant", "Substance migrante - MCDA > MCDA - Autre contaminant"),
                        (
                            "MCDA - Autre perturbateur endocrinien (hors bisphénol)",
                            "Substance migrante - MCDA > MCDA - Autre perturbateur endocrinien (hors bisphénol)",
                        ),
                        (
                            "MCDA - Bisphénol (hors contaminant)",
                            "Substance migrante - MCDA > MCDA - Bisphénol (hors contaminant)",
                        ),
                        ("MCDA - Cobalt", "Substance migrante - MCDA > MCDA - Cobalt"),
                        ("MCDA - Formaldéhyde", "Substance migrante - MCDA > MCDA - Formaldéhyde"),
                        (
                            "MCDA - Mélamine (hors contaminant)",
                            "Substance migrante - MCDA > MCDA - Mélamine (hors contaminant)",
                        ),
                        ("MCDA - Phtalates", "Substance migrante - MCDA > MCDA - Phtalates"),
                        ("Autre virus alimentaire ou indéterminé", "Virus > Autre virus alimentaire ou indéterminé"),
                        (
                            "Virus de la gastroentérite aigüe (GEA) (Calicivirus, Norovirus, Sapovirus, Rotavirus, Astrovirus, Adénovirus)",
                            "Virus > Virus de la gastroentérite aigüe (GEA)",
                        ),
                        (
                            "Virus de la gastroentérite aigüe (GEA) Norovirus",
                            "Virus > Virus de la gastroentérite aigüe (GEA) > Norovirus",
                        ),
                        (
                            "Virus de la gastroentérite aigüe (GEA) Autres",
                            "Virus > Virus de la gastroentérite aigüe (GEA) > Autres Calicivirus, Sapovirus, Rotavirus, Astrovirus, Adénovirus",
                        ),
                        ("Virus de l'encéphalite à tique (TBEV)", "Virus > Virus de l'encéphalite à tique (TBEV)"),
                        ("Virus de l'hépatite A (VHA)", "Virus > Virus de l'hépatite A (VHA)"),
                        ("Virus de l'hépatite E (VHE)", "Virus > Virus de l'hépatite E (VHE)"),
                        (
                            "Virus influenza zoonotique par voie alimentaire (IAHP zoo)",
                            "Virus > Virus influenza zoonotique par voie alimentaire (IAHP zoo)",
                        ),
                        ("Virus Nipah", "Virus > Virus Nipah"),
                        ("Entérovirus", "Virus > Entérovirus"),
                        ("SA - Autre en santé animale", "x Santé animale > SA - Autre en santé animale"),
                        ("SA - Fièvre aphteuse", "x Santé animale > SA - Fièvre aphteuse"),
                        (
                            "SA - Influenza aviaire hautement pathogène",
                            "x Santé animale > SA - Influenza aviaire hautement pathogène",
                        ),
                        ("SA - Peste porcine africaine", "x Santé animale > SA - Peste porcine africaine"),
                        ("SA - Peste porcine classique", "x Santé animale > SA - Peste porcine classique"),
                        ("SV - Organisme de quarantaine", "x Santé végétale > SV - Organisme de quarantaine"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Dangers retenus",
            ),
        ),
    ]
