# Generated by Django 5.2.8 on 2026-01-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_alter_document_document_type"),
        ("tiac", "0043_alter_investigationtiac_selected_hazard"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="investigationtiac",
            name="repas_ailment_only_if_conclusion_known",
        ),
        migrations.AddConstraint(
            model_name="investigationtiac",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("suspicion_conclusion", "UNKNOWN"), _negated=True),
                    models.Q(("conclusion_repas__isnull", True), ("conclusion_aliment__isnull", True)),
                    _connector="OR",
                ),
                name="repas_aliment_only_if_conclusion_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="investigationtiac",
            constraint=models.CheckConstraint(
                condition=models.Q(("analyses_sur_les_malades", "oui"), ("precisions", ""), _connector="OR"),
                name="precision_only_if_analyse",
            ),
        ),
    ]
