# Generated by Django 5.2.10 on 2026-02-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0045_alter_alimentsuspect_categorie_produit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenementsimple",
            name="follow_up",
            field=models.CharField(
                choices=[
                    ("aucune suite", "Aucune suite"),
                    ("programmation futur controle", "Futur contrôle programmé"),
                    (
                        "programmation au delegataire pour controle",
                        "Transmis au délégataire pour contrôle",
                    ),
                    ("programmation a une autre DD", "Transféré à une autre structure"),
                    ("investigation tiac", "Passé en investigation de TIAC"),
                    ("passe en evenement produit", "Passé en événement produit"),
                ],
                default="aucune suite",
                verbose_name="Suite donnée",
            ),
        ),
    ]
