# Generated by Django 5.2.10 on 2026-02-23 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_commune"),
        ("tiac", "0046_alter_evenementsimple_follow_up"),
    ]

    operations = [
        migrations.AddField(
            model_name="etablissement",
            name="new_commune",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)ss",
                to="core.commune",
                verbose_name="Commune",
            ),
        ),
    ]
