# Generated by Django 5.2.11 on 2026-03-13 13:46

from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models
from django.db.models import CharField, OuterRef, Subquery
from django.db.models.functions import Cast
from reversion.models import Version


def update_last_updated(apps, schema_editor):
    EvenementSimple = apps.get_model("tiac", "EvenementSimple")
    InvestigationTiac = apps.get_model("tiac", "InvestigationTiac")

    for model in (EvenementSimple, InvestigationTiac):
        content_type = ContentType.objects.get_for_model(model)
        latest_revision = (
            Version.objects.filter(object_id=Cast(OuterRef("pk"), CharField()), content_type=content_type)
            .select_related("revision")
            .order_by("-revision__date_created")
        )
        model.objects.update(last_updated=Subquery(latest_revision.values("revision__date_created")[:1]))


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0047_etablissement_code_postal"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementsimple",
            name="last_updated",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Date de dernière mise à jour",
            ),
        ),
        migrations.AddField(
            model_name="investigationtiac",
            name="last_updated",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Date de dernière mise à jour",
            ),
        ),
        migrations.RunPython(update_last_updated, migrations.RunPython.noop),
    ]
