# Generated by Django 5.2.11 on 2026-03-27 09:45

from django.db import migrations, models

from core.mixins import WithEtatMixin


def copy_date_creation_to_date_publication(apps, schema_editor):
    EvenementSimple = apps.get_model("tiac", "EvenementSimple")
    EvenementSimple.objects.exclude(etat=WithEtatMixin.Etat.BROUILLON).update(
        date_publication=models.F("date_creation")
    )

    InvestigationTiac = apps.get_model("tiac", "InvestigationTiac")
    InvestigationTiac.objects.exclude(etat=WithEtatMixin.Etat.BROUILLON).update(
        date_publication=models.F("date_creation")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0048_evenementsimple_last_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementsimple",
            name="date_publication",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de publication"),
        ),
        migrations.AddField(
            model_name="investigationtiac",
            name="date_publication",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de publication"),
        ),
        migrations.RunPython(copy_date_creation_to_date_publication, migrations.RunPython.noop),
    ]
