# Generated by Django 6.0.3 on 2026-04-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0049_evenementsimple_date_publication_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementsimple",
            name="numero_rasff",
            field=models.CharField(blank=True, max_length=255, verbose_name="N° RASFF/AAC"),
        ),
        migrations.AddField(
            model_name="investigationtiac",
            name="numero_rasff",
            field=models.CharField(blank=True, max_length=255, verbose_name="N° RASFF/AAC"),
        ),
    ]
