# Generated by Django 6.0.3 on 2026-05-21 13:15

from django.db import migrations, models


def set_default_nb_sick_persons(apps, schema_editor):
    InvestigationTiac = apps.get_model("tiac", "InvestigationTiac")
    InvestigationTiac.objects.filter(nb_sick_persons__isnull=True).update(nb_sick_persons=1)


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0050_evenementsimple_numero_rasff_and_more"),
    ]

    operations = [
        migrations.RunPython(set_default_nb_sick_persons, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="investigationtiac",
            name="nb_sick_persons",
            field=models.IntegerField(verbose_name="Nombre de malades total"),
        ),
    ]
