# Generated by Django 6.0.6 on 2026-06-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0062_message_date_picked_and_more"),
        ("tiac", "0052_alter_alimentsuspect_categorie_produit"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="investigationtiac",
            name="repas_aliment_only_if_conclusion_known",
        ),
        migrations.AddConstraint(
            model_name="investigationtiac",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("suspicion_conclusion", "DISCARDED"), _negated=True),
                    models.Q(
                        ("conclusion_repas__isnull", True),
                        ("conclusion_aliment__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="repas_aliment_only_if_conclusion_known",
            ),
        ),
    ]
