# Generated by Django 6.0.6 on 2026-07-02 07:50

from django.db import migrations, models
from django.db.models import Q


def migrate_etat(apps, schema_editor):
    InvestigationTiac = apps.get_model("tiac", "InvestigationTiac")
    InvestigationTiac.objects.filter(etat="en_cours").exclude(
        Q(suspicion_conclusion__isnull=True) | Q(suspicion_conclusion="")
    ).update(etat="conclu")


def reverse_migrate_etat(apps, schema_editor):
    InvestigationTiac = apps.get_model("tiac", "InvestigationTiac")
    InvestigationTiac.objects.filter(etat="conclu").update(etat="en_cours")


class Migration(migrations.Migration):
    dependencies = [
        (
            "tiac",
            "0053_remove_investigationtiac_repas_aliment_only_if_conclusion_known_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="investigationtiac",
            name="etat",
            field=models.CharField(
                choices=[
                    ("brouillon", "Brouillon"),
                    ("en_cours", "En cours"),
                    ("cloture", "Clôturé"),
                    ("conclu", "Conclu"),
                ],
                default="brouillon",
                max_length=100,
                verbose_name="État de l'événement",
            ),
        ),
        migrations.RunPython(migrate_etat, reverse_migrate_etat),
    ]
