# Generated by Django 6.0.6 on 2026-07-15 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tiac", "0054_alter_investigationtiac_etat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investigationtiac",
            name="conclusion_aliment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tiac.alimentsuspect",
            ),
        ),
        migrations.AlterField(
            model_name="investigationtiac",
            name="conclusion_repas",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tiac.repassuspect",
            ),
        ),
    ]
