STRUCTURE_EXPLOITANT = "Exploitant"
STRUCTURES_PRELEVEUSES = [
    "SRAL",
    "Délégataire",
    "DSF",
    "SIVEP",
    "SEMAE",
    "FAM",
    "CTIFL",
    STRUCTURE_EXPLOITANT,
    "Salim",
]

STATUTS_EVENEMENT = ["Foyer", "Interception", "Incursion", "Suspicion"]

STATUTS_REGLEMENTAIRES = {
    "OQP": "organisme quarantaine prioritaire",
    "OQ": "organisme quarantaine",
    "OQZP": "organisme quarantaine zone protégée",
    "ORNQ": "organisme réglementé non quarantaine",
    "OTR": "organisme temporairement réglementé",
    "OE": "organisme émergent",
}

CONTEXTES = [
    "enquête officielle relative aux organismes nuisibles",
    "enquête liée à un foyer existant ou éradiqué d’un organisme nuisible",
    "inspections phytosanitaires de tout type",
    "inspection de traçage en amont et en aval liée à la présence spécifique de l’organisme nuisible",
    "inspection officielle à des fins autres que phytosanitaires",
    "informations fournies par des opérateurs professionnels, des laboratoires ou d’autres personnes",
    "informations scientifiques",
    "notification rasff",
    "autre (à préciser dans le fil de suivi)",
]

KNOWN_OEPP_CODES_FOR_STATUS_REGLEMENTAIRES = {
    "OQ": [
        "XYLEFM",
        "POCZSH",
        "XYLOCH",
        "PSDMS2",
        "HETDPA",
        "RALSSL",
        "HETDRO",
        "MELGCH",
        "MELGFA",
        "PHYP64",
        "CERAFP",
        "RHIOHI",
        "ALECSN",
        "PITOJU",
        "TOLCND",
        "GEOHMO",
        "SCITDO",
        "DACULA",
        "MELGMY",
        "XIPHRI",
        "1BCTRG",
        "CORBFL",
        "PHYPAE",
        "PHYTRA",
        "1BEGOG",
        "ALECCT",
        "LIBEAM",
        "DRAERO",
        "ELSIAU",
        "BLMOV0",
        "GIBBCI",
    ],
    "OQZP": ["BNYVV0", "RHYCFE"],
    "OQP": [
        "GUIGCI",
        "DACUDO",
        "POPIJA",
        "DACUZO",
        "BURSXY",
        "ANOLCN",
        "XYLEFA",
        "TOBRFV",
        "1POMAG",
    ],
    "OE": ["TOUMPA", "XYLBAF", "XYLBFE", "SCITGI", "TOFBV0", "ALECCA", "STEHHA"],
}

KNOWN_OEPPS = [oepp for oepp_list in KNOWN_OEPP_CODES_FOR_STATUS_REGLEMENTAIRES.values() for oepp in oepp_list]

LABORATOIRES_AGREES = [
    "LDA 02",
    "LDA 13",
    "SEDIA 21",
    "Labocéa",
    "CTI 24",
    "BRET 29",
    "IFV 30",
    "LDA 31",
    "LCA 33",
    "LDA 33b",
    "QUAL 54",
    "COM 62",
    "LOOS 62",
    "LDA 67",
    "LDA 71",
    "CENTRESUD 87",
    "LDA 972 (Martinique)",
    "FDGDON 974 (Réunion)",
]
LABORATOIRES_CONFIRMATION_OFFICIELLE = [
    "ANSES 34",
    "ANSES 49",
    "ANSES 54b",
    "ANSES 35b",
    "ANSES 63",
    "ANSES 974",
    "SNES 49",
]

POSITION_CHAINE_DISTRIBUTION = [
    "Consommateur",
    "Expéditeur",
    "Agriculteur",
    "Destinataire",
    "Importateur",
    "Détaillant",
    "Emballeur",
    "Fabricant",
    "Entreprise de transport",
    "Producteur",
    "Point d'entrée",
    "Grossiste/entrepôt",
    "Stockage",
    "Achat en ligne",
]

SITES_INSPECTION = [
    "Verger à graine",
    "Peuplement classé",
    "Champ",
    "Verger",
    "Vignoble",
    "Pépinière",
    "Forêt",
    "Jardin privé",
    "Site public",
    "Espace protégé",
    "Friches",
    "Jardinerie",
    "Plateforme logistique",
    "Site de stockage de bois",
    "Serre",
    "Batiment privé",
    "Batiment public",
    "Autre (à préciser dans le fil de suivi)",
    "Sans objet",
]
