from django.urls import path

from .api_views import search_espece_echantillon
from .views import (
    EvenementDetailView,
    EvenementListView,
    EvenementUpdateView,
    EvenementVisibiliteUpdateView,
    FicheDetectionCreateView,
    FicheDetectionExportView,
    FicheDetectionUpdateView,
    FicheZoneDelimiteeCreateView,
    FicheZoneDelimiteeDeleteView,
    FicheZoneDelimiteeUpdateView,
    VisibiliteStructureView,
)

app_name = "sv"
urlpatterns = [
    path(
        "evenements/",
        EvenementListView.as_view(),
        name="evenement-liste",
    ),
    path(
        "evenement/<str:numero>/",
        EvenementDetailView.as_view(),
        name="evenement-details",
    ),
    path(
        "evenement/<int:pk>/modification/",
        EvenementUpdateView.as_view(),
        name="evenement-update",
    ),
    path(
        "fiches-detection/creation/",
        FicheDetectionCreateView.as_view(),
        name="fiche-detection-creation",
    ),
    path(
        "fiches-detection/export/",
        FicheDetectionExportView.as_view(),
        name="fiche-detection-export",
    ),
    path(
        "fiches-detection/<int:pk>/modification/",
        FicheDetectionUpdateView.as_view(),
        name="fiche-detection-modification",
    ),
    path(
        "evenement/<int:pk>/visibilite/",
        EvenementVisibiliteUpdateView.as_view(),
        name="evenement-visibilite-update",
    ),
    path(
        "api/espece/recherche/",
        search_espece_echantillon,
        name="api-search-espece",
    ),
    path(
        "fiche-zone-delimitee/creation/",
        FicheZoneDelimiteeCreateView.as_view(),
        name="fiche-zone-delimitee-creation",
    ),
    path(
        "fiche-zone-delimitee/<int:pk>/modification/",
        FicheZoneDelimiteeUpdateView.as_view(),
        name="fiche-zone-delimitee-update",
    ),
    path(
        "evenement/<int:pk>/structures/ajout/visibilite",
        VisibiliteStructureView.as_view(),
        name="structure-add-visibilite",
    ),
    path(
        "fiche-zone-delimitee/<int:pk>/delete/",
        FicheZoneDelimiteeDeleteView.as_view(),
        name="fiche-zone-delimitee-delete",
    ),
]
