from django.urls import path
from .views import (
    FicheDetectionListView,
    FicheDetectionDetailView,
    FicheDetectionCreateView,
    FicheDetectionUpdateView,
    FreeLinkCreateView,
    FicheDetectionExportView,
    FicheDetecionCloturerView,
    FicheZoneDelimiteeCreateView,
)

urlpatterns = [
    path(
        "fiches-detection/",
        FicheDetectionListView.as_view(),
        name="fiche-detection-list",
    ),
    path(
        "fiches-detection/<int:pk>/",
        FicheDetectionDetailView.as_view(),
        name="fiche-detection-vue-detaillee",
    ),
    path(
        "fiches-detection/creation/",
        FicheDetectionCreateView.as_view(),
        name="fiche-detection-creation",
    ),
    path(
        "fiches-detection/export/",
        FicheDetectionExportView.as_view(),
        name="fiche-detection-export",
    ),
    path(
        "fiches-detection/<int:pk>/modification/",
        FicheDetectionUpdateView.as_view(),
        name="fiche-detection-modification",
    ),
    path(
        "fiches-detection/<int:pk>/cloturer/",
        FicheDetecionCloturerView.as_view(),
        name="fiche-detection-cloturer",
    ),
    path(
        "lien/ajout/",
        FreeLinkCreateView.as_view(),
        name="free-link-add",
    ),
    path(
        "fiche-zone-delimitee/creation/",
        FicheZoneDelimiteeCreateView.as_view(),
        name="fiche-zone-delimitee-creation",
    ),
]
